### ISSUE TITLE
[QA] Not able to claim WETH on Sui, tx Fuji -> Sui

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1024]
## Describe the current behavior in detail
Not able to claim WETH on Sui, tx Fuji -> Sui.

Builds - Tested NOK:
- https://wormhole-connect.netlify.app/ [Testnet] 
- https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet]

Checked with macOS version 12.6.7 and Google Chrome 117.0.5938.92 (Official Build) (x86_64). 

Steps:
1. Prepare to send 0.001 WETH from Fuji (Metamask) to Sui (Sui wallet)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button on Redeem screen

Error is displayed in Console:
```
Error: Unknown RPC Error
    at ha.requestWithType (main.624ce4e7.js:37:4694169)
    at async mi.getObject (main.624ce4e7.js:37:4721070)
```

Send from tx: [Snowtrace](https://testnet.snowtrace.io/tx/0x4fbc39ef4d870e87504403533502f0ae40f8226148cfbf6c632f253346d303f0)

Note: Issue is reproducible when Testnet or Devnet option is selected in Sui wallet.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eb8d0cee-c555-40a4-a6cd-a7f3030b2869)

## What is the expected/desired behavior
User can successfully claim WETH on Sui.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. User can successfully claim WETH on Sui.

- Send from tx: [Snowtrace](https://testnet.snowtrace.io/tx/0x527a721fbbad60f1c1924a68e3937a5116acf7c4a874a55bfd46948964650ce0)
- Send to tx: [Sui explorer](https://suiexplorer.com/txblock/AszdgmBbLLsaLtWNsb4iKc22JgZxnS7f99n1GzNQnrXq?network=testnet)
