### ISSUE TITLE
[QA] WalletSendTransactionError when sending asset from Solana with Bitget wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1039]
## Describe the current behavior in detail
Checked on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] with macOS 12.6.7 and Google Chrome Version 117.0.5938.92 (Official Build) (x86_64).

Steps:
1. Disable Phantom extension on chrome://extensions/ 
2. Refresh wormhole-connect page https://deploy-preview-1029--wormhole-connect.netlify.app/
3. Click "Connect wallet" button in From section
4. Select Phantom option in From section (actual result: Bidget wallet is opened and successfully connected)
5. Prepare to send 0.001 SOL from Solana to Avalanche (Metamask)
6. Click "Approve and proceed with transaction" button

Error is displayed in Console:
```
WalletSendTransactionError: r.signAndSendTransaction is not a function
    at Kc.solana.phantom.sendTransaction (main.86afa21a.js:37:19815690)
    at async Fc.sendTransaction (main.86afa21a.js:37:19794674)
```

Note: BitKeep wallet is opened when user clicks on Phantom option (ticket #712).

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8b04f714-ee5e-481d-a3ab-a8e22c9f4b94

## What is the expected/desired behavior
"Install Phantom" is shown on "Connect wallet" screen when Phantom option is disabled or user is able to successfully send asset from Solana with Bitget wallet.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with the scenario from the description. Error is displayed in Console:
```
WalletSendTransactionError: r.signAndSendTransaction is not a function
    at GT.solana.phantom.sendTransaction (main.788b3894.js:2:15778716)
    at async LT.sendTransaction (main.788b3894.js:2:15757737)
```

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 WSOL from Solana (Bitget) to Avalanche (Metamask). 
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/1zS9F3KvqT4iRHc6fptBpuYBj62vDerV8HhoT3gvvZ1zVsEP3ueR1SK1YsWrkX9uE9hmSqzNkAZnaWGMuDC2S64)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0xa46ec676bccbfb3a08d82141571c399df626a624a90fb42e987f8749e8da1cda)

Ticket is closed.
