### ISSUE TITLE
[QA] Unable to change wallet several times

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1189]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.117 (Official Build) (x86_64).

Steps:
1. Connect Coin98 for Cosmos wallet in From section
2. Change wallet to Leap for Cosmos
3. Change wallet back to Coin98 for Cosmos
4. Check if wallet is connected

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c4b15eee-b921-42e4-8664-b62804e3d62a

## What is the expected/desired behavior
Wallet is connected.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Connect Coin98 for Cosmos wallet in From section
2. Disconnect wallet 
3. Connect Coin98 for Cosmos wallet again

Error:
```
Uncaught (in promise) Error: Chain id not set
    at lM.connect (main.804554ec.js:2:17650538)
    at main.804554ec.js:190:96593
    at main.804554ec.js:190:96960
    at Object.Ne (main.804554ec.js:2:15211976)
    at Fe (main.804554ec.js:2:15212130)
    at main.804554ec.js:2:15231991
    at Ur (main.804554ec.js:2:15232085)
    at jr (main.804554ec.js:2:15232499)
    at main.804554ec.js:2:15237927
    at ud (main.804554ec.js:2:15301266)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/16af9261-880e-46b6-b8e4-90b25ff5bedd

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:

1. Connect Coin98 for Cosmos wallet in From section
2. Change wallet to Leap for Cosmos
3. Change wallet back to Coin98 for Cosmos
4. Check if wallet is connected

Error:
```
Uncaught (in promise) Error: Chain id not set
    at CosmosWallet.connect (main.js:399:93491)
    at dr (main.js:794:91884)
    at main.js:794:92506
    at Object.Nb (main.js:37:10464)
    at Tb (main.js:37:10633)
    at Ub (main.js:37:10699)
    at nf (main.js:37:33630)
    at se$2 (main.js:37:34107)
    at main.js:37:39565
    at Rk (main.js:40:40739)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] with Coin98 (Cosmos) wallet and Keplr wallets (Cosmos).

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ when changing Coin9, Leap and Keplr wallets several times. 
Cosmos networks are currently not available on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZSIRWbaLlziqNWgApQSpbnIBrGPTB79SwRgAm5UQHdauTsIASjZpYgXv%2BgMYAFpjQiEicuIGQpJCUKIRefmDo0GgA5tFhAAwAHgBGAJwALAAcaAUAzCUATADsNgBsZTXcDQCsAIwVvDYdtSUFDUXsaKW1AGaQ1QBC7AUJSfqGJqHIuRMVBQDCbSUd3G0FbdNtFf5t%2FnkdBXnsWXkV4yU2vA3%2BlW2c1VtoWQuLEFwpDQ0Fo%2FkgGFgmTATAB%2Bl8cIgaBsNhitDMSFyvA6vC2Ww6kAakBsaGm1T23EgeRsBQ6nAqnTaWUq3A6XAp1Quf0UiIMAE8AA6QMIOcikFCBcgAG0g%2F0RAF8eQCALpKvyKxKWBFJIIhMLTMFyxYpdLQzE5BoFCltBrVDqWjpbabjensGzsNrVIo2Ti1DpZWoNPK1ArcLK8LJ1EpGpLLGDZHLVN5tSBZDqe73VTi2krh0rcarnLLjVrsSC1SCeziDDqOmN%2BIEgsEQqGkTy88yagHI1F0DG5PKQCrcCtZJq1LNZGytLbsWrcbgM6a1NCjaZXIpFBrsLYFK0NesA3CC4XIUXiyUyw%2FqtVJVVdpQau%2B3pQAdXbi21fl1WDCcmlIJoNe%2BgmhkbbIAAcsIuC8Gg5DsAAUoEJhuJAaAAGr8G40B8oEDh5AAChBvAQQ0r5pNMApuEYbjTMI%2FgNDYtSwIIADSwEGMY8bICUbTodM3AAIoAFq7sIwlGOMaACrg0yvgAVrA%2FAOLUACaeTCfJfKeq8KDybgBEAOLyc4gm8CggkcYCwKguCkLQrCvJft2KJohiUEwXBiHIZAqEYVhOF4YRxGkeRlHUbR9GMcxbFWZYx5CiKYoStKsovkkT5wveiIAI6UOQNDgUgEE5Y0AAaOW8CUgh5LQWyUIZJQALKCK%2Br6UARJTtBB6ENPJ4gdE1eRlZArE5OwRRuGxiEcZlSTOZYP6rOEkTRLE8TpZYoFmrk%2FgBjMOKcOMFQVESbqVgUEZFIMe5HUUkAlNw5QesUvClHFcbLbk0zFk9uZZFkJRdZW85dSinpDIUuzVHk1Q9CUtSw4UHQfTZzb2eBjmIgtSQ9m5CbsHkbRtNd1RMdcWTsB0eRoJwJS4nknBZJstZbEU9K%2BkUSYI1k%2FhxUsJ5JReqX82Ac2LNlizi94ONKEtYS8KQeQYECcRxdtRW5KcJ02OG%2FivEUoxMj0jSUiO27bl0tRtCOSZOqURQfVxX05D9JZoP9gPA20oOMTYENFFDNSw%2FDiMw7SqNNnZrYftjD6465fYEx0Hu8NMlqppGDREiUy60mg6bTGz1sdEU6bdEyRRtGgB6bbGgtnsll5pfHljS34ksZXXnaIvLyCSDJGAoBgtAba3EAawmKdFKyaAhsW1TDuMhS1BOgxvOni6MVsjS7MzFSQF0TsrAmbt%2FQDXtEj73Bg%2F7SaB0cwdwzYCNIxH3fWVHLYOePSiy94eMk5rByDcdgJRgxEzqFsN6hJahVH8LMUk05OhbGqF6bO1sGgBgqDYUWgIG5IHPClK8H9HykM7jeVu%2F8wB9yQNMNAtAW6IknsA7WOC9YGyNuGFEDQzaBnYJbCo1tbYNHtiUR2pDPqn1%2Bh7C%2BQMr6%2B3BvfIOMNn6v3DijSRaNo4%2Fw7NQ%2FQgD0TJ1TunAomckw5zzinQuxdOhl1OLwSu1da6%2FwFolRuwsSGuLFuQ7u7cIAUIgOLeUABKHk94SCUEYeIYkdAMBpFWKrSARASCfTquQaA4x4mIARE4Fw7har%2BByZqEwfIRTOFcG4Qp9ZaB8hQHkaU5T8luHrKkXA9ktjBF%2FMgA0fMXyfQAJI2GKTqLpy1enXkMf2RMyZUzpi9DYLMOY8yPULEyEs25yyVizDWOsL524YH8BksIgQ1ACnoAAeguQwxhuBaAsCOVgDI%2FgjDkAeeQFAFzHmgguUPU0tALkdCBhUIoFznAghJKQGwFy8mVJYAKaAaR6zfMMpAF55AhkimBAKIUNgAC0zg8CBGRdKMUYQADE3ReDDm4PWGwaK%2FlSjMECtU4tXy0AAqkEZlhSlhHZZyoCL5an1MacgV8rS0DtKhJ0vUyB%2FxSkAvWQZwye7fjGX%2BAVkzE5GJ4nxASIkxISSkjJOSillJqQ0lpHSDQ9IGWMqZcyll9kvkOcc5ApzcDnPgFcm5eB7nfOea895nzvkAr%2BRkAFDJAa1DBbgCFaAoUwo%2BaQZuogpTkDSPYcYlApRSlEEc9NpBRCkDSHkUQ1QL4ChyKICcOKMCiGXoGBoaB%2FC8TQPCxFAB%2BPogMmgDBJiSrAqL0WYo8cQphlh6X%2BEZWYBorK1SviJWtOI3L9C8rFUumIashV1IaVKPlEqpWQBld0laUQt1j28Mq1di11XIAiOe9aWrew6vNGfWRAN5Egxvn7AOKiQ4vzDsjesByjnLQ9V6n16I%2FXvKeWioNRyQ3kCwGG9AEaLlRoRrG%2BNibRQoBTalNNGas05rzQWsUxbS3lsrdW2tAp62Nuzi2ttHa0jdtqL2oGRwJGahRfBjFKrCFNxFi%2BKdM7EAsq8GyhNytVYoBvRAddSBXwyZVqQbdmphV7oPS%2BNpHS71IEVrJ9Tl74rO1HQtWhRm1MaYTi%2B6Z77PZfuvrfP9j9VGhzfpozUoG3VIAg5c650G7mwcRfx4NXzkM%2FPDXQDDTIsPgugJC6FeGCMyiI5mhtpH82kqLSWstFaAZVprdUOtDbgxMdbdXVj7HOP9p494PjI7BNEObnShl6AmUSZKPOrwr5yCD2HqPBTYAlP9cGyPUz%2BgtOiuU4e%2FTsqkAD3aUNqbnEVgWYfLQ5bQ9JvPvxsAxzcjvaKLvpDdzAH1HAedZqV14GzmBd9SFgN4XEORZQ78tDsXMMxsS8lpN%2BHU3psy9m3NOXC2UYKzRkrZXGPNqq%2B2hFbGe1dS4wOl8TXXmjqE54id%2BgxOdeZT1qTC6aaMJG2NsneOlAzf3WK%2Bb0qDP0MYUq8zKrLNM4YdTgx2qHMyKcydn9SjzvQ0u0B9%2BPmXVgZOQ971QXbn%2Bqi4Gt5b3Q2ff%2BXF6N2GksJpS8moHxGstg%2FI3lqjhWsjFbowxir8OWNI9q6j%2Brg7oDDqxy14TXjvAE7QF1sAkn9CZQ1PKAA3EAA%3D) and [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).

Ticket is closed.
