### ISSUE TITLE
[QA] Token registration warning is not displayed when sending wstETH from Base Goerli to Goerli

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1196]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.105 (Official Build) (x86_64).

Steps:
1. Select Base Goerli as source chain
2. Select Goerli as destination chain
3. Connect Metamask wallets in From and To sections
4. Open Assets list
5. Navigate to "All tokens" tab
6. Select wstETH asset
7. Enter amount, in my case 0.0001 
8. Click "Approve and proceed with transaction" button

Error in Console:
```
Error: token not registered
    at _k.mustGetForeignAsset (main.804554ec.js:2:17310083)
    at async _k.send (main.804554ec.js:2:17312934)
    at async d4.send (main.804554ec.js:37:401984)
    at async Object.send (main.804554ec.js:37:455519)
    at async Object.onClick (main.804554ec.js:137:5018)
```
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6683a955-bdad-40f8-b413-5c83f3a540cd)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f625c935-87d4-40da-a329-7a737fe23927

## What is the expected/desired behavior
Token registration warning is displayed.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. User can successfully send wstETH from Base Goerli (Metamask) to Goerli (Metamask). 
* Send from tx: [BaseScan](https://goerli.basescan.org/tx/0x59410a03c2cb17f679d0d38d8360ba4bd201c1cac3e7b9d31e761b87a31b4713)
* Send to tx: [Etherscan](https://goerli.etherscan.io/tx/0x57880e4f10e8bc5a21261191d0ee47e0633945d942cf5c157d4fbbea4aaebc22)

Ticket is closed.
