### ISSUE TITLE
[QA] [Mainnet] Cannot send tBTC from Optimism -> Ethereum 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1223]
## Describe the current behavior in detail
Checked on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.000002 tBTC from Optimism (Metamask) to Ethereum (Metamask)
2. Click "Approve and proceed with transaction" button

Errors in Console:
`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}, stack: '{\n  "code": -32603,\n  "message": "Internal JSON-RP…hfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935'}`

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: insufficient allowance", method="estimateGas", transaction={"to":"0x1293a54e160D1cd7075487898d65266081A15458","data":"0xf69785f3000000000000000000000000000000000000000000000000000001d1a94a200000000000000000000000000000000000000000000000000000000000000000020000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: ERC20: insufficient allowance","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d45524332303a20696e73756666696369656e7420616c6c6f77616e6365000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: ERC20: insufficient allowance\",\n    \"data\": \"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d45524332303a20696e73756666696369656e7420616c6c6f77616e6365000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:49968)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:50970\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:49968)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:50970\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (main.23680ae7.js:2:948592)
    at f.throwError (main.23680ae7.js:2:948712)
    at v (main.23680ae7.js:2:1006887)
    at u.<anonymous> (main.23680ae7.js:2:1016841)
    at Generator.throw (<anonymous>)
    at s (main.23680ae7.js:2:1005988)
```

![Screenshot 2023-11-14 at 11 09 40](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e8e0c03a-b80f-4841-88be-6cc5bce428ab)

Note:
* Similar issue: Cannot send tBTC from Arbitrum to Ethereum #1222 
* Issue is reproducible when clicking on "Approve and proceed with transaction" button again

## What is the expected/desired behavior
Transaction is approved and proceed.

**Comment by tsadovska** [comment]
Scenario is added to #1222 . Ticket is closed.
