### ISSUE TITLE
[QA] [Mainnet] Cannot send CELO from Evmos -> Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1230]
## Describe the current behavior in detail
Checked on https://deploy-preview-1227--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.001 CELO from Evmos (Leap) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button

Error in Console:

```
Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (124346821) and chain-id (evmos_9001-2): unauthorized
    at I.broadcastTxSync (main.45e311aa.js:2:891376)
    at async I.broadcastTx (main.45e311aa.js:2:891128)
    at async u0.sendTransaction (main.45e311aa.js:37:154485)
    at async main.45e311aa.js:37:243570
    at async K0 (main.45e311aa.js:37:243424)
    at async Object.send (main.45e311aa.js:37:455704)
    at async Object.onClick (main.45e311aa.js:137:5018)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/38d91eb2-d4b6-4d95-bf26-20586ac82b4d

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Scenario "Send 0.0001 CELO from Evmos (Metamask) to Solana (Phantom)".

Send from tx: [Mintscan](https://www.mintscan.io/evmos/tx/DB8CECFB748988B6EA80B39DF6CD73D8DFD41DE5E05602C15C36A791714B38C9)
Send to tx: [Solana explorer](https://explorer.solana.com/tx/5C19gZ5auWr57PKMASADBjpD7UkcYJ5YpksmMuigoBytFwU2qa9viyBzBjUN1xqzKkp5agPDyyDnKjE2ifvpFCUc)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/93652a23-7642-4011-9c1c-6863742cbe4b)


Ticket is closed.
