### ISSUE TITLE
[QA] [Mainnet] Cannot claim WFTM, tx Osmosis -> Ethereum 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1231]
## Describe the current behavior in detail
Checked on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.001 WFTM from Osmosis (Leap) to Ethereum (Metamask)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button

Send from tx: [Mintscan](https://www.mintscan.io/osmosis/tx/A8120D4207C99648E69325C96E6C150BBE30397528CB2472A03869283D5A98CF)

Error:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid EVM address" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="completeTransfer(bytes)", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e76616c69642045564d206164647265737300000000000000000000000000", errorArgs=["invalid EVM address"], errorName="Error", errorSignature="Error(string)", reason="invalid EVM address", code=CALL_EXCEPTION, version=abi/5.7.0)
    at f.makeError (main.119ba056.js:2:948592)
    at f.throwError (main.119ba056.js:2:948712)
    at A.decodeFunctionResult (main.119ba056.js:2:810718)
    at Object.<anonymous> (main.119ba056.js:2:846706)
    at Generator.next (<anonymous>)
    at a (main.119ba056.js:2:842193) 
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c81e1745-45c7-49e7-abba-7ae9366ae80f)

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://deploy-preview-1236--wormhole-connect-mainnet.netlify.app/ [Mainnet]. Transaction is completed. 

* Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/C73559239689F6786E0E7219C689EEAD8C50A21E2212C25F5BFD7FE2D3D38F09)
* Send to tx: [Etherscan](https://etherscan.io/tx/0x9f33bac0e00df8df1f598ba7c461362d17e77e1b4ea10dbc521faf26bcdbec36)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8489bbfd-1dbf-4aeb-b861-e5eea9ab7c95)

Ticket is closed.
