### ISSUE TITLE
[QA] [Mainnet] Cannot send WFTM from Osmosis -> Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1232]
## Describe the current behavior in detail
Checked on https://deploy-preview-1227--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.001 WFTM from Osmosis (Leap) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button

Errors in Console:

`POST https://osmosis-rpc.polkachu.com/ net::ERR_FAILED 502 (Bad Gateway)`

```
TypeError: Failed to fetch
    at t.http (main.45e311aa.js:2:1844708)
    at t.HttpClient.execute (main.45e311aa.js:2:1846615)
    at u.doCall (main.45e311aa.js:2:1875321)
    at u.abciQuery (main.45e311aa.js:2:1871865)
    at c.queryAbci (main.45e311aa.js:2:877975)
    at Object.request (main.45e311aa.js:2:879250)
    at t.QueryClientImpl.Account (main.45e311aa.js:2:916369)
    at Object.account (main.45e311aa.js:2:828839)
    at I.getAccount (main.45e311aa.js:2:888645)
    at I.getSequence (main.45e311aa.js:2:888814)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9a0ff4ed-888f-46e3-94ed-861dcc8907bd)

## What is the expected/desired behavior
Transaction is successfully started.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

Scenario "Send 0.0001 WFTM from Osmosis (Leap) to Solana (Phantom)".
Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/4D789151181B77DA2A3AF67877606CB0E6CD6656E5256D78F12099230A56C378)
Send to tx: [Solana explorer](https://explorer.solana.com/tx/3CdWxZVbcSYQGut4iAHedCsBsE8C5JM1cjH1faf83e6MpnPMr9tZJsUqQDusjxj5u9CboZk9JJxSzubBWS2Hae6o)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/54f7ddbd-e2e1-4578-9d56-193fc5554ae0)


Ticket is closed.
