### ISSUE TITLE
[QA] [Mainnet] Balance is not loading for Polygon

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1269]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Select Polygon as source chain
2. Connect Metamask wallet
3. Open Assets list

Actual result:
* Balance is not loading.
* Error is displayed in Console
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'error')
    at main.9ae2237b.js:2:2399781
    at Array.forEach (<anonymous>)
    at then.emit.action (main.9ae2237b.js:2:2399746)
```

Note: Issue is also reproducible when wallet is connected first. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/08bc209f-61a5-41db-86c3-c995949e7729

## What is the expected/desired behavior
 Balance is loaded.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Ticket is closed.
