### ISSUE TITLE
[QA] [Mainnet] Cannot register PYTH for transaction Solana -> Celo

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1332]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with Google Chrome Version 120.0.6099.71 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 PYTH from Solana (Phantom) to Celo (Metamask)
2. Click [register](https://portalbridge.com/advanced-tools/#/register) link in warning "This token is not registered.."
3. Select Solana network and connect Phantom wallet in Step "1.Source" 
4. Enter PYTH asset contract DRQ5Mn2mrB8Q4vDc5FNnTGgV2xHBDttdTVubsUKdNTuG ([Solscan](https://solscan.io/address/DRQ5Mn2mrB8Q4vDc5FNnTGgV2xHBDttdTVubsUKdNTuG))
5. Click Next button
6. Select Celo network and connect Metamask wallet in Step "2.Target"
7. Click Next button
8. Click "Attest" button in Step "3.Send attestation"

Error:
```
WalletSendTransactionError: Unexpected error
    at c.sendTransaction (203.4e846c05.js:2:11211248)
    at async o.sendTransaction (175.0bf05ec9.js:2:3060778)
    at async ir (main.e79d7efb.js:1:56897)
    at async main.e79d7efb.js:1:84205 
```

![Screenshot 2023-12-13 at 18 04 48](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/95d30fd8-307d-450d-b215-36a953bb3dd8)

## What is the expected/desired behavior
Token is successfully registered.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![Screenshot 2024-01-15 at 15 40 00](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/90126074-3833-4780-b151-3596f46c3db1)

Ticket is closed.
