### ISSUE TITLE
[QA] Cannot send USDC from Polygon to BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1352]
## Describe the current behavior in detail
Checked on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.109 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.02 USDC from Polygon (Metamask) to BSC (Metamask)
2. Click "Approve and proceed with transaction" button

Note: Tried 4 times.

Error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: transfer amount exceeds allowance", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE","data":"0x0f5287b00000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000004e2000000000000000000000000000000000000000000000000000000000000000040000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001d450100","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000","message":"execution reverted: ERC20: transfer amount exceeds allowance","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (main.73d22bf0.js:2:2343439)
    at f.throwError (main.73d22bf0.js:2:2343559)
    at v (main.73d22bf0.js:2:2401734)
    at u.<anonymous> (main.73d22bf0.js:2:2411688)
    at Generator.throw (<anonymous>)
    at s (main.73d22bf0.js:2:2400835)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b13644b2-20a8-4e08-bfdc-be2f45df37a8)

## What is the expected/desired behavior
Transaction is successfully started.

**Comment by tsadovska** [comment]
Not able to reproduce the issue on:
* https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet]
  -   Send from tx: [Polygonscan](https://polygonscan.com/tx/0xca96c354fcf46060e675a0846966753df5b71a8eb11e8e1476f45755638d035f)
  -   Send to tx: [BSCScan](https://bscscan.com/tx/0xe8f8d71ef91738c7833a853da76efd530e26380b068043d08c2200e9ad1f9cca)
  
 * https://preview.portalbridge.com/7102d8ccad/ [Mainnet]
    -  Send from tx: [Polygonscan](https://polygonscan.com/tx/0xa95bdf1c1d5d1fad72d448c7a6f412a0121d7b3e5642c1a601c88c60f9f31dd0)
    -  Send to tx: [BSCScan](https://bscscan.com/tx/0x8c280465e062e5d8ef461b7d2ddee8a1c65bcfc1d08de89b57bcaeba63cba287)
    
 Ticket is closed.
