### ISSUE TITLE
[QA] Sometimes slider is not properly moving 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1355]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.109 (Official Build) (x86_64).

Steps:
1. Prepare to send 4 USDC from Ethereum (Metamask through WalletConnect) to Polygon (Metamask through WalletConnect)
2. Change slider position in Native gas section

Reproducibility: 2/15

Errors in Console:
`GET https://api.coingecko.com/api/v3/simple/price?ids=usd-coin&vs_currencies=usd net::ERR_FAILED 429 (Too Many Requests)`

```
Uncaught (in promise) TypeError: Failed to fetch
    at oP (main.js:2:18468926)
    at main.js:110:33606
    at main.js:110:33624
```

Note: Issue is not reproducible after user changes options in Route section.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/931e3253-651c-4090-919f-226a98ef4363

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b2634fec-d1c0-4b27-b6be-79353b38e8c6

## What is the expected/desired behavior
Slider is properly moving.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].
Ticket is closed.
