### ISSUE TITLE
[QA] Cannot send asset with Rainbow-Ethereum wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1368]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with:
* macOS 12.7.1 and Google Chrome Version 120.0.6099.109 (Official Build) (x86_64)
* iPhone 11 Pro iOS 16.5.1 and Rainbow-Ethereum Wallet Version  v.1.9.11

Steps:
1. Connect Rainbow wallet in From section
2. Connect Solflare wallet in To section
3. Prepare to send 0.001 CELO from Celo to Solana
4. Click "Approve and proceed with transaction" button

Error is displayed in Console
```
Error: Missing or invalid. request() method: wallet_addEthereumChain
    at Ha.isValidRequest (main.ca264bfb.js:2:10883970)
    at async Ha.request (main.ca264bfb.js:2:10867433)
    at async Wa.request (main.ca264bfb.js:2:10890439)
    at async Is.request (main.ca264bfb.js:2:10969451)
    at async js.request (main.ca264bfb.js:2:10980978)
    at async tc.request (main.ca264bfb.js:2:10989908)
    at async y4.evm.bO.walletConnect.connectorOptions.projectId.addChain (main.ca264bfb.js:2:18665556)
    at async y4.evm.bO.walletConnect.connectorOptions.projectId.switchChain (main.ca264bfb.js:2:18665322)
    at async S4 (main.ca264bfb.js:37:280414)
    at async Object.onClick (main.ca264bfb.js:137:4924)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7691f375-0ce2-494a-ac57-1aa9c83b4842)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 CELO from Celo (Rainbow) to Polygon (Rainbow). Rainbow wallet is connected through QR Code. Rainbow app version - 1.19.18 (29). Checked on iOS 17.4.1. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7c2e4917-74df-4d10-bf6a-956767152921)

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ [Mainnet] with the same scenario "Send 0.001 CELO from Celo (Rainbow wallet) to Solana (Phantom)". Error appears in Console after clicking on "Approve and proceed with transaction" button: 
```
Wormhole Connect: error completing transfer Error: Missing or invalid. request() method: wallet_addEthereumChain
    at zp.isValidRequest (index.es-DTpG_imm-C4AjFW-c.js:40:109259)
    at async zp.request (index.es-DTpG_imm-C4AjFW-c.js:40:91737)
    at async fn.request (index.es-DTpG_imm-C4AjFW-c.js:40:115709)
    at async Ag.request (index.es-Bx6K8dMp-4tvrqKIy.js:33:15129)
    at async io.request (index.es-Bx6K8dMp-4tvrqKIy.js:33:27825)
    at async oo.request (index.es-Bx6K8dMp-4tvrqKIy.js:33:37365)
    at async ah.addChain (evm-zMaXwqxg-BjHYQ0Aw.js:37:16645)
    at async ah.switchChain (evm-zMaXwqxg-BjHYQ0Aw.js:37:16408)
    at async oh (evm-zMaXwqxg-BjHYQ0Aw.js:37:74131)
    at async switchChain (pb-index-Bl6bYNaM.js:502:56665)
```
