### ISSUE TITLE
[QA] Sometimes user is unable to change slider position after closing warning pop-up "This transaction requires 24 hours to complete"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1376]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.109 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 SOL from Solana (Phantom) to Goerli (Metamask)
2. Click Cancel button on pop-up "This transaction requires 24 hours to complete"
3. Enable "Native gas" section
4. Change slider position

Errors:

`GET https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd net::ERR_FAILED 429 (Too Many Requests)`

```
Uncaught (in promise) TypeError: Failed to fetch
    at aP (main.1f83fe90.js:2:18477243)
    at main.1f83fe90.js:110:33618
    at async main.1f83fe90.js:110:33567
```

Reproducibility: Issue is not always reproducible. Noticed 5 times today. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/10fe9068-03cf-417f-be45-df96a4d2808f

## What is the expected/desired behavior
User can change slider position.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 

Ticket is closed.
