### ISSUE TITLE
[QA] Cannot send ETH (Optimism) from Optimism to BSC 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1399]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/4adb101c39/ [Mainnet] with macOS Sonoma 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 ETH (Optimism) from Optimism (Metamask) to BSC (Metamask)
2. Click "Approve and proceed with transaction" button

Error:
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x1D68124e65faFC907325e3EDbF8c4d84499DAa8b","value":{"type":"BigNumber","hex":"0x5af3107a4000"},"data":"0x9981509f00000000000000000000000000000000000000000000000000000000000000040000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a6670000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted","cause":null}}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at f.makeError (main.js:2:2341430)
    at f.throwError (main.js:2:2341550)
    at v (main.js:2:2399495)
    at u.<anonymous> (main.js:2:2409679)
    at Generator.throw (<anonymous>)
    at s (main.js:2:2398826)
```

![Screenshot 2023-12-27 at 09 50 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b3c974f3-fe92-430f-97e0-ce3420ef5837)

## What is the expected/desired behavior
Asset is successfully sent.

**Comment by tsadovska** [comment]
Duplicate https://github.com/wormhole-foundation/wormhole-connect/issues/1367
