### ISSUE TITLE
[QA] Cannot send tBTC from Osmosis 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1417]
## Describe the current behavior in detail
Checked on https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Prepare to send 0.00001 tBTC from Osmosis (Leap) to Polygon (Metamask)
2. Click "Approve and proceed with transaction" button

Error:
```
Error: {"code":-32603,"message":"Internal error","data":"mempool is full: number of txs 10000 (max: 10000), total txs bytes 9365541 (max: 1073741824)"}
    at HttpClient.execute (main.js:358:19589)
    at async Tendermint37Client.doCall (main.js:358:99164)
    at async rr.broadcastTxSync (main.js:358:110630)
    at async rr.broadcastTx (main.js:358:110462)
    at async CosmosWallet.sendTransaction (main.js:362:76330)
    at async CosmosWallet.signAndSendTransaction (main.js:362:76537)
    at async signCosmosTransaction (main.js:480:314897)
    at async signAndSendTransaction (main.js:480:315557)
    at async Operator.send (main.js:486:65885)
    at async Object.sr [as onClick] (main.js:652:95511)
```

Note: Issue is also reproducible when sending asset to BSC, Avalanche, Celo.

![Screenshot 2024-01-03 at 17 50 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/84b1e372-95da-4c10-ba1a-f7806e1e52cf)

## What is the expected/desired behavior
Transaction is successfully started.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000001 tBTC from Osmosis (Leap) to Polygon (Metamask). 
* Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/7D03E6A429E8FF2288871931F40386C7C9B4A172851C55765B0473B54409F029)
* Send to tx: [Polygonscan](https://polygonscan.com/tx/0xede2dbfd3751d34eb87473721f2bb74d1987fe51cb9749bdc363bd80b2d8dc58)

Ticket is closed.
