### ISSUE TITLE
[QA] [Mainnet] Cannot send ETH (Optimism) from Optimism to Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1424]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Select Optimism in From section
2. Select Solana in To section
3. Connect Metamask in From section
4. Connect Phantom in To section
5. Click "Approve and proceed with transaction" button

Actual: Transaction fails. Warning to register token is not shown.

Error in Console:
```
Error: Token not registered
    at SolanaContext.mustGetForeignAsset (/main.js:343:8861)
    at async SolanaContext.getAssociatedTokenAddress (/main.js:353:183485)
    at async getSolanaAssociatedTokenAccount (/main.js:481:20443)
    at async BridgeRoute.send (/main.js:481:21878)
    at async Operator.send (/main.js:483:65983)
    at async Object.sr [as onClick] (/main.js:649:95511)
```

![Screenshot 2024-01-05 at 12 38 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1babac0a-a5f1-40fa-a5bc-95c95b798a90)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/232d38c6-bf8f-4070-aa7a-b80484d0adce

## What is the expected/desired behavior
Transaction is successfully started.

**Comment by tsadovska** [comment]
Scenario is added to ticket #1275.
