### ISSUE TITLE
[QA] [Testnet] Error "redeemRelay function not found" appears after clicking on "Claim" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1454]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.199 (Official Build) (arm64).

Steps:
1. Open Menu > Resume transaction
2. Search for tx hash 0xd274e4293c559cb272edd35f5859ee3d5b7a0ecb42413303dcf01aa5c1108c00 in "Base Goerli" network
3. Click on "Switch to manual claim" toogle
4. Connect wallet
5. Click on Claim button
6. Observe

Error:
```
Error: redeemRelay function not found
    at WormholeContext.redeemRelay (main.js:356:630120)
    at RelayRoute.redeem (main.js:481:30339)
    at Operator.redeem (main.js:483:66071)
    at Object.Zn [as onClick] (main.js:749:962)
    at ht (main.js:649:91967)
    at Object.Nb (main.js:37:10464)
    at Tb (main.js:37:10633)
    at Ub (main.js:37:10699)
    at nf (main.js:37:33554)
    at se$1 (main.js:37:34031)
```

Send from tx: [BaseScan](https://goerli.basescan.org/tx/0xd274e4293c559cb272edd35f5859ee3d5b7a0ecb42413303dcf01aa5c1108c00)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5d0ef639-ef80-4c4e-8200-1113ba119205

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by AigaD** [comment]
Blocked by: https://github.com/wormhole-foundation/wormhole-connect/issues/1613

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Resume transaction, tx hash `0xe5a852e61c82d3e16c9224f8ab5fe973be441c98170118640156d83374975377` (Fantom)
2. Click on "Switch to manual claim" in "Send to" section

Actual result: Transaction fails. 

```
Error: redeemRelay function not found
    at WormholeContext.redeemRelay (main-0-9QBYvg.js:501:628487)
    at RelayRoute.redeem (main-0-9QBYvg.js:509:101107)
    at Operator.redeem (main-0-9QBYvg.js:509:91842)
    at Object.rr [as onClick] (main-0-9QBYvg.js:548:1343)
    at Dt (main-0-9QBYvg.js:547:29337)
    at Object.Nb (main-0-9QBYvg.js:38:10464)
    at Tb (main-0-9QBYvg.js:38:10633)
    at Ub (main-0-9QBYvg.js:38:10699)
    at nf (main-0-9QBYvg.js:38:33554)
    at se$1 (main-0-9QBYvg.js:38:34031)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/363edd7f-1fd2-42f3-ac84-5dfc0efea69a)

**Comment by tsadovska** [comment]
Closing the ticket, because Base Goerli and Sei networks are not displayed in the networks list on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).
