### ISSUE TITLE
[QA] Asset claiming fails after switching to manual claim

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1462]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.216 (Official Build) (arm64).

Steps:
1. Send 0.00161 ETH (Arbitrum) from Arbitrum (Metamask) to Optimism (Metamask) with automatic route
2. Switch to manual claim when possible 
3. Observe

Error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: transfer already completed", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x9ae506cDDd27DEe1275fd1fe6627E5dc65257061","data":"0x3d528f35000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004d801000000030d010e84381db4e8ef2a3d1800ec3e1d78799dd19db135529054444afdd73fc9e4a83c1aa1f8998042111e1decb314734c6c6d3c037384f6f8203767068b99ae56a900033ce45a9815c89550e2030a2c0e849853c220e82b238c6a4089367fa4d6a007454233d697d99b3fc7f2dae726bfdc5c0afcd800464162b393ebbc5aacf098e71e0004d00ccc3840011f306a8085c9083df51652f12afef0e39bea0e1302c3130baf7100cf1cae9d49b631392f7b09dac2036d35f2a9a332747548a52506371346394c00052083ed5fb86f0c76e27635763b5317565201f6ca722859dd2cbc01a3f974077b231627c7748aa2eb564b8b2c9e59f7b778e788814a02bfe91a87b4dd4b4682c0000622f192c72af3d474dfacbf62ec28199dcd0b7b884896fd0a2f6a382d6884d28552c75c9396610ff985e5682f298f5e7ec385e45ac3ae9169f8fe54f1fd22a8b301080d079badd2713ba2da506d732e56acb52a3d793046a32912c6875ddf8bdc51516f35ac0ef2be46d9e157729f6e8a4a35b89e97c98d2a6a144ca9ea31c0ece3ff0109fe4db01f49effa1c770eb9910ca48d39da11e2dc0c1e63cccec8b2e7d9e982792ec09e1b3e9c68ba7e6538e3abe360e4dd4d5a23b59bf19247c4858447efdc96010c33b7be20882e99a56e46e03f6538a16d19206a0bfc390b76c90b03bf4664a06428832e17f24178f0db6864eccd1ab2db99331c12e6f5872bdb77b86ae70e4c66010e3a269a7388cae81c58a170f77886c52b04cbf1382380eb56c59645bc16636fe4773e60111acb035fe399240f3cd8d101ca1f8c4d3f7a86f22de07083b1d03a95000f77dbfdb494fa2eb1eadf60aa7b40440102c1293b2e633ffac69298a366641ca54115285c220ff8bb8c95d539f1b951f235c0c883ec385369e34c381a146050b80010b9bb6ee0f8f0dcc4c60028ca1779a9aeee7dd0ba4e6e8b45d2804ff067d1c6870e377dcdea320c991dcc93301de6c9521d6103bf38c325d65225ec358fdc1feb0111d49726e7cc85dd2e5f52d2d8bdc1ad0ddde8e4605db5e9a274079c1fe2b950f745eaeb81c1a9953cb21bd82e1d287d48d7f42fbbabc70ddbcb0b05566c3a208001125855a7259da00e8a844e647dbdc7fb57739f3c54d536c37e514b585889eedf63503b05f9e5e596e93bec420ebfdee9d655feae780e22390b2be503c198e679a300659ff3a5f8cfa85d00170000000000000000000000000b2402144bb366a632d14b83f244d2e0e21bd39c000000000001737e010300000000000000000000000000000000000000000000000000000000000274f6000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200020000000000000000000000009ae506cddd27dee1275fd1fe6627e5dc65257061001800000000000000000000000048fa7528bfd6164ddf09df0ed22451cf59c8413018005da8cff8640000640000000000000000000000000000000000000000000300000000000000000000000042000000000000000000000000000000000000060000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000005b86c4071d3420000000000000000000000000000000000000000000000000005b3970ce0cfef000000000000000000000000000000000000000000000000000518e6beff66f60000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: transfer already completed","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a7472616e7366657220616c726561647920636f6d706c65746564000000000000","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46766)
    at Logger.throwError (main.js:166:46899)
    at checkError$1 (main.js:178:125408)
    at Web3Provider$1.<anonymous> (main.js:178:136016)
    at Generator.throw (<anonymous>)
    at pn (main.js:178:124429)
```

Notes:
* Asset is received and "Send to" transaction appears after few seconds. 
* Send from tx: [Arbitrum explorer](https://arbiscan.io/tx/0x07a375df30a71a4f6d6796e5091a32d5eb173e53d220e21862c031a0671456ce)
* Send to tx: [Optimism Etherscan](https://optimistic.etherscan.io/tx/0x1b449d610f556e5a82fc5c01dcb7d9ead4ff7ccac539c0f31ff65a20f3ceaa51)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0476430b-7eda-4620-a971-2516f4503c50

## What is the expected/desired behavior
Transaction proceeds without error.

**Comment by kev1n-peters** [comment]
This has already been redeemed, need to look into why it takes so long to update the redeemed status

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 ETH (Base) from Base (Metamask) to BSC (Metamask). 

Error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: transfer already completed", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x05498574BD0Fa99eeCB01e1241661E7eE58F8a85","data":"0x3d528f35000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004d801000000030d01fa03e98740bb911447e3ad700f6296ca7cebfedd1da80acf3fd1aa51b2b13b824876b3f75b6ce50aa5d31c110f220882bf4a4e5e23ec3db38f6c241c3863207200022767805e73fba07a6a28a95be89b3fd96d85bf1bf6587a517eec575d2ab8750808f4b29efafa5bb9b347f814ade8ba8c9d791cbe56b714bcf734ccaa2b8351cd0103b1a3b0bdc35bf997d25cc4a5ae350bcb2c09b3f3854db7426fdb15492c2d058c43727b5c48214c58dd61af119ca22a5383e0ec4707731f2262a14f2eb2dce54301042025ab8318ae6952b86040e7e3531fecc48502b6c4b5120988bdabdd5387811669dd4b5f6a86686c6253ba80cb3997497a883e71b2fa901b3df0085ee63efd61000564f42c4d9bf5422fe58c5ea0f03d1c5acd9256d1007754d21bdeac2ca9648f5c5d618e6540ef645f46f3c228b51d792310dfd5948a8652dcb56689bf0df130670006e1fee8d1f1726aef549c7785c5ef38c03b2fa76225a31fc34d5421af735c24df31c54d17f94a86169290426a28e27ebfe21f4400fa09a16de38d7daa48554dd50107109fedcc385b7613a4a6f24aa2e9a66b3135f0d0a130475ce474836fcc199d6275208dff7f88bb3327c0998d20adeff48fd6f8d0a39c196bc21d72365a6cd9dd01090774414ac008b5c7857730b693489b6faff443aba4986cff96e903de154c96de5b031f55a59da202eaaa72d26d5c17a5a839ff239bcddd57e4cd8000edcf2559010ab771611cdfd86c0bcb42cb8d0f5d116fac460d337e8f0eb89d0612aa3c1c2fb94b27578777ef28d3f42b300586c68619ebbd4fb92534b3c626dffa239af8006a000d7770b603cce43e50fc00cf0208de1efe620898eed6c734e18681085b8c63bcde7f0f3dbb2df86dea114f45542fb2c68829772e0b124f0aa211c78dd34dba3f52000e76ff668b3bbf34955a0e6564acb9dc8812cf0456c71dedccbbb44e15ae37ed73609c64be847e69353b0716a43541ce2bccc6c686a5db3cd695a745f691ac44cf010f6954dbdb3880dff131491792ff385a3a5a4defd030cbfb1a44c1c911c18387bf078a3a1d652c92aba06861378fd942901a5c3f30b5e146424e5644abb2c4b8cb0110508443e20ab760f335ad357fe1f49f312e52a459c79b4ebc40079fbc86097e7c51b407a28360e6a010530a295bebac9ec0b2e95bfefdf731b886d52715bc51d10165a17197fea39301001e0000000000000000000000008d2de8d2f73f1f4cab472ac9a881c9b123c7962700000000000067190103000000000000000000000000000000000000000000000000000000000001869b000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000200000000000000000000000005498574bd0fa99eecb01e1241661e7ee58f8a850004000000000000000000000000610d4dfac3ec32e0be98d18ddb280dacd76a188904000193a3fe64000064000000000000000000000000000000000000000000010000000000000000000000002170ed0880ac9a755fd29b2688956bd959f933f80000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000000000000000000000000000000038d731712951f00000000000000000000000000000000000000000000000000038aa38f6b9c5600000000000000000000000000000000000000000000000000019c65520d09fc0000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: transfer already completed","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a7472616e7366657220616c726561647920636f6d706c65746564000000000000","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46766)
    at Logger.throwError (main.js:166:46899)
    at checkError$1 (main.js:178:125408)
    at Web3Provider$1.<anonymous> (main.js:178:136016)
    at Generator.throw (<anonymous>)
    at pn (main.js:178:124429)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ea59e06a-c99b-4475-b9e3-4cc670857ecb

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/59e0c1fff9/ [Mainnet] when sending 0.0016 WETH (Avalanche) from Avalanche (Metamask) to Base (Metamask).Send from tx: [Avanscan](https://avascan.info/blockchain/c/tx/0xb5670848094e6a0dc0c081e1cd9434bcb46ca34a6f92a50518ea3c8549acbf29). After few seconds tx is shown as completed. 

Error:
```
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x13a59cf61813a53d166fd25739cbcd1b80ca325acea62f9a71e5716b80836201", transaction={"hash":"0x13a59cf61813a53d166fd25739cbcd1b80ca325acea62f9a71e5716b80836201","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","gasPrice":{"type":"BigNumber","hex":"0x0145f8"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x01449e"},"maxFeePerGas":{"type":"BigNumber","hex":"0x0145f8"},"gasLimit":{"type":"BigNumber","hex":"0x067a52"},"to":"0x610d4DFAC3EC32e0be98D18DDb280DACD76A1889","value":{"type":"BigNumber","hex":"0x00"},"nonce":193,"data":"0x3d528f35000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004d801000000030d0173d130fcd750b8feffa05e6bfa1b3a6079d05b77e1e537a69994214f52e8edea444548e475c2095b03841ec169c44eae76126c9acc06ee7e3985b0596b1999a30102f67edca591945d55c9a15a064b8fc9ab0c270dea3f8a1a679a9320a4282c13cd2610914370845f8fd7b5d29a922588935b672071650d9dcbb293c0a4c2dbcc8101039ad55c7c888999e1e2bebf8ef17ddfcb93543646e26069c4a13db812db710c3e383277186b3cf6e1c401cd1ea88ef3c7ad249b0d0450141a87682c8aa7dc684a0004189b15b63b5bdab54c423721238c11099c000b422586baf5d084fc7c19d88cf41990a0dd077288729753a6354d62ef5b0b5ff4a128524613d5304062da6feb9f0006ff0b473aae6a04c52e5e3a442fd9e3d2bc82945f2e0f85b2cbad32c471fcd7f722846ce7f5706942355b178868b8fccd6d79aaba7c74201b0f55b93119df2fe2000768b5db0934d20accb4ab8479efa8d99acef6b6e9422019ebe8b47cabd6349461433456ddb668377dff06a79049f2cac006fd703b1d0e9b9f1635d4f41ffdea78000837411b1a0a92f215940879d9a3c3ded943122b074b2a0b59eb631e0ec7f892d1236c167203371997bf4d4c23b2c97c60c11271f7b0ae569aeeb9fe47a3268942010aeb7eca949f811d436c0457b4a5cea7a044eaf12614dfaee4403809b34d414363639058769d888ce1c9bba00e4d7aa674355575110751356169797538f2dada32000d13c19a0a3a14d3f852e57ba00f708da2ff0d9159ca0bea4640db49c5ec7a294f68a74d90b43d19a06dc0c60fa90975efe4595f9440118169bae4f4ba99acc41d000f57d27d180a80d7e34899cd4c5485b677865ae836d619cb0949c74b7385bc0ddf7a6e01639ce8582c51cf2b8a7b1bd0473c125be4fd4aa5f5c7955330f93d13060110c22fe883adbf92a3c77913f8ea79fa3940b54901fdc39678600dd5d45f047e8c1499dfc1d181f7f15efb114f04aa5f1ba117805249467075f18b5fe1b39dccf700111f39b686571c17c8904598c597469edce73b336383025ea8e0cf2e462f1e4dd945628bab24ee8c266dc562f6852c8e024b97f8ec0a85ff07ff914edd4d35b44a00128619ae91b4d8552fbd7ea55761273ce6eaa8c4e31dd705adbcec37de4c470e2e354b019062abb61d74ae2b53eca4fb46456e79902ac4f91c12fb9f888d5bdcb40165a6abd5130ec26900060000000000000000000000000e082f06ff657d94310cb8ce8b0d9a04541d80520000000000021cda010300000000000000000000000000000000000000000000000000000000000270ed000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20002000000000000000000000000610d4dfac3ec32e0be98d18ddb280dacd76a1889001e000000000000000000000000e565e118e75304dd3cf83dff409c90034b7ea18a1e0069c20e13640000640000000000000000000000000000000000000000000200000000000000000000000042000000000000000000000000000000000000060000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000005af0523d0acc20000000000000000000000000000000000000000000000000005aa6d013ba64400000000000000000000000000000000000000000000000000052b3b3f09e0f50000000000000000","r":"0x82fad9db23a7121ee135fffa7e1ac00e268dabdc6b0ebf858e791c328207d0bc","s":"0x73fe93de90c3e80e5b045e5c4a0d2177767d552e08d6f3f4b69f1e885238c3fd","v":1,"creates":null,"chainId":0}, receipt={"to":"0x610d4DFAC3EC32e0be98D18DDb280DACD76A1889","from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","contractAddress":null,"transactionIndex":3,"gasUsed":{"type":"BigNumber","hex":"0x035498"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x046b51fde91a9704cca548f3df5fb58d0578f904201483186e41dfe73ffbf331","transactionHash":"0x13a59cf61813a53d166fd25739cbcd1b80ca325acea62f9a71e5716b80836201","logs":[],"blockNumber":9316244,"confirmations":8,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x0c85fd"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x01459e"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46766)
    at Logger.throwError (main.js:166:46899)
    at Web3Provider$1.<anonymous> (main.js:178:112484)
    at Generator.next (<anonymous>)
    at ln (main.js:178:90254)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1e57aa62-e633-49d9-b828-cedbf0f91ab1

**Comment by AigaD** [comment]
Tested OK from: https://wormhole-connect-mainnet.netlify.app/#
Transaction from [BSC](https://bscscan.com/tx/0xa53d4ef2458143ec7fb1b8f198c719c5e5878a4cd2242e34c3b53805b3ea00b4) to [Moonbeam](https://moonscan.io/tx/0x610fdd1cb6289a890f8dd808e2e98edbab5d035b62060e9be3d126d50f1c1b43) completed successfully after switching to manual Claim
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/59e6dcfe-5e5a-490c-8549-bf6048a3b6ee

Tested OK from: https://portalbridge.com/
Transaction from [Moonbeam](https://moonscan.io/tx/0x681851ed4f87929ab5d9a346d8027f4bf68e7171039cc6a9b3e4f73404cf8896) to [Polygon](https://polygonscan.com/tx/0x38f55241880fab5ac1787379a588432ff42512b81f31b8bb069c4056a629a01c) was completed after switching to Manual Claim

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dbfb628c-6100-4edb-a6ac-9680a9eeced6


Issue regarding missing native gas token and relayer fee info reported here: https://github.com/wormhole-foundation/wormhole-connect/issues/1657
