### ISSUE TITLE
[QA] Cannot connect wallet with "WalletConnect for Solana"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1508]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.2.1, Google Chrome Version 120.0.6099.216 (Official Build) (arm64), iPhone 11 Pro iOS 16.5.1, Phantom app Version 23.19.0. 

1. Open wormhole-connect on computer
2. Click "Connect wallet" and select "WalletConnect Solana" option
3. Open Phantom app on mobile and scan QR Code
4. Check if wallet is connected

Actual result: Wallet is not connect. QR Code is not valid. 

![IMG_3562](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/acd05612-f13e-4ccf-aa94-78f504623ba8)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ed1532c0-c51c-44a9-8fab-c597d32767cf)

## What is the expected/desired behavior
Wallet is successfully connected.

**Comment by kev1n-peters** [comment]
I get the invalid QR code error when using Phantom and Solflare on mobile. Spot wallet scans it, but then I get an error when trying to sign a TX:
```
index.es-65y4fMxF.js:27 {context: 'core'} {context: 'core/crypto'} Error: No matching key. keychain: 1bf01f0b87270dbfcd2eb1ffcc1e3f6ee8c3d2cb18179b53750e4495547fcf6b
    at Yu.get (index.es-65y4fMxF.js:40:38388)
    at Qu.getSymKey (index.es-65y4fMxF.js:40:41255)
    at Qu.decode (index.es-65y4fMxF.js:40:40475)
    at jn.<anonymous> (index.es-65y4fMxF.js:40:111848)
    at jn.emit (main.js:84:3305)
    at ff.onMessageEvent (index.es-65y4fMxF.js:40:60704)
    at async ff.onProviderPayload (index.es-65y4fMxF.js:40:60551)
(anonymous) @ index.es-65y4fMxF.js:27
(anonymous) @ index.es-65y4fMxF.js:27
(anonymous) @ index.es-65y4fMxF.js:27
Qu.decode @ index.es-65y4fMxF.js:40
await in Qu.decode (async)
(anonymous) @ index.es-65y4fMxF.js:40
jn.emit @ main.js:84
onMessageEvent @ index.es-65y4fMxF.js:40
await in onMessageEvent (async)
onProviderPayload @ index.es-65y4fMxF.js:40
await in onProviderPayload (async)
onPayloadHandler @ index.es-65y4fMxF.js:40
jn.emit @ main.js:84
onPayload @ index.es-65y4fMxF.js:40
(anonymous) @ index.es-65y4fMxF.js:40
jn.emit @ main.js:84
onPayload @ index.es-65y4fMxF.js:40
e.onmessage @ index.es-65y4fMxF.js:40
index.es-65y4fMxF.js:27 {context: 'client'} Error: Missing or invalid. Decoded payload on topic 1bf01f0b87270dbfcd2eb1ffcc1e3f6ee8c3d2cb18179b53750e4495547fcf6b is not identifiable as a JSON-RPC request or a response.
    at zf.onRelayEventUnknownPayload (index.es-65y4fMxF.js:40:99486)
    at jn.<anonymous> (index.es-65y4fMxF.js:40:112100)
(anonymous) @ index.es-65y4fMxF.js:27
(anonymous) @ index.es-65y4fMxF.js:27
(anonymous) @ index.es-65y4fMxF.js:40
await in (anonymous) (async)
jn.emit @ main.js:84
onMessageEvent @ index.es-65y4fMxF.js:40
await in onMessageEvent (async)
onProviderPayload @ index.es-65y4fMxF.js:40
await in onProviderPayload (async)
onPayloadHandler @ index.es-65y4fMxF.js:40
jn.emit @ main.js:84
onPayload @ index.es-65y4fMxF.js:40
(anonymous) @ index.es-65y4fMxF.js:40
jn.emit @ main.js:84
onPayload @ index.es-65y4fMxF.js:40
e.onmessage @ index.es-65y4fMxF.js:40
main.js:691 TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 4pXb12oZk7ysBWuxgEPkKaWoUgHd5aycDn75ZvX1yiEJauwt81AXRBJQAoXRE9BBS3Kf8Hx3kkkjKzZdLJbsLV9i using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61281)
    at async Connection$1.confirmTransaction (main.js:171:56723)
    at async SolanaWallet.sendTransaction (main.js:517:300050)
    at async signSolanaTransaction (main.js:519:14303)
    at async signAndSendTransaction (main.js:519:15745)
    at async BridgeRoute.send (main.js:523:22384)
    at async Operator.send (main.js:525:79338)
    at async Object.gr [as onClick] (main.js:691:95817)
    ```

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet] when scanning QR Code from Phantom app.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/ac97e9d348/ [Mainnet] when scanning QR Code from Phantom app.

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/
Cannot connect through Wallet Connect Solana with Phantom app, shows message that the QR code is not valid
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1607
Attachment:

![IMG-0129](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b9b54b60-1a9c-4c87-91f2-5951a6b52a2e)

**Comment by AigaD** [comment]
Issue is reproduced from: https://preview.portalbridge.com/749d45da9e/#
Cannot connect to Wallet Connect Solana through Phantom mobile app

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Cannot connect with WalletConnect Solana using Phantom mobile app
Attachment:

![90083](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/40118312-90c1-46f9-92c5-a8e62104e1bc)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
Cannot scan the QR code to Solana WalletConnect option, shows that the QR code is invalid
Attachment:

![17624](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0a9e837a-d42e-4ee9-8a23-6c3da44b246f)

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZSIRWbaLlziqNWgApQSpbnIBrGPTB79SwRgAm5UQHdauTsIASjZpYgXv%2BgMYAFpjQiEicuIGQpJCUKIRefmDo0GgA5tFhAAwAHgBGAJwALAAcaAUAzCUATADsNgBsZTXcDQCsAIwVvDYdtSUFDUXsaKW1AGaQ1QBC7AUJSfqGJqHIuRMVBQDCbSUd3G0FbdNtFf5t%2FnkdBXnsWXkV4yU2vA3%2BlW2c1VtoWQuLEFwpDQ0Fo%2FkgGFgmTATAB%2Bl8cIgaBsNhitDMSFyvA6vC2Ww6kAakBsaGm1T23EgeRsBQ6nAqnTaWUq3A6XAp1Quf0UiIMAE8AA6QMIOcikFCBcgAG0g%2F0RAF8eQCALpKvyKxKWBFJIIhMLTMFyxYpdLQzE5BoFCltBrVDqWjpbabjensGzsNrVIo2Ti1DpZWoNPK1ArcLK8LJ1EpGpLLGDZHLVN5tSBZDqe73VTi2krh0rcarnLLjVrsSC1SCeziDDqOmN%2BIEgsEQqGkTy88yagHI1F0DG5PKQCrcCtZJq1LNZGytLbsWrcbgM6a1NCjaZXIpFBrsLYFK0NesA3CC4XIUXiyUyw%2FqtVJVVdpQau%2B3pQAdXbi21fl1WDCcmlIJoNe%2BgmhkbbIAAcsIuC8Gg5DsAAUoEJhuJAaAAGr8G40B8oEDh5AAChBvAQQ0r5pNMApuEYbjTMI%2FgNDYtSwIIADSwEGMY8bICUbTodM3AAIoAFq7sIwlGOMaACrg0yvgAVrA%2FAOLUACaeTCfJfKeq8KDybgBEAOLyc4gm8CggkcYCwKguCkLQrCvJft2KJohiUEwXBiHIZAqEYVhOF4YRxGkeRlHUbR9GMcxbFWZYx5CiKYoStKsovkkT5wveiIAI6UOQNDgUgEE5Y0AAaOW8CUgh5LQWyUIZJQALKCK%2Br6UARJTtBB6ENPJ4gdE1eRlZArE5OwRRuGxiEcZlSTOZYP6rOEkTRLE8TpZYoFmrk%2FgBjMOKcOMFQVESbqVgUEZFIMe5HUUkAlNw5QesUvClHFcbLbk0zFk9uZZFkJRdZW85dSinpDIUuzVHk1Q9CUtSw4UHQfTZzb2eBjmIgtSQ9m5CbsHkbRtNd1RMdcWTsB0eRoJwJS4nknBZJstZbEU9K%2BkUSYI1k%2FhxUsJ5JReqX82Ac2LNlizi94ONKEtYS8KQeQYECcRxdtRW5KcJ02OG%2FivEUoxMj0jSUiO27bl0tRtCOSZOqURQfVxX05D9JZoP9gPA20oOMTYENFFDNSw%2FDiMw7SqNNnZrYftjD6465fYEx0Hu8NMlqppGDREiUy60mg6bTGz1sdEU6bdEyRRtGgB6bbGgtnsll5pfHljS34ksZXXnaIvLyCSDJGAoBgtAba3EAawmKdFKyaAhsW1TDuMhS1BOgxvOni6MVsjS7MzFSQF0TsrAmbt%2FQDXtEj73Bg%2F7SaB0cwdwzYCNIxH3fWVHLYOePSiy94eMk5rByDcdgJRgxEzqFsN6hJahVH8LMUk05OhbGqF6bO1sGgBgqDYUWgIG5IHPClK8H9HykM7jeVu%2F8wB9yQNMNAtAW6IknsA7WOC9YGyNuGFEDQzaBnYJbCo1tbYNHtiUR2pDPqn1%2Bh7C%2BQMr6%2B3BvfIOMNn6v3DijSRaNo4%2Fw7NQ%2FQgD0TJ1TunAomckw5zzinQuxdOhl1OLwSu1da6%2FwFolRuwsSGuLFuQ7u7cIAUIgOLeUABKHk94SCUEYeIYkdAMBpFWKrSARASCfTquQaA4x4mIARE4Fw7har%2BByZqEwfIRTOFcG4Qp9ZaB8hQHkaU5T8luHrKkXA9ktjBF%2FMgA0fMXyfQAJI2GKTqLpy1enXkMf2RMyZUzpi9DYLMOY8yPULEyEs25yyVizDWOsL524YH8BksIgQ1ACnoAAeguQwxhuBaAsCOVgDI%2FgjDkAeeQFAFzHmgguUPU0tALkdCBhUIoFznAghJKQGwFy8mVJYAKaAaR6zfMMpAF55AhkimBAKIUNgAC0zg8CBGRdKMUYQADE3ReDDm4PWGwaK%2FlSjMECtU4tXy0AAqkEZlhSlhHZZyoCL5an1MacgV8rS0DtKhJ0vUyB%2FxSkAvWQZwye7fjGX%2BAVkzE5GJ4nxASIkxISSkjJOSillJqQ0lpHSDQ9IGWMqZcyll9kvkOcc5ApzcDnPgFcm5eB7nfOea895nzvkAr%2BRkAFDJAa1DBbgCFaAoUwo%2BaQZuogpTkDSPYcYlApRSlEEc9NpBRCkDSHkUQ1QL4ChyKICcOKMCiGXoGBoaB%2FC8TQPCxFAB%2BPogMmgDBJiSrAqL0WYo8cQphlh6X%2BEZWYBorK1SviJWtOI3L9C8rFUumIashV1IaVKPlEqpWQBld0laUQt1j28Mq1di11XIAiOe9aWrew6vNGfWRAN5Egxvn7AOKiQ4vzDsjesByjnLQ9V6n16I%2FXvKeWioNRyQ3kCwGG9AEaLlRoRrG%2BNibRQoBTalNNGas05rzQWsUxbS3lsrdW2tAp62Nuzi2ttHa0jdtqL2oGRwJGahRfBjFKrCFNxFi%2BKdM7EAsq8GyhNytVYoBvRAddSBXwyZVqQbdmphV7oPS%2BNpHS71IEVrJ9Tl74rO1HQtWhRm1MaYTi%2B6Z77PZfuvrfP9j9VGhzfpozUoG3VIAg5c650G7mwcRfx4NXzkM%2FPDXQDDTIsPgugJC6FeGCMyiI5mhtpH82kqLSWstFaAZVprdUOtDbgxMdbdXVj7HOP9p494PjI7BNEObnShl6AmUSZKPOrwr5yCD2HqPBTYAlP9cGyPUz%2BgtOiuU4e%2FTsqkAD3aUNqbnEVgWYfLQ5bQ9JvPvxsAxzcjvaKLvpDdzAH1HAedZqV14GzmBd9SFgN4XEORZQ78tDsXMMxsS8lpN%2BHU3psy9m3NOXC2UYKzRkrZXGPNqq%2B2hFbGe1dS4wOl8TXXmjqE54id%2BgxOdeZT1qTC6aaMJG2NsneOlAzf3WK%2Bb0qDP0MYUq8zKrLNM4YdTgx2qHMyKcydn9SjzvQ0u0B9%2BPmXVgZOQ971QXbn%2Bqi4Gt5b3Q2ff%2BXF6N2GksJpS8moHxGstg%2FI3lqjhWsjFbowxir8OWNI9q6j%2Brg7oDDqxy14TXjvAE7QF1sAkn9CZQ1PKAA3EAA%3D) (Connect v2) when scanning QR Code in Phantom app.

**Comment by tsadovska** [comment]
Reopening the ticket, issue can be reproducible on [Netlify](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGUyYHWACyeAE88SAdENWgyfyCQsPVfAGEbTi8o4NDw92E2ExtlCDB9XUhYWHT1BgAKUHz82ERUaEgGOh8a8wA5GydfOwt3A3itVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMXjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GTBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyM8VBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQoCAAdoHMkMgcCwADbQX1%2BpQbEYAXTygrjCvlsqmMzmJmCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3Z8WBwOe31hjMeK8JVLwU4xwqaYslJe0fvy6bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o%2FIi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS54m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWF4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMeJ4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVPiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIjglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgAImHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAteJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2FjgIz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBh4ioQvgV8KxhGEKhOCJb52m16F44cW5fFBQ%2FoDdw4DJ2Lu1VpFTmIxhb5FFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG75GbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7PEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZy8QAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mnp4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nx4hfQKouYEExjLFTxmpeIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7PyM4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAivyNs5x%2FUFAAEo8gUUoFQaVDhoBiEEAQXgOI%2FERBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNACCGFibF2L9rvAwAIOBQREVHb29id5tiwGfPEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDHxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYsEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHvyMOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5M%2BEUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJdnwwhECnPOZc83lv1%2Bb4ufb%2FIjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaeQcYCgAA3CAEAA).
Warning "QR Code is not valid" is shown when trying to connect Phantom wallet via WalletConnect (Solana). I am using iPhone 11 Pro, Phantom app version 24.22.1 (27724). 


![IMG_5566](https://github.com/user-attachments/assets/337bf32f-162d-4375-9b04-f9aee87e804f)

**Comment by emreboga** [comment]
I've verified that Phantom is not connecting via WalletConnect. It works with MetaMask.

**Comment by emreboga** [comment]
After some research, Phantom mobile may not be supporting WalletConnect. When you look at the WalletConnect's official [list of wallets](https://walletguide.walletconnect.network/), you'll notice that Phantom is not certified and also the Phantom mobile app is not listed there (only Chrome extension). On top of that there is a [Reddit post](https://www.reddit.com/r/Phantom/comments/1b3bs5n/comment/ksrkd33/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) (although 9 months old) someone from Phantom team says WalletConnect is not supported.
@tsadovska  All being said, is there another place we can verify whether Phantom mobile app supports WalletConnect?

**Comment by tsadovska** [comment]
I can confirm that Phantom mobile app is not supported by WalletConnect according their official [list of wallets](https://walletguide.walletconnect.network/).

**Comment by tsadovska** [comment]
I could reproduce the issue with Solflare mobile application that is supported by WalletConnect. 

![image](https://github.com/user-attachments/assets/55767b86-e332-4d1d-b1c6-e9cbe89832d1)

@emreboga Could you please have a look? Thank you :) 

https://github.com/user-attachments/assets/6d8f0514-d40a-403b-ae34-60002d7b54c4

**Comment by emreboga** [comment]
We are currently in the process of replacing the current wallet aggregator in Connect. Therefore we'll postpone any wallet related non-P0 issue until we have the new aggregator.

Cc: @Wesleyleung

**Comment by tsadovska** [comment]
Rechecked the issue.
It is reproducible on https://wormhole-connect-mainnet.netlify.app/. "This QR Code is not valid" message is shown. 


QR Code was scanned using Phantom mobile app on iOS. 
Phantom version: 25.14.0. 

![Image](https://github.com/user-attachments/assets/1f1c56a6-6294-43db-b786-6d64d2657288)

![Image](https://github.com/user-attachments/assets/68c20b2b-11b6-4074-99ec-56e54b579620)

**Comment by agodlevska** [comment]
Issue is reproducible on portal-bridge-staging preview. 
"This QR Code is not valid" message is shown. 
QR Code was scanned using Phantom last version of mobile app on Android.

**Comment by agodlevska** [comment]
MetaMask → Solana wallet connection fails via WalletConnect

Description:
When trying to connect a Solana wallet via MetaMask using WalletConnect, the connection does not complete successfully.

Steps to reproduce:
1. Initiate a Solana wallet connection via WalletConnect.
2. Scan the QR code with the MetaMask mobile app.
3. MetaMask shows a connection request after scanning the QR code.
4. Approve the connection request in MetaMask.

Actual result:

- After approving the connection request, the wallet is not connected.
- The wallet state remains empty and shows “Not connected”.
- On subsequent attempts to connect the wallet via WalletConnect, the QR code does not appear at all.

Expected result:

- The Solana wallet should connect successfully after approving the connection request in MetaMask.
- The wallet address should be displayed and the connection status should change to “Connected”.
- On retry, WalletConnect should consistently display a QR code.
