### ISSUE TITLE
[QA] [Mainnet] Transaction fails with "WalletSendTransactionError: failed to send transaction"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1552]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.0001 SOL from Solana (Bitget) to Moonbeam (Bitget)
2. Click "Approve and proceed with transaction" button

Error:
```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1
    at BitgetWalletAdapter.sendTransaction (main.js:484:164714)
    at async SolanaWallet.sendTransaction (main.js:517:299960)
    at async signSolanaTransaction (main.js:519:14303)
    at async signAndSendTransaction (main.js:519:15745)
    at async BridgeRoute.send (main.js:523:22384)
    at async Operator.send (main.js:525:79299)
    at async Object.gr [as onClick] (main.js:691:95817)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f2109d4e-a398-42a3-90ca-f64bf0b8d0a0

## What is the expected/desired behavior
Transaction proceeds without errors

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet] when sending 0.001 SOL from Solana (Coin98) to Polygon (Metamask). 

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1
    at Coin98WalletAdapter.sendTransaction (main.js:484:164714)
    at async SolanaWallet.sendTransaction (main.js:517:299960)
    at async signSolanaTransaction (main.js:519:14303)
    at async signAndSendTransaction (main.js:519:15745)
    at async BridgeRoute.send (main.js:523:22384)
    at async Operator.send (main.js:525:79512)
    at async Object.gr [as onClick] (main.js:691:95817)
```

**Comment by tsadovska** [comment]
Tested OK:
* Check that transaction from Solana (Bitget) to Moonbeam (MetaMask) is successful on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] (Send from tx: [Solana explorer](https://explorer.solana.com/tx/3YKddPGTHVGesmmtsfQFkkE8PQFSrrR7pCiPn4enmUAX3bJvFxcM94NuWjHcHbdspb49had9R5egUQ3SKcWqTbde), Send to tx: [Moonbeam](https://moonscan.io/tx/0xa27d761044e566e826b8e6320e48d3794631354356c716aacd5e70741f740b56))
* Check that transaction from Solana (Coin98) to Polygon (MetaMask) is successful on https://portalbridge.com/ [Mainnet] (Send from tx: [Solana explorer](https://explorer.solana.com/tx/5wyT4y72Z1XFtUMCns3g22wNtbavw37kGtjxWeFRW1aqEFqA24Dqw1dR6xpxfS2v6vxnEb3BAuXmuhJ1QSSXUeZU), Send to tx: [PolygonScan](https://polygonscan.com/tx/0x07e4ee902bb7a94d4ce6af67443e623d8d0ab3bbbc4e69d86e949a9450808760))

Ticket is closed.

**Comment by tsadovska** [comment]
Reopening the ticket. 
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

Scenarios - Tested NOK :
* Send 0.0001 SOL from Solana (Coin98) to BSC (MetaMask). Transaction fails after clicking on "Approve and proceed with transaction" button with error:

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1
    at Rt.sendTransaction (solana-3Sa-HcsX.js:1:6027)
    at async O.sendTransaction (solana-3Sa-HcsX.js:1:39962)
    at async Ie (solana-3Sa-HcsX.js:1:48158)
    at async signAndSendTransaction (main.js:322:775114)
    at async BridgeRoute.send (main.js:326:22209)
    at async Operator.send (main.js:328:80407)
    at async Object.Gn [as onClick] (main.js:499:101875)
```

* Send 0.0001 SOL from Solana (Solflare) to BSC (MetaMask). Transaction fails after clicking on "Approve and proceed with transaction" button with error:

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at oe.sendTransaction (solana-3Sa-HcsX.js:1:44299)
    at async O.sendTransaction (solana-3Sa-HcsX.js:1:39962)
    at async Ie (solana-3Sa-HcsX.js:1:48158)
    at async signAndSendTransaction (main.js:322:775114)
    at async BridgeRoute.send (main.js:326:22209)
    at async Operator.send (main.js:328:80407)
    at async Object.Gn [as onClick] (main.js:499:101875)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet], https://portalbridge.com/ [Mainnet] and https://preview.portalbridge.com/ [Mainnet] when sending 0.0001 SOL from Solana (Solong) to Fantom (MetaMask). 

Error appears after clicking on "Approve and proceed with transaction" button:
```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Kt.sendTransaction (solana-aFYDy2Js-BE3Rb0Re.js:7:6012)
    at async E.sendTransaction (solana-aFYDy2Js-BE3Rb0Re.js:7:39993)
    at async ge (solana-aFYDy2Js-BE3Rb0Re.js:7:48239)
    at async signAndSendTransaction (pb-index.js:490:768742)
    at async BridgeRoute.send (pb-index.js:494:22387)
    at async Operator.send (pb-index.js:496:81757)
    at async Object.Sr [as onClick] (pb-index.js:692:32413)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 SOL from Solana (Coin98) to Moonbeam (MetaMask). 

Error appears after clicking on "Approve and proceed with transaction" button:
```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x1
    at Rt.sendTransaction (solana-3Sa-HcsX.js:1:6027)
    at async O.sendTransaction (solana-3Sa-HcsX.js:1:39962)
    at async Ie (solana-3Sa-HcsX.js:1:48158)
    at async signAndSendTransaction (main.js:322:777245)
    at async BridgeRoute.send (main.js:326:22203)
    at async Operator.send (main.js:328:81316)
    at async Object.Gn [as onClick] (main.js:522:101074)
```

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/
Transaction 0.001 WGLMR from Solana (Clover) to Fantom (Metamask) fails, reason `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: Program failed to complete`
Attachment:

<img width="1305" alt="Screenshot 2024-04-03 at 16 23 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b20b7448-3868-4074-aa96-fa1c30b98a2b">

**Comment by AigaD** [comment]
Tested from: Mainnet
Transaction 0.001 SOL from [Solana](https://explorer.solana.com/tx/vxwwxfoEy3eGdwHcPeb4D18XoQdoc5EeJcZH8NyrpG8jGLoMQN9YbifYSk1Kunp5sc6MEff6LPREvRaoWFTUPvW) (Coin98) to [BSC](https://bscscan.com/tx/0x2d33a14573ebf441f287bf123d981e3c4e45bafda97c2657afb9407f29c1145f) (Metamask) was completed
Transaction 0.001 SOL from [Solana](https://explorer.solana.com/tx/4txnHZhLnUMtRkEC9Nyuv1hixq7KxRaTkmkBF9QbQkcWe1wtpQDPaxUdQFbowYNE4NQxZ8Y54EdxZdMKbRhszFY8) (Solflare) to [BSC](https://bscscan.com/tx/0x56d47da123b08a9a0a68406e25bc074b080e04fe875ae5e261197751da429ec4) (Metamask) was completed

Tested from: https://portalbridge.com/
Transaction 0.001 SOL from [Solana](https://explorer.solana.com/tx/43YtmBA7wSg8XQyJPsXPLd2KnRFUoRa8PsWhE9NCUpCLm4nAoYwytkkxmWjZGjTW1Hsuobk5jiC7XRLW1i7DPNXM) (Solong) to [Fantom](https://ftmscan.com/tx/0xca4c89fc06f042faf35967f6f4a65c10d940737a21f834527ca7e452f8a798d6) (Metamask) was completed

Closing the ticket

Attachment:

<img width="670" alt="Screenshot 2024-05-21 at 13 54 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/72820caa-45cd-428e-9847-d66b35424a96">

<img width="667" alt="Screenshot 2024-05-21 at 14 14 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ba39bce3-5288-4f77-9515-302a08c1bbb3">
