### ISSUE TITLE
[QA] Evmos network cannot be selected and Evmos icon is not hidden when OKX Wallet (Cosmos) is connected 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1573]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portal-bridge-ui.pages.dev/ac97e9d348/ [Mainnet] with macOS and Google Chrome.

1. Click "Connect wallet" button
2. Select "OKX Wallet" (Cosmos) 
3. Click "Select network" button
4. Click on "Evmos" network

Error:
```
Uncaught (in promise) Error: No chain info found for evmos_9001-2
    at CosmosWallet.addChain (main.js:399:94142)
    at CosmosWallet.connect (main.js:399:93438)
    at async CosmosWallet.switchChain (main.js:399:94360)
    at async switchChain (main.js:519:13882)
    at async selectChain (main.js:519:27369)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/14b1ea08-0dfe-4ff7-8fe8-8f3611f313a7

## What is the expected/desired behavior
Evmos icon is shown as hidden.

**Comment by tsadovska** [comment]
Tested OK:
* Evmos icon is shown as hidden on https://wormhole-connect.netlify.app/ [Testnet] when OKX Wallet is connected
* Evmos icon is shown as hidden on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when OKX Wallet is connected.

Ticket is closed.
