### ISSUE TITLE
[QA] [Testnet] [Fewcha] Claiming on Aptos fails with "ApiError: Bad Request" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1652]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.0001 MATIC from Mumbai (MetaMask) to Aptos (Fewcha)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button

Error:
```
ApiError: Bad Request
    at catchErrorCodes (main.js:88:63393)
    at main.js:88:63853
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ffa2dbfa-984f-416a-aa07-eda398adebe0)

Notes:
* User can successfully send assets from Aptos with Fewcha wallet (Send from tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0x0817286d21409dfb01986a2d12d2edc3c71c8965fadc850b01812ca1c5b61f65?network=testnet), Send to tx: [FtmScan](https://testnet.ftmscan.com/tx/0x42b097f7c581d483562f213fb6aa9ba35dce232cebd1aca0e6e452384fbc979b)).
* User can successfully claim assets with other Aptos wallet, for example Spika (Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x41cda246440fcc373a4a75bce2efc0d30fa613d97cc6942ac78e78621b099dc1), Send to tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0x43384da2a21df9c2974f54d834b23e6759bd652068fff59484f06dd6f0184ef7?network=testnet)).
* Issue is also reproducible on [mainnet](https://wormhole-connect-mainnet.netlify.app/), ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1602.

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet].
Checked following scenarios:
* BNB transfer from [BSC](https://testnet.bscscan.com/tx/0xc1b39fb381415bccc1943271785245730e4ca15a9697709d22e617451447a351) (MetaMask) to [Aptos](https://explorer.aptoslabs.com/txn/0x22038b5552312d332aa8d4e4c34910eeb9403485649cc17f965f0f3105c2a140?network=testnet) (Fewcha), link to [Womholescan](https://wormholescan.io/#/tx/0xc1b39fb381415bccc1943271785245730e4ca15a9697709d22e617451447a351?network=TESTNET)
* FTM from [Fantom](https://testnet.ftmscan.com/tx/0xadbf581ea7a08179c3d55604ce84e70987680f4b45107309b256252ce0392939) (MetaMask) to [Aptos](https://explorer.aptoslabs.com/txn/0x31b0192acc9c7c90568614cc58b70d7ed176cc170512f48df184402ca1e86cbe?network=testnet) (Fewcha), link to [Wormholescan](https://wormholescan.io/#/tx/0xadbf581ea7a08179c3d55604ce84e70987680f4b45107309b256252ce0392939?network=TESTNET)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/01511f4e-eabe-4a8b-9642-8c517e93d74a)


Ticket is closed.
