### ISSUE TITLE
[QA] [Testnet] Neither Approve button nor Token registration warning are present when sending asset to Evmos/ Kujira

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1666]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Select Mumbai as source chain
2. Select Evmos/ Kujira as destination chain
3. Connect MetaMask wallets in From and To sections
4. Select MATIC
5. Enter Amount, 1
6. Check if Approve button or Token registration warning is present

Errors:
```
Uncaught (in promise) Error: Query failed with (18): alloc::string::String not found: query wasm contract failed: invalid request
    at QueryClient.queryAbci (main.js:349:2208)
    at async Object.request (main.js:349:3708)
    at async Object.queryContractSmart (main.js:350:403586)
    at async CosmWasmClient.queryContractSmart (main.js:350:412059)
    at async CosmosContext.getIbcSourceChannel (main.js:350:621606)
    at async CosmosContext.getIbcDestinationChannel (main.js:350:621105)
    at async CosmosContext.deriveIBCDenom (main.js:350:620901)
    at async CosmosContext.getForeignAsset (main.js:350:620195)
    at async WormholeContext.getForeignAsset (main.js:350:628273)
    at async main.js:696:167643
```
```
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (main.js:166:46766)
    at Logger.throwError (main.js:166:46899)
    at Logger.throwArgumentError (main.js:166:46960)
    at main.js:172:45317
    at Generator.next (<anonymous>)
    at ir (main.js:172:44772)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ea58769b-d071-4346-b9b5-7da0741d5f15

## What is the expected/desired behavior
Approve button or Token registration warning is shown when transaction details are entered.

**Comment by AigaD** [comment]
Linking to tickets https://github.com/wormhole-foundation/wormhole-connect/issues/1141 and https://github.com/wormhole-foundation/wormhole-connect/issues/1143 balance not loading for these chains could be related to why the Approve button and other fields are not shown for the transaction.
