### ISSUE TITLE
[QA] [Mainnet] [BscScan] Invalid hash error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1746]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Open Menu > Resume transaction
2. Search for tx hash 0x22ba20d60bfbe94f5ef6bdc5d22cdead79a21687c9abd1b603ff10f7c5fe9224 in Optimism network
3. Open BscScan link

Actual result: Link opens page with "An invalid Txn hash has been entered" error.

Notes:
* Link in "Send from" section: https://optimistic.etherscan.io/tx/0x22ba20d60bfbe94f5ef6bdc5d22cdead79a21687c9abd1b603ff10f7c5fe9224
* Link in "Send to" section: https://bscscan.com/tx/0x0x303a66a745c1d108d754e51415717cd3527df039ad4eb8d0342333d98815215c

Error:
```
Error: invalid hash (argument="value", value="0x0x303a66a745c1d108d754e51415717cd3527df039ad4eb8d0342333d98815215c", code=INVALID_ARGUMENT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46729)
    at Logger.throwError (main.js:166:46862)
    at Logger.throwArgumentError (main.js:166:46923)
    at Formatter.hex (main.js:172:74280)
    at Formatter.hash (main.js:172:74951)
    at StaticJsonRpcProvider.<anonymous> (main.js:172:108055)
    at Generator.next (<anonymous>)
    at ln (main.js:172:79026)
```

![Screenshot 2024-03-04 at 17 47 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f12476be-d488-459d-af32-14efbab235a9)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d4b2e116-811f-4652-b9d5-157d11bde0b4)

## What is the expected/desired behavior
* Correct link: https://bscscan.com/tx/0x303a66a745c1d108d754e51415717cd3527df039ad4eb8d0342333d98815215c

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/252dd1e6-d79d-46f3-8285-020a9d9afd64)

* "Amount" and "Gas fee" are displayed in "Send to" section.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] with following scenario:
1. Open Menu > Resume transaction
2. Search for transaction hash 0x96274321811caf6e02371713564c8c4c3cf4fa8ad6f19a2f8db821030a00e5b8 in Ethereum network
3. Open BscScan link in "Send to" section

Actual result: Link opens page with "An invalid Txn hash has been entered" error, https://bscscan.com/tx/0x0xce89c3bbde19b9999ad6e107ac982ddd7a7c37ec2dde825ee66da0d0cfc21c2f

Correct page is: https://bscscan.com/tx/0xce89c3bbde19b9999ad6e107ac982ddd7a7c37ec2dde825ee66da0d0cfc21c2f

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].

Ticket is closed.
