### ISSUE TITLE
[QA] [Mainnet] [Avascan] Invalid hash error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1760]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Open Menu > Resume transaction
2. Search for transaction hash 0xbfb49782da7487532ff51de38fa5ca1aadac2ce74aaa11a7b54752c6fb16ab1e (Optimism)
3. Click on Avascan link 

Actual result: Link opens page with "HASH NOT VALID" error.

Notes:
* Link in "Send from" section:
https://optimistic.etherscan.io/tx/0xbfb49782da7487532ff51de38fa5ca1aadac2ce74aaa11a7b54752c6fb16ab1e
* Link in "Send to" section: https://avascan.info/blockchain/c/tx/0x0x2f764e23863a0202d51ae4baed270350bb7623564eb1b0f6668cd0df9345164c

Error:
```
Error: invalid hash (argument="value", value="0x0x2f764e23863a0202d51ae4baed270350bb7623564eb1b0f6668cd0df9345164c", code=INVALID_ARGUMENT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46729)
    at Logger.throwError (main.js:166:46862)
    at Logger.throwArgumentError (main.js:166:46923)
    at Formatter.hex (main.js:172:74280)
    at Formatter.hash (main.js:172:74951)
    at StaticJsonRpcProvider.<anonymous> (main.js:172:108055)
    at Generator.next (<anonymous>)
    at ln (main.js:172:79026)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/de2f65d1-e81b-4bdc-9e7f-dd08bc10c37c)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5f3ecd51-1746-4551-a7b0-9f6506a1250e)

## What is the expected/desired behavior
Correct link is: https://avascan.info/blockchain/c/tx/0x2f764e23863a0202d51ae4baed270350bb7623564eb1b0f6668cd0df9345164c

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/001fb396-4b84-4ba0-8f50-1562e5da864d)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].


Ticket is closed.
