### ISSUE TITLE
[QA] Transaction from OneKey wallet fails 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1773]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.00001 APT from Osmosis (OneKey) to Moonbeam (MetaMask through WalletConnect)
2. Click "Approve and proceed with transaction" button

Actual result: Transaction fails.

Error:
```
Error: Broadcasting transaction failed with code 11 (codespace: sdk). Log: out of gas in location: ReadFlat; gasWanted: 0, gasUsed: 1000: out of gas
    at Pr.broadcastTxSync (pb-index.js:490:109837)
    at async Pr.broadcastTx (pb-index.js:490:109584)
    at async fr.sendTransaction (cosmos-nV16HvSD-CyAO9FXW.js:27:776891)
    at async fr.signAndSendTransaction (cosmos-nV16HvSD-CyAO9FXW.js:27:777090)
    at async Dk (cosmos-nV16HvSD-CyAO9FXW.js:112:138489)
    at async signAndSendTransaction (pb-index.js:490:769495)
    at async Operator.send (pb-index.js:496:81757)
    at async Object.Sr [as onClick] (pb-index.js:692:32413)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/55834d6c-9a35-498d-83da-6e29d16b050e)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 
Scenario checked: Send 0.00001 APT from Osmosis (OneKey) to Moonbeam (MetaMask via WalletConnect).

* Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/CA3F9D33FA97DBAC5F38EEDFDD1689F73BEC08A3AEA0EBB92906E77A0A871776)
* Send to tx: [Moonscan](https://moonscan.io/tx/0x839e3c38744ff7e3a3449743e6bd77914502de0339eb82c4c2f36d0d52647d52)
* Link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/34306)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f52b52fd-ce7c-4aec-8c9b-90467ec35832)

Ticket is closed.
