### ISSUE TITLE
[QA] Cannot connect OneKey wallet when Kujira/ Evmos/ Injective network is selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1783]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Select Kujira/ Evmos/ Injective network
2. Try to connect OneKey wallet

- Error when Kujira network is selected and then user wants to connect OneKey wallet
```
Uncaught (in promise) Error: No chain info found for kaiyo-1
    at tu.addChain (cosmos-inyqw_uq.js:27:776273)
    at tu.connect (cosmos-inyqw_uq.js:27:775627)
    at async Fn (main.js:522:205929)
```
- Error when Evmos network is selected and then user wants to connect OneKey wallet
```
Uncaught (in promise) Error: No chain info found for evmos_9001-2
    at xP.addChain (cosmos-inyqw_uq.js:27:776273)
    at xP.connect (cosmos-inyqw_uq.js:27:775627)
    at async Fn (main.js:522:205929)
```
- Error when Injective network is selected and then user wants to connect OneKey wallet
```
Uncaught (in promise) Error: No chain info found for injective-1
    at xP.addChain (cosmos-inyqw_uq.js:27:776273)
    at xP.connect (cosmos-inyqw_uq.js:27:775627)
    at async Fn (main.js:522:205929)
```
    
    
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3d7bcc88-c37e-47a3-80c0-bf4318edd23c)

## Note
Linked to https://github.com/wormhole-foundation/wormhole-connect/issues/1763.

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/. Cannot connect OneKey wallet when Kujira/ Evmos/ Injective network is selected. 

![image](https://github.com/user-attachments/assets/cba9a2ef-b106-4efd-a96a-d4bc69ba4885)

**Comment by tsadovska** [comment]
Cosmos networks are no longer displayed in Networks list on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Closing the ticket.
