### ISSUE TITLE
[QA] [Testnet] Balance is not loading for Injective

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1791]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Select Injective network as source chain
2. Connect Leap wallet 
3. Open Assets list 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/89674924-c858-4e11-9a61-03998a4eb3b6

## What is the expected/desired behavior
Balance is loaded.

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/
Injective Network token balance are not loading, `Failed to fetch balances Error: 3104 RPC not configured`

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIkFaACtIAYxQVYkfIQgphklDPmK9AsIbkxzBCAF8QDoA) [Testnet].
Balance for Injective network is not loading and error appears in Console. 

```
Failed to get token balances Error: Query failed with (18): alloc::string::String not found: query wasm contract failed: invalid request
    at QueryClient.queryAbci (main-UFl2dA4n.js:483:2208)
    at async Object.request (main-UFl2dA4n.js:483:3706)
    at async Object.queryContractSmart (main-UFl2dA4n.js:484:402360)
    at async CosmWasmClient.queryContractSmart (main-UFl2dA4n.js:484:410807)
    at async CosmosContext.getIbcSourceChannel (main-UFl2dA4n.js:484:619878)
    at async CosmosContext.getIbcDestinationChannel (main-UFl2dA4n.js:484:619377)
    at async CosmosContext.deriveIBCDenom (main-UFl2dA4n.js:484:619173)
    at async CosmosContext.getForeignAsset (main-UFl2dA4n.js:484:618468)
    at async Promise.all (/index 0)
    at async CosmosContext.getTokenBalances (main-UFl2dA4n.js:484:620981)
```
