### ISSUE TITLE
[QA] Assets and fees are withdrawn from the account even if transfer approval transaction fails 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1797]
## Describe the current behavior in detail
Checked on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Check WETH (Ethereum) and SOL balance on Solana (Phantom)
2. Prepare to send 0.0001 WETH (Ethereum) from Solana (Phantom) to Ethereum (MetaMask)
3. Click "Approve and proceed with transaction" button
4. If transaction fails with `TransactionExpiredTimeoutError` check WETH (Ethereum) and SOL balance again. 

Actual result: Assets and fees are withdrawn from the account even if transfer approval transaction fails 

Error after clicking on "Approve and proceed with transaction button":
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 4ugEXcPSxPbMCCMA2yuN4SobWj9pwF2aFtWfgsmmfvhFPskUtEAzF22UECA4daj4qoPc1U7vhvGhZNEz5pEAdT2R using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61258)
    at async Connection$1.confirmTransaction (main.js:171:56700)
    at async O.sendTransaction (solana-3Sa-HcsX.js:1:40048)
    at async Ie (solana-3Sa-HcsX.js:1:48158)
    at async signAndSendTransaction (main.js:322:777245)
    at async BridgeRoute.send (main.js:326:22203)
    at async Operator.send (main.js:328:81316)
    at async Object.Gn [as onClick] (main.js:522:101074)
```

Starting balance on Solana:

![Screenshot 2024-03-15 at 10 12 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4825e1f8-804e-4ac7-9b8c-0b825461e14b)

Error after clicking on "Approve and proceed with transaction button":

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/21e7b889-4868-4fd4-a2cb-c99c64a4c579)

Balance after confirmation transaction failure:

![Screenshot 2024-03-15 at 10 15 49](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ffd59ee3-a60e-4a83-9319-30dceccf0cf2)

## What is the expected/desired behavior
Assets and fees are not withdrawn from the account if transaction approval fails.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ [Mainnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Ticket is closed.
