### ISSUE TITLE
[QA] "Insufficient token allowance" error appears in Console when sending USDC from Arbitrum to Solana for the first time

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1832]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 USDC (Arbitrum) from Arbitrum (MetaMask) to Solana (Coin98)
2. Click "Approve and proceed with transaction" button
3. Check if transaction is started

Actual result: Transaction fails with "Insufficient token allowance" error. Transaction is successfully started after user clicks on "Approve and proceed with transaction" button again. 

```
Error: Insufficient token allowance
    at EthContext.approve (pb-index-DsRyVLaa.js:487:81260)
    at async ManualCCTPEvmImpl.send (pb-index-DsRyVLaa.js:495:3827)
    at async CCTPManualRoute.send (pb-index-DsRyVLaa.js:495:83823)
    at async Operator.send (pb-index-DsRyVLaa.js:496:83184)
    at async Object.Co [as onClick] (pb-index-DsRyVLaa.js:715:27517)
```

![Screenshot 2024-03-25 at 16 21 32](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/91500c1c-160f-4aff-81df-986862f10db6)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/3b81f32422/ [Mainnet]. 
USDC transfer from [Arbitrum](https://arbiscan.io/tx/0x7b738a4fe96798d3ae396a1548f187f2870b516e57296e8b7add4260c1247664) (MetaMask) to [Solana](https://explorer.solana.com/tx/2wW4wAutdtLa3Kho1y9uJSyBsiBBbjn2eocLQkqxtVKcPmZMcRrj8e4PzakSkbrovf9UsJ9ahymMBUJXShEfV372) (Coin98) was successful. 
Ticket is closed.
