### ISSUE TITLE
[QA] Claim transaction failed with "Invalid signature for public key" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1840]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 WSOL from Klaytn (MetaMask) to Solana (Clover)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button

Actual result: Claim transaction failed. 

Error:
```
WalletSendTransactionError: Signature verification failed.
Invalid signature for public key [`2WNrr91UNTSc9CxLyEmY6tP4sDekrr8cx4WkYUmtLTSk`].
    at Gt.sendTransaction (solana-qEMpaaW1-Sd7WE_ds.js:7:6021)
    at async C.sendTransaction (solana-qEMpaaW1-Sd7WE_ds.js:7:39970)
    at async Me (solana-qEMpaaW1-Sd7WE_ds.js:7:48208)
    at async signAndSendTransaction (pb-index-DsRyVLaa.js:490:771108)
    at async BridgeRoute.redeem (pb-index-DsRyVLaa.js:494:23028)
    at async Operator.redeem (pb-index-DsRyVLaa.js:496:83271)
    at async Object.Ao [as onClick] (pb-index-DsRyVLaa.js:716:1112)
```

Send from tx: https://klaytnscope.com/tx/0x843fa15ede217bd0a64831ae2f93404371af4cafca4b6428199b14ccf5782cf7

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/09b666ed-686e-4c43-8fe9-d549f568671d)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is also reproducible when sending 0.0001 WSOL from Klaytn (MetaMask) to Solana (Solong). Send from tx: https://klaytnscope.com/tx/0x90fb776ed1701236cb7b3ed03f2210a0084feedbcbf4b987754003ec2f202ab3
 
```
WalletSendTransactionError: Signature verification failed.
Invalid signature for public key [`Dsx5ekUYNM39XX1FQKMYpsjqSVZajTJTEnRZ6xXTjSXV`].
    at Ft.sendTransaction (solana-qEMpaaW1-Sd7WE_ds.js:7:6021)
    at async C.sendTransaction (solana-qEMpaaW1-Sd7WE_ds.js:7:39970)
    at async Me (solana-qEMpaaW1-Sd7WE_ds.js:7:48208)
    at async signAndSendTransaction (pb-index-DsRyVLaa.js:490:771108)
    at async BridgeRoute.redeem (pb-index-DsRyVLaa.js:494:23028)
    at async Operator.redeem (pb-index-DsRyVLaa.js:496:83271)
    at async Object.Ao [as onClick] (pb-index-DsRyVLaa.js:716:1112)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b97066d5-ae9b-4404-800b-372d57234c5a)

**Comment by artursapek** [comment]
is this reproducible on prod portal?

**Comment by tsadovska** [comment]
Linked https://github.com/wormhole-foundation/wormhole-connect/issues/1754

Results with Solflare wallet on https://preview.portalbridge.com/b05f4e9322/ [Mainnet].

Claim fails with TransactionExpiredBlockheightExceededError. Tried 3 times to approve Solflare notification. 
```
TransactionExpiredBlockheightExceededError: Signature 21WTXP1Ci7vVsPih7fsTQQvy91yyokE1MsKUmRVCv7kt3KDrvbHRC23ACws26pjUBDoY2ghcbQ8em7MyTM6QnQAk has expired: block height exceeded.
    at Connection$1.confirmTransactionUsingBlockHeightExceedanceStrategy (pb-index-DsRyVLaa.js:339:58907)
    at async Connection$1.confirmTransaction (pb-index-DsRyVLaa.js:339:56831)
    at async sendAndConfirmTransactionsWithRetry (pb-index-DsRyVLaa.js:487:91554)
    at async postVaaWithRetry (pb-index-DsRyVLaa.js:490:628972)
    at async postVaa (pb-index-DsRyVLaa.js:490:772008)
    at async BridgeRoute.redeem (pb-index-DsRyVLaa.js:494:22857)
    at async Operator.redeem (pb-index-DsRyVLaa.js:496:83271)
    at async Object.Ao [as onClick] (pb-index-DsRyVLaa.js:716:1112)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/de7cac98-f320-475e-b64e-b54a16fbad1d)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/#
Transaction 0.001 WSOL from Klaytn (Metamask) to Solana (Phantom) fails, reason `WalletSendTransactionError: Unexpected error` issue has been reported here https://github.com/wormhole-foundation/wormhole-connect/issues/1807
Attachment:

<img width="1304" alt="Screenshot 2024-03-26 at 16 27 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c848126b-8b06-490b-84cd-192772e93832">

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Linking to this issue https://github.com/wormhole-foundation/wormhole-connect/issues/1754
Transaction results using steps related to this ticked added to the linked ticket

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
Transaction 0.001 WSOL from Aptos (Petra) to Solana (Nighly) failed at Claim, reason `TransactionExpiredBlockheightExceededError: Signature 3oFWeWUJ1dC2jMrnTsgeBF25nfcyHy4L7nAoLSkxcRviEsJw61LHVdNkjdt2TtN5Eems58k3T87DAByE8jZFLL3J has expired: block height exceeded.`
Attachment:
<img width="1346" alt="Screenshot 2024-04-12 at 15 46 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b6ed6712-1b61-4e77-8711-dda55fd9163a">

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/ed4e22522f/
Transaction 0.0001 W from Base to Solana (Solflare) Manual Token transfer route fails at Claim, `TransactionExpiredBlockheightExceededError: Signature 5ni8v3MVFUbUWeteKmJTq63SAZfCTwRDoitpChiF1oe46vbBgow9BAnrBnVMwbuTtwst3mVWykWZ8N8MACi9tTmK has expired: block height exceeded.`
Attachment:

<img width="1283" alt="Screenshot 2024-04-19 at 10 15 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d739d186-cf8c-457e-90b7-2ce829ec76bf">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ed4e22522f/ [Mainnet] (Portal Bridge: 0.2.13, Wormhole Connect: 0.3.4-beta.5-development) when sending 0.0011 W from Ethereum (MetaMask) to Solana (Phantom). 

- Send from tx: [Etherscan](https://etherscan.io/tx/0xfbbf418cea264b9eb8b2356f81fdc15b70201eedf03c7334bf65adeca3f24cbb)
- Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0xfbbf418cea264b9eb8b2356f81fdc15b70201eedf03c7334bf65adeca3f24cbb)

```
TransactionExpiredBlockheightExceededError: Signature 4Z612ZxySyB8x8qJFSLvLucjG6QvLG9htUxgHDHPUf89n7nA1CCQQ57aH852s3k3iihEL9gGYUBMdbkZWiZ1t8i7 has expired: block height exceeded.
    at Connection$1.confirmTransactionUsingBlockHeightExceedanceStrategy (pb-index-uz2Jxxzd.js:347:59105)
    at async Connection$1.confirmTransaction (pb-index-uz2Jxxzd.js:347:57029)
    at async sendAndConfirmTransactionsWithRetry (pb-index-uz2Jxxzd.js:495:91564)
    at async postVaaWithRetry (pb-index-uz2Jxxzd.js:498:629568)
    at async postVaa (pb-index-uz2Jxxzd.js:498:776025)
    at async IA.receiveMessage (pb-index-uz2Jxxzd.js:503:102925)
    at async NttManual.redeem (pb-index-uz2Jxxzd.js:503:120580)
    at async Operator.redeem (pb-index-uz2Jxxzd.js:503:131755)
    at async Object.Ao [as onClick] (pb-index-uz2Jxxzd.js:726:1113)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fd56b17a-c565-43df-af2f-3f662838adf0)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] (Portal Bridge: v0.2.13-Pfe79048439, Wormhole Connect: v0.3.8-beta.0-development) when sending 0.00001 WBNB from Sui (Sui wallet) to Solana (Phantom).

* Send from tx: https://suiscan.xyz/tx/5bZLncB7uxFWrNobUSRSf3w45RZiQQGtFQW29LC9RZow
* Link to Wormholescan: https://wormholescan.io/#/tx/21/ccceeb29348f71bdd22ffef43a2a19c1f5b5e17c5cca5411529120182672ade5/126795

```
TransactionExpiredBlockheightExceededError: Signature qDeRdPNMQQVoJHEjChh9CiciG3R1HurEtoXQ6z49pLfkefPb2WXNoDEzStGMRiC6nXCwzmfQzVLppcCRKCnkVKV has expired: block height exceeded.
    at Connection$1.confirmTransactionUsingBlockHeightExceedanceStrategy (pb-index-DrUOIUci.js:347:58986)
    at async Connection$1.confirmTransaction (pb-index-DrUOIUci.js:347:56910)
    at async sendAndConfirmTransactionsWithRetry (pb-index-DrUOIUci.js:495:91549)
    at async postVaaWithRetry (pb-index-DrUOIUci.js:498:609400)
    at async postVaa (pb-index-DrUOIUci.js:502:58105)
    at async BridgeRoute.redeem (pb-index-DrUOIUci.js:502:78022)
    at async Operator.redeem (pb-index-DrUOIUci.js:505:131972)
    at async Object.Ao [as onClick] (pb-index-DrUOIUci.js:728:1327)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/85b1f1fa-04e4-4bec-8612-a6bd9e21b3cc)

**Comment by tsadovska** [comment]
Issue is no longer reproducible. 

Checked following scenarios on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]:
* Send WSOL from Klaytn (MetaMask) to Solana (Clover): [Klaytnscope](https://klaytnscope.com/tx/0x0f10a1505aae6b82895615fc5fb14ae183918776bbf87c913e66edad1b536326),  [Solana explorer](https://explorer.solana.com/tx/nwCjrX9CnYN9y3ktTyXd4wBALsLeuaktA7JRaUX63XgLKzWZu865jRtTLMJf3vnDuaZHyfkjMkSLm4WhkVuuHAc)
* Send USDT from Base (MetaMask) to Solana (Solong): [Basescan](https://basescan.org/tx/0xae05ecebfcc59594b5a4752546a8a501fa64410e01c63020aee0830c7baedc9b), [Solana explorer](https://explorer.solana.com/tx/3yFMVbQtZEJxygiKpNe47kfq6x6m1x1PMwC128M9cA5AxKHd9TXRg26fVZErfiqqy86mSmQyFL34ptd7MLcUMUu2)

Checked following scenarios on https://portalbridge.com/ [Mainnet]:
* Send WSOL from Klaytn (MetaMask) to Solana (Phantom): [Klaytnscope](https://klaytnscope.com/tx/0x6c463a5cc37331250f98b8b7308c3326d549c5652e42c99bd2bb440f41ce7987?tabId=tokenTransfer), [Solana explorer](https://explorer.solana.com/tx/31moZ9y8NeVyFNVM7sDgGSgQyqDoasUab59pgoFnWgpH6oyxdK8pV9vyWy3ASApHiYiMJ6gDaKqsnheTbyKf9yKy)
* Send WBNB from Sui (Sui wallet) to Solana (Phantom): [Suiscan](https://suiscan.xyz/tx/GiVNeYqHBWdUsHwELwBDLRmEWHDTbVoUo99TYn8pJY4d), [Solana explorer](https://explorer.solana.com/tx/4kwNshNehydHiCqY7XNRHt2eiDzytPeP5U1uKG3XhKH3AKt6zYzJJAi7PcxzwZgMWtyAzU5pM2N8tkXvX3Tfbomd)

Ticket is closed.
