### ISSUE TITLE
[QA] The WalletConnect popup appears approximately 20 seconds after the user clicks the "WalletConnect" option

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1877]
## Describe the current behavior in detail
Checked on https://deploy-preview-1674--wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Select any network (in my case, Fuji)
2. Click "Connect wallet" button
3. Select "WalletConnect" option
4. Notice whether the WalletConnect pop-up appears immediately or after a while

Actual result: WalletConnect pop-up appears after around 20 seconds.

Error appears many times:
```
Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at Al.onClose (index.es-JTK1_VJG.js:40:9364)
    at EventEmitter$2.<anonymous> (index.es-JTK1_VJG.js:40:10005)
    at EventEmitter$2.dt [as emit] (main-Us1SJ_pK.js:84:3498)
    at Ul.onClose (index.es-JTK1_VJG.js:40:13157)
    at e.onclose (index.es-JTK1_VJG.js:40:13025)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bb36e922-d9ad-4ce7-88b0-9639f75fca4a

## What is the expected/desired behavior
WalletConnect pop-up is shown immediately after user selects "WalletConnect" option.

## Notes
Issue is not reproducible on https://wormhole-connect.netlify.app/ [Testnet], https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].

**Comment by tsadovska** [comment]
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/2098.
