### ISSUE TITLE
[QA] WebSocket errors occur repeatedly

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1882]
## Describe the current behavior in detail
Checked on https://deploy-preview-1674--wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome.

Steps:
1. Open Inspect -> Console
2. Select Fuji as source chain
3. Connect MetaMask wallet in From section
4. Select Alfajores network as destination chain
5. Connect MetaMask wallet in To section
6. Select USDC (Fuji) asset
7. Enter amount 0.01
8. Click "Approve and proceed with transaction" button
9. Check if WebSocket errors occur in the Console.

Actual result: WebSocket errors occur repeatedly

`WebSocket is already in CLOSING or CLOSED state.`

```
{context: 'core'} {context: 'core/relayer'} Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at Al.onClose (index.es-JTK1_VJG.js:40:9364)
    at EventEmitter$2.<anonymous> (index.es-JTK1_VJG.js:40:10005)
    at EventEmitter$2.dt [as emit] (main-Us1SJ_pK.js:84:3498)
    at Ul.onClose (index.es-JTK1_VJG.js:40:13157)
    at e.onclose (index.es-JTK1_VJG.js:40:13025)
```
    
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/177c1e53-5094-4003-b802-ece82f5ebfe8)

## What is the expected/desired behavior
WebSocket errors do not occur in the Console.

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/ [Mainnet].

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bf3bd43d-a799-49b9-8458-b42a5ef38305)

**Comment by tsadovska** [comment]
Issue is not reproducible on https://portalbridge.com/. WebSocket error does not occur. 
Scenario checked: 0.00001 WETH (Polygon) transfer from Polygon (MetaMask) to Optimism (MetaMask).

![image](https://github.com/user-attachments/assets/6669beb3-00d8-43b1-a4ee-acd4885b9222)


Issue is also no longer reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).
Scenario checked: 0.001 AVAX transfer from Fuji (MetaMask) to Alfajores (MetaMask).

![image](https://github.com/user-attachments/assets/c037cffc-aa50-4b9c-b2a0-d5644383b01b)


Closing the ticket.
