### ISSUE TITLE
[QA] Error "Account does not exist" appears in Console after changing the asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1943]
## Describe the current behavior in detail
Reproducible on:
* https://testnet.portalbridge.com/ed4e22522f/ [Testnet] (Portal Bridge: 0.2.12, Wormhole Connect: 0.3.4-beta.4-development) 
* https://wormhole-connect.netlify.app/ [Testnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

Checked with macOS 14.4.1 (23E224) and Google Chrome Version 123.0.6312.107 (Official Build) (arm64). 

Steps:
1. Select Solana network as source chain
2. Select Sepolia or Ethereum as destination chain 
3. Connect Phantom or Solflare wallet in From section
4. Connect MetaMask wallet in To section
5. Open Console
6. Select any asset
7. Change asset several times

Actual result: Error "Account does not exist" appears in Console. 
```
Error: Account does not exist 6edQhDFMcCgWrgkvMUJHnPa9SaneFuQx4v2unEGRKMx5
    at En.fetch (pb-index-BqOk2Zp5.js:436:46603)
    at async SolanaRelayer.getForeignContract (pb-index-BqOk2Zp5.js:495:186808)
    at async Promise.all (ed4e22522f/index 0)
    at async SolanaRelayer.calculateRelayerFee (pb-index-BqOk2Zp5.js:495:185146)
    at async SolanaContext.getRelayerFee (pb-index-BqOk2Zp5.js:495:205977)
    at async RelayRoute.getRelayerFee (pb-index-BqOk2Zp5.js:503:143148)
    at async RelayRoute.isRouteAvailable (pb-index-BqOk2Zp5.js:503:137824)
    at async Operator.isRouteAvailable (pb-index-BqOk2Zp5.js:503:129369)
    at async pb-index-BqOk2Zp5.js:725:13859
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c2d98836-7409-40ea-b40d-ee6592d44386

## What is the expected/desired behavior
The error does not appear in the Сonsole after changing an asset.

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ed4e22522f/ [Mainnet] when user prepares to send asset from Solana (Phantom) to Arbitrum (MetaMask). 

Errors appears in Console when user changes assets. 
```
Error: Account does not exist ChePh3HUPs9BdUvxX5Ns7fv7oZbpD2QxDoot8pjuYdN9
    at En.fetch (pb-index-uz2Jxxzd.js:436:46603)
    at async SolanaRelayer.getRegisteredToken (pb-index-uz2Jxxzd.js:495:186950)
    at async Promise.all (ed4e22522f/index 1)
    at async SolanaRelayer.calculateRelayerFee (pb-index-uz2Jxxzd.js:495:185146)
    at async SolanaContext.getRelayerFee (pb-index-uz2Jxxzd.js:495:205977)
    at async RelayRoute.getRelayerFee (pb-index-uz2Jxxzd.js:503:143262)
    at async RelayRoute.isRouteAvailable (pb-index-uz2Jxxzd.js:503:137938)
    at async Operator.isRouteAvailable (pb-index-uz2Jxxzd.js:503:129483)
    at async pb-index-uz2Jxxzd.js:725:13859
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5b853c06-46c2-43d9-8560-d2b2368365f9
