### ISSUE TITLE
[QA] [Mainnet] Transaction fails with "Call exception" error 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1966]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/ed4e22522f/ [Mainnet] (Portal Bridge: 0.2.13, Wormhole Connect: 0.3.4-beta.5-development) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.0011 W from Ethereum (MetaMask) to Solana (Phantom)
2. Select "Native Token Transfer (Approve transfer with destination wallet)" route
3. Click "Approve and proceed with transaction" button

Actual result: Transaction fails with "Call exception" error. 

```
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x0579d9c0fe89997f18b128faa8e78a51fc7eb252a440c6a7bcc56dae76cec71c", transaction={"hash":"0x0579d9c0fe89997f18b128faa8e78a51fc7eb252a440c6a7bcc56dae76cec71c","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","gasPrice":{"type":"BigNumber","hex":"0x03038efd87"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x014832f9"},"maxFeePerGas":{"type":"BigNumber","hex":"0x03038efd87"},"gasLimit":{"type":"BigNumber","hex":"0x040a48"},"to":"0xc072B1AEf336eDde59A049699Ef4e8Fa9D594A48","value":{"type":"BigNumber","hex":"0x00"},"nonce":253,"data":"0xb293f97f0000000000000000000000000000000000000000000000000003e871b540c00000000000000000000000000000000000000000000000000000000000000000013559e9e11c7c0d54d982b103ea3194140a5f1ed299bdb673f1b67fa98a94f4a73559e9e11c7c0d54d982b103ea3194140a5f1ed299bdb673f1b67fa98a94f4a7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000040100010100000000000000000000000000000000000000000000000000000000","r":"0x208ff6ca122d4d780283a8e22dcd3166b95ff712890969614212b17a44d26bf5","s":"0x4b77f5e20b07f4eb8b1fdcd0142c1c9fab72623de2b22f215cc1c32e7b1fafc9","v":0,"creates":null,"chainId":0}, receipt={"to":"0xc072B1AEf336eDde59A049699Ef4e8Fa9D594A48","from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","contractAddress":null,"transactionIndex":164,"gasUsed":{"type":"BigNumber","hex":"0x03fa23"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x45fff58379e35c00f26759a6bc1bb3ac1787c0adb0d6c5e252939978a8da16ca","transactionHash":"0x0579d9c0fe89997f18b128faa8e78a51fc7eb252a440c6a7bcc56dae76cec71c","logs":[],"blockNumber":19688601,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0xcba8a8"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x021074121e"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (pb-index-uz2Jxxzd.js:342:46729)
    at Logger.throwError (pb-index-uz2Jxxzd.js:342:46862)
    at Web3Provider.<anonymous> (pb-index-uz2Jxxzd.js:348:101399)
    at Generator.next (<anonymous>)
    at no (pb-index-uz2Jxxzd.js:348:79192)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c62e2de9-adf7-4e76-aa67-e9605c98616b)

## What is the expected/desired behavior
Transaction has successfully started.

**Comment by tsadovska** [comment]
Tested on https://portalbridge.com/ [Mainnet]. 
Transaction 0.0011 W from [Ethereum](https://etherscan.io/tx/0xaf7731dfe4c6150eefd7a9d0b0986672f038a24b00f2669fd30b6a9c7f9c9da3) (MetaMask) to [Solana](https://explorer.solana.com/tx/BSSx7mtaWNcwyCbB9ukSeGJqvuzvPg5AjWJYhxKhWsFLcE8vVfgwX5fnPvNpyUu73d1m4LiTVhrFcpFyDV7Q3wA) (Phantom) was successfully completed. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5e08cb84-f7ed-4c03-a9ec-18f4964b9d8a)


Ticket is closed.
