### ISSUE TITLE
[QA] [Testnet] Transaction to Mumbai is stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1977]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64).

Steps:
1. Prepare to send 0.01 WBNB from BSC (MetaMask) to Mumbai (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Check if transaction completes

Actual result: Transaction to Mumbai is stuck on Step 2. Send from tx: https://testnet.bscscan.com/tx/0x88e5caabae029a9c97b3eccac86ab011784f87b1ee1035de795ff2e9f6911887

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (main-Zxun-uEe.js:166:46729)
    at Logger.throwError (main-Zxun-uEe.js:166:46862)
    at StaticJsonRpcProvider.<anonymous> (main-Zxun-uEe.js:172:122106)
    at Generator.throw (<anonymous>)
    at Gn (main-Zxun-uEe.js:172:113322)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a25d0a14-7d8e-4c6c-9626-c561a8a1f72a)

## What is the expected/desired behavior
The transaction completes successfully.

**Comment by tsadovska** [comment]
Closing as Mumbai network is no longer displayed in list of networks. 

![image](https://github.com/user-attachments/assets/6b7ac173-a269-427f-ae80-832dc14fa44b)
