### ISSUE TITLE
[QA] "Error: account info is null" occurs when sending from Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1986]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64).

Steps:
1. Prepare to send 0.00001 WETH (Ethereum) from Solana (Phantom) to Osmosis (Leap)
2. Click "Approve and proceed with transaction" button
3. Check for errors in Console

Actual result: "Error: account info is null" occurs.
```
Error: account info is null
    at getAccountData (main-AY3V3pGa.js:319:89653)
    at main-AY3V3pGa.js:319:95307
    at async SolanaContext.getMessage (main-AY3V3pGa.js:319:199245)
    at async WormholeContext.getMessage (main-AY3V3pGa.js:322:628864)
    at async getUnsignedMessageFromNonCosmos (main-AY3V3pGa.js:325:31374)
    at async Object.er [as onClick] (main-AY3V3pGa.js:524:97505)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2d4a359b-5ab5-40c8-bd7f-bd1840e1750c)

## What is the expected/desired behavior
Transaction has successfully started.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Scenario checked: "Send 0.00001 WETH (Ethereum) from Solana (Phantom) to Osmosis (Leap)"
* Send from tx: [Solana explorer](https://explorer.solana.com/tx/4Xo6yU48pMCJBzSd5GMSbGR1P3Z9cpVUJBdZCqqvy6NpJgLw78JpUT3L7r2FTgKZnMq4Vy3ucYBzhVgNdGh7ULzK)
* Send to tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/E69E18EDF394A4837FCE5C8D1A0CF01C69701BC6A7B3F888E85422A0AB36752E)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/01f9b89b-76a6-4b5f-87be-ebbabbfed82d)


Ticket is closed.
