### ISSUE TITLE
[QA] Error "Wormhole Circle relayer contract not found" appears in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2017]
## Environment
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'celo',
    toNetwork: 'fantom',
    token: 'WMATIC',
  }
}
```
## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFraNpQbBYbXJiKA6gFkAggBUAkgGEzYAL4gvQA%3D%3D%3D#) 
2. Open Console
3. Check errors

Actual result: Error occurs in Console.
```
Error: Wormhole Circle relayer contract for domain celo not found
    at EthContracts.mustGetWormholeCircleRelayer (main-aNdJO9Jn.js:481:77754)
    at CCTPRelayRoute.getRelayerFee (main-aNdJO9Jn.js:486:117888)
    at CCTPRelayRoute.isRouteAvailable (main-aNdJO9Jn.js:486:114369)
    at Operator.isRouteAvailable (main-aNdJO9Jn.js:489:129967)
    at main-aNdJO9Jn.js:524:15583
```
Expected result: Error do not occur. 

## Notes/ Attachments

![Screenshot 2024-04-30 at 09 57 02](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f073540a-bb78-40eb-982b-bc878b7200fe)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when Blast network is selected. 

```
Error: Wormhole Circle relayer contract for domain blast not found
    at EthContracts.mustGetWormholeCircleRelayer (pb-index-u9c9TQ3X.js:495:77754)
    at CCTPRelayRoute.getRelayerFee (pb-index-u9c9TQ3X.js:502:216627)
    at CCTPRelayRoute.isRouteAvailable (pb-index-u9c9TQ3X.js:502:213066)
    at Operator.isRouteAvailable (pb-index-u9c9TQ3X.js:505:130047)
    at pb-index-u9c9TQ3X.js:727:13912
```

**Comment by agodlevska** [comment]
Reproducible on https://deploy-preview-2153--wormhole-connect-mainnet.netlify.app/ [Mainnet] when Scroll network is selected.
```
Error: Wormhole Circle relayer contract for domain scroll not found
    at EthContracts.mustGetWormholeCircleRelayer (main-DJhNbBqY.js:498:77756)
    at CCTPRelayRoute.getRelayerFee (main-DJhNbBqY.js:508:131239)
    at CCTPRelayRoute.isRouteAvailable (main-DJhNbBqY.js:508:127720)
    at Operator.isRouteAvailable (main-DJhNbBqY.js:509:89894)
    at main-DJhNbBqY.js:547:18361
```
