### ISSUE TITLE
[QA] Error "Wormhole Connect: error completing transfer TypeError: Failed to fetch" occurs when sending PYTH from Injective to Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2021]
## Environment
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.93 (Official Build) (arm64).
```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'injective',
    toNetwork: 'solana',
    token: 'PYTH',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJFgBWkAMa4MsSIWIRcIybhnzF3ERzTQ0uwWANyYigAoBNACoAJW2AC%2BIXyA#)
2. Enter 0.0001 in Amount field
3. Click "Approve and proceed with transaction" button

Actual result: Transaction fails.
```
Wormhole Connect: error completing transfer TypeError: Failed to fetch
    at iP.getAccount (cosmos-z_FWm-It.js:112:136578)
    at iP.signTransaction (cosmos-z_FWm-It.js:112:137234)
    at async iP.signAndSendTransaction (cosmos-z_FWm-It.js:112:137796)
    at async qO (cosmos-z_FWm-It.js:112:138646)
    at async signAndSendTransaction (main-aNdJO9Jn.js:484:781865)
    at async Operator.send (main-aNdJO9Jn.js:489:132100)
    at async Object.er [as onClick] (main-aNdJO9Jn.js:524:31299)
```
Expected result: Transaction proceeds without errors. 

## Notes/ Attachments
Reproducibility: Issue noticed only once. 

<img width="1130" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dfbb54e9-5a6c-46cb-b529-ba7b796b188a">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending PYTH from Injective (Leap) to Solana (Phantom). 
* Send from tx: [Injective Explorer](https://explorer.injective.network/transaction/894542AD17D3A6EFE8586C1840E1A161786BAB1D3E4038E91A8747757ED5F372/)
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/WU4zGtm9bc43hC7BhkfLsVbVhYkZnyiptrbQ924wKDAbFieXPeT3LK4TVyUnqGWo9YesdkPRm4BerYT3WgKUSRU)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/38157)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6df590c8-a97d-4c82-abf9-814e8a7b4f92)


Ticket is closed.
