### ISSUE TITLE
[QA] "Error computing receive amount" occurs when sending asset via wstETH Bridge

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2024]
## Environment
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.93 (Official Build) (arm64).

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'arbitrum',
    toNetwork: 'optimism',
    token: 'wstETHarbitrum',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGgpkMuCmxSFiEXCMm4Z8xSIAOuDCgzctRQWD1yYiqd1wBRACoAJZavWa2hAAviDBQA#)
2. Enter 0.0000001 in Amount field

Actual result: Warning is shown - Error computing receive amount. 
Expected result: Warning that input amount is too small is shown. 

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/98ce9bd3-3b58-45fb-94d9-399225c9f931)

**Comment by tsadovska** [comment]
Error "Error computing receive amount" occurs on https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000668 wstETH from Polygon (Rabby) to BSC (Rabby). 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cf997dc9-d210-48f0-bc49-8db5bb041954)

**Comment by tsadovska** [comment]
Rechecked scenarios mentioned in the ticket.
* Scenario "Send 0.0000001 wstETH from Arbitrum (MetaMask) to Optimism (MetaMask)" is still reproducible, https://github.com/wormhole-foundation/wormhole-connect/issues/2024#issue-2271440335.  
* Scenario "Send 0.000668 wstETH from Polygon (Rabby) to BSC (Rabby)" is no longer reproducible, https://github.com/wormhole-foundation/wormhole-connect/issues/2024#issuecomment-2116967226

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0003 ETH from Optimism (MetaMask) to Polygon (MetaMask). 

Error appears in Console after clicking on "Approve and proceed with transaction" button:
```
Error: Error computing receive amount
    at H6.computeReceiveAmountInternal (main-KkNX3ZDf.js:509:31694)
    at H6.computeReceiveAmountWithFees (main-KkNX3ZDf.js:509:32190)
    at Operator.computeReceiveAmountWithFees (main-KkNX3ZDf.js:509:92529)
    at tr (main-KkNX3ZDf.js:547:15337)
    at main-KkNX3ZDf.js:547:15627
    at Qj (main-KkNX3ZDf.js:41:26721)
    at Hk (main-KkNX3ZDf.js:41:46757)
    at Wk (main-KkNX3ZDf.js:41:45450)
    at Pk (main-KkNX3ZDf.js:41:44404)
    at Ek (main-KkNX3ZDf.js:41:40660)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e53eb461-7ef7-4ba6-b508-18d5e2fa6f97)
