### ISSUE TITLE
[QA] Notification to add Blast network to MetaMask does not appear

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2043]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64).

Preconditions:
Blast network has not been added to MetaMask.

Steps:
1. Prepare to send 0.002 WAVAX from Avalanche (MetaMask) to Blast (MetaMask)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Check if notification to add network is displayed

Actual result: Notification to add network is not displayed.
```
ChainNotConfiguredForConnectorError: Chain "81457" not configured for connector "injected".
    at Kr.switchChain (evm-DHUFH6z6-C-Y5i1xL.js:35:109543)
    at async ah.switchChain (evm-DHUFH6z6-C-Y5i1xL.js:37:15619)
    at async sh (evm-DHUFH6z6-C-Y5i1xL.js:37:73446)
    at async switchChain (pb-index-DrUOIUci.js:502:56320)
    at async Object.Ao [as onClick] (pb-index-DrUOIUci.js:728:1154)
```
Expected result: Notification to add network is displayed. 

## Notes/ Attachments
* Send from tx: https://avascan.info/blockchain/c/tx/0x7dee6dcca174f366bd197542c5b6a75899c6fe9a2704eb390063beadd32c59cb
* Link to Wormholescan: https://wormholescan.io/#/tx/0x7dee6dcca174f366bd197542c5b6a75899c6fe9a2704eb390063beadd32c59cb

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4d025d3f-b08f-4467-8aca-2f97355a1f91)

Notification to add network appears after clicking on "Claim" button for AVAX transfer from Avalanche to Scroll.

![Screenshot 2024-05-07 at 10 32 32](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/561c290c-a61e-43cc-923c-cb89649d00f9)

**Comment by tsadovska** [comment]
Tested OK on https://deploy-preview-2050--wormhole-connect-mainnet.netlify.app/.
