### ISSUE TITLE
[QA] "TransactionExpiredTimeoutError" occurs during Token registration

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2076]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/3064c36d95/advanced-tools/#/register with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64).

1. Select Solana as source chain and connect Phantom wallet
2. Select asset `So11111111111111111111111111111111111111112`
3. Select Blast as target chain and connect MetaMask wallet
4. Click on "Attest" button

Actual result: Error "TransactionExpiredTimeoutError" appears in Console. 

```
TransactionExpiredTimeoutError: Transaction was not confirmed in 30.00 seconds. It is unknown if it succeeded or failed. Check signature 2ziHGjdRu9RGAxLEja1tSJ6jpvj94Yb4tjNK5kuyMh5DQ2GV1jFKHbF6WbSDa4aEYThiHuZY5ySia7R1TmZqn7KT using the Solana Explorer or CLI tools.
    at e.<anonymous> (854.51b9bdf5.js:2:8509439)
    at p (762.155453d1.js:37:1272458)
    at Generator.<anonymous> (762.155453d1.js:37:1273804)
    at Generator.next (762.155453d1.js:37:1272887)
    at a (762.155453d1.js:37:1420573)
    at s (762.155453d1.js:37:1420776)
```

Expected result: Token is successfully attested. 

## Notes/ Attachments

![Screenshot 2024-05-13 at 12 08 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1c15ff69-8338-4cda-a8f1-00da700af561)

**Comment by tsadovska** [comment]
Step 3 was successfully completed, but Token Registration still failed on Step 4 (ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2079).  
Ticket is closed.

**Comment by tsadovska** [comment]
Successfully registered token. 
* "Send attestation" step: [Solscan](https://solscan.io/tx/5GMkGKzAgdtZnyAwS4m33sFBG4MCNcBbvBqQMFdPHxpmehdcFBTD3nDKZ8nscKcWCBCKVyPoJz2BZAioorCaFuFf)
* "Create wrapped token" step: 0x2ca9bdc622e3f36a6925a8c84f45a1cdd897d629909eb9b1f6ee55d1db45c738

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/85e12ac0-8db9-443a-8cf3-23ff55890a0d)

SOL transfer from [Solana](https://explorer.solana.com/tx/23rVmoRJ61HAiDz6PugHENjqgge5uqGHRYXrx7buCg5hWdeFjX59ZnmqqK6vu6FXpFgHwU5xNmxhfZHx9J41aowJ) (Phantom) to [Blast](https://blastscan.io/tx/0x83cfda064148f9a85d783d141538d41356a7e47933d92ab128f6ce095b865124) (MetaMask) was successful. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2b8e94ea-3442-409f-9819-837a664cddf1)
 
 Ticket is closed.
