### ISSUE TITLE
[QA] [Testnet] Balance is not loading for Blast

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2078]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64).

Steps:
1. Select Blast network as source chain
2. Connect MetaMask wallet in From section
3. Open Assets list

Actual result: Balance is not loading for Blast.
```
Failed to get token balances Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (main-YBVxpu1n.js:329:46729)
    at Logger.throwError (main-YBVxpu1n.js:329:46862)
    at Interface.decodeFunctionResult (main-YBVxpu1n.js:330:14689)
    at Contract.<anonymous> (main-YBVxpu1n.js:335:50203)
    at Generator.next (<anonymous>)
    at Hn (main-YBVxpu1n.js:335:44855)
```

Expected result: Balance is loaded. 

## Notes/ Attachments
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7263fbe9-4fdd-40ef-89b3-aaa6ce8d322e)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/. 
Balance is not loading for Blast.

Attachment:
<img width="1440" alt="Screenshot 2024-09-24 at 10 57 27" src="https://github.com/user-attachments/assets/24ebd49f-010a-455b-b5a9-bb7f37e0ae40">

**Comment by agodlevska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/.
Balance is not loading for Blast.

Reopening the ticket. 

Attachment:
<img width="1435" alt="Screenshot 2024-12-12 at 14 02 39" src="https://github.com/user-attachments/assets/1e7c0ca1-f44e-4aa0-83d1-3a75c9901620" />

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/. 
Balance is not loading for Blast.

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/d7ea3f03-de64-4613-9fa9-75fdd4a610ae" />

**Comment by agodlevska** [comment]
Blast is no longer available on https://wormhole-connect.netlify.app/. 
Closing the ticket.
