### ISSUE TITLE
[QA] [Mainnet] Balances are not loading for Cosmos chains

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2110]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.61 (Official Build) (arm64). 

Steps:
1. Select Osmosis/ Injective/ Evmos/ Kujira as source chain
2. Connect Leap wallet
3. Open Assets list

Actual result: Balances are not loading. 
Errors:
```
main-DW8UvUuB.js:527 Failed to get token balances TypeError: Failed to fetch
    at http (main-DW8UvUuB.js:485:16389)
    at HttpClient.execute (main-DW8UvUuB.js:485:19058)
    at Tendermint37Client.detectVersion (main-DW8UvUuB.js:485:93825)
    at Tendermint37Client.connect (main-DW8UvUuB.js:485:93607)
    at CosmosContext.getTmClient (main-DW8UvUuB.js:485:603650)
    at async CosmosContext.getCosmWasmClient (main-DW8UvUuB.js:485:603905)
    at async CosmosContext.getWhForeignAsset (main-DW8UvUuB.js:485:600192)
    at async CosmosContext.getGatewayForeignAsset (main-DW8UvUuB.js:485:598652)
    at async CosmosContext.getForeignAsset (main-DW8UvUuB.js:485:598457)
    at async Promise.all (/index 5)
```
`POST https://rpc.wormchain-pub.ccvalidators.com/ net::ERR_CERT_DATE_INVALID`

Expected result: Balances are loaded. 

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0b8da85a-9b3e-4b61-96c6-9fcd570761b1)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].

Ticket is closed.

**Comment by agodlevska** [comment]
Reopening.
Tested on https://portalbridge.com/ [Mainnet]
Balance is not loading for Osmosis. 
```
Failed to get token balances Error: Bad status on response: 502
    at filterBadStatus (pb-index-B1Fzf62i.js:511:16065)
    at async HttpClient.execute (pb-index-B1Fzf62i.js:511:19057)
    at async Tendermint37Client.detectVersion (pb-index-B1Fzf62i.js:511:94134)
    at async Tendermint37Client.connect (pb-index-B1Fzf62i.js:511:93914)
    at async CosmosContext.getTmClient (pb-index-B1Fzf62i.js:511:623689)
    at async CosmosContext.getCosmWasmClient (pb-index-B1Fzf62i.js:511:623977)
    at async CosmosContext.getWhForeignAsset (pb-index-B1Fzf62i.js:511:620260)
    at async CosmosContext.getGatewayForeignAsset (pb-index-B1Fzf62i.js:511:618718)
    at async CosmosContext.getForeignAsset (pb-index-B1Fzf62i.js:511:618523)
    at async Promise.all (/index 5)
``` 
Attachment: 
<img width="1440" alt="Screenshot 2024-05-29 at 12 24 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/c3771e07-3b73-41f7-9d8c-1e9b91baaac3">

**Comment by tsadovska** [comment]
Balances on Osmosis, Injective, Evmos, Kujira networks are successfully loaded.
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.

Closing the ticket.
