### ISSUE TITLE
[QA] [Mainnet] Failed to get token balances for multiple networks

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2133]
## Describe the current behavior in detail
Environment:
* Tested NOK: https://wormhole-connect-mainnet.netlify.app/ 
* Tested OK: https://portalbridge.com/ 

Steps:
1. Select Ethereum/ Polygon/ Avalanche/ Blast network as source chain
2. Connect MetaMask wallet
3. Open Assets list

Actual result: Balances are not loading. 

```
Failed to get token balances Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (main-B9lVWixN.js:339:46683)
    at Logger.throwError (main-B9lVWixN.js:339:46816)
    at JsonRpcBatchProvider.<anonymous> (main-B9lVWixN.js:345:122669)
    at Generator.throw (<anonymous>)
    at Gn (main-B9lVWixN.js:345:113885)
```

Expected result: Balances are loaded. 

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/da4dc011-77b7-487b-bc54-cb9253090536)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e31a5848-d4bd-4345-b487-364271336e46

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 
Closing the ticket.

**Comment by tsadovska** [comment]
Issue occurs again. Balances on Ethereum and Fantom are not loading. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
Closing the ticket.
