### ISSUE TITLE
[QA] Balance is not loading for X Layer

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2142]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 125.0.6422.113 (Official Build) (x86_64).

Steps:

1. Select X Layer network as source chain
2. Connect Metamask wallet in From section
3. Open Assets list

Actual Result: Only OKB balance is loaded, the rest of the balance is not loading.
```
Failed to get token balances 
Error: missing revert data in call exception; 
Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] 
(data="0x", transaction={"to":"0x5537857664B0f9eFe38C9f320F75fEf23234D904","data":"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","accessList":null}, error={"reason":"bad response","code":"SERVER_ERROR","status":413,"headers":{"content-length":"30","content-type":"text/plain; charset=utf-8"},"body":"batch requests limit exceeded\n","requestBody":"[{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\"},\"latest\"],\"id\":45,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599\"},\"latest\"],\"id\":46,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000002000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7\"},\"latest\"],\"id\":47,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000020000000000000000000000006b175474e89094c44da98b954eedeac495271d0f\"},\"latest\"],\"id\":48,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000020000000000000000000000004fabb145d64652a948d72533023f6e7a623c7c53\"},\"latest\"],\"id\":49,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000050000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf1270\"},\"latest\"],\"id\":50,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000050000000000000000000000007ceb23fd6bc0add59e62ac25578270cff1b9f619\"},\"latest\"],\"id\":51,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000050000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c3359\"},\"latest\"],\"id\":52,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000004000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c\"},\"latest\"],\"id\":53,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e28600000000000000000000000000000000000000000000000000000000000000040000000000000000000000008ac76a51cc950d9822d68b83fe1ad97b32cd580d\"},\"latest\"],\"id\":54,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000006000000000000000000000000b31f66aa3c1e785363f0875a1b74e27b85fd66c7\"},\"latest\"],\"id\":55,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000006000000000000000000000000b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e\"},\"latest\"],\"id\":56,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e286000000000000000000000000000000000000000000000000000000000000000600000000000000000000000049d5c2bdffac6ce2bfdb6640f4f80f226bc10bab\"},\"latest\"],\"id\":57,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d904\",\"data\":\"0x1ff1e286000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c83\"},\"latest\"],\"id\":58,\"jsonrpc\":\"2.0\"},{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5537857664b0f9efe38c9f320f75fef23234d9    at Logger.makeError (main-Bag6NT_N.js:339:46683)
    at Logger.throwError (main-Bag6NT_N.js:339:46816)
    at checkError$1 (main-Bag6NT_N.js:345:114653)
    at JsonRpcBatchProvider.<anonymous> (main-Bag6NT_N.js:345:125508)
    at Generator.throw (<anonymous>)
    at Gn (main-Bag6NT_N.js:345:113930)
``` 
Expected result: Balance is loaded for all tokens.

## Attachments
<img width="1440" alt="Screenshot 2024-05-29 at 11 58 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/aa986a58-0e3a-4d73-bde4-5e2d2a7f6421">

**Comment by agodlevska** [comment]
Reproducible on https://wormhole-connect.netlify.app/. [Testnet]
Balance is not loading for all tokens. 
Attachment:
<img width="1440" alt="Screenshot 2024-05-29 at 12 42 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/b9d74ff2-7f13-407c-9082-34f83384faec">

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/ (Portal Bridge: v0.2.15-a72f06ca0f, Wormhole Connect: v^0.3.20-beta.1-development), token balances have been loaded successfully.
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2232.
Closing the ticket.

**Comment by agodlevska** [comment]
Issue reproducible on https://wormhole-connect.netlify.app/, balance is not loading. 

Reopening the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2024-12-12 at 11 23 00" src="https://github.com/user-attachments/assets/ae1922eb-c039-4e2e-8dda-3c031ae7899e" />

**Comment by tsadovska** [comment]
Balances are now displayed on https://wormhole-connect.netlify.app/.

![image](https://github.com/user-attachments/assets/baa23050-015d-44a5-af2d-d523fab09897)
