### ISSUE TITLE
[QA] Cannot connect Solong wallet after resuming transaction 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2163]
## Describe the current behavior in detail
Checked on https://deploy-preview-2153--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Resume transaction (0.00123 USDC transfer from Optimism (MetaMask) to Solana (Solong)) `0xc608ae7b0925bd5699eff86dfc239c1bf0cc667c37e05601fcb19ff74dd82095` (Optimism)
2. Click on "Connect wallet" button
3. Click on Solong option
4. Check if Solong wallet is connected 

Actual result: Wallet is not connected.
```
Uncaught (in promise) WalletAccountError
    at qt.connect (solana-B7KdUVUi.js:2:29578)
```
Expected result: Wallet is connected. 

## Notes/ Attachments
* Send from tx: [Optimism explorer](https://optimistic.etherscan.io/tx/0xc608ae7b0925bd5699eff86dfc239c1bf0cc667c37e05601fcb19ff74dd82095)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0xc608ae7b0925bd5699eff86dfc239c1bf0cc667c37e05601fcb19ff74dd82095)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fd2fe66b-2611-408a-b700-1165143bc8cd

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Transaction is completed. 
* Send from tx: https://optimistic.etherscan.io/tx/0xc608ae7b0925bd5699eff86dfc239c1bf0cc667c37e05601fcb19ff74dd82095
* Send to tx: https://explorer.solana.com/tx/43W3KEn6rjMCM5JsciNMDxSTPAaLkGnRxQNjSCcCDFAqz6tFyFsVWy3U97GWgV91rrQ4cY2KW759tTxTbvUrhyHR
* Link to Wormholescan: https://wormholescan.io/#/tx/0xc608ae7b0925bd5699eff86dfc239c1bf0cc667c37e05601fcb19ff74dd82095

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/291fcdfb-5275-4b89-82be-a154a95ba475)


Ticket is closed.

**Comment by tsadovska** [comment]
Reopening the issue. It is reproducible on https://preview.portalbridge.com/933197c94d/ [Mainnet] when sending 0.00001 W from Ethereum (MetaMask) to Solana (Solong). Cannot connect Solong wallet after transaction is resumed. 
* Send from tx: [Etherscan](https://etherscan.io/tx/0x0916b311beb3f5e47554669b627d915fa5d7d867a749c86c0c2f44642926613f)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x0916b311beb3f5e47554669b627d915fa5d7d867a749c86c0c2f44642926613f) 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/94dff2da-a63c-4089-b26f-b8a97bde9107

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ [Mainnet]. Cannot connect Solong wallet after resuming tx. 
* Send from tx: https://etherscan.io/tx/0xfcfd2690f9bd4445cf243149c87cbfa9d6b2567b7b4c062c82ab6de54c588fb6
* Link to Wormholescan: https://wormholescan.io/#/tx/0xfcfd2690f9bd4445cf243149c87cbfa9d6b2567b7b4c062c82ab6de54c588fb6

Error appears in Console after user click on Solong option: 
```
Uncaught (in promise) WalletAccountError
    at Kt.connect (solana-CF9C9ZOg-CG5RsVLZ.js:7:29592)
```
