### ISSUE TITLE
[QA] An "Unexpected error" occurs when user changes network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2176]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/3b81f32422/ [Mainnet] (Portal Bridge: v0.2.15-Pf0410ac8df Wormhole Connect: v0.3.12-beta.2-development) with macOS Sonoma 14.5 and Google Chrome Version 125.0.6422.113 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.001 BNB from BSC (MetaMask) to Solana (Phantom)
2. Change "From" network to Fantom.

Actual result: An unexpected error has occurred - "An unexpected error has occurred. Please refresh the page."
```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Xh (pb-index-W-Mx2rcE.js:44:21973)
    at dj (pb-index-W-Mx2rcE.js:46:3493)
    at Wk (pb-index-W-Mx2rcE.js:46:49465)
    at Vk (pb-index-W-Mx2rcE.js:46:43855)
    at Uk (pb-index-W-Mx2rcE.js:46:43778)
    at Jk (pb-index-W-Mx2rcE.js:46:43618)
    at Ok (pb-index-W-Mx2rcE.js:46:39596)
    at Fk (pb-index-W-Mx2rcE.js:46:40494)
    at jg (pb-index-W-Mx2rcE.js:44:3542)
    at pb-index-W-Mx2rcE.js:46:37736 
``` 
## Attachments  

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/d7df83b9-0457-42c5-ac19-9b3aa711428f

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:
1. Select Ethereum as source chain and connect MetaMask wallet
2. Select Avalanche as target chain and connect MetaMask wallet
3. Select ETH asset
4. Change target chain to Fantom 

Actual result: An unexpected error has occurred - "An unexpected error has occurred. Please refresh the page."

```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nh (main-HNR-Orw1.js:39:19157)
    at cj (main-HNR-Orw1.js:41:3497)
    at Vk (main-HNR-Orw1.js:41:49475)
    at Uk (main-HNR-Orw1.js:41:43863)
    at Tk (main-HNR-Orw1.js:41:43786)
    at Ik (main-HNR-Orw1.js:41:43626)
    at Nk (main-HNR-Orw1.js:41:39598)
    at Ek (main-HNR-Orw1.js:41:40496)
    at jg (main-HNR-Orw1.js:39:3536)
    at main-HNR-Orw1.js:41:37740 

```


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3468fe6c-5714-4394-adae-8fb0dc54dccb

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/2c6f665417/ [Mainnet] with the scenario mentioned in the comment above:

1. Select Ethereum as source chain and connect MetaMask wallet
2. Select Avalanche as target chain and connect MetaMask wallet
3. Select ETH asset
4. Change target chain to Fantom

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ [Mainnet] with following scenario:
1. Select Ethereum as source chain and connect MetaMask wallet
2. Select BSC as target chain and connect MetaMask wallet
3. Select wstETH Bridge
4. Change target chain to Solana

Error appears in Console:
```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Xh (pb-index-CrEkVHsa.js:44:21973)
    at dj (pb-index-CrEkVHsa.js:46:3493)
    at Wk (pb-index-CrEkVHsa.js:46:49465)
    at Vk (pb-index-CrEkVHsa.js:46:43855)
    at Uk (pb-index-CrEkVHsa.js:46:43778)
    at Jk (pb-index-CrEkVHsa.js:46:43618)
    at Ok (pb-index-CrEkVHsa.js:46:39596)
    at Fk (pb-index-CrEkVHsa.js:46:40494)
    at jg (pb-index-CrEkVHsa.js:44:3542)
    at pb-index-CrEkVHsa.js:46:37736 {componentStack: '\n    at RouteOption (https://preview.portalbridge.…dge.com/ba2ee08429/pb-index-CrEkVHsa.js:61:12462)'}
```


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/77b7b8ba-0691-42e5-857d-5fbe2da2656a

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
The issue is no longer reproducible; no errors occur when the user changes the network.

Closing the ticket.
