### ISSUE TITLE
[QA] [Mainnet] Balances for multiple networks are not loading

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2182]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Select Ethereum as source chain
2. Connect MetaMask wallet
3. Open Assets list
4. Check if balances are loaded 

Actual result: Balance is not loading. 

```
Failed to get token balances Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (main-HNR-Orw1.js:339:46683)
    at Logger.throwError (main-HNR-Orw1.js:339:46816)
    at JsonRpcBatchProvider.<anonymous> (main-HNR-Orw1.js:345:122714)
    at Generator.throw (<anonymous>)
    at Gn (main-HNR-Orw1.js:345:113930)
```
    
Expected result: Balance is loaded. 

## Notes/ Attachments
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following networks: 
* Ethereum
* Polygon
* Avalanche
* Fantom
* Celo
* Moonbeam
* Arbitrum
* Optimism
* Klaytn
* Scroll
* Blast
* X Layer

Issue is reproducible on https://portalbridge.com/ [Mainnet] with Klaytn network.

Issue is not reproducible on https://portalbridge.com/ [Mainnet] with following networks:  Ethereum, Polygon, Fantom, Celo, Moonbeam, Arbitrum, Optimism, Scroll, Z Layer networks.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7d6bfe52-7214-4658-a200-3af512ba4484

**Comment by tsadovska** [comment]
Balances are successfully loading for Ethereum, Polygon, Avalanche, Fantom, Celo, Moonbeam, Arbitrum, Optimism, Klaytn, Scroll and Blast on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2142.
