### ISSUE TITLE
[QA] An "Unexpected error" occurs after swapping chains - Token Bridge route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2184]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Brave Browser Version 1.66.115 Chromium: 125.0.64322.112. 

Steps:
1. Prepare to send AVAX from Fuji (Brave wallet) to Solana (Brave wallet)
2. Click on "Swap" button

Actual result: An unexpected error has occurred.

```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nh (main-0-9QBYvg.js:39:19157)
    at cj (main-0-9QBYvg.js:41:3497)
    at Vk (main-0-9QBYvg.js:41:49475)
    at Uk (main-0-9QBYvg.js:41:43863)
    at Tk (main-0-9QBYvg.js:41:43786)
    at Ik (main-0-9QBYvg.js:41:43626)
    at Nk (main-0-9QBYvg.js:41:39598)
    at Ek (main-0-9QBYvg.js:41:40496)
    at jg (main-0-9QBYvg.js:39:3536)
    at main-0-9QBYvg.js:41:37740
```

Expected result: Error does not occur after swapping chains. 

## Notes/ Attachments

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ffa95f11-8c3f-4445-b009-4e5fc4fde997

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/2c6f665417/ [Mainnet] with following scenario:
1. Select Avalanche network as source chain and connect MetaMask wallet
2. Select Solana network as target chain and connect Backpack wallet
3. Select AVAX asset
4. Change target chain to Aptos
5. Change target chain back to Solana
6. Click on "Swap" button

Actual result: An "Unexpected error" occurs.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/84b5bd1e-f0f5-4145-a3fe-8416c20cdd70
