### ISSUE TITLE
[QA] Fee and asset info are not displayed in "Send to" section when sending asset to Sui network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2189]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Prepare to send 0.001 wKLAY from Fantom (MetaMask) to Sui (Sui Wallet)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Check "Send to" section

Actual result: Fee and asset info are not displayed in "Send to" section.
Expected result: Fee and asset info are displayed in "Send to" section.

## Notes/ Attachments
* Send from tx: [FtmScan](https://testnet.ftmscan.com/tx/0x841145d2220e091ecdd21819b81718386ae378344fe052e86a438df9fa1aabfe)
* Send to tx: [Sui Explorer](https://suiscan.xyz/testnet/tx/7EPDxqcsqZH4zDC9XeoY3zsaRH5VQSr9VeQdEdzaES7p)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x841145d2220e091ecdd21819b81718386ae378344fe052e86a438df9fa1aabfe?network=TESTNET)
* Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/975

```
Error: RPC Error: Could not find the referenced transaction [TransactionDigest(7EPDxqcsqZH4zDC9XeoY3zsaRH5VQSr9VeQdEdzaES7p)].
    at JsonRpcClient$1.requestWithType (main-0-9QBYvg.js:471:958)
    at async JsonRpcProvider.getTransactionBlock (main-0-9QBYvg.js:471:34073)
    at async SuiContext.getTxGasFee (main-0-9QBYvg.js:498:211498)
    at async WormholeContext.getTxGasFee (main-0-9QBYvg.js:501:627523)
    at async BridgeRoute.getTransferDestInfo (main-0-9QBYvg.js:506:85124)
    at async main-0-9QBYvg.js:548:111

```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3b492029-d37a-4ea7-854d-439306355940)

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 SUI from Evmos (Leap) to Sui (Sui Wallet) with Cosmos Gateway route. 
* Send from tx: [MintScan](https://www.mintscan.io/evmos/tx/D1F4ACB5C4E2BC7391A0A73E3BCCF05C02CD91D2BB70F01B45828282FD3BE7F9)
* Send to tx: [Sui Explorer](https://suiscan.xyz/tx/9Au57VTD5uVYYSziiS7c8L9wPA2JM9egYCF5GFA7gH7m)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5a104c83-9fc5-49db-8714-64bee8834100)

**Comment by tsadovska** [comment]
Issue is not reproducible on https://portalbridge.com/ [Mainnet]. Amount and Gas fee are shown. 

![image](https://github.com/user-attachments/assets/94c0efbe-b15e-401a-aa91-97f65c0f002d)

Only Amount is displayed in "Send to" section on https://wormhole-connect.netlify.app/ [Testnet]. Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2269

![image](https://github.com/user-attachments/assets/af794761-4812-402e-b13a-042d7ce0b600)


Ticket is closed.
