### ISSUE TITLE
[QA] Native balance is not loading for Aptos network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2200]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/2c6f665417/ with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.57 (Official Build) (x86_64).

Steps:
- Select Aptos network as source chain
- Connect Rise/Petra wallet in From section
- Open Assets list

Actual Result: Native balance is not loading.
```
Failed to get native balance Error: {"message":"Bad Request"}
    at Dt.value (pb-index-sxeJvfjX.js:349:26354)
    at async CoinClient.checkBalance (pb-index-sxeJvfjX.js:349:34293)
    at async AptosContext.checkBalance (pb-index-sxeJvfjX.js:499:20594)
    at async AptosContext.getNativeBalance (pb-index-sxeJvfjX.js:499:19902)
    at async WormholeContext.getNativeBalance (pb-index-sxeJvfjX.js:511:626934)
    at async pb-index-sxeJvfjX.js:742:68062
``` 

Expected result: Native balance is loading.
## Notes/Attachments
<img width="1440" alt="Screenshot 2024-06-17 at 10 54 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/ef854243-4b56-48cc-9239-1600e0c7de68">

**Comment by agodlevska** [comment]
Closing ticket since the issue is only reproduced on the Portal Bridge. Issue opened here - https://github.com/XLabs/portal-bridge-ui/issues/886.
