### ISSUE TITLE
[QA] [Testnet] Transaction stuck on Step 2, SUI transfer from Sui to BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2206]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Prepare to send 0.3 SUI from Sui (Sui Wallet) to BSC (MetaMask) with Automatic route
2. Click on "Approve and proceed with transaction" button

Actual result: Transaction stuck on Step 2.

```
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":47,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}", error={"code":-32005}, requestBody="{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x2769fca\",\"toBlock\":\"latest\",\"address\":\"0x9563a59c15842a6f322b10f69d1dd88b41f2e97b\",\"topics\":[\"0xcaf280c8cfeba144da67230d9b009c8f868a75bac9a528fa0474be1ba317c169\",\"0x0000000000000000000000000000000000000000000000000000000000000015\",\"0x40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9\",\"0x00000000000000000000000000000000000000000000000000000000000002a2\"]}],\"id\":47,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://data-seed-prebsc-1-s3.binance.org:8545", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (main-B4sWFOrU.js:339:46683)
    at Logger.throwError (main-B4sWFOrU.js:339:46816)
    at main-B4sWFOrU.js:342:100881
    at Generator.next (<anonymous>)
    at Hn (main-B4sWFOrU.js:342:96208)
```

 
Expected result: Transaction completed successfully. 

## Notes/ Attachments
* Send from tx: [Sui Explorer](https://suiscan.xyz/testnet/tx/EKbTgbATXYSdYxQVBrWtRfkLArYtgSghZFT6M363DcEr)
* Link to [Wormholescan](https://wormholescan.io/#/tx/21/40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9/674?network=TESTNET) 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/96994c0a-f4c6-441b-8da0-a6cfc887de9d)

**Comment by tsadovska** [comment]
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/1160.
