### ISSUE TITLE
[QA] Transaction from Ethereum fails with "MetaMask - RPC Error" and "computing receive amount" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2209]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/933197c94d/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 126.0.6478.62 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0002 ETH from Ethereum (MetaMask) to Optimism (MetaMask)
2. Click on "Approve and proceed with transaction" button
3. Confirm MetaMask notification

Actual result: Transaction fails. 
`MetaMask - RPC Error: Transaction does not have a transaction hash, there was a problem {code: -32603, message: 'Transaction does not have a transaction hash, there was a problem'}`

`Wormhole Connect: error completing transfer {code: -32603, message: 'Transaction does not have a transaction hash, there was a problem'}`

```
Error: Error computing receive amount
    at f3.computeReceiveAmountInternal (pb-index-D31SaQCC.js:519:31402)
    at f3.computeReceiveAmountWithFees (pb-index-D31SaQCC.js:519:31900)
    at Operator.computeReceiveAmountWithFees (pb-index-D31SaQCC.js:519:92458)
    at ko (pb-index-D31SaQCC.js:742:10883)
    at pb-index-D31SaQCC.js:742:11175
    at Rj (pb-index-D31SaQCC.js:46:26723)
    at Ik (pb-index-D31SaQCC.js:46:46749)
    at Xk (pb-index-D31SaQCC.js:46:45442)
    at Qk (pb-index-D31SaQCC.js:46:44396)
    at Fk (pb-index-D31SaQCC.js:46:40658)
```

## Notes/ Attachments
* Issue is reproducible with ETH Bridge route. Scenario checked - 0.0002 ETH transfer from Ethereum (MetaMask) to Arbitrum (MetaMask).
* Issue is reproducible with Native Token Transfer route. Scenario checked - 0.00001 W transfer from Ethereum (MetaMask) to Solana (Solong). 
* Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2186

ETH Bridge route: 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8ecbb39b-2f45-4ea3-bba4-755d518f7d80)

![Screenshot 2024-06-19 at 09 54 05](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6b295ed3-5a60-45a6-9f6e-4260695ec3fd)

Native Token Transfer route:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/969ebc30-c8c8-42f3-aada-46f27e00e645)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/933197c94d/ 
Scenarios - Tested OK:
* ETH transfer from [Ethereum](https://etherscan.io/tx/0x3f648fb6afb45a09fad87d6989b6ddc391a4614e5c9d376a835a59b1fc67e679) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0x4589e069382d3ab8405d3e008c595cefcd3f5516345e8c6a68756ad8bddcbe59) (MetaMask)
* ETH transfer from [Ethereum](https://etherscan.io/tx/0x35adafa5b92f94805f19a0a9bfcd091efb8da2a1c8372e9b05ee2e55e844c336) (MetaMask) to  [Optimism](https://optimistic.etherscan.io/tx/0x6932e0a82c819f35175354937fca60c9c933bd5f7863dfbe6b4243b984380822) (MetaMask)

Ticket is closed.
