### ISSUE TITLE
[QA] Transaction from Base to Arbitrum fails with "cannot estimate gas" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2220]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/954c469c33/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.115 (Official Build) (arm64).

Steps:
1. Prepare to send 0.1 USDT from Base (MetaMask) to Arbitrum (MetaMask)
2. Click on "Approve and proceed with transaction" button

Actual result: Transaction fails. 

```
Wormhole Connect: error completing transfer Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: target not registered", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0xaE8dc4a7438801Ec4edC0B035EcCCcF3807F4CC1","data":"0x1019d654000000000000000000000000ff0c62a4979400841efaa6faadb07ac7d5c98b2700000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000170000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: target not registered","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000015746172676574206e6f7420726567697374657265640000000000000000000000","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (pb-index-BFfMC7jt.js:349:46683)
    at Logger.throwError (pb-index-BFfMC7jt.js:349:46816)
    at checkError$1 (pb-index-BFfMC7jt.js:355:114909)
    at Web3Provider.<anonymous> (pb-index-BFfMC7jt.js:355:125508)
    at Generator.throw (<anonymous>)
    at ar (pb-index-BFfMC7jt.js:355:113930)
    at ir.invoke (pb-index-BFfMC7jt.js:748:6920)
    at Tr.run (pb-index-BFfMC7jt.js:748:1929)
    at pb-index-BFfMC7jt.js:749:647
    at ir.invokeTask (pb-index-BFfMC7jt.js:748:7579)
```

Expected result: Transaction proceeds without error. 

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/92c5c3d3-aec1-4a8d-b3a7-d3a64a8dd48b)

Issue is also reproducible when sending 0.01 DAI from Base (MetaMask) to Arbitrum (MetaMask).

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/17d84b48-8d6d-4f9a-b7a6-d019f1c14d77)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/954c469c33/ [Mainnet].
Scenarios checked:
* USDT transfer from [Base](https://basescan.org/tx/0xc2b917cc2990b21cecaad535671dde1424455f9a933752a01a0d2ad567ab9291) to [Arbitrum](https://arbiscan.io/tx/0x67955ad8070b147bd476246e7077d193b617b323c353c3e5267a686707d3cc57)
* DAI transfer from [Base](https://basescan.org/tx/0x01e8d872f061dcd935062b79d3f9903ca92dafc85affe885cf25d631931082a7) to [Arbitrum](https://arbiscan.io/tx/0x3e7df1c625c6b15c65263978095d7f364f7caacc3f7601328eeda531ae3d4d6e)
* USDT  transfer from [Base](https://basescan.org/tx/0x61bd1d71a1a21905a9f8129ec34cf284640cab2a6f87f03afa34fc88cc7703b7) to [Optimism](https://optimistic.etherscan.io/tx/0x4a20bf128dd9460c3bd323057698f012be9501be6aff2d9f01659983766a7909)
* DAI transfer from [Base](https://basescan.org/tx/0xffece9e6791c57853fcd1abecfea28a7e041a4422f19721a4d747e7acf988c92) to [Optimism](https://optimistic.etherscan.io/tx/0xc89ccbf3599a1a904aaee5c2ea7d5c68e876365dbe9f28ae8c40ade5d5be660d) 

Ticket is closed.
