### ISSUE TITLE
[QA] Transactions from Polygon fails with "missing revert data in call exception" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2231]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.0001 MATIC from Polygon (MetaMask) to Arbitrum (MetaMask)
2. Click on "Approve and proceed with transaction" button

Actual result: Transaction fails. 
Expected result: Transaction proceeds without errors. 

```
Wormhole Connect: error completing transfer Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE","value":{"type":"BigNumber","hex":"0x5af3107a4000"},"data":"0x9981509f00000000000000000000000000000000000000000000000000000000000000170000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060c00000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"header not found","cause":null}}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (main-BsiPvwn7.js:339:46683)
    at Logger.throwError (main-BsiPvwn7.js:339:46816)
    at checkError$1 (main-BsiPvwn7.js:345:114653)
    at Web3Provider.<anonymous> (main-BsiPvwn7.js:345:125508)
    at Generator.throw (<anonymous>)
    at Gn (main-BsiPvwn7.js:345:113930)
```

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d5319290-8717-4640-bd64-3acbde8595aa)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ [Mainnet]. 
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x5e4912e63d7be7b1e43a137bec5bf5362ad25a11eaeeefa7ecfff200edd526d7)
* Send to tx: [Arbiscan](https://arbiscan.io/tx/0x8fbbb02ad256bc38e739f726d0861647de09a20777e51621a98d60306cc600e4)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x5e4912e63d7be7b1e43a137bec5bf5362ad25a11eaeeefa7ecfff200edd526d7)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6a9aa9d9-66ba-4724-977a-de40b9f38d12)

Ticket is closed.
