### ISSUE TITLE
[QA] Transaction is shown as complete, although "Send to" transaction fails with "Insufficient Funds For Rent" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2245]
## Describe the current behavior in detail
Сhecked on https://preview.portalbridge.com/3365c86aff/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (arm64).

Preconditions:
User has small amount of SOL (in my case, 0.00145 SOL $0.20).

Steps:
1. Prepare to send 0.00001 tBTC from Optimism (MetaMask) to Solana (Phantom)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Check transaction status on Portal Bridge
5. Click on "Solana Explorer" link
6. Check transaction status

Actual result: Transaction is shown as completed on Portal Bridge and failed on Solana Explorer.
Expected result: A transaction is shown as complete on the Portal Bridge only if it is successfully completed on the Solana Explorer.

## Notes/ Attachments
* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x33d238e8999c392fcfbb9ed17128329d9a8aac789e97efef125861b1dbb509c9)
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/5XQB3HVZ1L7XCVPVPBLwkADU9aLaFocAs4GSEdZepSVMrfoknELpj7TS8U6bSxEoquQNDMdG1vVmW2Sjp2TN9mnH)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x33d238e8999c392fcfbb9ed17128329d9a8aac789e97efef125861b1dbb509c9)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/60efdbe8-6f83-454a-942f-9c84b0150dab

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet]. 
Scenario checked: 0.00001 tBTC transfer from Optimism (MetaMask) to Solana (Phantom).

Transaction is shown as complete on the Portal Bridge even though it failed.
Error in Console:
```
TypeError: Cannot read properties of undefined (reading 'instructions')
    at SolanaContext.getTxGasFee (pb-index-COTaCqdP.js:508:190847)
    at async WormholeContext.getTxGasFee (pb-index-COTaCqdP.js:511:627532)
    at async TBTCRoute.getTransferDestInfo (pb-index-COTaCqdP.js:516:84904)
    at async pb-index-COTaCqdP.js:743:111
```

![image](https://github.com/user-attachments/assets/e5ed22ff-34eb-4d93-ab92-19355bf79060)

* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x625a4637561d61625cf906f25a1df4f626d4a8f8f62f9d6fc57776f953d51171)
* Send to tx: [Solscan](https://explorer.solana.com/tx/65KJe7cxAYmucTrAvgtgZcBX1TwHvJu6TVKqTCKmX5MHRogkH61tvuQieAuocoYPq31pDZba4Ec1hAcNsKhYC2SQ)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x625a4637561d61625cf906f25a1df4f626d4a8f8f62f9d6fc57776f953d51171) 


![image](https://github.com/user-attachments/assets/7e30c8c1-d012-405a-ad33-b16a64ef5700)
