### ISSUE TITLE
[QA] "Amount" and "Gas fee" are not shown in "Send to" section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2254]
## Describe the current behavior in detail
Checked on https://portalbridge.com/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (arm64).

Steps:
1. Send 0.00001 WMATIC from Injective (Leap) to Base (MetaMask)
2. Check if "Amount" and "Gas" are shown in "Send to" section

Actual result: "Amount" and " Gas fee" are not shown.
Expected result: "Amount" and " Gas fee" are shown.

## Notes/ Attachments
* Send from tx:[Injective Explorer](https://explorer.injective.network/transaction/881E9356B0032B9FE33A61DF1799F0DC36BD83DCEE6AB775A71CD98BD9135516/)
* Send to tx: [BaseScan](https://basescan.org/tx/0x5300cfa0eda63de926dde57332babe13debcb5eb40cd6e98ceb0de3901311bda)
* Link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/39380)

![Screenshot 2024-07-17 at 17 24 47](https://github.com/user-attachments/assets/b7b7c0cc-ce53-41ff-8720-5dbdaa824d8c)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/3365c86aff/ [Mainnet] when sending 0.0001 USDC from Arbitrum (MetaMask) to Avalanche (MetaMask). 
* Send from tx: [Arbiscan](https://arbiscan.io/tx/0xdbb3e6f407b4859ec647a1c490bb23a1c073ca80d792a3feb76354b9771c35ea)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0x3ba1aad87715e8160f464a219c7c0948868af40d4862bebc14d228a0748096c4)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xdbb3e6f407b4859ec647a1c490bb23a1c073ca80d792a3feb76354b9771c35ea)


![image](https://github.com/user-attachments/assets/349b162b-2c74-4d8d-8a01-18f50ed035d6)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/859350d189/ [Mainnet] when sending 0.0001 WIF from Solana (Phantom) to Moonbeam (MetaMask). 

```
TypeError: Cannot destructure property 'gasUsed' of 'yr' as it is null.
    at EthContext.getTxGasFee (pb-index-CZhFlO9z.js:515:78634)
    at async WormholeContext.getTxGasFee (pb-index-CZhFlO9z.js:522:627562)
    at async BridgeRoute.getTransferDestInfo (pb-index-CZhFlO9z.js:527:80017)
    at async pb-index-CZhFlO9z.js:764:111
```

![image](https://github.com/user-attachments/assets/be8c770b-96e0-44e0-b568-fc90d59fdd61)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. Amount and Gas fees are displayed in "Send to" section.  

Checked following scenarios:
* WMATIC transfer from [Injective](https://explorer.injective.network/transaction/DF0F7C042DCFCDF0A1D144C46EDB27396B1699CFD2100E139439BAB93FD6CD14/) (Leap) to [Base](https://basescan.org/tx/0x65c2f67d5d35c7370611327938f792b92142d49a6a9d4ca07f6054fc68ed3d38) (MetaMask) 
* USDC transfer from [Arbitrum](https://arbiscan.io/tx/0x4b88c919a19bc869ec1f33c22c8dfd551f53179b8331f1193f7bc175c6d0cc7f) (MetaMask) to [Avalanche](https://avascan.info/blockchain/c/tx/0x0da1c3ec6769c31436d157a57a597c04406cb570078eefbff5e18c7f8fe8b911) (MetaMask)
* WIF transfer from [Solana](https://explorer.solana.com/tx/5n8ntMA7QMJPS9xfmsrdngynLZk8LVfUNc4WmrupjomxVRXjn5w1F92HZrPvSp9niquTqH5w1yKPzHTwycdKhVoC) (Phantom) to [Moonbeam](https://moonscan.io/tx/0x79af11cd5d8dbf47a6a97178b6bf5b28a1d1c847f7f9bf37efb9168ce33857e7) (MetaMask)

Ticket is closed.
