### ISSUE TITLE
[QA] Balances for several networks are not loaded

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2298]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

* Balances for following networks are **not loaded**: Ethereum, Polygon, Avalanche, Fantom, Celo, Moonbeam, Arbitrum, Optimism, Klaytn, Injective, Scroll, Blast.
* Balances for following networks are successfully loaded: BSC, Solana, Sui, Aptos, Base, X Layer.

Error appears in Console:
```
Failed to get token balances TypeError: Failed to fetch
    at value (injected.js:1:5221721)
    at cu.$ (main-BIXv4aXg.js:235:53083)
    at cu.wl (main-BIXv4aXg.js:235:60786)
    at cu.send (main-BIXv4aXg.js:235:58013)
    at Ku._send (main-BIXv4aXg.js:236:216442)
    at main-BIXv4aXg.js:236:214775
    at main-BIXv4aXg.js:236:215372
```

https://github.com/user-attachments/assets/4aa09d28-a20a-4927-8e29-b2e34e51fed6

**Comment by tsadovska** [comment]
Issue is no longer reproducible on following networks: Ethereum, Polygon, Avalanche, Fantom, Celo, Moonbeam, Arbitrum, Optimism.
Remaining issues: 
* https://github.com/wormhole-foundation/wormhole-connect/issues/2232 Reproducible on Klaytn, Scroll, Blast, X Layer
* https://github.com/wormhole-foundation/wormhole-connect/issues/2301 

Ticket is closed.
