### ISSUE TITLE
[QA] Tokens are not displayed on Injective network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2301]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Select Injective as source chain
2. Connect Leap wallet
3. Open assets list

Actual result: Message "No balances detected" is shown. 
Expected result: Available tokens are displayed

```
Error: No protocols registered for Cosmwasm:AutomaticTokenBridge. This may be because the platform specific protocol implementation is not registered (by installing and importing it) or no implementation exists for this platform
    at getProtocolInitializer (main-BIXv4aXg.js:240:147339)
    at Hn.getProtocolInitializer (main-BIXv4aXg.js:240:153323)
    at _l.getProtocol (main-BIXv4aXg.js:240:254173)
    at async AutomaticTokenBridgeRoute.supportedSourceTokens (main-BIXv4aXg.js:245:41851)
    at async SDKv2Route.supportedSourceTokens (main-BIXv4aXg.js:287:148525)
    at async Operator.allSupportedSourceTokens (main-BIXv4aXg.js:287:154430)
    at async main-BIXv4aXg.js:319:92666
```

```
Failed to get token balances TypeError: Cannot read properties of undefined (reading 'abciQuery')
    at sl.queryAbci (cosmwasm-yHfqIc1b.js:4:1812)
    at Object.request (cosmwasm-yHfqIc1b.js:4:2977)
    at m.AllBalances (cosmwasm-yHfqIc1b.js:4:51487)
    at Object.allBalances (cosmwasm-yHfqIc1b.js:4:53959)
    at Hn.getBalances (cosmwasm-yHfqIc1b.js:4:1062485)
    at main-BIXv4aXg.js:319:69142
```

## Notes/ Attachments

https://github.com/user-attachments/assets/6940cdbe-99d1-4ddf-a0af-4788a6794741

**Comment by kev1n-peters** [comment]
Cosmos Gateway route is not supported in the redesign currently so these chains (cosmos) should probably be removed for now

**Comment by tsadovska** [comment]
Injective network is no longer displayed on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2).
Closing the ticket.
