### ISSUE TITLE
[QA] [Testnet] Tokens are not displayed on Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2302]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64).

Steps:
1. Select Solana as source chain
2. Connect Phantom wallet
3. Open Assets list

Actual result: Message "No balances detected" is shown.
Expected result: Available tokens are displayed

```
Failed to get token balances Error: failed to get balance of account 7yEFBzgwqBHmEtPLvKcQgzPTpfcnrScAfrvenvnBJA5n: Error: 401 : {"message":"Usage without a token is no longer available. For future use, register and receive a free API token https://app.extrnode.com"}

    at main-DbLKtWH6.js:262:34255
    at async Connection$2.getBalance (main-DbLKtWH6.js:262:34181)
    at async qs.getBalances (main-DbLKtWH6.js:281:440595)
    at async main-DbLKtWH6.js:319:69125
```

## Notes/ Attachments

https://github.com/user-attachments/assets/2afbbb37-f205-4f39-998e-0c797c4979f6

**Comment by tsadovska** [comment]
An incorrect configuration was selected. 
Ticket is closed.
