### ISSUE TITLE
[QA] Sometimes transaction fails with "missing response for request" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2308]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.000104 USDC from Arbitrum (MetaMask) to Base (MetaMask)
2. Click on "Approve and proceed with transaction" button 

Actual result: Transaction fails.

```
Wormhole Connect: error completing transfer Error: missing response for request (value=[ { "error": { "code": 0, "message": "we can't execute this request" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_call", "params": [ { "data": "0xdd62ed3e0000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000019330d10d9cc8751218eaf51e8885d058642e08a", "to": "0xaf88d065e77c8cc2239327c5edb3a432268e5831" }, "latest" ] } }, code=BAD_DATA, version=6.13.1)
    at makeError (main-BIXv4aXg.js:235:42962)
    at main-BIXv4aXg.js:236:215083
```
    
Expected result: Transaction proceeds without errors. 

## Notes/ Attachments
Note: The transaction started successfully after more tries. 

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/f25e24ef-6fe0-491d-95ed-a8245a981d5b">

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://portalbridge.com/.
* Send from tx: [Arbitrum Explorer](https://arbiscan.io/tx/0xe625f390d5be9f3657635a0137bca24d982211ab82727f7d4125e36336c68d39)
* Send to tx: [BaseScan](https://basescan.org/tx/0x093c555bb14cb161d95f34eee53017400c87973927e05d16316c0bb6d0e8dfde)

Ticket is closed.
