### ISSUE TITLE
[QA] Transaction is shown as failed on wormhole-connect, but is shown as started in Explorer 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2312]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] witjh macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64).

Steps:
1. Prepare to send 2 USDC from Arbitrum (MetaMask) to Avalanche (MetaMask)
2. Select Circle CCTP Automatic route
3. Change slider position - 8%
4. Click on "Approve and proceed with transaction" button

Actual result: Transaction is shown as failed, but it is started in Explorer. Link to [Arbiscan](https://arbiscan.io/tx/0x163e1ed015fe73878521e2471edbd0a7150690f93ccdb59d2114d7391ce1646b). 

```
Wormhole Connect: error completing transfer Error: No receipt for 0x80e0ad0896bea8124b77a2d039beab27f1e46f7f9c8472b04a5ab8b3925a62e8 on Arbitrum
    at E.parseTransactionDetails (index-Cm-9v0oU.js:1:3906)
    at async CircleTransfer.st [as getTransferMessage] (main-BIXv4aXg.js:245:18072)
    at async AutomaticCCTPRoute.initiate (main-BIXv4aXg.js:245:51565)
    at async SDKv2Route.send (main-BIXv4aXg.js:287:151064)
    at async Operator.send (main-BIXv4aXg.js:287:155390)
    at async Object.Mt [as onClick] (main-BIXv4aXg.js:319:30397)
```

Expected result: Transaction screen is opened. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/93229e9c-bc5d-4ac8-8c37-87f0b833fc56)

**Comment by tsadovska** [comment]
Issue will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/2363 is solved.
