### ISSUE TITLE
[QA] Transaction fails with "Dry run failed, could not automatically determine a budget" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2316]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.11 SUI from Sui (Sui wallet) to BSC (MetaMask) 
2. Select Automatic Bridge route
3. Change slider position - 14%
4. Click on "Approve and proceed with transaction" button

Actual result: Transaction fails.

```
Wormhole Connect: error completing transfer Error: Transaction failed with the following error. Dry run failed, could not automatically determine a budget: MoveAbort(MoveLocation { module: ModuleId { address: 12eb7e64389d8f0e052d8bda10f46aab1dcb6efeec59decf1897708450171050, name: Identifier("transfer") }, function: 0, instruction: 91, function_name: Some("transfer_tokens_with_relay") }, 2) in command 3
    at dapp-interface.js:1:60444
    at dapp-interface.js:1:16148
    at a._next (dapp-interface.js:1:15582)
    at t.next (dapp-interface.js:1:8268)
    at dapp-interface.js:1:60361
    at a._next (dapp-interface.js:1:15582)
    at t.next (dapp-interface.js:1:8268)
    at dapp-interface.js:1:16141
    at a._next (dapp-interface.js:1:15582)
    at t.next (dapp-interface.js:1:8268)
```

Expected result: Transaction proceeds without errors. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/aae6ca7a-157e-4401-9848-4b34ab18440b)

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/2402 is solved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible.
Scenario: 1.3 SUI transfer from SUI (Sui wallet) to BSC (MetaMask) with Automatic route, gas 14%. Link to [Wormholescan](https://wormholescan.io/#/tx/Es7CztD3KYzoehAGA2zk2ScVPa7RMFoaiWBWrVmqUFjL).

Checked on https://portalbridge.com/. 
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

![image](https://github.com/user-attachments/assets/0ee47733-9ae9-45d4-8f2c-26006e925d57)


Ticket is closed.
