### ISSUE TITLE
[QA] Link to BaseScan is not displayed in "Send to" section - NTT Manual route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2328]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERLgPYDWMMgGFe0AGZNEoCBADqZXgBs00NNOKywggJ6IkC5arSFNssjpQAjZfrmmtENbgyxIwgBaYWyRSrUOjnyC0ACSNBqOsgDGXlj6fsaBUWg0NGz0ZPoAHACsAGoAQgBiAIoAWsIAnAAq5fziaAAOuIVyAFawAKoA7gDsAJpW5e06uQBMAIIAbCjtuAAKAOLtZLilkyilybIAvtyOGNFi%2Bh64uE1ZAPRXaGQUuGQAdMdYjJDR%2FLwvvChXr9AyFcMOh3kCAMy5AAM2T6VzWqhoaDYNCuPV%2BbA8ykgAH0lLxGLwceISEolDjjvi2Di2IwrDjxlCmU0AB44vrjJpNDDEqx9abTNDRPJoJ5NaCMAD8AEY%2BjDptlslVcgAWHYQAFLD5fcL6dFsFBYpSQdVgOjREFoJRZMAyKJmyCNUm4RDTA5afZmT1aOR4DyQDIkFCRRy6Ox%2BgOQIOmizWWzIezu2TOVzuOI%2BJARwMoU3BGC621mLSxbz6LNRnNJrSpdKZfRQlmFKHiYpobJMmHZaaQXJ9YpdtITaYqqzK7LjKxTGiwyej6Wm72HY4Zs4Xa63e54Z4A96fb7HP4AoGWsFXSEwuEI6BIlFojFG3H4wnE0nkym8am0%2BmM5lsjlcnlxD5AUhRFMUJRlOUu0VZU1SrMBNW1XgCyQfVDWxU1zUta0QyiOgnSUF0wGlbJ4MXCByLAORkSsDB2CDXDZDDBMaLojhKyLMBYxsJQ7FNFM3E8UtkFY%2BiOKiPMwgiQt7QQ9N9FE9jTQgGsMnuetG2bVt2yZRVu17ftpkHcZh1HXJx0nSZpz6WcqnnMj4KOE5kFXS54BuO4Hm3Xg3iQn5Dx8wFgVBegz2hWF4VwRFkVRdEUExbE8QJIkSTJCllA%2FGk6QZDtWXZTluV5flBWFXJRXFKVZXlGDVVNRC9xQtCH0wj5sJtO08MdNBnUQEiHK9JM5F4FoQQwMhgxk0NID0BNhpcFAxvExxuPjAx%2BLQFxBPk5A5tG8bcwEfNpI6xwS3iHaRoW%2Fb4JUtI1JtJAGybFs2w7PSez7AcaCHEcxwnKcZwnOyF0c5dTnONyPM3R4fl8vd%2FP%2BQLjxCiFwsvKLrxiu94ofJLn1St8Ms%2FbKfyhPL%2F0KoDitAsrwMqqCFSVWr4PqnVpNQj90ONFqLXQHDJs6giiL6zjKMouQrDuSBGIgZiDEligY0sHi%2BPggS02EpAFZNeDJILE7i22rWpeUsBVLrZAnq017dK7D7DOM0y%2Fss6zbPs0XQecpBXPXTyt1hiU%2FIPRGsGRtBT3PCKrxvWL70Sp8UtfdKqSy79cr%2FArAOAkqwIqyDqqZuDONZ5D2aajD4Kwvn2s4iB8O6wjetIj2BuIRdoHOJY2F4Eg3IFqiZbADvcAAWWMd42BtABtWv%2B6iM7oAAOTQFBpd8IwAhu2RzfU5BF5qXBJjQXgABEACkPEEAAJSA0HyLor%2BgHQPB6KwFkXyZF%2BmORGEKJor%2F4FfQoNRohGT6LAAAMgAaVNjwQ60AoHTTsIkTes8eBsFUGQaIkBUyT0QDPWSWgDaEJ3g9feh9j7n0vpAG%2Bd8H5Pxfm%2FD%2BX8f5%2FwAUAkBYDIEwK3hJHQTQ14cwNM1XhexREAF1REoLQKUEgvBcABn0IvAAjjQaYAANZRkxsgQKsCIEgSxsgjwgXIOQJAFhdlyIvfI0x2iUGlCPKw6jIBQJZCfFUV9oHn1NpRIhaC5LeGXqvMsuB%2FTZlgWbO6FtHosmiFCDkhRpSTAAKLiHBOCbsJ86C5CqJMKEKoqjTCqFUVJKpIDZFbFUE%2BOSVSTBVNkCJklEEzQMOWaMoj2CYOwbg6e%2FiIDENkqQjSJ8rC5FVFUcYNA%2BjSiqFCE%2B0pJbJOyJMYQVhklQnBHZaUwgVTJPBMkvoKoTKwihNECJWhcD8MEeXbmoiKISK3r42QAyYjpiCYIxS7T%2FFDMtiyXI6TwQ0ChJMaIMwVRoBVNCKyajiiQGKPyE%2B0x5ngj6LkeFJlhCFHqUXQhYAmlIJYmwWiYlGkYMBN0tweCwAENxXPEhUTd4xPmW2SYhQimQCZCZbs2RCh9DsmgaUuRCg7NRdKFUgrwSTGhJCtA0xzmyEuQIvUnMRF9LAE8rQkjZ4arpYbQJK9BG7SuktQZDKHoNmlBC4olq%2BXNnGOCYoQEqh9A5IU6Y0Q2XFAyTQYQajzIbPBJAaU4JGnwOaXYI1i1SVdJwZS3ptLdX2h%2BTEqoVgT7ZD5KM8YfRhB1MgNMPo4JsgepPmgQoNBii5G2eMcYKoBSoumPEwF8qeBXOVcIiuaqdUQC1bJHVLyNRvINfobWETk0Nn%2BekoFIKwUQqhWkaYsL4VIqRcG1F6LpiYuxaGkI4aEyjo6WSrBsaAzxtpQOxw463GWuWWyqoHKoRcvKby%2FlgrhUqlFeK%2F5Ur8llTlXchVbbkA3J1l2h52r4K9rEW3IguwgA) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64).

Scenario checked: 0.00001 W transfer from Solana (Phantom) to Base (MetaMask) with Native Token Transfer Manual route. 

Link to BaseScan did not appear in "Send to" section after transaction was completed. Asset is received. 
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/2cfetpopvfVRPYyUQfqMSYVc9NeVgqE6KkeF8S13LdvQvTxhxQYwkP4wZfskbo6vjiCf8MnDzdSn2Sq4AEwv2HX3)
* Send to tx: [BaseScan](https://basescan.org/tx/0xd149a70cad78b2767249b93ac5d80fb72d82bfc1b22ac5510e27bf3af83cd51d)
* Link to [Wormholescan](https://wormholescan.io/#/tx/2cfetpopvfVRPYyUQfqMSYVc9NeVgqE6KkeF8S13LdvQvTxhxQYwkP4wZfskbo6vjiCf8MnDzdSn2Sq4AEwv2HX3)

Error in Console:
```
Error: could not coalesce error (error={ "code": -32603, "data": { "cause": null, "error": { "code": -32016, "message": "over rate limit" }, "id": 3876930157, "jsonrpc": "2.0" }, "message": "Non-200 status code: '429'" }, payload={ "id": 20, "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": [ "0x113cd94", true ] }, code=UNKNOWN_ERROR, version=6.13.1)
    at makeError (main-B_vQ2Uks.js:235:42962)
    at Co.getRpcError (main-B_vQ2Uks.js:236:212926)
    at Co.getRpcError (evm-DHyBQGy7.js:2:7703)
    at main-B_vQ2Uks.js:236:215228
```

![Screenshot 2024-08-06 at 13 26 24](https://github.com/user-attachments/assets/0c1319f9-cc73-4bc5-abfd-10b76ca94ef0)

## Custom config

```
{
  env: 'mainnet',
  useRedesign: true,
  tokensConfig: {
    Wsolana: {
      key: 'Wsolana',
      symbol: 'W',
      nativeChain: 'solana',
      tokenId: {
        chain: 'solana',
        address: '85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ',
      },
      icon: 'https://assets.coingecko.com/coins/images/35087/standard/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954',
      coinGeckoId: 'wormhole',
      decimals: {
        default: 6,
      },
    },
    Wethereum: {
      key: 'Wethereum',
      symbol: 'W',
      nativeChain: 'ethereum',
      tokenId: {
        chain: 'ethereum',
        address: '0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91',
      },
      icon: 'https://assets.coingecko.com/coins/images/35087/standard/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954',
      coinGeckoId: 'wormhole',
      decimals: {
        default: 18,
      },
    },
    Warbitrum: {
      key: 'Warbitrum',
      symbol: 'W',
      nativeChain: 'arbitrum',
      tokenId: {
        chain: 'arbitrum',
        address: '0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91',
      },
      icon: 'https://assets.coingecko.com/coins/images/35087/standard/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954',
      coinGeckoId: 'wormhole',
      decimals: {
        default: 18,
      },
    },
    Woptimism: {
      key: 'Woptimism',
      symbol: 'W',
      nativeChain: 'optimism',
      tokenId: {
        chain: 'optimism',
        address: '0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91',
      },
      icon: 'https://assets.coingecko.com/coins/images/35087/standard/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954',
      coinGeckoId: 'wormhole',
      decimals: {
        default: 18,
      },
    },
    Wbase: {
      key: 'Wbase',
      symbol: 'W',
      nativeChain: 'base',
      tokenId: {
        chain: 'base',
        address: '0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91',
      },
      icon: 'https://assets.coingecko.com/coins/images/35087/standard/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954',
      coinGeckoId: 'wormhole',
      decimals: {
        default: 18,
      },
    },
  },
  nttGroups: {
    W: {
      nttManagers: [
        {
          chainName: 'solana',
          address: 'NTtAaoDJhkeHeaVUHnyhwbPNAN6WgBpHkHBTc6d7vLK',
          tokenKey: 'Wsolana',
          transceivers: [
            {
              address: 'NTtAaoDJhkeHeaVUHnyhwbPNAN6WgBpHkHBTc6d7vLK',
              type: 'wormhole',
            },
          ],
          solanaQuoter: 'Nqd6XqA8LbsCuG8MLWWuP865NV6jR1MbXeKxD4HLKDJ',
        },
        {
          chainName: 'ethereum',
          address: '0xc072B1AEf336eDde59A049699Ef4e8Fa9D594A48',
          tokenKey: 'Wethereum',
          transceivers: [
            {
              address: '0xDb55492d7190D1baE8ACbE03911C4E3E7426870c',
              type: 'wormhole',
            },
          ],
        },
        {
          chainName: 'arbitrum',
          address: '0x5333d0AcA64a450Add6FeF76D6D1375F726CB484',
          tokenKey: 'Warbitrum',
          transceivers: [
            {
              address: '0xD1a8AB69e00266e8B791a15BC47514153A5045a6',
              type: 'wormhole',
            },
          ],
        },
        {
          chainName: 'optimism',
          address: '0x1a4F1a790f23Ffb9772966cB6F36dCd658033e13',
          tokenKey: 'Woptimism',
          transceivers: [
            {
              address: '0x9bD8b7b527CA4e6738cBDaBdF51C22466756073d',
              type: 'wormhole',
            },
          ],
        },
        {
          chainName: 'base',
          address: '0x5333d0AcA64a450Add6FeF76D6D1375F726CB484',
          tokenKey: 'Wbase',
          transceivers: [
            {
              address: '0xD1a8AB69e00266e8B791a15BC47514153A5045a6',
              type: 'wormhole',
            },
          ],
        },
      ],
    },
  },
}
```

**Comment by tsadovska** [comment]
Issue is not reproducible on https://portalbridge.com/, link to BaseScan is displayed when sending W from Solana (Phantom) to Base (MetaMask) with NTT Manual route. 
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/3zMPGPibZWW5Wq11Hbxr2RgqL5xyEWpExUv4GmPosqGD9t1gzxifHRqQGm3JutomAXyivJFd2dn5rPTPZZo5qScH)
* Send to tx: [BaseScan](https://basescan.org/tx/0xfef0cce3dfdfb45f48f825c829588aedc6971a233e1cc1130fd4ee3cf2c9358f)

![image](https://github.com/user-attachments/assets/ed527a9e-4435-4360-b33f-337be692d884)


The only link displayed on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZQJgAsmgCeaaOKo0iEVm2i5cW6nQAUoPXtzkA1jHphLVvYIwATcqIDutXJ2EACUZmFwhnMKsAYwALTGhEJE5cGMhSSEoUQlDIsHRoNABzNMSABgAPACMATgAWAA40aoBmeoAmAHZ3ADZG9u5ugFYARmbed2GO%2Buru2vY0Bo6AM0g2gCF2auzcqxt7BOQK5ebqgGFB%2BuHuQerBtcHmqMGoyuHqyvZSyual%2BvdebpRFqDThtU5oUrbHYQXCkDS0KKQDCwEpgJjQqwRDEQNDudzpWiOJAVXjDXinU7DSDdSDuNBrNqXbiQSruarDTjNEaDUotbjDLhMtrPSG6bHWVQAB0giW85FIKBi5AANpAodiAL5i6EAXW1kS1ORcWNysXiiTWCPVO3yRVRxPK3WqTMG3Tawydw1OayWnPY7nYgzatXcnA6w1KHW6lQ61W4pV4pU69WtuT2MDK5TagMGkFKwyDIbanDd9QTDW4bSepSWA3YkA6kCDnBmwy9qcisPhiORqPR4pNGNx%2BLoRIqlUgzW4jdKvQ6xdK7gGp3YHW43C5aw6aAWa1etVq3XYp2qzu6HehuClMuQcoVStVF4N%2BtyeqNVkNr5fegA6iFoYOYRmlgiRyCqGhoE%2BVi2sUpCJAAcsIuC8Gg5DsAAUjE9iBJAaAAGr8IE0CqDE3iVAACvBvDwd0P6FGskqBLYgRrMIUTdO4HSwIIADSUHWHYGbIPUgx4Ws3AAIoAFonsIUm2EsaCSrgaw%2FgAVrA%2FDeB0ACalRSWpqhBgCKBqbg5EAOJqX4Em8CgEn8TCcLQAiSIonBaLvpEgE7MOBJEohyGoRhWGQDh%2BGEcRpEUVRNF0QxTEsWxHFcbxjkuFe0qyvKioqmq365J%2BGJvtiACOlDkDQHlIPBpU9AAGqVvD1IIlS0KclAWfUSiCD%2BP6UOR9RDPBeHdGp4jDEolT1ZAPHlOwtSBLxGH8UVuQ%2BdEcQgcgySpOkmTpTB9oVFEkbrGSnBLM0zQ0v6TbVImtQzKel21JA9TcE0gZ1LwDTpemBwOmsNafWWpSlPUQ1NmuQ14kGsw1BcbSVG04z1B0KM1MM%2F3Oa5vYef22IbZEfmjpm7CVIMgxPW0nFvKU7DDJUaCcPU5KVJwpQnG2py1JyYa1Nm6OlFE6W7Ne2X3nlYtgGtOwlTscthMTEDAYDvCkJUGCwgdBUuEd1UVA813uAmUQArUCw8uMPTMtOR5HqMHSDNO2beg0tT%2FYJgMVMDtZoGDENQ4MMMce48O1Ij7Qo2jGPI%2ByOPdm5fZecrqck3i%2Fnk8MAe8GsTp5km3Q0vUW7smgBZrLzzvDLUBZjDytSDGg5562mEu3jlD75enH5t3oCuFf3KtgGriSSMpGAoBgtBZP3EAG5mOe1PyaCxjWbRTksNQdPOMyAvnG4cacPQXFzzSQKMXv7Jmfug%2BDQc0iH3Cw%2BH2aR7c0eo%2B46OYwn89gC7C5Hs7l%2FwDl7i4UmhJMzvHYPUGMlNOinF%2BtSDorQogbHpEuEYpw2jBmLs7bokZmjuBljCDuSA7y5UfAAiAStIiD2fOnEeY9kBrDQLQHu2JF6HHKMbEhZsLZWwTHibodsozsEds0Z2rtuju3qJ7ABANb4gwDg%2FSGT9Q5w3flHZG39f7x2xko3GICU7iicBAqwUCxzzRzmzfO1RC7ZhLmXHOldq4jDrg8Xgjdm6t0sRKLKncpY0ICfQsIjCwjhLAJE2W%2BoNQAEoxRvhIJQTh4haR0AwIUA4OtIBEBIADdq5BoBLGyYgLEvh%2FBBDalECpRp7CqFlH4AIgRakdloKoFAlQVTNOqYEDsBRcC9lOFtQGlpRbfgBgASXcPU00YyLRWj1tYzM2Ynh5gLMGdwxZSzlg%2BlWHktYjwNibMWVs7Zvz0IwFEEpiQYhGElPQAA9M8jhnDcC0BYLcrAxQoi2HIN88gKBnk%2FJcs8qedpaDPOGJDZotRnl%2BA0HSUg7hnlVNaSwSU0BCgdjBRZSA%2FzyCzNlHCSU0p3AAFo%2FB4BiHilU8pEgAGIxi8CnNwDs7hCWQuVI4WF8T9Q%2FloOBAo8yXCNMSEKkVkFvydO6b05AP5BloGGSiUZ5pkBgWVBBDsMy5kWIWRqpAWqdUrMzmTYSolxLSVkvJRSylVIaS0rpfShljLdFMuZKyNk7IOSud%2BG5dzkAPNwE8%2BArz3l4C%2BWCv5AKgUgrBdCyFxRoVcghh0RFuBkVoFRei4FpBu6iGVOQQoXgliUGVMqUQtzi2kFEKQQolRRBtAfpKcooh5zkowKIbeUZuhoCiCJNAWKcUAH5JgQ16NMam9KsAEqJSS4J1CuEuC5VEHljhugCtCD%2BWlaQMgoDFVYCViq937TnkaOVPTlSSuVaqyA6rtpJBSPu3WRo9VHpcKw59e0D1PlWbwu%2BajwYaOhi%2FMOEddExx%2FnHLGHZrm3MBiGsNEbCRRqBb8wlcbbkJvIFgJN6AU3PLTejTN2bc1yhQAWvKRaS1lorVWmt8p62Nuba29tnbJTdt7cXAdQ6R2FHHR0SdkNbiKKNPirDxL9WUK7tLb8a6N2IH5aEOWP4c1ax1oeg14rIBNMVRp7WpA31hCvQqpASrvxDJGYs5AGtNPGYvWED9OmgK2aQPZozJmM4jmgYB1RgdQPP1fpBz%2BejY5%2FyMUaBDQakDIZeW8tDnyMM4qk%2FG0FeHwXJroMRnkpGkXQBRWiyj1HVS0dLT2hj1aGV1obU2lt4M20draF2ntMZeODubgJoTInp3iaApl%2BdALF2yZCSuqwin0C8uU%2FUbdVgfzkEntPWen6IAnos4t4Zy2nMuDMzexVd6bNGonltmeO3dje0XT5b9J2p5nf%2FeavzQMAvqODlot%2BCMwvQYMXB%2F1RpA1IceQlyNyWY1pZwxl%2FDELCM5ZIxmgrRW81UcLcWir5bK3VdrSx%2Br7HmutZ4%2F2zrw7sWCYnUNUTM7vySYXTJqh3dOXcqm3y2bqnBXM04atsA62fzs%2FG3oPbt6rMqqO0%2B9hnDdWXf1dd9zYu%2BdWMezYoDgW3vge0Z9pG33YP%2F2iwGxD9ygfhsSx86NmXY2Aoh4m6HULcvprI4VnNxX80o7o5VjHTHausYa6UJrnHuPtcJ%2FxknPXyd9dndAIb0nJbLoZ%2BupnM25txJABqAA3EAA%3D%3D%3D) is to [Wormholescan](https://wormholescan.io/#/tx/3JEN7nboMGfNNyjse4HgkV8vcmKH95yBB6cRyzWyaACCR1Z3jCXtAMcjWyXNgkPRckuFhXViFogUVXgi5Uh6vGxV).

Ticket is closed.
