### ISSUE TITLE
[QA] [Mainnet] Corresponding asset is not displayed in "To" section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2397]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Prepare to send FTM from Fantom (MetaMask) to BSC (MetaMask)
2. Check if WFTM token is displayed in the list

Actual result: WFTM token is not displayed in the list. 
Expected result: WFTM token is displayed in the list. 

## Notes/ Attachments

```
Error: No native address type registered for platform Evm, import the platform directly or, if using sdk package, import the addresses conditional export
    at toNative$3 (main-BlRpU2F-.js:278:78391)
    at $u.parseAddress (main-BlRpU2F-.js:278:232310)
    at $u.chainAddress (main-BlRpU2F-.js:278:232435)
    at $u.tokenId (main-BlRpU2F-.js:278:232522)
    at main-BlRpU2F-.js:278:233319
    at Array.map (<anonymous>)
    at Object.tt [as resolveSourceTokens] (main-BlRpU2F-.js:278:233242)
    at $.supportedSourceTokens (main-BlRpU2F-.js:278:280702)
    at SDKv2Route.supportedSourceTokens (main-BlRpU2F-.js:280:197908)
    at async Operator.allSupportedSourceTokens (main-BlRpU2F-.js:280:203899)
```

```
Error: Chain Fantom not supported
    at toMayanChainName (main-BlRpU2F-.js:278:786317)
    at fetchTokensForChain (main-BlRpU2F-.js:278:786766)
    at MayanRoute.supportedSourceTokens (main-BlRpU2F-.js:278:789550)
    at SDKv2Route.supportedSourceTokens (main-BlRpU2F-.js:280:197908)
    at async Operator.allSupportedSourceTokens (main-BlRpU2F-.js:280:203899)
    at async main-BlRpU2F-.js:313:24488
```

![image](https://github.com/user-attachments/assets/9e149dd2-c0dd-4d1d-b910-abd7713bb542)

**Comment by tsadovska** [comment]
Issue is also reproducible when sending SOL from Solana (Torus). WSOL asset is not displayed in "To" section when BSC, Polygon, Avalanche or Ethereum network is selected. 

![image](https://github.com/user-attachments/assets/ff32559e-beaf-4bdb-9d9a-6884e56b1394)

**Comment by agodlevska** [comment]
Issue is also reproducible when sending AVAX/WAVAX from Avalanche. WAVAX asset is not displayed in "To" section when BSC, Polygon, Avalanche, Fantom, or Ethereum network is selected.

Attachment:
<img width="1440" alt="Screenshot 2024-08-19 at 13 27 27" src="https://github.com/user-attachments/assets/58180695-4e0f-49c9-ac01-68ffcda12c72">

**Comment by tsadovska** [comment]
* WFTM asset is displayed in "To" section when FTM token and Fantom network are selected in "From" section
* WSOL asset is displayed in "To" section when SOL token and Solana network are selected in "From" section
* WAVAX asset is displayed in "To" section when AVAX token and Avalanche network are selected in "From" section

Ticket is closed.
