### ISSUE TITLE
[QA] [Mainnet] Balance is not loading for Polygon

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2405]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.6.1 and Google Chrome Version 127.0.6533.120 (Official Build) (x86_64).

Steps:

1. Select Polygon network in From section
2. Connect MetaMask wallet
3. Open dropdown in From section and check tokens balances

Actual Result: Balance for Polygon is not loading.
Expected result: Balance is loading for all tokens.

## Attachments/Notes
```
Failed to get token balances Error: could not coalesce error (error={ "code": -32062, "message": "Batch size too large" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (main-8gg2Q0ny.js:235:71362)
    at cu.getRpcError (main-8gg2Q0ny.js:236:212926)
    at main-8gg2Q0ny.js:236:215228
``` 
<img width="1440" alt="Screenshot 2024-08-20 at 10 55 59" src="https://github.com/user-attachments/assets/b1902462-37c2-485a-861c-ceb8fca213ba">

**Comment by agodlevska** [comment]
Closing the ticket, monitoring of the token balance for networks will be in this ticket - #2359.
