### ISSUE TITLE
[QA] Phantom notification to enter password does not appear and transaction fails after confirming

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2472]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Refresh the page
2. Select Solana network and SOL token in "From" section (Phantom wallet was auto-connected)
3. Select Ethereum network and ETH token in "To" section 
4. Click on "max" option (in my case, 0.288334)
5. Click on "Connect destination wallet" and select MetaMask option
6. Select "Automatic route Mayan Finance" option
7. Click on "Review transaction" button
8. Confirm transfer

Actual result: Transaction fails. Phantom notification to enter wallet password does not appear.
Expected result: Phantom notification to enter password appears.

## Notes/ Attachments

```
Wormhole Connect: error completing transfer Error: Simulation failed: {"InstructionError":[3,{"Custom":1}]}
Logs:
Program ComputeBudget111111111111111111111111111111 invoke [1]
  Program ComputeBudget111111111111111111111111111111 success
  Program ComputeBudget111111111111111111111111111111 invoke [1]
  Program ComputeBudget111111111111111111111111111111 success
  Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
  Program log: Create
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: GetAccountDataSize
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 1394256 compute units
  Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program 11111111111111111111111111111111 invoke [2]
  Program 11111111111111111111111111111111 success
  Program log: Initialize the associated token account
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: InitializeImmutableOwner
  Program log: Please upgrade to SPL Token 2022 for immutable owner support
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 1387616 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: InitializeAccount3
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 1383733 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20512 of 1399700 compute units
  Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
  Program 11111111111111111111111111111111 invoke [1]
  Transfer: insufficient lamports 286190338, need 288334000
  Program 11111111111111111111111111111111 failed: custom program error: 0x1
    at Tt (solana-CLKdWfDc.js:2:52135)
    at async he (solana-CLKdWfDc.js:2:50812)
    at async signAndSendTransaction (main-D-Ks2QVS.js:273:62617)
    at async SDKv2Signer.signAndSend (main-D-Ks2QVS.js:273:65649)
    at async MayanRoute.initiate (main-D-Ks2QVS.js:313:547842)
    at async SDKv2Route.send (main-D-Ks2QVS.js:273:70252)
    at async ht (main-D-Ks2QVS.js:313:65254)
```

![image](https://github.com/user-attachments/assets/608514c8-0525-42ab-a2f4-e644b32b26ab)

https://github.com/user-attachments/assets/aa10dc4c-232e-4db1-a45b-7c43132b4a43

**Comment by Wesleyleung** [comment]
@sebastianscatularo another wallet related

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/b1f3c5115d/ when swapping 0,455927 SOL from Solana (Phantom) to tBTC on Ethereum (MetaMask).
Error appears after clicking on "Confirm transaction" button:
```
Wormhole Connect: error completing transfer Error: Simulation failed: {"InstructionError":[3,{"Custom":1}]}
Logs:
Program ComputeBudget111111111111111111111111111111 invoke [1]
  Program ComputeBudget111111111111111111111111111111 success
  Program ComputeBudget111111111111111111111111111111 invoke [1]
  Program ComputeBudget111111111111111111111111111111 success
  Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
  Program log: Create
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: GetAccountDataSize
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 1394256 compute units
  Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program 11111111111111111111111111111111 invoke [2]
  Program 11111111111111111111111111111111 success
  Program log: Initialize the associated token account
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: InitializeImmutableOwner
  Program log: Please upgrade to SPL Token 2022 for immutable owner support
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 1387616 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: InitializeAccount3
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 1383733 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20512 of 1399700 compute units
  Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
  Program 11111111111111111111111111111111 invoke [1]
  Transfer: insufficient lamports 453782474, need 455927000
  Program 11111111111111111111111111111111 failed: custom program error: 0x1
    at Tt (solana-CFUFmt1f-B_hZfG2S.js:7:52127)
    at async he (solana-CFUFmt1f-B_hZfG2S.js:7:50804)
    at async signAndSendTransaction (pb-index-BwMC8vQL.js:307:61387)
    at async SDKv2Signer.signAndSend (pb-index-BwMC8vQL.js:307:64375)
    at async MayanRouteSWIFT.initiate (pb-index-BwMC8vQL.js:472:469576)
    at async SDKv2Route.send (pb-index-BwMC8vQL.js:307:68515)
    at async vt (pb-index-BwMC8vQL.js:470:135480)
```
Phantom notification to enter password does not appear. 


https://github.com/user-attachments/assets/401f9fbd-edfe-4e0f-915f-043263c0d633

**Comment by tsadovska** [comment]
Issue in no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/.
