### ISSUE TITLE
[QA] Transaction fails on claim on Mantle with error message: Error: execution reverted: "invalid emitter"

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2576]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) and https://preview.portalbridge.com/0af992dedf/ with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.120 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.01 WMATIC from X Layer (MetaMask) to Mantle (MetaMask)
2. Select Manual route
3. Click on "Claim" button

Expected Result: The transaction should successfully complete without any errors.

Actual Result: The transaction fails with the error message: Error: execution reverted: "invalid emitter". 

```
MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
``` 
```
Error: execution reverted: "invalid emitter" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f696e76616c696420656d69747465720000000000000000000000000000000000", reason="invalid emitter", transaction={ "data": "0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000040d007111e5e8ae210d833345151d5c46f4b04f85dc2c50b3635487380799de6f87553e52d0ccc3799d0e7954f870a1652a5eb89487d1db021dd421eb186e7a6b55e00003b3e562a433d2b1fa4e8cd499fb9ed5ffcff4e8610a5643bce0b57abc31a8978a3cf4145efc08aca62d90679d701b13351b2fe6cc83ce9ad83ec4a7e97dbd772400049e65e00f397a1266b5574af3d7c0edbf9712fe322cdd19ec19c8206ecbf8cb7310f93a42aaf272c1a289e5000777a25432b216f81de2e350ef7588a91b4055d00105d60ebd2c5037dd204e73f115ae3e97c98ca49893c02b0129479c4fe09ac178f053057cde1cbfc9ec1e104bfa373f96e64f8c7ccbd7b856dcb53600d5c49e33590007a6a2d8f428ec603bf147efd4830adc15560aeefb824116277157d85edf2c8deb2b44654d9914095e955c880f4813e445230ec27f29dbb9e3517d14befa3f0bb80109859207d90f75e5a50df43569fef8aa829ae1d9683276cb80cf31c900d609662d3d72cbdf0db0857b530557f17898b6ee93c6a3800461efd0d42498f059a2b767000a353789df1b2edaeb7f269fee088f59422bfbf282258d00807f768051d37138167b6389e62fe8b03ec937e9692c1541d1d6fda059925948f9e8c3245514ff1652010b8c1ef02991a9204e0ffabf2344d525d136997855784f9f1a6f49008e9babb86063efcb456eb1a85784543c4dd3564a28f3dadbcb8f12eebd142b9d3d717d5616010ceeeefa244a45409afd21f2c7758bae4732985eb64d194b5623e4e77d02bc3db96bdbb15b13b4c454b0444928deb2c1727e84f84d5e4d06fe787c745c4d8927ef000da7ef619b3008845cdfe424210b73ea028f1ce4e62345b5eb91cff64cd6b92c5d22076d1bebba64159c04955609da2b1e61e165a71d2f6d92b8027d4f8df95af2010e032a5066ad2464130c74c26acc6d5ae99e811d10535cfb05c8215b903bd1885b30f29add5c1eb77775889c64bcd5f383ffcb570e22bb423198996eba60d16f9a000f742e9bf7777b4902facc37834992df0e1f8f21b9697803b40cc92b9c836c232146438fd4e196fee9b2bb2eb4019483b3959d914e8b3fa8010f1ccfe876bd6e040010a013d43229096d44af5cf056887205312768d1961f32f063594e8766bd3e3c09115ea58a21e77ddf30a75e491a135faa583498cdd59eef3e3c523374180856e80066e2a71f0000000000250000000000000000000000005537857664b0f9efe38c9f320f75fef23234d9040000000000000021010100000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700005000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe01002300000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xd493066498aCe409059fDA4c1bCD2E73D8cffE01", "to": "0x24850c6f61C438823F01B7A3BF2B89B72174Fa9d" }, invocation=null, revert={ "args": [ "invalid emitter" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (main-C0zm6LbP.js:235:68988)
    at getBuiltinCallException (main-C0zm6LbP.js:236:107247)
    at du.getBuiltinCallException (main-C0zm6LbP.js:236:108201)
    at Ra.getRpcError (main-C0zm6LbP.js:236:211293)
    at Ra.getRpcError (evm-B8cLuHNF.js:2:1700)
    at main-C0zm6LbP.js:236:215228
``` 

## Attachments/Notes

<img width="1440" alt="Screenshot 2024-09-12 at 11 30 53" src="https://github.com/user-attachments/assets/86bcb5ca-099b-45e0-bc19-15bd386665eb">

<img width="1440" alt="Screenshot 2024-09-12 at 12 10 17" src="https://github.com/user-attachments/assets/722789f0-2ebf-4bbf-8672-ee896c2b62b0">

**Comment by agodlevska** [comment]
Reopening the ticket. 

Issue is reproducible on https://preview.portalbridge.com/cdab46534d/, when sending 0.00015 WBNB from X Layer to Mantle. 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/2cc1de1b-cb6e-43cb-9269-32e61e57d82b" />

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/cdab46534d/, when sending 0.0001 WBNB from X Layer to Mantle.

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/1d029d94-e95a-4a7f-bf36-f0cfdcf16be6" />

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 
Transfer completed successfully - 0.00001 WBNB from X Layer (MetaMask) to Mantle (MetaMask), [Wormholescan](https://wormholescan.io/#/tx/0x053f3833efd665276a0c7a6ab90622e209051092a9455d4c0a8dda69a120bad9).

![Image](https://github.com/user-attachments/assets/7f0e5754-ccda-4c70-a873-fe08599a3f42)
