### ISSUE TITLE
[QA] Transaction fails with "SafeERC20: low-level call failed" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2635]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://preview.portalbridge.com/b1f3c5115d/ and with macOS Sonoma 14.5 and Google Chrome Version 129.0.6668.59 (Official Build) (arm64).

Steps:
1. Prepare to send 0.000004 WBTC from Ethereum (Backpack) to Base (Backpack)
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button

Actual result: Transaction fails.
Expected result: Transaction proceeds without errors.

## Notes/ Attachments

```
Wormhole Connect: error completing transfer Error: execution reverted: "SafeERC20: low-level call failed" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000205361666545524332303a206c6f772d6c6576656c2063616c6c206661696c6564", reason="SafeERC20: low-level call failed", transaction={ "data": "0x0f5287b00000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c5990000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x3ee18B2214AFF97000D974cf647E7C347E8fa585" }, invocation=null, revert={ "args": [ "SafeERC20: low-level call failed" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (main-DdjFQnWn.js:178:68988)
    at getBuiltinCallException (main-DdjFQnWn.js:179:107247)
    at x1.getBuiltinCallException (main-DdjFQnWn.js:179:108201)
    at Pi.getRpcError (main-DdjFQnWn.js:179:211293)
    at Pi.getRpcError (evm-BWWQa1Dc.js:2:2070)
    at main-DdjFQnWn.js:179:215228
```

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/0fe344b5-4620-465b-afa5-d3a29e19d467">

https://github.com/user-attachments/assets/302b5966-ddbb-4f6a-a714-963863c7740a

**Comment by kev1n-peters** [comment]
Unable to reproduce this using backpack wallet: https://wormholescan.io/#/tx/0x3ef6c19fac02e97a8f44a0ebc0fd984388b438149b86b99a7714bd9507029455

**Comment by kev1n-peters** [comment]
seems like an intermittent issue related to the wallet sometimes calculating too low of a gas fee https://support.allianceblock.io/support/solutions/articles/80000974593-what-does-a-safeerc20-low-level-call-failed-mean-

**Comment by tsadovska** [comment]
1. Was able to reproduce the issue when sending max available amount, 0.000004 WBTC from Ethereum (Backpack) to Base (Backpack). In this case, error "SafeERC20: low-level call failed" appeared in Console after clicking on "Confirm transaction" button.


https://github.com/user-attachments/assets/88bf55f2-9436-4206-9840-181e318f45be


2. Transfer 0.000001 WBTC from Ethereum (Backpack) to Base (Backpack) started successfully, link to [Wormholescan](https://wormholescan.io/#/tx/0x7515dab06e2f450764a40b7b598104a3bdcd3f94a86e003df2f358965bc2f1d9).

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
Sent max available WBTC from Ethereum (Backpack) to Base (Base), link to [Wormholescan](https://wormholescan.io/#/tx/0x34d11826ba833c4f8da4d6f018c245bb801befde65e6dddb4d96d3260789116c). 
Closing the ticket.

**Comment by tsadovska** [comment]
Issue is reproducible on [deploy-preview-3247](https://deploy-preview-3247--wormhole-connect.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgDGiRA4tFaogIIAOBA0tAJ6ZYBhOgFoAogBEAMgDNYkvADFRAdQCaARwBaAOQDOABQBq8AELiWnAaPKUArgUzAwugBaJ4ASUj7kiAObI0Lq6ygQAJn5wmLDIttBgAL4UEL62sEGYANqUEAB0%2BeKiCiwAqpIAKgD6AEoA8iXlogDKyRBgALJ4PHiQ1Yhp0E0AEg3lkqKtALoUCQDcIEA%3D) when sending 0.00125 WBTC from Ethereum (MetaMask) to Solana (Phantom). 

Error in Console:
```
Wormhole Connect: error completing transfer Error: execution reverted: "SafeERC20: low-level call failed" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000205361666545524332303a206c6f772d6c6576656c2063616c6c206661696c6564", reason="SafeERC20: low-level call failed", transaction={ "data": "0x30dedc570000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599000000000000000000000000000000000000000000000000000000000001e848000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005e18824bb0e73bb9bd78e7b2d38a3289bccdee1d00000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000071556a2000000000000000000000000cbe9186a89db78714785765055e09dd6166e0833000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000001a4224bb30f0000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599000000000000000000000000000000000000000000000000000000000001e84800000000000000000000000040aa958dd87fc8305b97f2ba922cddca374bcd7f0000000000000000000000007d0ccaa3fac1e5a943c5168b6ced828691b46b3600000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c40d5f0e3b000000000000000000019b1e0654874eb7f59c6f5b39931fc45dc45337c967c3000000000000000000000000000000000000000000000000000000000001e8480000000000000000000000000000000000000000000000000000000006c35400000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009a772018fbd77fcd2d25657e5c547baff3fd7d16000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e443fc7da0678d9f6525bdb0bc0692b1a4bb3895bd68225d522ca8e65af0b93ed15e853281000000000000000000000000000000000000000000000000000000000001e84800000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002a0100000002e3fc67bc8eef02000000000000d75cc06001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3" }, invocation=null, revert={ "args": [ "SafeERC20: low-level call failed" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.5)
    at makeError (main-2V6Xf61K.js:266:33151)
    at getBuiltinCallException (main-2V6Xf61K.js:267:104085)
    at xs.getBuiltinCallException (main-2V6Xf61K.js:267:105006)
    at pc.getRpcError (main-2V6Xf61K.js:267:204777)
    at pc.getRpcError (evm-MFWHfApn.js:2:1690)
    at main-2V6Xf61K.js:267:208582
```

![Image](https://github.com/user-attachments/assets/602f005d-b783-4e1e-a303-1f1a7ba52402)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ with the scenario - 0.000001 WBTC transfer from Ethereum (MetaMask) to Solana (Phantom). Transaction started and completed successfully. Link to [Wormholescan](https://wormholescan.io/#/tx/0x594756238f4fbc470d82c6948bcacb125994512a67818dd3cfb4c7bfdd359056).

![Image](https://github.com/user-attachments/assets/089ade2b-f92a-4db2-90c7-19f44ace60fd)
