### ISSUE TITLE
[QA] [Improvement] Add an error message when a user tries to connect a wallet and the connection fails

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2708]
## Describe the current behavior in detail
Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Steps:
1. Open Fewcha extension and select Aptos mainnet network
2. Open https://portalbridge.com/
3. Select Sui network in "From" section
4. Click on "Connect source wallet" button and select "Fewcha Move" (SUI) wallet
5. Check if warning is displayed

Actual result: Wallet is not connected and warning is not displayed. When clicking on "Fewcha Move" option no action occurs.
Expected result: A warning should be displayed that the wallet is not connected and the user should check the wallet settings.

## Notes/ Attachments

```
Failed to get token balances Vr: Invalid array length, expecting 32
    at gi.request (https://portalbridge.com/assets/sui-Cyoug3Go-DalDwhiw.js:11:14154)
    at async Os.getBalance (https://portalbridge.com/assets/sui-Cyoug3Go-DalDwhiw.js:11:43003)
    at async he.getBalance (https://portalbridge.com/assets/sui-Cyoug3Go-DalDwhiw.js:11:54634)
    at async https://portalbridge.com/assets/sui-Cyoug3Go-DalDwhiw.js:11:54786
    at async Promise.all (index 4)
    at async he.getBalances (https://portalbridge.com/assets/sui-Cyoug3Go-DalDwhiw.js:11:54744)
    at async https://portalbridge.com/pb-index-BDwcyk1t.js:522:12560
```

https://github.com/user-attachments/assets/87f8d7c9-5e08-4c15-be43-2dc49ed93c5c

**Comment by tsadovska** [comment]
Another case is when the user tries to connect different wallet after resuming the transfer. For example, user sent an asset from MetaMask wallet to Sui wallet, but during claiming step tries to connect Fewcha Move wallet.

**Comment by tsadovska** [comment]
Improvement is still relevant. Checked on https://wormhole-connect-mainnet.netlify.app/.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-3065--wormhole-connect-mainnet.netlify.app/ with following scenario:
1. Send 0.001 CELO from Celo (MetaMask) to Aptos (Pontem)
2. Wait until transaction in "Ready to claim" step
3. Disable Pontem extension
4. Refresh the page
5. Try to connect different wallet, for example Bitget, Martian, Petra
6. Check if warning "Not connected to the receiving wallet" is displayed

Actual result: Warning is not displayed.
Expected result: Warning "Not connected to the receiving wallet" is displayed


https://github.com/user-attachments/assets/d61ee0fd-6f26-4abd-b429-6fa95d230f04
