### ISSUE TITLE
[QA] Error 404 is shown for api.wormholescan.io

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2735]
## Describe the current behavior in detail
Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAKnEhGAEIJ4AmA5hABKVGgF0QAXyA%3D).

Steps:
1. Send 0.0001 APT from Base (MetaMask) to Aptos (Spika)
2. Check for errors in Console

Actual result: "Attestation not found" occurs.
Expected result: Transaction proceeds without errors.

## Notes/ Attachments

```
Error tracking transfer: Error: Attestation not found
    at TokenTransfer.tt [as track] (main-qo3ftEYA.js:238:28090)
    at async TokenBridgeRoute.track (main-qo3ftEYA.js:238:49974)
    at async main-qo3ftEYA.js:300:159566
```

`GET https://api.wormholescan.io/v1/signed_vaa/30/0000000000000000000000008d2de8d2f73f1f4cab472ac9a881c9b123c79627/88375 404 (Not Found)`

<img width="1113" alt="Screenshot 2024-09-25 at 19 35 57" src="https://github.com/user-attachments/assets/6fd129d9-e067-4831-af6d-54b2aa83faf3">

**Comment by SergejsBeikulis** [comment]
Issue is still reproducible, tested on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/) and [https://preview.portalbridge.com/ecdc890a68/](https://preview.portalbridge.com/ecdc890a68/)

Sending 0.0001 WAVAX from Scroll (MetaMask) to Mantle (MetaMask)
![WAVAX](https://github.com/user-attachments/assets/d6bc0c05-3b4c-4f26-9f65-579a45b9ee95)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/, when sending 0.0001 APT from Base (MetaMask) to Aptos (Petra). 

Attachment:
<img width="1440" alt="Screenshot 2025-01-15 at 13 23 21" src="https://github.com/user-attachments/assets/902ca3f8-ec28-4ccc-835b-1a617dad19d4" />

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ with different scenarios. 

Closing the ticket. 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/60ede44e-4f93-4734-b8dc-1e26d1e93d78" />
<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/5f5950cf-f92f-42fa-a723-7012cd2bc20e" />

**Comment by agodlevska** [comment]
Ticket closed by mistake, issue is still reproducible on claim step. 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/500da1e7-3a25-48e6-ab70-54122a065089" />
