### ISSUE TITLE
[QA] Infinite loading when resuming transaction sent from Sui Network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2741]
## Describe the current behavior in detail

Environment:
- OS: macOS Sequoia 15.0
- Wallets: Sui, Coinbase
- Browser: Google Chrome Version 129.0.6668.59 (Official Build) (x86_64)
- https://preview.portalbridge.com/712d941311/

Steps:

1. Initiate a transaction from the Sui network
2. Attempt to resume the transaction (e.g. 2vTzdZa4yZmaHatnBA9xx6FBHdgmVjFbEbceV9D4o9kS)
3. Observe the infinite loading

Actual Result: The transaction remains in an infinite loading state and does not resume.

Expected Result: The transaction should resume successfully.

## Attachments/Notes

Errors in console: 
```
Uncaught (in promise) Error: when deserializing item 'mintRecipient': chunk is shorter than expected: 1048 < 1060
    at updateOffset (pb-index-lWqu3ugb.js:276:9987)
    at deserializeLayoutItem (pb-index-lWqu3ugb.js:276:11825)
    at internalDeserializeLayout (pb-index-lWqu3ugb.js:276:10219)
    at deserializeLayout (pb-index-lWqu3ugb.js:276:9683)
    at pb-index-lWqu3ugb.js:276:145813
    at deserializePayload (pb-index-lWqu3ugb.js:276:146056)
    at deserialize$1 (pb-index-lWqu3ugb.js:276:145451)
    at getVaa (pb-index-lWqu3ugb.js:281:20216)
``` 
```
Uncaught (in promise) Error: Unknown token
    at parseTokenBridgeReceipt (pb-index-lWqu3ugb.js:309:45059)
    at async parseReceipt (pb-index-lWqu3ugb.js:309:44198)
    at async Object.vt [as onClick] (pb-index-lWqu3ugb.js:490:45074)
``` 
<img width="1440" alt="Screenshot 2024-09-26 at 09 47 59" src="https://github.com/user-attachments/assets/feb2f171-f342-4a71-b52c-de802b0a2ca5">

**Comment by kev1n-peters** [comment]
This appears to only be an issue when resuming a manual token bridge transfer from Sui where the token is the native gas token 0x2::sui::SUI

**Comment by tsadovska** [comment]
Rechecked the issue on [Netlify](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDIwHTB9XUhYWBCwhgAKUG9vWERUaEgGOij08wA5GycfOwt3AwBhLQL0sDSG5oBjJkJITCwjWCZoASoccnrm%2FEg8SWQugAYAD2gAITFq6ABOPFWARgBmMVWAFmnpoyMAdgBWaAAzbc2VgA4AIzFt%2Ff2ANgAmA2nNvE2Wpths1mplsp1sHMzNNHvd3qsti0vpsntt3oCxJtVgZ9nhPmsjI9pi0jGjpu9Fvt7sCQekZEEGC1oAQAG79Oq05pNTkNPBiMQCIQzWbnc5XU73T7TbbnU7mTanMybIzVR5Uoyrc7Y85Gd7bU6PEwmTXvMTvEw0nl0%2FwAB2gXSQyBwLAANtBLValCMGgBdLy0r087mctodLomIKZIb%2BzljCbsyGzd73MQLT5XabnMx4sSnU7GK6re6bK5iT6PaDbT7vd47Q4tVafJsmBYe2lgnLCz4mU7bbbTTULe7TaH7R7bJ7TAybYnVe73fbnT643YD2FovBtkH03JM1kJ7RW7zBo98gWCPKJp77U4Z%2FGnaBShX7Fqnd54QszvktaZ8%2B54MdpX2dMXy3HlYFte1sEdZ1EDdMCQUDK0%2FW9CAkOaFDaSscREDseAGFgIwbAACQ5TkTxBUMiC6Ho%2BgGaNUO8ONJmFR4Dn%2FVYJ0%2BU4zX%2FSUTHec4djMTEJVWd59gMAD7lvR8FgMVYELpLJO0TW9tlWapzmLEwtXOBZzm2FpzhaR4sUeH5xyuFMzHRTidU%2Bao8GmJSMmQBk9zZKYwEPI9GkY5oz0FS8sChTYzGqapNmgCkxDwNMdOgZ4tlJITzgHbYTE2YwdM%2BEyXJjI8ILtB0UFg%2BDCs5dDOUwqrKvSCjWnaajsAWRlXIgZiE1CpMi02XTkXhO4FiuUkDDEAwl32MQzhnN9HlOVYTBHaZuOpeqGg7CEeurYzoF%2BKay11T5hzMKkTE%2BYzpiuASDGgB8lw1Ws7g6sAd0ZZkvLIo9Gs5IKL1Yyse325NTk%2BIxpjEATqgMOUTBlBZTjwACFjMt53hqBE4Ve60SugsrXXdDbmmq2laoDDbyYaYRvpBX70io7b3DgoJN2JpjWZY7ASlgbNEAMAApJhsmI6A8AANQsYjIH8Jh4EeTgijMIp3mEXgFhtYjUGIhYbCRXMWSsABpV6tq6e5znFhYTAARQALWqVYbDt1ArjwG1YAWYQACsWQseBTgATUeO3vf8JdbJwb3YE4ABxb2CJtswcBt033N3T6DwC49s%2FSf6hW5mxebwfmhZFsXJel2X5cV5XVfVzXtd1%2FXTkNk32dBSDSqdQmccUDuwCp2kAEcqEQdRvKwIph7NAANYezHuKxHgYaoqFj%2B4fCsYRhCoTg4XOIpxfeb2HE2HxHln6AjdmHFiONwXXNJhp6e8RmaN6fpoEGV6usnuYfxgwWOFIwNw0TQHGtALUo5xIIlAfsaA9wIzagOGdda2czaJgWNdCMw4jjzgpLKEwcJ%2BRLgkmxbS5ZPgiRko8csWw04eUzt5XyP1c7eHziFOYBhHiin2I2XMWIpybEeHgIw9wIqPAhhpTYdx9ikjOMBUGxI%2B4QGKlBLAMFe4DzQgPIeDRn4NWzu%2FbAZhkCPAIDIH%2BA8%2F7CkMn2MQI4Wi2VxIuEc%2FJzTQB7BjDGOwLg9mrNUBYVJ9imxUttOY2Cbp4DwdMAhUC5QkLEGQscmpJR0JoQaehQIB7vU8lnPy%2FlCkQE4cKacMSzALHhPtVaNZEGIy2P8fS1QbxCX2JsQyZh0qLjwO8VRb0u74x7nBIm7DDG%2BnZuMiAr8IAmKwE4D2BAcAEAYAxI8tjEx%2FH2FlPAi1rqfEylcNieZPjiXRFU%2BGppqhmm0tKbY0AdhhPBMKKJuCjhxLhAk4hppknVlSZQjJYhaHZMYRnfcLD2EzN5PyYKwpVgWSeAaJcpxqhnRir2e4LR5LxShkJaoTYPjvAuO8aYvYxD9PUd3cqozClTO8Po9IdKoVzIWHgBgNKrQbJ6vY1cZhnESQAulESZoTBeLfAYXx%2BpzgBPeEEkJTzVI9VeTE958SiFJJSRQ9J1CgVZLYjkjB6cPrgtpkGdhJSYUA0TOUiRVTVg1OrBSe4DS%2FgdIWC0i4mx2mdO6ecXpFLBmaIJiMvudKIAMu8OM%2FR1UFAAEovC1SoOyhw0AxCCAILwCEVjwiUC2qvRAkArgZvyOkfChESIrxaCWho2R%2FAOgIkRYilatwMH8DgR4cF63luIlucYsB9zVGattNqLQtxbTYGIatTUwytXahtUpiZdqXAOsuI6XxTrnUuulG6GN7pQPBuJWR1QtzPwIC0AtXQmDxBtHkAA9Letl7LYAMF0OeogkgWioEQK%2BxAOBb1vtyLepZ8YGC3pRPcV4t6CJBDisgMQt6y2Nt0DaSAvAtwAdjtAT9iAJ0OncjaO0YgAC0BE4BMHQ3BFAXQADE2wzBmEyhaSqaaWjAZdJeFEMZqrCAYCzcYU7vC1q6DxvjbN6itvbZ27Awhe14H7WyQdM6sDMxdKzMd4TcNFMokOroKm1PzstQXLAFsra2wdk7F2bsPZe19v7IOIcw4R3eFHGO8dE7J1TpVU957tpXtgDe9A97H1wBfQBj9X6f1%2FoA6B4DkhQMyjiacKDsAYN4Dgwh39yBCZ2BdHwXCVwqAuhdHYc9uXkB2GQLwR4dgpRHBtLMOwYMCMEDsEct874WgWzwMh1DAB%2BBUcTkz3E1KEyqGGsNfs00G4ZFV6gsbY5ed4XGYzCDI1%2FQYAmIBCek2t%2BiLa20dpdMJ2T8noCKZat0T%2Be3KrjsnVp6dF3aLrbWSCBdSqcEqvwZ89VPzNVpKoZkuh%2BqT2VTPRe7AfmAtBaECFn976JvfvPVFxARAYv4Di7ehLMlkupfS0gHAWWRk5by61wrxXSsoAq1Vmr7z6uNc%2BM11rC0ax4E636nrvB%2BunEG%2FOEbFGiCYew1NrRIbmNYYW5gTjURuNpYsVYnAm2wDbawMIWXljZAvfSBJw7x3Kp9oHTp0x5j1fWPqLdxXszDdYDMXLjXCE3uRI%2B7EtViTft%2FK1QD3VQOGFedBz5y91670Pph8%2BuHqGEeRf%2FSjwDsXBCY%2FStj6DkBYPwfx4Tt0xPeD5bJyVyj5XKvVdq9MOnTWbQtbayztn3WUOc4G3CXn5xRv1HG0Lu703qVbnm%2Fgdjkv7jLaiMIRAizlmrMV8rwfw%2BVma%2B8NrqTKuTsG6Uws%2FtI%2Fp9qI03d36czl9LKn%2FbwzXDZjKud9913pD3f%2FcBcC4Hvv6hg984HwLwen2hej%2BFxHv6o%2Bo6A%2BjuPWOktJ4p4ZYE7Za5ZZ6k5Fa55lZU6F604Nal7l7M4dZdYc5c487DaN786QCC6TZt4i6zbNBd54A95gBS6MoraiLspj7QB1rSaUEcpa4HZz4yZ65yaL4XasrsrqbgiaZb5W6cEMHQrnhGaO7RIn6EJn6%2FLkKX46rX4%2B71Debg5YCQ5B7Bah5hYR5I5f4x6%2F7xYJ4AEpbJ5pap6ZagEk4FaQEU757U5F4l4M5l5M7tas4oE15oH14YFN6tDR44E4Z4HBoEENBEEkFkGRpeBegKAADcIAQAA%3D%3D%3D), issue is still reproducible. 
Checked the transfer: tx hash `2vTzdZa4yZmaHatnBA9xx6FBHdgmVjFbEbceV9D4o9kS` (Sui).

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/0a16bf3ef2/ when sending 0.001 SUI from Sui (Sui wallet) to Solana (Phantom) with Token Bridge route. The transaction could not be found via "Resume Transaction".



https://github.com/user-attachments/assets/8c1f82b8-a12c-4ec6-bfe0-d4d4cc15eb42

**Comment by SergejsBeikulis** [comment]
Issue is reproducible on [https://preview.portalbridge.com/0a16bf3ef2/](https://preview.portalbridge.com/0a16bf3ef2/)
Sending 0.001 SUI from Sui (Sui wallet) to Fantom (Rabby) with Token Bridge route. When user resumes transaction the transactions infinite loads.
Transaction hash: `4YRVbC9g1SbADiPjSQ9T5wL4GZigeA63GSDZPXTv3MxX`

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/, when sending 0.001 SUI from Sui (Sui) to Base (MetaMask). The tx remains in an infinite loading state and does not resume.

- [Wormholescan link](https://wormholescan.io/#/tx/311tz3NdVP2f2A8mpPLUZfuNFgtyoW2GomWBUxSg2nsW)

**Comment by SergejsBeikulis** [comment]
Issue is still reproducible on [https://preview.portalbridge.com/079ceedd85/](https://preview.portalbridge.com/079ceedd85/), when sending 0.0001 SUI from World Chain (MetaMask) to Sui (Sui). The transaction remains in an infinite loading state and does not resume. [Wormholescan](https://wormholescan.io/#/tx/0x3b6407615fce206204b2305e376f0ac8837b76b965c00425cfb1941ffb90344d)

**Comment by agodlevska** [comment]
Closing this ticket in favor of #3165, which provides a more accurate representation of the issue.

**Comment by agodlevska** [comment]
Issue is reproducible on portal preview - [Wormholescan]( https://wormholescan.io/#/tx/7fhaRZ375YvQC4NfFenRtPdJcXj5jAQqD3yf3rKsZScp). 
Reopening the ticket.

**Comment by dianabuksa13** [comment]
Closing, because there is a duplicate issue - https://github.com/wormhole-foundation/wormhole-connect/issues/3165

**Comment by agodlevska** [comment]
Reopening the issue. 
Issue is reproducible on staging portal preview when trying to resume TAKE token transaction from Sui. 
[Wormholescan](https://wormholescan.io/#/tx/49briUE6PfzHxpmFUXf77c6GBRy5vZUq2YTZN3ZjbfKQ)

Attachment:

<img width="1440" height="773" alt="Image" src="https://github.com/user-attachments/assets/2aa23c6c-6114-4c95-9df2-8ec59093b6f7" />
