### ISSUE TITLE
[QA] Notification to switch network is not displayed in MetaMask mobile app after clicking on "Confirm transaction" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2772]
## Describe the current behavior in detail
Checked on https://portalbridge.com/. 
Devices:
* macOS Sonoma 14.5 and Google Chrome Version 129.0.6668.59 (Official Build) (arm64)
* iPhone 11 Pro iOS 17.6.1 and MetaMask version v7.31.0 (1432)

Precondition:
Ethereum network is selected in MetaMask mobile app

Steps:
1. Open MetaMask mobile app
2. Open https://portalbridge.com/ in Desktop Browser
3. Select Avalanche network and AVAX token in "From" section
4. Select Moonbeam network and WAVAX token in "To" section 
5. Click on "Source chain wallet" button and select WalletConnect option (WalletConnect wallet is auto-connected)
6. Click on "Connect destination wallet" button and select WalletConnect option (WalletConnect wallet is auto-connected)
5. Click on "Review transaction" button
6. Click on "Confirm" button

Actual result: Transaction fails. Notification to switch network does not appear in MetaMask mobile app. 

Expected result: Notification to switch network appears in MetaMask mobile app.

## Notes/ Attachments

Issue is reproducible only when wallets are automatically connected in Steps 5 and 6. When user needs to scan a QR Code in Step 5, notification to switch network is not displayed.

```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": 1, "message": "Invalid chainId" }, payload={ "id": 13, "jsonrpc": "2.0", "method": "eth_sendTransaction", "params": [ { "chainId": "0xa86a", "data": "0x9981509f00000000000000000000000000000000000000000000000000000000000000100000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0x9631288f4050f7cfbf77b77f8540decf6cfc7012", "gas": "0x143c4", "to": "0x0e082f06ff657d94310cb8ce8b0d9a04541d8052", "value": "0x5af3107a4000" } ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (pb-index-DngrRvHL.js:271:19452)
    at Ui.getRpcError (pb-index-DngrRvHL.js:272:212791)
    at Ui.getRpcError (evm-CkxKsuQ--dCdzA_ux.js:7:2076)
    at pb-index-DngrRvHL.js:272:215073
```

https://github.com/user-attachments/assets/461d6084-13f5-45b5-9c4b-4400e6a8185c

**Comment by tsadovska** [comment]
Notification to switch network is also not shown in Claiming step. In this recording, I am sending 0.0001 BNB from BSC to Ethereum with Manual route. I am using MetaMask wallet via WalletConnect for source and destination chains. 

Transaction can be completed only by manually switching the network in the wallet, as the notification to confirm the transaction appears only when the correct network is chosen.


https://github.com/user-attachments/assets/b2f66ba1-e5fa-419f-bf11-b9cc6529e4c3

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/0a16bf3ef2/ when sending 0.0001 osETH from Ethereum (MetaMask via WalletConnect) to Arbitrum (MetaMask via WalletConnect). Issue is reproducible when wallet is auto-connected and when wallet is connected with scanning the QR Code. 


```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": 5000, "message": "{\"code\":-32602,\"message\":\"Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received:\\n0x01\"}" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "wallet_addEthereumChain", "params": [ { "blockExplorerUrls": [ "https://etherscan.io", "https://etherscan.io" ], "chainId": "0x01", "chainName": "Ethereum", "nativeCurrency": { "decimals": 18, "name": "Ether", "symbol": "ETH" }, "rpcUrls": [ "https://cloudflare-eth.com" ] } ] }, code=UNKNOWN_ERROR, version=6.13.3)
    at makeError (pb-index-D1b0I4ms.js:271:19062)
    at Go.getRpcError (pb-index-D1b0I4ms.js:272:212916)
    at Go.getRpcError (evm-rrw6v-Sy-fFnn0oAc.js:7:2047)
    at pb-index-D1b0I4ms.js:272:215198
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ with following scenario:
1. Select Ethereum or Avalanche network in MetaMask mobile app
2. Open https://portalbridge.com/ on mobile with Google Chrome
3. Prepare to send 4 USDT from Arbitrum (MetaMask via WalletConnect) and Base (MetaMask via WalletConnect)
4. Click on "Review transaction" button
5. Click on "Confirm transaction" button
6. Check if notification to change network is displayed

Actual result: Notification to change network is not displayed. However, notification to confirm transaction appears when Arbitrum network is selected in MetaMask mobile app. 

[recording](https://drive.google.com/file/d/1Eqt1osnNG2iRJ_k3krPeXfxUvaya3pmR/view?usp=sharing)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/, network is automatically switched in MetaMask mobile app. Checked with MetaMask v7.44.0 (1676). 

Scenarios checked:
* AVAX transfer from Avalanche to Moonbeam
* ETH transfer from Ethereum to Arbitrum
* USDT transfer from Arbitrum to Base
