### ISSUE TITLE
[QA] Transaction fails after confirming when sending maximum available amount

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2794]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select Solana network and SOL token in "From" section, connect Nightly wallet
2. Select Ethereum network and WSOL token in "To" section, connect MetaMask wallet
3. Click on "max", in my case maximum available amount is 0.008686
4. Click on "Review transaction" button
5. Click on "Confirm transaction" button

Actual result: Transaction fails. 
Expected result: Transaction proceeds without errors or warning about insufficient amount is shown. 

## Notes/ Attachments

```
Wormhole Connect: error completing transfer Error: Simulation failed: {"InstructionError":[1,{"Custom":1}]}
Logs:
Program 11111111111111111111111111111111 invoke [1]
  Program 11111111111111111111111111111111 success
  Program 11111111111111111111111111111111 invoke [1]
  Transfer: insufficient lamports 6631540, need 8686000
  Program 11111111111111111111111111111111 failed: custom program error: 0x1
    at Tt (solana-COyeEaTm.js:2:52141)
    at async he (solana-COyeEaTm.js:2:51000)
    at async signAndSendTransaction (main-HZXt6WuX.js:319:63482)
    at async SDKv2Signer.signAndSend (main-HZXt6WuX.js:319:66586)
    at async ssw (main-HZXt6WuX.js:291:7760)
    at async signSendWait (main-HZXt6WuX.js:291:7467)
    at async TokenBridgeRoute.initiate (main-HZXt6WuX.js:291:49425)
    at async SDKv2Route.send (main-HZXt6WuX.js:319:70844)
    at async pt (main-HZXt6WuX.js:353:138257)
```

![image](https://github.com/user-attachments/assets/67f9c131-e2d7-47fb-bfc7-b6df22cc8d02)

Nightly notification opens and transaction starts successfully when sending 0.0001 WSOL.

https://github.com/user-attachments/assets/f1719028-e30f-4d14-b9ae-3b0b8b5f0fdb

**Comment by kev1n-peters** [comment]
Simulation fails because there is no SOL leftover to pay for the transaction https://github.com/solana-labs/solana-program-library/blob/ea354ab358021aa08f774e2d4028b33ec56d4180/token/program/src/error.rs#L16

**Comment by Wesleyleung** [comment]
@danielisaacgeslin is the same issue with insufficient gas you were looking at?

**Comment by tsadovska** [comment]
Rechecked the [scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2794#issue-2563365286) on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsJ8AYRtOCL9A4ND1d2E2ExsvPX1IWFgY9QYAClBvb1hEVGhIBjodKrBzADkbJx87C3cDOK1mlrBK4ZaAYyZCSEwsI1gmaAEqHHIhsfxIPElkWYAGAA9oACExOOgATjwLgEYAZjELgBY9vaMjAHYAVmgAMzubucABwAIzEdyeTwAbAAmAx7G54G7jG5rMYtGp1GbYQ5mPYgoFQi63cawm6gu5QlFiG4XAxPPAwy5GEF7cZGSl7KEnJ5AtHo6rIIIMcbQAgANyWgwFLVGMqqeDEYgEQn2By%2BX1%2BHyBML2dy%2BH3MNw%2BZhuRjiIN5RguXzpXyMULuHxBJhMNqhYihJn58uq%2FgADtBZkhkDgWAAbaA%2B%2BVKdbDAC6eTGsZlcoFk2msxMQRqqyT6M22ylOIOUKBYmOMN%2Bey%2BZkZYg%2BH2MvwuQJuvzEMJB0DuMKhUPuL3GFxho5Mx2j6Mx9TVMJMHzudz2NuOQL2eKeILuoL2BhubLiQKBTy%2BMIZD2XBMpeEnYxkwtFEuL2l9EDTvsVysEjRLoKeH2rJkPmgXVjSecYPihPAW33RVxj2RUgTwTc9SeKtwNvGVYADINsBDMNEEjTDk3zMZEzjbwUzI0iICscREDseAGFgIwbAACWlAV3zGDMiFmeZFmWPMKKqQsdjVEFniQi5txhD5PSQnUTChL57jMGltQuKEngMZCgQAkDjgMC5iKqadsSwQ4ALuC44i%2BNsTFtL5ji%2BO5xi%2BcYQVpEF4S3X5yzMKkZPtGE4jwPZTMFB8xUlXYwBfV9uJlT8VR%2FSyDlNMw4jiG5oG5MQ8ErBzoDBW4OVUr5lzuEwbmMByYQ8iKaIFbDA2DFACKI5rhiomVyJlXqxiSiYpj47BjhFSKIDE4t0qJByvjJIlAWOX4OQMMQDFPJ4xE%2BfdIJBD4LhMdc9jkvluuqWoZxLPt3OgBFts7B0YTXMxeRMGF3L2X5lIMaBgNPa0B0BKawHvBpH1izjfWG9EUu%2FCSe3nB6yw%2BGEjD2MRlLiAxDRMfVjg%2BPBkOOLzIShfpiUJMGzJw9rQwjKNLqqQb0X6gU2e8DnhmEGGhpE7xeIs9xCKCG8WbAGa4qwDpYDrRADAAKSYOo2OgPAADULDYyB%2FCYeAQU4NozDaKFhF4Y5%2FTY1A2OOGxSQbcUrAAaTB8zZiBL5NeOEwAEUAC04guGwA9QX48H9WBjmEAArcULHgD4AE0QQD2P%2FFPQKcFj2BOAAcVj5i%2FbMHA%2FfdoVIZi59BaqOGxgR1VsDlhXldV6B1a1nW9YNo2TbNi2rZtu2HY9D5nbdyW6bavCOqZ2nFElnmBQARyoRB1BltoV89AANFezCBKwQQYOIqHzoEfCsYRhCoThCS%2BNpNahWOHBuHwQV36AXYOek2Nd5WkUuZ11rmAYW%2FEFhLGgCsMG0s1TwXRscG4ZgjD%2FEpNADa0BbQbi0sSVBTxoBAmzHaZ470LqgI9iWY4P1sxrleEebkBoTCEiVKebSkl7JdhhOpfSIIuy3ArtFJ8cUEqw1AQqJUqU1QGBBBqJ4I4Gy0l3DcEEeAjBAiyiCTGNkbiAieByT4aE0ZsgXhAVquEsD4XnlPReoDl49UuvXCA4DsBmGQCCAgMgYGSzgSWVyi4xDrnGIFBkJ51xKi9NAeclNKb3G%2BPOPscRji8ieO7a6FlDjUN%2BngOhewGFYMNCwsQbDNw2h1Hwnhzp%2BGoklhDEU1cRHiJGE0iAjc0qHD3DkswxwiQPTOv2QhRNbhImcnEf8qkng3FcmYSqJ48BQlMeDems9GaEWZk04BLR7EtE2W%2BUBLisBOCjgQHABAGDCV9L49KiIng1TwEdH6MJqq%2FEko2GEWkqQ9IJh6OInp7J6juNAe4aSsRqiybQ14eTCQFOYR6YpfZSmcIqWIXh1TBFV2EfzVMLSwBtLVBcHyoJnSng%2BHEd6eUFxAnGEZQq2NVJxFHNCKE3woR7AXGIRZ5iGadXWa%2BWxvptms0cfs0aFljh4AYLy%2BUVzDj%2BIvGYYJ2lkKVXUp6EwUTIIGFiU6L4CSoRJJSSCm66VwU5MhfkphRSSkcPKdwlFVTJI1IoZXepmL4pNKcS0PFJZOkaJ6RcPpfZuRAiGYiKZxwxnfBuJM6ZsyvjzM5csyxc81kL12dzS6mztmDQUAASi8BzKgkqHDQDEIIAgvBsRePCJQcyp9ECQF%2BBWpoVQmIsXYifcYLaWh1H8MGZirE2KdtvAwfwOAQSEX7e2tit4tiwCfHEUVswJrjFvOZNgYhu3DAOSu4i3r0p3R%2BI9M8z1YRvQ%2Bl9Sqv1KYAywRjLSui4i3i5gQcYDbZhMCKP6RoAB6H9ErJWwAYLoN9RBJDjFQIgEDiAcA%2FtAw0H9JyiwMB%2FeSIEEIf3MSCAVZAYgf1tsHbof0kBeC3ng%2FnaAEHEAbuDEKf0gYxAAFpmJwCYGRwiKBZgAGI7hmDMNVb0pEy3jCQ%2BGH85IkyDWEAwMWWwt3eF7bMaTsmJbrFHeOyd2BhCzrwPOyUi7MzYFFuGcWa70k0eaeiA5xnTPNX3V7H2%2Fsg4hzDhHKOMd46JxTmnDOWcoQ5zzoXYupdy6kRfW%2Biyn7YDfvQH%2BgDcBgPwfA5B6DsH4MoaQ5IFD%2Bo8kfEw7AbDeBcP4Zg8gJmdhwx8AYr8Kg4Zwx2DfZV5AdhkC8BBHYXUrx%2FQHDsOjejBA7AvMglBcYXs8BEZIwAfmNHkssQIbSpNIuRyjkGLPJtWV1dYwnRM%2FihJJpMwhWNQJWPJiAimtNHaEiOsdE7wxKZ03p6ABmxpzEgVd0i67N2WZ4ku7AAljsXIbpIxGVCaFmvodCy1cLrVlK4ZUvhjrn2kVfe%2B7AUWYtxaEAl6DYGVtQbfWlxARAMv4Cyz%2BnL%2Bl8uFeK0gHAZW1kVaq4N2r9XGsoBa21jrkLuu9ZhP1wbh1%2Bx4FG%2FGibvBpsfFm0eBb7GiAUao2tqxqahOUZ25gCTzQpNFY8V4nAp2wDnawMIbXnjZCA6qOp2793SJzoXb9rAbiddm7M1iCzw0DmO9N94ii%2B7Mlg9yRawp0OEU2rh%2FahHAiwvI4ix%2Br9v7%2F1Y6AzjkjePUtwaJwhzLghyeVUp1hyAOG8O0%2Fp5GRnvBqss4axx5rrX2udb2Dzvr%2FoBtDaFyL8bxHxczcJNLr4i31jLYV199bPLbzbfwGJ9XQJ9vNGEIgY5pzzn68N3PhfZzzfeEt5po3D27eGcOWv85Lv6hu4ogco587F8b4kV%2BJuJr%2Ffmsh0H1hIfYfItRYjqP6wUeRbj7FhPgGiWGeyW%2BOMG6exOiGpO2eFOeW%2BeheJWdO5WlW5ezOdWVeTWHOde3OPWTeLeguI2Y2YuEuUu82fesukA8uq2w%2BSum2ww4%2BeAk%2BYAGuQqs%2Bqikqy%2B0AfaWmbBUqFuN22%2B2mNuume%2BL24qkqx%2BkAp%2BVm9uYhvBXqwOd%2Bfu2SAeT%2BsKL%2B7Cb%2BdqH%2Bke6w4WqOWA6O8e8WSeSWqeBO4BmeUB2WuesBBWBeRWRepWSBTONWaBbONenO9ejefOzeAuw2wuhBnexBPepB%2Fe26GelB1G1BKatBLQ9BjBzBlEXgsYCgAA3CAEAA%3D%3D), issue is still reproducible.

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Closing the ticket.
