### ISSUE TITLE
[QA] Sometimes transaction fails with "MayanForwarder: insufficient middle token amount" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2797]
## Describe the current behavior in detail
Checked on https://portalbridge.com/. 

Steps:
1. Prepare to send 6 POL from Polygon (MetaMask) to Base (MetaMask) with Mayan MCTP route
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button

Actual result: Transaction fails. 
Expected result: Transaction proceeds without errors. 

## Notes/ Attachments
The transaction starts successfully after several attempts. 

```
Wormhole Connect: error completing transfer Error: execution reverted: "MayanForwarder: insufficient middle token amount" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000304d6179616e466f727761726465723a20696e73756666696369656e74206d6964646c6520746f6b656e20616d6f756e7400000000000000000000000000000000", reason="MayanForwarder: insufficient middle token amount", transaction={ "data": "0xfa74fd4300000000000000000000000000000000000000000000000053444835ec580000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e00000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c335900000000000000000000000000000000000000000000000000000000002215f5000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000420000000000000000000000000000000000000000000000000000000000000030807ed2379000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd09000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c3359000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c300000000000000000000000000000000000000000000000053444835ec5800000000000000000000000000000000000000000000000000000000000000208b510000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001a100000000000000000000000000000000000000000000000000000000018300a007e5c0d200000000000000000000000000000000000000015f0000fc0000a900001a40410d500b1d8e8ef31e21c99d1db9a6444d3adf1270d0e30db00c200d500b1d8e8ef31e21c99d1db9a6444d3adf12701a881d021d346c5433b2cf8fb46ee00dec89070d6ae40711b8001e84801a881d021d346c5433b2cf8fb46ee00dec89070d7b3e67e63906d8576466c2f48158a30be0a9e36c0000000000000000000000000000000000000000009f3116b6641f78bca48bf70d500b1d8e8ef31e21c99d1db9a6444d3adf127000206ae4071118002dc6c07b3e67e63906d8576466c2f48158a30be0a9e36c0000000000000000000000000000000000000000000000000000000000208ae98a953cfe442c5e8855cc6c61b1293fa648bae47202a00000000000000000000000000000000000000000000000000000000000208b51ee63c1e58100604dcc4463d6c39d957bc25c7b6683ddd2ba902791bca1f2de4661ed88a30c99a7a9449aa84174111111125421ca6dc452d289314280a0f8842a65000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c4afd9b7060000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c335900000000000000000000000000000000000000000000000053444835ec58000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005f3e0000000000000000000000000000000000000000000000000000000066fea3130000000000000000000000000000000000000000000000000000000000194e4f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3" }, invocation=null, revert={ "args": [ "MayanForwarder: insufficient middle token amount" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (pb-index-C8xM5-1W.js:271:19354)
    at getBuiltinCallException (pb-index-C8xM5-1W.js:272:107223)
    at Ju.getBuiltinCallException (pb-index-C8xM5-1W.js:272:108177)
    at Ui.getRpcError (pb-index-C8xM5-1W.js:272:211164)
    at Ui.getRpcError (evm-DPxnFflA-DPdu5TCy.js:7:2076)
    at pb-index-C8xM5-1W.js:272:215073
```
    

![Screenshot 2024-10-03 at 16 22 43](https://github.com/user-attachments/assets/918c594e-085d-41f2-8da8-5c44f234db4b)

**Comment by tsadovska** [comment]
Error "transaction execution reverted" occurred in Console when trying to reproduce the scenario. Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2833.
