### ISSUE TITLE
[QA] [Improvement] Prevent users from attempting to claim a transaction twice while the first claim is processing

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2806]
## Describe the current behavior in detail

Environment:

- OS: macOS Sequoia 15.0
- Wallets: MetaMask
- Browser: Google Chrome Version 129.0.6668.71 (Official Build) (x86_64)
- https://wormhole-connect-mainnet.netlify.app/

Steps to reproduce:

1. Initiate a transaction (0.0000001 WBTC from BSC (MetaMask) to Avalanche (MetaMask))
2. Wait for the transaction to reach the claiming stage and claim the transaction
3. While the first claim is still processing, attempt to claim the same transaction again
3. Observe the errors in the console and on the transaction screen

```
Error: execution reverted: "transfer already completed" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a7472616e7366657220616c726561647920636f6d706c65746564000000000000", reason="transfer already completed", transaction={ "data": "0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000040d008da812ac8d67e6505e0dc5f15a0a457fef0553576ae190833aef40386053ad9e3eb60c865b3b0210cb3392c76991572d1c3e553fd88207e9a6375dcb9bb740330102a83ba891faeb9129b80e9e9485217c642becafff6dc2b969dbbbd30a20d91fcc58a691a63373bd05f8b37715fc2daab3654ee04f5b12796aed310e32269d49590103505dff2e3fabad59220274553a0762e3f521127b21967970a93b0010cf53c6bd4290ea9ef95cc25acd9977c55efe9a58f85a0a6400aff3aa40de2a611a78cd8b01043d174930fba6da49c55549dfb0ac0f46a821ec5fe30aa64abbac60d90b5869624cac678b869206d480994981bce78f6d1ce375ea147c957b76d83029140fc1530006befb0070b86f7ede5b34250b58a1aab8d44010f98452473a89dc66ab71b350963bc88bc732808b6a1ab5e4bed152523ea733b5d19a438cb51b7428de51401e450109d0ae1b6d67d173b8de81a66e475b6aa5de32dada6909f7bcf4931a779825894c5d28cac42f4b11bd0005f57fa9d0dd3b06727494da940dca76ebf6d8ab09b026010abd99c320c0b5927e5e111f92424c8dd74e8a6bfb8a69a8bcdbbf69fb59253a160334a8dae1badc829ee188b8502a3669dd3a013e2b333ae30a24cc1f00b07223010c3afff03ec303b26c06af409254603daf280256f98774b9104c090ab51fdc1268655e6d4716a60ef362e326cba5ac29da0a5ac42a51cd4f0eef52af16ba195123000d796e0aef248ee8e283cae74e8706aef0a699931fef0acdbc74f450a0b77e44472025770c72e803e0497f5d21f949d0c241d2be6a832b7d62f5b066010fa9b745010e6ef2ec2fbc759b912a5797feaeb8280cb11c0e5aa6b2afe69a2597f78a2b08200813533df3819cf20821880027fd7f23537f06c3e39be05e7644f9b550bed0fb010f2699ce191c1c7747fbe8d40579c0bb930c93823379045273a57b9128de4d73bf5a0d96ebfce63faf2d8b2e4a38a34e02e7432d1ab898bb88673f1e35ac9396830010b20e871cfa05301c5ee31c5aaaa14910b4c802d9bf24f1a9fd5cdd322757abf36edb2aa8d1c4eecfae01f257308a29bc99f794a2debd80996036f3fbb255be270012eccfa0744a719f18d50b4ffdbf4b537669db7601b002cb495fc5ba3afd10f37052ec89253c7201ece0ee13864b09b9bd9bab48bc253bcb35e0c491d52c22b2250066ffd44c000000000004000000000000000000000000b6f6d86a8f9879a9c87f643768d9efc38c1da6e70000000000095a1b0f01000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c5990002000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe01000600000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xd493066498aCe409059fDA4c1bCD2E73D8cffE01", "to": "0x0e082F06FF657D94310cB8cE8B0D9a04541d8052" }, invocation=null, revert={ "args": [ "transfer already completed" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (main-C4LaN1gL.js:281:68890)
    at getBuiltinCallException (main-C4LaN1gL.js:282:107247)
    at fu.getBuiltinCallException (main-C4LaN1gL.js:282:108201)
    at Ui.getRpcError (main-C4LaN1gL.js:282:211293)
    at Ui.getRpcError (evm-Anl1ZR7e.js:2:2079)
    at main-C4LaN1gL.js:282:215228
``` 

Actual Result: Users are able to initiate multiple claims on the same transaction while the first claim is still processing, leading to errors in the console and on the transaction screen.

Expected Result: The claim button should be disabled after the first claim is initiated, and the button should display the text "Transaction in Progress" to indicate that the transaction is currently being processed.

## Attachments/Notes

https://github.com/user-attachments/assets/e7e3b4f4-4c6d-47c2-9bdb-3546b72e4e97

<img width="1440" alt="Screenshot 2024-10-04 at 14 49 17" src="https://github.com/user-attachments/assets/fb2cd988-cc95-4557-80ad-0ce7b994fa9c">

**Comment by agodlevska** [comment]
Issue is no longer reproducible, the transaction cannot be reclaimed while the first claim is still in process.

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/bfd9260d-2817-4e1a-a003-2c4de8d3150e
