### ISSUE TITLE
[QA] User is not warned that account does not have any token balance

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#285]
#### Steps:
1. Select Phantom wallet in ‘From’ section
2. Select CELO asset
3. Select Solana network in ‘From’ section
4. Select Metamask wallet in ‘To’ section
5. Select Goerli network
6. Type Amount, for example 0.01
7. Click “Approve and proceed with transaction” button

#### Actual result:
User is not warned that account does not have any token balance
* Error message is displayed to the user: “Error sending transfer, please try again”
* Error in Console:

```
Error: account does not have any token balance
    at SolanaContext.send (index.ts:343:1)
    at async sendTransfer (index.ts:153:1)
    at async Object.send [as onClick] (Send.tsx:78:1)
```

#### Expected result:
User is warned that account does not have any token balance

#### Tested device:
MacBook Pro, macOS Monterey 12.6.1, Chrome Version 111.0.5563.110 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/229540074-7c07a21a-af74-4155-8756-c8cfd78f1246.mov

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Solana network in 'From' section
2. Connect Phantom wallet in 'From' section (user has some CELO in Phantom account)
3. Select CELO asset
4. Change Phantom account in extension (user doesn't have CELO in second account)
5. Click on Phantom address and select option "Change wallet"
6. Select Phantom option
7. Type amount, for example 0.01
8. Select any destination chain (in my case, Fantom)
9. Connect wallet in 'To' section
10. Observe if 'Approve and proceed with transaction' button is clickable and if warning message is displayed

Actual result:
* Warning message is not displayed
* Error in Console:
```
Error: account does not have any token balance
    at w.send (context.ts:496:15)
    at async index.ts:167:11
    at async Object.onClick (Send.tsx:104:13)
```


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/410e5678-5c9f-4d05-8fca-7b3032a94f04

**Comment by tsadovska** [comment]
Closing as duplicate of #927.
