### ISSUE TITLE
[QA] "Error: No protocols registered" occurs in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2884]
## Describe the current behavior in detail
Reproducible on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aC89fUhYWBCwhgAKUG9vWERUaEgGOh0UsHMAORsnHzsLdwMAYS1cvLBkuryAYyZCSEwsI1gmaAEqHHJaxvxIPElkDoAGAA9oACExSugATjxlgEYAZjFlgBZJyaMjAHYAVmgAM031pYAOACMxTd3dgDYAJgNJ9bx1pvXBo08mkMu1sDMzJN7rdXssNk0PusHptXv8xOtlgZdnh3isjPdJk0jCjJq95rtboCgalkEEGE1oAQAG69GrUvINdkpPBiMQCIRTaanU4XY63d6TTanY7mdbHMzrIyVe4UozLU6Y05GV6bY73EwmdWvMSvExUrmpfwAB2gHSQyBwLAANtBzVylEM6gBdCKND3sznUlptDomIJpAa%2BoEjMas8HTV63MRzd4XSanMw4sTHY7GC7LW7rC5id73aCbd6vV5bfZNZbvBsmOZuoEgzKC94mY6bTaTdVzW6TSG7e6bB6TAzrQmVW63Xand7Y7Z96EovAtxoyOkM5lx7QWiCBi08vmCbLxh67Y5p3HHaASuW7JrHV54fNTnlNSY8254EeS3ZUyfDd2Vga1bWwe1HUQF0QL9KNGh9T1vH9RCEIgKxxEQOx4AYWAjBsAAJNlqSPRpgyIDouh6PpI2QlIY3GQV7j2X9ljHd5jhNX9xRMV5Ti2Mx0TFZZXl2Aw%2F1ua97zmAxljglI2zBLAZmvTZlkqU5CxMDVTjmU5NiaU4mnuDF7i%2BUcLiTMxUXYrV3kqPBJgUmlt0ZFkJjAfcDzI9kT35c8VOmBUzEqSp1mgMkxDwFNtOgR4NmJATTj7TYTHWYxtPeYznPQ6kwJtO0UGg2C8rqVD2SQ9kKsaXzmlaSjsDmekXIgRi4yC2FtNORFYRuOYLmJAwxAMBddjEE4pxfe5jmWEwh0mTjKTK1J0nbeNKyM6BvjGkttXeQczApEx3iMyYLj4gxoDvBc1WrG5WrALcsh3DySItOqgX8s9mPLLttsTY53iMSYxD4yoDBlEwpTmY48D%2FOZTJeV4qjhGFHsU8CiodZ1XRWlIaqBKrqUJ7xibqYR3tq%2BjvAo5T3BgoJ13xsB2s8rAilgTNEAMAApJgMkI6A8AANQsQjIH8Jh4HuTgCjMApXmEXg5itQjUEIuYbARbMmSsABpR6lI6W5ThFuYTAARQALUqZYbGt1ALjwK1YDmYQACsmQseBjgATXua2Pf8BcbJwD3YE4ABxD28MtswcEto3aRe9y9xplJPsab6BWwTnub5gXoCF0Xxcl6XZflxXldV9XNe141jj1w2WcxwrIOK3GMcUFnyepABHKhEHUdmCn7k0AA1%2B7MW4rHuBhKioKPbh8KxhGEKhOBhU4ChF14PYcdYfHuCfoH16YsUIg2%2BZc0nM4zsA6ao7pemgfpHrZwUvyBuZ1jMIwrgomgMNaAGphyiThAA3Y0Bbhhk1HsI6y0H7G3jHMc6YZBwHFnGSaUJgYS8gXGJFiWlSzvCElJe4pYNjJzcruTy3kPoP25LyAKgoDD3GFLses2YMQTnWPcPARhbihXuCDdS6wbi7GJCcQCgNCTdwgAVCCWAoJd1bj3B%2BfdyorSzhAJ%2B2AzDIHuAQGQ78Waf3jAZHsYghxNBstiecQ5eSmmgF2FGKMthnC7JWSocwKS7CNmtZSMw0EXTwJgyY2DQEynwWIQhI51TikoeQvUVCAQs2evSNO9CmH1FyRAHOgUZiTnCWYOYsJtqLSrDA2GGxfh6UqFeASux1gGTMCleceBXgKKeljDuOMYJ41yXfPIWi8gjMPA%2FfRWAnCuwIDgAgDA6IWgsUFH4ux0p4Fmudd4aULgsRzO8USqJynQ2NJUE0WlJSbGgFsQJoJBShIwQcSJMJol4ONHEysCSSHJLEBQtJNDU50KpgGfJYBCmCmWOZB4eoFzHEqEdSK3ZbhNFkjFMGAlKgNjeK8M4rxJjdjED0pR2MSpDIPBoi0YyCY6KmQ1ZScw8AMApVyVZMwrHLjMHYsSf4UpCRNCYVxL4DAeN1KcbxrxfH%2BPuetIKTzwkvKibg2J8TiFJLIf81JLF0nIJTlkkFXlcm6LyJC%2BMJThHlOWJUysZJbi1J%2BK0uYjSzjrBaW0jppwukkr6Sozugzu4TLJitEZYyaoKAAJReCQpQKgLKHDQDEIIAgvAwSmPCCASgSkF6IEgBcFNOQUi4XwkReeTRC15AyP4O0eECKETLRuBg%2FgcD3BgjWkthENyjFgLuSoDKOjNSaBuJSbAxAVrqNMwdcEzVBU2ucHai49ofEOsdU6KULoo2uqA4GokJGVA3KTAgTRc0dCYDEK02QAD0l7mUstgAwXQx6iCSCaKgRAj7EA4EvU%2BrIl75mxgYJepEtxniXrwkEaKyAxCXuLXW3QVpIC8A3D%2BqO0BX2IFHXaWkVobRiAALR4TgEwZDMEUAdAAMSbDMGYNKZoEJJqaP%2Bp054kS%2BhqsIBgjNRjju8FWjoHGuPMyGE2ltbbsDCC7XgHtLI%2B0hmwAzJ0TNh1BMw3koE0yFNKbyjO025sra23to7Z2rt3Zex9v7QOwdQ6vHDpHGOccE5JwQoe49ykz2wAvega9t64APp%2FS%2Bt9H6v0%2FsA%2F%2ByQgGpSROOGB2AEG8BQZg5%2B5AuM7BOj4NhC4VAnROjsMetLyA7DIF4PcOwEoDhWmmHYIGOGCB2H2S%2BV8TRTZ4Hg4hgA%2FHKSJiZbjqgCQhFDaG32qb9QM0qQwGNMfPK8NjvphBEdfv0HjEA%2BPifm7RRtzbW1On45J6T0BZONU6C%2FdbCER1jrU%2BRft2BqILeWdnFhP1UHoMVVgt5KrPlqsSaQlJlCdUHoQkek92B3Oee80IXzH7n2Dffce4LiAiChfwOFy9kWpIxbiwlpAOBkuDNS%2BlurWWct5ZQIV4rpWXkVaq%2B8GrdWZpVjwE1r1rXeAdeOF12cvWSNEFQ%2Bh4bqiA30bQ5NzArHcjsfi8Y0xOAltgBW1gYQEuTGyDuykETW2dsIW7b2q7WBDGS%2BV8p0Eqm6rTL10rsxyEZ0hOexE5VMSPvfPVd9rVv3qHOYB650956r03vB%2FeyHiHodBe%2FfD39YXBAo5Smj8DkBIPQaxzjl0ePeAZcJ7l0jBWislbK5MSn1WrS1fq%2FTxnLWEMs86zCDnpw%2BtDAG7z87I3yUbgm%2FgZjIvbgzdyMIRAcyFlLJl3L7vvfFkq%2B8GrsT8vdva7kzM4fSzDeZGN8haZsye199H8w08ud5U26VW9%2B3BDHdfb%2BQCv77uhiA7c97rzvu71%2BdDwFmHn6Q8I7%2FUjiPqPosx7j4l7HKW0sp4E7Zbp75ak7Z4U6Vb56F506NbNbM6s7s49bV5c6QA85DYN785jZ1At54Bt5gCi60pd4CIsoD7QDVribEGsqq6bYT4Saa5SbT6HZMosoL6QBL7qY67MFUGmoPbb7W5hK2774fKH5ELH6aqn5u5DAuZA5YAg4%2B4%2Bb%2B7%2BZB6w4v5h7v4RZR5f6xax7xbx5Jb%2F746ZbAHE6Z5k45557U4F604NYM5wFl4IGV5IE14Tqh5oEYYYH%2BpYF5A4F4EEEoReAegKAADcIAQAA%3D%3D%3D). and https://portalbridge.com/. 

Steps:
1. Open Console
2. Select Solana wallet (Phantom wallet is auto-connected)

Actual result: Error is shown in Console. 

```
Error: No protocols registered for Solana:PorticoBridge. This may be because the platform specific protocol implementation is not registered (by installing and importing it) or no implementation exists for this platform
    at getProtocolInitializer (main-Caub6XFs.js:286:142508)
    at Zs.getProtocolInitializer (main-Caub6XFs.js:286:148492)
    at SolanaChain.getProtocol (main-Caub6XFs.js:286:249906)
    at async f0.supportedSourceTokens (main-Caub6XFs.js:291:50082)
    at async SDKv2Route.supportedSourceTokens (main-Caub6XFs.js:319:68398)
    at async main-Caub6XFs.js:321:204306
    at async Promise.all (/index 4)
    at async RouteOperator.allSupportedSourceTokens (main-Caub6XFs.js:321:204259)
    at async main-Caub6XFs.js:326:35544
```

Expected result: Error does not occur. 

## Notes/ Attachments

Reproducibility: 5/5

![image](https://github.com/user-attachments/assets/7dbb8679-183a-4eba-8d02-c89a39b507d1)

**Comment by tsadovska** [comment]
"Error: No protocols registered for Aptos:AutomaticTokenBridge." occurs when Aptos network is selected as target chain.

`Failed to get destination token: Error: No protocols registered for Aptos:AutomaticTokenBridge. This may be because the platform specific protocol implementation is not registered (by installing and importing it) or no implementation exists for this platform`


![image](https://github.com/user-attachments/assets/0678ade1-0d7b-4168-98ba-b17328b7cbcd)

**Comment by hustynetwork** [comment]
Is there a update on tihs? Im getting the No protocols registered error for Solana when trying to bridge tokens between ETH on Eth chain to SOL on solana chain. 

https://tickertrending-swap.vercel.app/

Do i need to add any custom config to be able to bridge between ETH to SOL? The viceversa doesn't work either. 



<img width="1308" alt="Image" src="https://github.com/user-attachments/assets/d77c0a80-cfe8-48d2-a841-0e314e359282" />

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
