### ISSUE TITLE
[QA] "Error with transfer, please try again" error message appears when trying to send FTM to WFTM

### ISSUE THREAD

**Issue by SergejsBeikulis** [wormhole-foundation/wormhole-connect#2919]
## Describe the current behavior in detail
Repro on build: [https://preview.portalbridge.com/ac2a9a0933/](url)

Steps:
1. Prepare to send 0.0001 FTM (MetaMask) to WFTM (MetaMask)
2. Enter ammount 0.0001
3. Click on "Review transaction"
4. Proceed till second transaction confirmation step 

Actual result: "Error with transfer, please try again" error message appears.
Expected result: Transaction is completed.

## Notes/ Attachments
Issue is inconsistent, transaction started successfully after clicking on "Confirm transaction" button again, but it is in infinite "Wrapping up..." loading phase.

`Failed to load resource: the server responded with a status of 403 ()`

```
inpage.js:1 MetaMask - RPC Error: JsonRpcEngine: Response has no error or result for request:
{
  "id": 2382174903,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": [
    "0x55bada56381030a316e7812ba2ca3a9e04fce2ff88d44d1d5fdda99dcfc96fff"
  ]
```
  
 ```
 Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": -32603, "data": { "cause": null, "request": { "id": 2382174903, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x55bada56381030a316e7812ba2ca3a9e04fce2ff88d44d1d5fdda99dcfc96fff" ] } }, "message": "JsonRpcEngine: Response has no error or result for request:\n{\n  \"id\": 2382174903,\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_getTransactionReceipt\",\n  \"params\": [\n    \"0x55bada56381030a316e7812ba2ca3a9e04fce2ff88d44d1d5fdda99dcfc96fff\"\n  ]\n}" }, payload={ "id": 24, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x55bada56381030a316e7812ba2ca3a9e04fce2ff88d44d1d5fdda99dcfc96fff" ] }, code=UNKNOWN_ERROR, version=6.13.3)
    at makeError (pb-index-DMUGiEOY.js:271:19062)
    at Go.getRpcError (pb-index-DMUGiEOY.js:272:212916)
    at Go.getRpcError (evm-DMvzqxcS-CLx0ixND.js:7:2047)
    at pb-index-DMUGiEOY.js:272:215198
```
    
    
<img width="1440" alt="FTM_to_WFTM_bouth_MetaMask_wallets_error_screenshot" src="https://github.com/user-attachments/assets/a0f5f949-64b8-48af-a930-da5c25e5b118">

**Comment by tsadovska** [comment]
Initiated FTM transfers from Fantom (MetaMask) to Polygon (MetaMask) 5 times and all transfers started successfully. Changing priority to p2. 
* https://wormholescan.io/#/tx/0x06f3b37676dd5b8604f62b3429367060e580b3c72e3a4492b0f9b24589c34104
* https://wormholescan.io/#/tx/0xbfff6756fb05b79ba4834ff8a08ae17ba805dc24a1721b177f0afc1e26c081ec
* https://wormholescan.io/#/tx/0xc894a7032cf4ca8fa2f97aabb96cdc6a03dc279ce9518463f1466e262c455f04
* https://wormholescan.io/#/tx/0xfea5aeef5f9525b69fc18e6c477518239381d4cfc6024672a075ba9dad78ff07
* https://wormholescan.io/#/tx/0xa34d13479b43ddba786daf49039472ad51b5dbfec1b33db35d196cb5d880e05d

Checked on https://preview.portalbridge.com/ac2a9a0933/ (Wormhole connect: v^1.1.3-beta.4-development, Portal Bridge: v0.2.17-P33ee44a737).

**Comment by artursapek** [comment]
OK. I tried to repro this yesterday and couldn't

**Comment by agodlevska** [comment]
The issue is not reproducible on https://portalbridge.com/, transfer started successfully.

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/2872dba8-440b-48e3-b784-0258c9356d9d
