### ISSUE TITLE
[QA] [Testnet] Transaction fails with "transfer value exceeded balance of sender" 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2927]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/. 

Steps:
1. Prepare to send max available amount of CELO from Alfajores (MetaMask) to Solana (Phantom), in my case 5.776554444652050888
2. Select Automatic route
3. Click on "Review transaction" button
4. Change slider position to 12%
5. Click on "Confirm transaction" button

Actual result: Transaction fails. 
Expected result: Transaction proceeds without errors. 

## Notes/ Attachments

```
Wormhole Connect: error completing transfer Error: execution reverted: "transfer value exceeded balance of sender" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000297472616e736665722076616c75652065786365656465642062616c616e6365206f662073656e6465720000000000000000000000000000000000000000000000", reason="transfer value exceeded balance of sender", transaction={ "data": "0x1019d654000000000000000000000000f194afdf50b03e69bd7d057c1aa9e10c9954e4c9000000000000000000000000000000000000000000000000502a71a9733079c8000000000000000000000000000000000000000000000000065b92e2d27e640000000000000000000000000000000000000000000000000000000000000000013559e9e11c7c0d54d982b103ea3194140a5f1ed299bdb673f1b67fa98a94f4a70000000000000000000000000000000000000000000000000000000000000000", "from": "0x0a370E7c5F7F944d451B48bc151a7BEC454bc185", "to": "0x9563a59C15842a6f322B10f69d1dD88b41f2E97B" }, invocation=null, revert={ "args": [ "transfer value exceeded balance of sender" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.3)
    at makeError (main-CF-1d58_.js:281:68558)
    at getBuiltinCallException (main-CF-1d58_.js:282:107247)
    at hu.getBuiltinCallException (main-CF-1d58_.js:282:108201)
    at Go.getRpcError (main-CF-1d58_.js:282:211418)
    at Go.getRpcError (evm-hEE1ibje.js:2:2041)
    at main-CF-1d58_.js:282:215353
```

![image](https://github.com/user-attachments/assets/6ef6d41d-d860-4149-8f84-8aee1a86304a)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/, when sending max available amount of CELO from Alfajores. 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/e4237296-7b1b-4970-8a67-3a6b0ffa9c21" />

**Comment by tsadovska** [comment]
Issue is no longer reproducible, CELO transfer from Alfajores to Solana using Token Bridge automatic route can be successfully started , additional gas - 5%.

Link to view transaction details:  https://wormholescan.io/#/tx/0xdff6b4b085dc558fdefda2f15f3eb92efd748e7541de60a999c29b5cfff8e0fc?network=Testnet
