### ISSUE TITLE
[QA] Unexpected warning about "Insufficient funds" is displayed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2935]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/ac2a9a0933/. 

Preconditions:
User has 0.03573 ETH ($100.89) on Ethereum. 

Steps:
1. Select Ethereum network and ETH token in "From" section (Binance wallet is auto connected)
2. Select BSC network and BNB token in "To" section (Binance wallet is auto-connected)
3. Enter min required amount, in my case 0.0059 ETH
4. Click on "Review transaction" button
5. Click on "Confirm transaction" button
6. Check if notification to confirm transaction is displayed

Actual result: Transaction fails. Warning "Insufficient funds" is displayed for the user.
Expected result: Transaction proceeds without errors. 

## Notes/ Attachments

```
Wormhole Connect: error completing transfer Error: insufficient funds (transaction={ "chainId": "0x1", "data": "0xfa74fd430000000000000000000000000000000000000000000000000014f604cc2cc000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000000fb3efd000000000000000000000000c38e4e6a15593f908255214653d3d947ca1c23380000000000000000000000000000000000000000000000000000000000000520000000000000000000000000000000000000000000000000000000000000040807ed23790000000000000000000000003451b6b219478037a1ac572706627fc2bda1e812000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000003451b6b219478037a1ac572706627fc2bda1e8120000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c30000000000000000000000000000000000000000000000000014f604cc2cc0000000000000000000000000000000000000000000000000000000000000ea28a60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000028a00001a4041c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2d0e30db05120111111125421ca6dc452d289314280a0f8842a65c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2012456a7586849c1c1d31c19b8f9ae6c7dc43561f5e3af46541bfcc05f035d2ff057718ecea9000000000000000000000000807cf9a772d5a3f9cefbc1192e939d62f0d9bd380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000000fd1ff70000000000000000000000000000000000000000000000000014f604cc2cc00000000000000000000000000000000115e900672c79650000000000000000000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000041bd4d7ba6ac3f023be712c6308cb67a02781435a57755151344d26dd4cecf63393a2a932b08181593d3a94ee0cf0ff0ade4177b8d8d65a08029d1773150c772471b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014111111125421ca6dc452d289314280a0f8842a650000000000000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e48e8d142b000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000014f604cc2cc000000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb6137000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000226aa300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011a8200000000000000000000000000000000000000000000000000000000006cbe7a00000000000000000000000000000000000000000000000000000000672c923a000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb6137000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022fb0a4f5138006f048dae7c5c0ecee48bfa2bfcf527c0ed3aa4c44f3b6a58dca00000000000000000000000000000000000000000000000000000000", "from": "0xc911cbcdd18b2019a884db5a2bc7c3a8bfb61370", "to": "0x0654874eb7f59c6f5b39931fc45dc45337c967c3", "value": "0x14f604cc2cc000" }, info={ "error": { "message": "insufficient funds for gas * price + value: address 0xc911CBcdd18B2019A884db5A2Bc7c3a8bfb61370 have 0 want 5900000000000000" }, "payload": { "id": 13, "jsonrpc": "2.0", "method": "eth_estimateGas", "params": [ { "chainId": "0x1", "data": "0xfa74fd430000000000000000000000000000000000000000000000000014f604cc2cc000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000000fb3efd000000000000000000000000c38e4e6a15593f908255214653d3d947ca1c23380000000000000000000000000000000000000000000000000000000000000520000000000000000000000000000000000000000000000000000000000000040807ed23790000000000000000000000003451b6b219478037a1ac572706627fc2bda1e812000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000003451b6b219478037a1ac572706627fc2bda1e8120000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c30000000000000000000000000000000000000000000000000014f604cc2cc0000000000000000000000000000000000000000000000000000000000000ea28a60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000028a00001a4041c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2d0e30db05120111111125421ca6dc452d289314280a0f8842a65c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2012456a7586849c1c1d31c19b8f9ae6c7dc43561f5e3af46541bfcc05f035d2ff057718ecea9000000000000000000000000807cf9a772d5a3f9cefbc1192e939d62f0d9bd380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000000fd1ff70000000000000000000000000000000000000000000000000014f604cc2cc00000000000000000000000000000000115e900672c79650000000000000000000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000041bd4d7ba6ac3f023be712c6308cb67a02781435a57755151344d26dd4cecf63393a2a932b08181593d3a94ee0cf0ff0ade4177b8d8d65a08029d1773150c772471b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014111111125421ca6dc452d289314280a0f8842a650000000000000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e48e8d142b000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000014f604cc2cc000000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb6137000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000226aa300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011a8200000000000000000000000000000000000000000000000000000000006cbe7a00000000000000000000000000000000000000000000000000000000672c923a000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb6137000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022fb0a4f5138006f048dae7c5c0ecee48bfa2bfcf527c0ed3aa4c44f3b6a58dca00000000000000000000000000000000000000000000000000000000", "from": "0xc911cbcdd18b2019a884db5a2bc7c3a8bfb61370", "to": "0x0654874eb7f59c6f5b39931fc45dc45337c967c3", "value": "0x14f604cc2cc000" } ] } }, code=INSUFFICIENT_FUNDS, version=6.13.3)
    at makeError (pb-index-BKcRdQCG.js:271:19062)
    at Go.getRpcError (pb-index-BKcRdQCG.js:272:211103)
    at Go.getRpcError (evm-PQkeIuTi-C-9rRWIo.js:7:2047)
    at pb-index-BKcRdQCG.js:272:215198
```

https://github.com/user-attachments/assets/bcef647a-27db-42db-8f27-0deb001bedc1

**Comment by tsadovska** [comment]
Transaction screen didn't appear when sending ETH from Ethereum (Binance wallet) to BNB on BSC (Binance wallet) with Mayan Swift route. Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/3027#issuecomment-2528283036.
