### ISSUE TITLE
[QA] Error "Encoded data does not match any of the given payload types" occurs in Console when transaction is resumed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2947]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/0a16bf3ef2/. 

Steps:
1. Open Resume transaction screen
2. Open Console
3. Search transaction by hash `3oiaMTm1tgHhJb1FBFUSpgTa8RvFuMJ3CzJbGyaexxsJ6r9XzaVXk3XnMJ1T3idJZTVijefzajVSCsW5nuQQMb8v` (Solana)
4. Check errors in Console

Actual result: "Error: Encoded data does not match any of the given payload types" occurs in Console.
Expected result: Error does not appear. 

## Notes/ Attachments

```
Uncaught (in promise) Error: Encoded data does not match any of the given payload types - 1,0,0,0,4,13,0,178,38,23,252,206,87,240,119,56,167,38,185,15,64,93,125,6,105,38,140,136,209,248,242,119,155,28,227,153,154,87,55,104,243,69,233,240,238,179,121,149,226,35,188,35,2,40,178,206,19,193,94,155,178,152,75,51,225,250,43,252,94,134,204,0,2,120,139,57,139,244,62,235,23,28,115,165,224,102,17,58,190,83,6,89,180,221,176,93,233,95,251,184,209,24,233,221,116,55,173,231,196,21,196,199,10,239,32,30,76,59,181,47,220,12,209,205,195,211,146,194,54,165,228,118,33,106,16,104,181,0,4,54,140,89,29,220,228,104,173,199,166,227,123,15,196,181,48,152,177,205,229,24,208,103,160,186,79,44,134,35,88,113,94,41,219,144,228,52,147,134,68,168,211,60,31,231,157,83,99,9,250,241,31,120,76,86,22,121,152,223,108,171,122,231,209,1,5,51,207,74,165,196,220,222,149,233,101,223,131,81,23,185,68,237,57,195,59,91,123,90,89,98,1,83,170,68,162,55,241,62,136,25,223,48,215,254,101,158,10,114,132,112,62,36,79,55,75,232,128,73,238,202,71,163,77,31,209,200,96,154,218,0,6,211,110,122,7,144,143,138,103,218,113,214,5,175,123,12,63,82,98,83,31,181,25,202,208,175,142,202,50,216,75,89,143,90,65,201,190,195,237,63,48,189,142,207,144,88,238,98,41,248,142,234,218,218,180,10,176,79,13,28,156,162,119,90,58,1,8,103,105,153,187,73,237,53,231,209,247,58,5,94,37,247,196,77,14,228,23,187,216,30,140,42,148,139,119,172,10,0,88,49,22,95,11,121,109,232,231,201,140,220,56,58,69,134,124,248,171,200,214,123,136,247,132,2,252,94,155,209,117,18,48,1,9,12,147,64,131,112,121,192,107,194,154,35,247,172,60,245,173,139,50,127,190,254,161,214,53,248,240,32,108,19,232,21,17,69,17,97,227,216,79,102,136,200,58,165,51,172,108,187,42,207,94,227,142,237,62,244,192,207,89,5,221,250,204,202,203,1,10,147,166,29,200,203,239,11,226,76,211,32,159,150,47,142,120,110,15,7,171,87,133,46,183,111,52,32,20,93,6,32,218,114,193,234,115,154,43,66,203,180,140,6,30,132,245,176,254,131,155,23,254,31,63,117,117,119,66,73,77,64,247,128,182,1,13,254,234,128,188,244,84,41,249,229,56,88,167,158,179,137,112,49,11,79,211,43,94,188,106,170,173,216,106,193,146,196,44,81,19,245,169,39,218,22,211,141,206,4,204,62,206,39,178,244,172,159,198,194,63,108,113,214,37,208,15,185,153,162,151,1,15,202,188,136,238,54,233,17,102,8,180,96,76,75,54,207,119,0,154,63,123,189,162,224,118,108,89,21,155,59,117,3,147,81,186,205,43,215,199,90,89,46,54,236,159,204,77,196,213,226,15,77,69,207,3,48,230,169,174,89,115,19,190,163,97,0,16,60,154,39,222,126,244,130,216,13,153,16,59,108,179,187,169,14,188,28,128,108,6,92,54,67,74,226,19,186,5,27,21,0,128,40,40,133,152,50,176,170,154,149,222,59,165,90,212,75,237,122,134,224,19,26,123,117,25,159,66,119,227,80,53,1,17,116,66,143,189,240,183,28,252,131,210,14,99,203,226,133,154,52,146,195,129,176,81,198,157,142,143,76,244,37,149,180,79,62,41,119,59,83,150,66,109,140,213,34,124,133,245,181,54,72,211,50,147,173,42,38,181,219,41,17,14,135,102,217,54,0,18,154,248,24,237,233,95,193,215,208,233,6,220,98,185,181,46,90,240,39,240,89,107,10,28,197,58,44,52,76,81,135,244,72,5,5,209,24,31,14,249,66,98,155,178,48,86,211,165,240,212,242,39,135,51,73,223,234,165,37,233,49,253,85,147,1,103,50,5,207,0,0,0,0,0,1,207,95,54,20,226,205,155,55,69,88,243,92,118,24,178,95,13,48,109,94,116,155,125,41,204,3,10,26,21,104,98,56,0,0,0,0,0,1,88,210,32,153,69,255,16,5,127,151,190,28,57,71,142,87,151,79,108,201,219,251,238,187,14,92,227,64,194,239,213,43,130,149,232,137,169,237,228,0,0,0,0,0,0,0,0,0,0,0,0,83,51,208,172,166,74,69,10,221,111,239,118,214,209,55,95,114,108,180,132,0,145,22,193,11,12,184,181,160,130,211,28,13,75,234,133,81,1,10,91,170,236,156,161,196,65,63,240,73,186,93,123,253,20,53,89,233,225,28,124,13,84,217,130,177,3,234,49,148,20,10,95,30,210,153,189,182,115,241,182,127,169,138,148,244,167,0,79,153,78,84,84,6,0,0,0,0,0,0,0,100,105,39,253,192,30,169,6,249,109,113,55,135,76,221,122,218,208,12,163,87,100,97,147,16,229,65,150,199,129,216,77,91,0,0,0,0,0,0,0,0,0,0,0,0,150,49,40,143,64,80,247,207,191,119,183,127,133,64,222,207,108,252,112,18,0,23,0,0
    at pb-index-D1b0I4ms.js:276:149658
    at deserializePayload (pb-index-D1b0I4ms.js:276:149803)
    at deserialize$1 (pb-index-D1b0I4ms.js:276:149227)
    at getVaa (pb-index-D1b0I4ms.js:281:20402)
```

https://github.com/user-attachments/assets/220482bf-1601-42db-aabd-a17b233c0207

**Comment by SergejsBeikulis** [comment]
Reproduced on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/) and [https://portalbridge.com/](https://portalbridge.com/)
Transaction hash: `26XmivVyg5ZaCpuEc7R4yLFP1jMUFaBBHnSKgPEb15w6SoK9XkKYjgF7K2u8H6nWRQCR2ZtdywXCAHCfCv3i1t2H` Solana

<img width="1440" alt="solana" src="https://github.com/user-attachments/assets/21f3c93e-bddd-42bc-b097-b6560f44e560">

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/. 

![Image](https://github.com/user-attachments/assets/05f39a73-fd8d-4f8f-8e79-40831f1c0cf5)
