### ISSUE TITLE
[QA] Transaction fails with "Transaction does not have a transaction hash" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2955]
## Describe the current behavior in detail
Checked on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsJ8AYRtOCL9A4ND1d2E2ExsvPX1IWFgY9QYAClBvb1hEVGhIBjodKrBzADkbJx87C3cDOK1mlrBK4ZaAYyZCSEwsI1gmaAEqHHIhsfxIPElkWYAGAA9oACExOOgATjwLgEYAZjELgBY9vaMjAHYAVmgAMzubucABwAIzEdyeTwAbAAmAx7G54G7jG5rMYtGp1GbYQ5mPYgoFQi63cawm6gu5QlFiG4XAxPPAwy5GEF7cZGSl7KEnJ5AtHo6rIIIMcbQAgANyWgwFLVGMqqeDEYgEQn2By%2BX1%2BHyBML2dy%2BH3MNw%2BZhuRjiIN5RguXzpXyMULuHxBJhMNqhYihJn58uq%2FgADtBZkhkDgWAAbaA%2B%2BVKdbDAC6eTGsZlcoFk2msxMQRqqyT6M22ylOIOUKBYmOMN%2Bey%2BZkZYg%2BH2MvwuQJuvzEMJB0DuMKhUPuL3GFxho5Mx2j6Mx9TVMJMHzudz2NuOQL2eKeILuoL2BhubLiQKBTy%2BMIZD2XBMpeEnYxkwtFEuL2l9EDTvsVysEjRLoKeH2rJkPmgXVjSecYPihPAW33RVxj2RUgTwTc9SeKtwNvGVYADINsBDMNEEjTDk3zMZEzjbwUzI0iICscREDseAGFgIwbAACWlAV3zGDMiFmeZFmWPMKKqQsdjVEFniQi5txhD5PSQnUTChL57jMGltQuKEngMZCgQAkDjgMC5iKqadsSwQ4ALuC44i%2BNsTFtL5ji%2BO5xi%2BcYQVpEF4S3X5yzMKkZPtGE4jwPZTMFB8xUlXYwBfV9uJlT8VR%2FSyDlNMw4jiG5oG5MQ8ErBzoDBW4OVUr5lzuEwbmMByYQ8iKaIFbDA2DFACKI5rhiomVyJlXqxiSiYpj47BjhFSKIDE4t0qJByvjJIlAWOX4OQMMQDFPJ4xE%2BfdIJBD4LhMdc9jkvluuqWoZxLPt3OgBFts7B0YTXMxeRMGF3L2X5lIMaBgNPa0B0BKawHvBpH1izjfWG9EUu%2FCSe3nB6yw%2BGEjD2MRlLiAxDRMfVjg%2BPBkOOLzIShfpiUJMGzJw9rQwjKNLqqQb0X6gU2e8DnhmEGGhpE7xeIs9xCKCG8WbAGa4qwDpYDrRADAAKSYOo2OgPAADULDYyB%2FCYeAQU4NozDaKFhF4Y5%2FTY1A2OOGxSQbcUrAAaTB8zZiBL5NeOEwAEUAC04guGwA9QX48H9WBjmEAArcULHgD4AE0QQD2P%2FFPQKcFj2BOAAcVj5i%2FbMHA%2FfdoVIZi59BaqOGxgR1VsDlhXldV6B1a1nW9YNo2TbNi2rZtu2HY9D5nbdyW6bavCOqZ2nFElnmBQARyoRB1BltoV89AANFezCBKwQQYOIqHzoEfCsYRhCoThCS%2BNpNahWOHBuHwQV36AXYOek2Nd5WkUuZ11rmAYW%2FEFhLGgCsMG0s1TwXRscG4ZgjD%2FEpNADa0BbQbi0sSVBTxoBAmzHaZ470LqgI9iWY4P1sxrleEebkBoTCEiVKebSkl7JdhhOpfSIIuy3ArtFJ8cUEqw1AQqJUqU1QGBBBqJ4I4Gy0l3DcEEeAjBAiyiCTGNkbiAieByT4aE0ZsgXhAVquEsD4XnlPReoDl49UuvXCA4DsBmGQCCAgMgYGSzgSWVyi4xDrnGIFBkJ51xKi9NAeclNKb3G%2BPOPscRji8ieO7a6FlDjUN%2BngOhewGFYMNCwsQbDNw2h1Hwnhzp%2BGoklhDEU1cRHiJGE0iAjc0qHD3DkswxwiQPTOv2QhRNbhImcnEf8qkng3FcmYSqJ48BQlMeDems9GaEWZk04BLR7EtE2W%2BUBLisBOCjgQHABAGDCV9L49KiIng1TwEdH6MJqq%2FEko2GEWkqQ9IJh6OInp7J6juNAe4aSsRqiybQ14eTCQFOYR6YpfZSmcIqWIXh1TBFV2EfzVMLSwBtLVBcHyoJnSng%2BHEd6eUFxAnGEZQq2NVJxFHNCKE3woR7AXGIRZ5iGadXWa%2BWxvptms0cfs0aFljh4AYLy%2BUVzDj%2BIvGYYJ2lkKVXUp6EwUTIIGFiU6L4CSoRJJSSCm66VwU5MhfkphRSSkcPKdwlFVTJI1IoZXepmL4pNKcS0PFJZOkaJ6RcPpfZuRAiGYiKZxwxnfBuJM6ZsyvjzM5csyxc81kL12dzS6mztmDQUAASi8BzKgkqHDQDEIIAgvBsRePCJQcyp9ECQF%2BBWpoVQmIsXYifcYLaWh1H8MGZirE2KdtvAwfwOAQSEX7e2tit4tiwCfHEUVswJrjFvOZNgYhu3DAOSu4i3r0p3R%2BI9M8z1YRvQ%2Bl9Sqv1KYAywRjLSui4i3i5gQcYDbZhMCKP6RoAB6H9ErJWwAYLoN9RBJDjFQIgEDiAcA%2FtAw0H9JyiwMB%2FeSIEEIf3MSCAVZAYgf1tsHbof0kBeC3ng%2FnaAEHEAbuDEKf0gYxAAFpmJwCYGRwiKBZgAGI7hmDMNVb0pEy3jCQ%2BGH85IkyDWEAwMWWwt3eF7bMaTsmJbrFHeOyd2BhCzrwPOyUi7MzYFFuGcWa70k0eaeiA5xnTPNX3V7H2%2Fsg4hzDhHKOMd46JxTmnDOWcoQ5zzoXYupdy6kRfW%2Biyn7YDfvQH%2BgDcBgPwfA5B6DsH4MoaQ5IFD%2Bo8kfEw7AbDeBcP4Zg8gJmdhwx8AYr8Kg4Zwx2DfZV5AdhkC8BBHYXUrx%2FQHDsOjejBA7AvMglBcYXs8BEZIwAfmNHkssQIbSpNIuRyjkGLPJtWV1dYwnRM%2FihJJpMwhWNQJWPJiAimtNHaEiOsdE7wxKZ03p6ABmxpzEgVd0i67N2WZ4ku7AAljsXIbpIxGVCaFmvodCy1cLrVlK4ZUvhjrn2kVfe%2B7AUWYtxaEAl6DYGVtQbfWlxARAMv4Cyz%2BnL%2Bl8uFeK0gHAZW1kVaq4N2r9XGsoBa21jrkLuu9ZhP1wbh1%2Bx4FG%2FGibvBpsfFm0eBb7GiAUao2tqxqahOUZ25gCTzQpNFY8V4nAp2wDnawMIbXnjZCA6qOp2793SJzoXb9rAbiddm7M1iCzw0DmO9N94ii%2B7Mlg9yRawp0OEU2rh%2FahHAiwvI4ix%2Br9v7%2F1Y6AzjkjePUtwaJwhzLghyeVUp1hyAOG8O0%2Fp5GRnvBqss4axx5rrX2udb2Dzvr%2FoBtDaFyL8bxHxczcJNLr4i31jLYV199bPLbzbfwGJ9XQJ9vNGEIgY5pzzn68N3PhfZzzfeEt5po3D27eGcOWv85Lv6hu4ogco587F8b4kV%2BJuJr%2Ffmsh0H1hIfYfItRYjqP6wUeRbj7FhPgGiWGeyW%2BOMG6exOiGpO2eFOeW%2BeheJWdO5WlW5ezOdWVeTWHOde3OPWTeLeguI2Y2YuEuUu82fesukA8uq2w%2BSum2ww4%2BeAk%2BYAGuQqs%2Bqikqy%2B0AfaWmbBUqFuN22%2B2mNuume%2BL24qkqx%2BkAp%2BVm9uYhvBXqwOd%2Bfu2SAeT%2BsKL%2B7Cb%2BdqH%2Bke6w4WqOWA6O8e8WSeSWqeBO4BmeUB2WuesBBWBeRWRepWSBTONWaBbONenO9ejefOzeAuw2wuhBnexBPepB%2Fe26GelB1G1BKatBLQ9BjBzBlEXgsYCgAA3CAEAA%3D%3D). 

Steps:
1. Select Ethereum network and ETH token in "From" section (MetaMask wallet auto-connects)
2. Select Solana network and SOL token in "To" section (Phantom wallet auto-connects)
3. Click on "Review transaction" button 
4. Click on "Confirm transaction" button

Actual result: Transaction fails. 
Expected result: Transaction proceeds without error. 

## Notes/ Attachments

Transaction started successfully from the second attempt, link to[ Mayan Explorer](https://explorer.mayan.finance/swap/0x045f42ce3989c90c9b0066a5e544fccbf6e7c6094afa8b0a7ba03760122f1acd). 

```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": -32603, "message": "Transaction does not have a transaction hash, there was a problem" }, payload={ "id": 8, "jsonrpc": "2.0", "method": "eth_sendTransaction", "params": [ { "chainId": "0x1", "data": "0xfa74fd430000000000000000000000000000000000000000000000000005af3107a40000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000004cee01000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000520000000000000000000000000000000000000000000000000000000000000040807ed23790000000000000000000000003451b6b219478037a1ac572706627fc2bda1e812000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000003451b6b219478037a1ac572706627fc2bda1e8120000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c30000000000000000000000000000000000000000000000000005af3107a4000000000000000000000000000000000000000000000000000000000000004973520000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000028a00001a4041c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2d0e30db05120111111125421ca6dc452d289314280a0f8842a65c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2012456a75868bf2176f8654f14ab2d8050dd274ceff9de25e98e0ee48d6bc7dee6e657d44292000000000000000000000000807cf9a772d5a3f9cefbc1192e939d62f0d9bd380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000004d4ba80000000000000000000000000000000000000000000000000005af3107a40000000000000000000000000000000001a63000673468c00000000000000000000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000041a2786dcb789f65ff0eaa374d154a32af8dfa16ae6ffbf64297cc3a79d99ba7677dc0f188f61a31ae049acfce0ec9af076b33292627d930ddbb7c4c63ca5f2be31b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014111111125421ca6dc452d289314280a0f8842a650000000000000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c4afd9b706000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000005af3107a4000000000000000000000000000000000000000000000000000000000000000000003559e9e11c7c0d54d982b103ea3194140a5f1ed299bdb673f1b67fa98a94f4a700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003a03b0000000000000000000000000000000000000000000000000000000067347a55000000000000000000000000000000000000000000000000000000000045a306000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005ccc17da2378a3dd885a3a46d21eaee35540503c3c316f80e57ea27a73a2895b0e7a885e54d080de088b949c28db5e166ccd25658e4752f5faed32c2ebc55dc4500000000000000000000000000000000000000000000000000000000", "from": "0x9631288f4050f7cfbf77b77f8540decf6cfc7012", "gas": "0x7f254", "to": "0x0654874eb7f59c6f5b39931fc45dc45337c967c3", "value": "0x5af3107a40000" } ] }, code=UNKNOWN_ERROR, version=6.13.3)
    at makeError (main-ByugNXs_.js:281:68250)
    at Go.getRpcError (main-ByugNXs_.js:282:213051)
    at Go.getRpcError (evm-ClwpBObL.js:2:2041)
    at main-ByugNXs_.js:282:215353
```

![image](https://github.com/user-attachments/assets/d63e2776-8535-4f5b-88aa-d57b58e5af9d)

![image](https://github.com/user-attachments/assets/d7c6c871-cb9c-4956-8b0d-f8e92f803ce4)

**Comment by tsadovska** [comment]
Issue is no longer reproducible with the original scenario on [Netlify](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDIwHTB9XUhYWBCwhgAKUG9vWERUaEgGOij08wA5GycfOwt3AwBhLQL0sDSG5oBjJkJITCwjWCZoASoccnrm%2FEg8SWQugAYAD2gAITFq6ABOPFWARgBmMVWAFmnpoyMAdgBWaAAzbc2VgA4AIzFt%2Ff2ANgAmA2nNvE2Wpths1mplsp1sHMzNNHvd3qsti0vpsntt3oCxJtVgZ9nhPmsjI9pi0jGjpu9Fvt7sCQekZEEGC1oAQAG79Oq05pNTkNPBiMQCIQzWbnc5XU73T7TbbnU7mTanMybIzVR5Uoyrc7Y85Gd7bU6PEwmTXvMTvEw0nl0%2FwAB2gXSQyBwLAANtBLValCMGgBdLy0r087mctodLomIKZIb%2BzljCbsyGzd73MQLT5XabnMx4sSnU7GK6re6bK5iT6PaDbT7vd47Q4tVafJsmBYe2lgnLCz4mU7bbbTTULe7TaH7R7bJ7TAybYnVe73fbnT643YD2FovBtkH03JM1kJ7RW7zBo98gWCPKJp77U4Z%2FGnaBShX7Fqnd54QszvktaZ8%2B54MdpX2dMXy3HlYFte1sEdZ1EDdMCQUDK0%2FW9CAkOaFDaSscREDseAGFgIwbAACQ5TkTxBUMiC6Ho%2BgGaNUO8ONJmFR4Dn%2FVYJ0%2BU4zX%2FSUTHec4djMTEJVWd59gMAD7lvR8FgMVYELpLJO0TW9tlWapzmLEwtXOBZzm2FpzhaR4sUeH5xyuFMzHRTidU%2Bao8GmJSMmQBk9zZKYwEPI9GkY5oz0FS8sChTYzGqapNmgCkxDwNMdOgZ4tlJITzgHbYTE2YwdM%2BEyXJjI8ILtB0UFg%2BDCs5dDOUwqrKvSCjWnaajsAWRlXIgZiE1CpMi02XTkXhO4FiuUkDDEAwl32MQzhnN9HlOVYTBHaZuOpeqGg7CEeurYzoF%2BKay11T5hzMKkTE%2BYzpiuASDGgB8lw1Ws7g6sAd0ZZkvLIo9Gs5IKL1Yyse325NTk%2BIxpjEATqgMOUTBlBZTjwACFjMt53hqBE4Ve60SugsrXXdDbmmq2laoDDbyYaYRvpBX70io7b3DgoJN2JpjWZY7ASlgbNEAMAApJhsmI6A8AANQsYjIH8Jh4EeTgijMIp3mEXgFhtYjUGIhYbCRXMWSsABpV6tq6e5znFhYTAARQALWqVYbDt1ArjwG1YAWYQACsWQseBTgATUeO3vf8JdbJwb3YE4ABxb2CJtswcBt033N3T6DwC49s%2FSf6hW5mxebwfmhZFsXJel2X5cV5XVfVzXtd1%2FXTkNk32dBSDSqdQmccUDuwCp2kAEcqEQdRvKwIph7NAANYezHuKxHgYaoqFj%2B4fCsYRhCoTg4XOIpxfeb2HE2HxHln6AjdmHFiONwXXNJhp6e8RmaN6fpoEGV6usnuYfxgwWOFIwNw0TQHGtALUo5xIIlAfsaA9wIzagOGdda2czaJgWNdCMw4jjzgpLKEwcJ%2BRLgkmxbS5ZPgiRko8csWw04eUzt5XyP1c7eHziFOYBhHiin2I2XMWIpybEeHgIw9wIqPAhhpTYdx9ikjOMBUGxI%2B4QGKlBLAMFe4DzQgPIeDRn4NWzu%2FbAZhkCPAIDIH%2BA8%2F7CkMn2MQI4Wi2VxIuEc%2FJzTQB7BjDGOwLg9mrNUBYVJ9imxUttOY2Cbp4DwdMAhUC5QkLEGQscmpJR0JoQaehQIB7vU8lnPy%2FlCkQE4cKacMSzALHhPtVaNZEGIy2P8fS1QbxCX2JsQyZh0qLjwO8VRb0u74x7nBIm7DDG%2BnZuMiAr8IAmKwE4D2BAcAEAYAxI8tjEx%2FH2FlPAi1rqfEylcNieZPjiXRFU%2BGppqhmm0tKbY0AdhhPBMKKJuCjhxLhAk4hppknVlSZQjJYhaHZMYRnfcLD2EzN5PyYKwpVgWSeAaJcpxqhnRir2e4LR5LxShkJaoTYPjvAuO8aYvYxD9PUd3cqozClTO8Po9IdKoVzIWHgBgNKrQbJ6vY1cZhnESQAulESZoTBeLfAYXx%2BpzgBPeEEkJTzVI9VeTE958SiFJJSRQ9J1CgVZLYjkjB6cPrgtpkGdhJSYUA0TOUiRVTVg1OrBSe4DS%2FgdIWC0i4mx2mdO6ecXpFLBmaIJiMvudKIAMu8OM%2FR1UFAAEovAoUoFQdlDhoBiEEAQXgEIrHhBAJQLaq9ECQCuJm%2FI6R8KERIivFoZaGjZH8A6AiRFiLVq3AwfwOBHhwUbZW4iW5xiwH3NUZq202otC3FtNgYha1NTDK1dqG1SmJl2pcA6y4jpfFOudS66UboY3ulA8G4lZHVC3M%2FAgLQi1dCYPEG0eQAD0962XstgAwXQl6iCSBaKgRA77EA4HvR%2B3I96lnxgYPelE9xXj3oIkEOKyAxD3orc23QNpIC8C3EB2O0Bv2ICnQ6dyNo7RiAALQETgEwTDcEUBdAAMTbDMGYTKFpKrppaKBl0l4UQxmqsIBgLNxgzu8PWrofGBNs3qO2zt3bsDCH7XgQdbJh1zqwMzF0rMJ3hPw0UyiI6uhqY04uy1BcsAWytrbB2TsXZuw9l7X2%2Fsg4hzDhHd4UcY7x0TsnVOlVz2Xu2je2Ad70CPufXAN9QGv0%2Fr%2FQBoD4HQOSHAzKOJpwYOwDg3gBDSH%2F3IEJnYF0fBcJXCoC6F0dhL35eQHYZAvBHh2ClEcG0sw7BgyIwQOwRy3zvhaBbPAqH0MAH4FRxOTPcTUoTKpYZwz%2B7TQbhkVXqGxjjl53g8ZjMICjX9BhCYgCJ2TG36Jto7V2l0on5OKegMplq3RP4HcqpO6dOnZ1XdopttZIIl1KpwSq%2FBnz1U%2FM1WkqhmS6H6rPZVC9V7sABaCyFoQYW%2F2fqm7%2By9MXEBEDi%2FgBL96ksyVS%2BlzLSAcA5ZGXlgr7XiulfKygKrNW6vvMa81z4rX2sLRrHgbrfq%2Bu8EG6cYb84xtUaINh3DM2tEhtYzhpbmBuNRF4xlixVicDbbALtrAwh5eWNkG99IUnjuncqgOodenTHmM19Y%2Bo93lezON1gMxCutcIQ%2B5Er7sS1WJP%2B38rVQPdUg4YT58Hfnr23ofU%2BuHr6EfoaR9FwDaPgPxcENj9KuPYOQHg4hwnxO3Sk94IVinZXqOVeq7V%2Br0wGctZtG1jrbOOe9bQ9zobcJ%2BfnHG%2FUSbIuHuzepVuRb%2BBOPS%2FuKtqIwhECLOWas5Xqvh%2Bj5Wdr7wuuZNq7O0blTCzB1j9n2orTD3fpzNX0smfjvjNcNmMq13v33ekM94DwFwLQf%2B%2FqBD%2Fzwfguh5feF2PkXkf%2Fpj%2BjkDmOE844pYp5p5ZZE65b5Y57k4lb54VY07F705Nbl6V6s5dY9Zc48586jbN6C6QDC7TYd5i7zbNA954B95gAy6MpraiLsoT7QANqybUEco65HYL5yYG4KbL5XasrsqabgjaY7427cFMHQrngmbO7RJn6EIX6%2FLkLX46q35%2B71C%2BaQ5YDQ4h6hbh4RZR4o4%2F5x7%2F6JZJ5AFpap4Zbp7ZbgFk5FbQFU6F604l5l5M4V4s6dbs5oF14YGN5YEt6tCx54F4YEHBpEENAkFkEUGRpeBegKAADcIAQAA%3D%3D%3D). Link to [Mayan Explorer](https://explorer.mayan.finance/tx/0xedd917d9439da10fac782d494f9681e6e3e6caeee8250f1104b231b210cf394f).

https://github.com/user-attachments/assets/5639b473-5a4b-4e4b-ac19-4fbc0fa7d7f6
