### ISSUE TITLE
[QA] [Binance wallet] Transaction fails after clicking on "Confirm transaction" button 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2964]
## Describe the current behavior in detail
Reproducible on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Prepare to send 0.001 GLMR from Moonbeam (Binance wallet) to Base (Binance wallet)
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button

Actual result: Transaction fails. 

```
Wormhole Connect: error completing transfer TypeError: from address mismatch (argument="transaction", value={ "chainId": 1284, "data": "0x9981509f000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb6137000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xc911CBcdd18B2019A884db5A2Bc7c3a8bfb61370", "to": "0xb1731c586ca89a23809861c6103f0b96b3f57d92", "value": 1000000000000000 }, code=INVALID_ARGUMENT, version=6.13.3)
    at makeError (main-ByugNXs_.js:281:68146)
    at assert$5 (main-ByugNXs_.js:281:68434)
    at assertArgument (main-ByugNXs_.js:281:68489)
    at main-ByugNXs_.js:282:203312
    at async Promise.all (/index 0)
    at async JsonRpcSigner.sendUncheckedTransaction (main-ByugNXs_.js:282:203692)
    at async JsonRpcSigner.sendTransaction (main-ByugNXs_.js:282:203888)
    at async Module.kd [as signAndSendTransaction] (evm-ClwpBObL.js:32:168112)
    at async signAndSendTransaction (main-ByugNXs_.js:319:62062)
    at async SDKv2Signer.signAndSend (main-ByugNXs_.js:319:64294)
```

Expected result: Transaction proceeds without errors. 

## Notes/ Attachments

Issue is not reproducible with MetaMask wallet. 

![image](https://github.com/user-attachments/assets/7b77c7a0-eec7-4b0e-9ccf-e4b1b0709879)

![image](https://github.com/user-attachments/assets/bb343e45-62a3-4649-bf8e-f48f5946fece)

**Comment by tsadovska** [comment]
Binance wallet is no longer displayed in the Wallets list.
