### ISSUE TITLE
[QA] Route activation issue after token swap with insufficient balance

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3000]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.0.1
- Wallets: Rabby
- Browser: Google Chrome Version 130.0.6723.70 (Official Build) (x86_64)
- https://preview.portalbridge.com/ecdc890a68/

Steps to Reproduce:

1. Prepare to send USDC from Ethereum (Rabby) to USDC.e on Fantom 
3. Enter the amount as 1
4. Switch to a different token where the balance is less than 1 (eg. ETH)
5. Observe that the routes remain active
6. Attempt to initiate the transaction

Expected Result: The routes should be deactivated when switching tokens if the balance is less than the entered amount, preventing the user from attempting the transaction.

Actual Result: The routes remain active even when switching to a token with a balance of less than 1. This allows the user to attempt a transaction, leading to an error.

## Attachments/Notes

https://github.com/user-attachments/assets/bd185284-fbb6-4444-a7b1-cb1327cdf2f4

**Comment by agodlevska** [comment]
Issue is reproducible on https://portalbridge.com/, with the scenario described above. 


Attachment:

**Comment by agodlevska** [comment]
Issue is reproducible on https://portalbridge.com/, with the scenario described above. 

The routes remain active even when switching to a token with a balance of less than 1. This allows the user to attempt a transaction, leading to an error.

Attachment:

https://github.com/user-attachments/assets/732dc54f-f81c-4364-bcca-76bf1dd9ebba

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
The routes remain active even when switching to a token with a balance of less than 1. 

Attachment:

https://github.com/user-attachments/assets/f5a3d752-8afa-4bc1-b393-1c3209f2dd14

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
The routes remain active.

Attachment:

https://github.com/user-attachments/assets/9a500a1b-3fce-4536-a49e-41f6aa7556d3

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
The routes remain active.

Attachment:

https://github.com/user-attachments/assets/5f642283-969e-48a3-ab8b-8a8a6ebc7d2b

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
After pressing the confirm button, the issue is appeared.

```
Wormhole Connect: error completing transfer Error: missing revert data (action="estimateGas", data=null, reason=null, transaction={ "data": "0xb0f584ff000000000000000000000000c38e4e6a15593f908255214653d3d947ca1c2338000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001a4b866e173000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe01000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000001d626877a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000065470000000000000000000000000000000000000000000000000000000000000273000000000000000000000000000000000000000000000000000000006835ab6a000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe0100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024b97d59bc0220fc66f3932a4619f7cd9adab5d761939a8bd3062d86760c1a68b00000000000000000000000000000000000000000000000000000000", "from": "0xd493066498aCe409059fDA4c1bCD2E73D8cffE01", "to": "0x337685fdaB40D39bd02028545a4FfA7D287cC3E2" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.5)
    at ca (e97f6bc9-c2bb6852c09415aa.js:3:89228)
    at 1609-d9eb6a05ac0b4dc9.js:2:89685
    at e.getBuiltinCallException (1609-d9eb6a05ac0b4dc9.js:2:89772)
    at b.getRpcError (370f8473-39492378182595af.js:1:161653)
    at b.getRpcError (42beb1bf.b92711812b56d7ce.js:1:2067)
    at 370f8473-39492378182595af.js:1:165577
``` 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/9ffc7d52-af66-4163-a041-8433951ef016" />
