### ISSUE TITLE
[QA] Unable to resume transaction: USDC transfer from Sui to Solana using CCTP Manual route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3058]
## Describe the current behavior in detail
Reproducible on https://wormhole-sui-cctp-test.netlify.app/.

Steps:
1. Send 0.001 USDC from Sui (Sui wallet) to Solana (Phantom)
2. Wait until transaction is in "ready to claim" step
3. Search for transaction
4. Check if transaction is found

Actual result: Transfer not found. 

```
Error: WormholeMessage not found
    at c.parseMessages (index-Ba2R0y12.js:1:1498)
    at async c.parseTransaction (index-Ba2R0y12.js:1:1084)
    at async main-Bq31vNj3.js:290:45725
    at async main-Bq31vNj3.js:290:10439
```
    
Expected result: Transaction can be successfully resumed. 

## Notes/ Attachments

- transaction hash: CzSkifYa2Dngx2Yi7ZB9Z4HusLS2yHRwTm2nSzy92a9b (Sui)
- send from tx: https://suiscan.xyz/mainnet/tx/CzSkifYa2Dngx2Yi7ZB9Z4HusLS2yHRwTm2nSzy92a9b
- link to Wormholescan: https://wormholescan.io/#/tx/CzSkifYa2Dngx2Yi7ZB9Z4HusLS2yHRwTm2nSzy92a9b

https://github.com/user-attachments/assets/acac0f73-44fc-4031-a49a-35fb3cbdc77d

![image](https://github.com/user-attachments/assets/f71f320a-0d4a-40e7-b162-cb7b92b1e3a9)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-sui-cctp-test.netlify.app/.
Transaction was successfully resumed: tx hash e6ZW48VUJiquuf7dqg9jYb5TKDztbAzvdjy2hb4fwN9 (Sui).


https://github.com/user-attachments/assets/5bb58d3c-ad0e-4fd4-b7e7-80c07b690c78
