### ISSUE TITLE
[QA] Transaction fails with "Cannot read properties of undefined (reading 'numRequiredSignatures')" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3059]
## Describe the current behavior in detail
Reproducible on https://wormhole-sui-cctp-test.netlify.app/. 

Steps:
1. Prepare to send 0.00106 USDC from Solana (Phantom) to Sui (Sui wallet)
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button

Actual result: Transaction fails.

```
Wormhole Connect: error completing transfer TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures')
    at l5.populate (main-BKG6qSeo.js:314:1309)
    at Connection$3.simulateTransaction (main-BKG6qSeo.js:318:75611)
    at zt (solana-Dx2uBgqJ.js:2:52572)
    at Module.ye (solana-Dx2uBgqJ.js:2:51455)
    at async signAndSendTransaction (main-BKG6qSeo.js:325:62090)
    at async SDKv2Signer.signAndSend (main-BKG6qSeo.js:325:64189)
    at async ssw (main-BKG6qSeo.js:290:11781)
    at async signSendWait (main-BKG6qSeo.js:290:11488)
    at async CircleTransfer.$ [as transfer] (main-BKG6qSeo.js:290:18917)
    at async CCTPRoute.initiate (main-BKG6qSeo.js:290:59685)
```
    
Expected result: Transaction proceeds without errors.

## Notes/ Attachments

https://github.com/user-attachments/assets/8d3d893b-5d30-4847-81b5-f3a4674b680e

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-sui-cctp-test.netlify.app/. Transaction completed successfully. 
* LInk to [Wormholescan](https://wormholescan.io/#/tx/7Dt8c3KhhkHLRE1Gnkb7smEvJNKZwHLEJsaWdD5uCK7UmxwwgKJ13FSekF9RmiVYg8TZnDqkKELbmnQiFWFp4rr)
* Link to [Solscan](https://solscan.io/tx/7Dt8c3KhhkHLRE1Gnkb7smEvJNKZwHLEJsaWdD5uCK7UmxwwgKJ13FSekF9RmiVYg8TZnDqkKELbmnQiFWFp4rr)
* Link to [Suiscan]( https://suiscan.xyz/mainnet/tx/CziTvW5jQ5ib1sV96Z11krrjo2KqYNb9zU6uPHtuRd5N)


![image](https://github.com/user-attachments/assets/1cfbc74c-ab46-47de-937b-5e0a24fdf310).
