### ISSUE TITLE
[QA] Sometimes transaction fails with "Unexpected error"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3076]
## Describe the current behavior in detail
Reproducible on https://wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select Ethereum network and ETH token in "From" section (Phantom wallet is auto-connected)
2. Select Polygon network and POL token in "To" section (Phantom wallet is auto-connected)
3. Select Mayan MCTP route
4. Click on "Review transaction" button
5. Click on "Confirm transaction" button

Actual result: Transaction fails.

```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": -32603, "message": "Unexpected error" }, payload={ "id": 22, "jsonrpc": "2.0", "method": "eth_sendTransaction", "params": [ { "chainId": "0x1", "data": "0xfa74fd4300000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000003a781e000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000520000000000000000000000000000000000000000000000000000000000000040807ed23790000000000000000000000003451b6b219478037a1ac572706627fc2bda1e812000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000003451b6b219478037a1ac572706627fc2bda1e8120000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c300000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000037d32b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000028a00001a4041c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2d0e30db05120111111125421ca6dc452d289314280a0f8842a65c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2012456a758681c2caed32f1a338f786179c5b46c866bc1bd9b159cda7245cd61f25c04e385af000000000000000000000000807cf9a772d5a3f9cefbc1192e939d62f0d9bd380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000003ac2fc00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000027d68006762d75f000000000000000000000000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000004179e219bf7d6dd1114446e8ccd0321167f73fe5d09472fe6345a4855745f14e5c1f4a2092090944815c3879efae224996f019b55338cdee41ae8e88304d9b39d71b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014111111125421ca6dc452d289314280a0f8842a650000000000000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c4afd9b706000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014e0ee2000000000000000000000000000000000000000000000000000000006762e900000000000000000000000000000000000000000000000000000000000038db86000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000", "from": "0x9631288f4050f7cfbf77b77f8540decf6cfc7012", "gas": "0x7f0cf", "to": "0x0654874eb7f59c6f5b39931fc45dc45337c967c3", "value": "0x38d7ea4c68000" } ] }, code=UNKNOWN_ERROR, version=6.13.3)
    at makeError (main-DVpQetl9.js:281:68524)
    at Fo.getRpcError (main-DVpQetl9.js:282:213051)
    at Fo.getRpcError (evm-DSoTLgvM.js:2:2041)
    at main-DVpQetl9.js:282:215353
```

Expected result: Transaction starts successfully. 

## Notes/ Attachments

https://github.com/user-attachments/assets/93e0dc89-b125-4b35-a656-5a8d233454f6

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ with scenario described above.

Transaction starts successfully.

Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/573a314e-8a6e-4e57-ba1a-1964e3b90343
