### ISSUE TITLE
[QA] Unable to connect Brave EVM wallet 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3087]
## Describe the current behavior in detail
Reproducible on https://preview.portalbridge.com/7e1e7d6a3d/ and https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select Ethereum as source chain
2. Click on "Connect source wallet" button
3. Select "Brave EVM" option
4. Check if wallet is connected

Actual result: Brave wallet notification to connect to wormhole-connect is not displayed.
Expected result: Wallet is successfully connected. 

## Notes/ Attachments

Issue is not reproducible on https://portalbridge.com/. 

```
Uncaught (in promise) DynamicError: Invalid wallet option key provided.
    at pb-index-B-mi_hOO.js:403:53742
    at Generator.next (<anonymous>)
    at pb-index-B-mi_hOO.js:378:45060
    at new Promise (<anonymous>)
    at __awaiter$o (pb-index-B-mi_hOO.js:378:44823)
    at selectWalletOption (pb-index-B-mi_hOO.js:403:53493)
    at pb-index-B-mi_hOO.js:403:54862
    at Object.onConnectWallet (pb-index-B-mi_hOO.js:728:78490)
    at pb-index-B-mi_hOO.js:632:65467
    at onClick (pb-index-B-mi_hOO.js:632:65870)
```

https://github.com/user-attachments/assets/8e9e0286-6a2b-4e11-b05d-b59596f99df5

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/710f467d-3636-44e9-a8fd-98a48d9aabc5" />
