### ISSUE TITLE
[QA] Unable to connect Keplr wallet if Coin98 extension is active

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3095]
## Describe the current behavior in detail
Reproducible on https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/.

Preconditons:
* Keplr and Coin98 extensions are installed and wallets are configured. 
* Keplr wallet was previously connected to wormhole-connect
* Coin98 extension is disabled

Steps:
1. Enable Coin98 extension
2. Select Ethereum as source chain
3. Check if Keplr wallet is auto-connected

Actual result: "Something went wrong" error message appears in "Log in or sign up" pop-up. 
Expected result: Keplr wallet is successfully connected

## Notes/ Attachments

When page is loaded error appears in Console:
```
Uncaught (in promise) TypeError: Cannot destructure property 'currentChainId' of '(intermediate value)' as it is undefined.
    at f.<anonymous> (injectedScript.bundle.js:2:181862)
    at Generator.next (<anonymous>)
    at a (injectedScript.bundle.js:2:161717)
```

When network is selected another error appears in Console:
```
[WalletConnector] [ERROR]: TypeError: Cannot read properties of undefined (reading 'map')
    at requestAddresses (https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/assets/main-B1kY4Esc.js:379:4426)
```

https://github.com/user-attachments/assets/7847f717-25b8-4b53-a2c6-8c74d8113a73

**Comment by tsadovska** [comment]
Keplr wallet is no longer displayed in the list when Ethereum network is selected.
