### ISSUE TITLE
[QA] Notication to approve claim transaction does not appear in Coinbase mobile app

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3109]
## Describe the current behavior in detail
Reproducible on https://preview.portalbridge.com/7e1e7d6a3d/. 

Steps:
1. Initiate a transfer: 0.001 USDC from Ethereum (Coinbase mobile app) to Base (Coinbase mobile app)
2. Click on "Claim" button

Actual result: Notification to approve claim transaction does not appear in Coinbase mobile app. 
Expected result: Transaction completes without errors. 

## Notes/ Attachments

```
Error handling event: TypeError: Cannot read properties of undefined (reading 'amount')
    at validateAmount (pb-index-CQ4CcOOK.js:758:474015)
    at display (pb-index-CQ4CcOOK.js:758:473570)
    at whole (pb-index-CQ4CcOOK.js:758:473951)
    at eventHandler (pb-index-CQ4CcOOK.js:769:72756)
    at eventHandler (pb-index-CQ4CcOOK.js:1196:43330)
    at Object.triggerEvent (pb-index-CQ4CcOOK.js:307:129311)
    at Wo (pb-index-CQ4CcOOK.js:756:187657)
    at Object.Nb (pb-index-CQ4CcOOK.js:43:10500)
    at Tb (pb-index-CQ4CcOOK.js:43:10669)
    at Ub (pb-index-CQ4CcOOK.js:43:10735)
```

![image](https://github.com/user-attachments/assets/d8ed63a2-9626-4602-be58-5499a5ac57ab)

**Comment by tsadovska** [comment]
Rechecked the issue again and it is no longer reproducible. 
Checked on https://preview.portalbridge.com/7e1e7d6a3d/. 

https://github.com/user-attachments/assets/7e09e66e-688e-46bc-8445-a78604932e49
