### ISSUE TITLE
[QA] Unable to resume transaction via manual route - unexpected error

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3122]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.0.1
- Wallets: Solflare, Martian
- Browser: Google Chrome Version 131.0.6778.140 (Official Build) (x86_64)
- [Netlify preview](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D)

Steps to Reproduce:
1. Perform a transaction via the manual route - 0.001 SOL from Solana (Solflare) to Aptos (Martian)
2. Attempt to resume the transaction 

Expected Result: The transaction should resume without any errors.
Actual Result: An error message is displayed, and the transaction cannot be resumed - An unexpected error has occurred. Please refresh the page.

Console:
```
Uncaught (in promise) Error: when deserializing item 'mintRecipient': chunk is shorter than expected: 133 < 145
    at updateOffset (main-BqCbYcCJ.js:286:9999)
    at deserializeItem (main-BqCbYcCJ.js:286:11810)
    at internalDeserialize (main-BqCbYcCJ.js:286:10219)
    at deserialize$2 (main-BqCbYcCJ.js:286:9768)
    at main-BqCbYcCJ.js:286:149265
    at deserializePayload (main-BqCbYcCJ.js:286:149502)
    at deserialize$1 (main-BqCbYcCJ.js:286:148883)
    at getVaa (main-BqCbYcCJ.js:291:20192)
``` 
```
TypeError: Cannot read properties of undefined (reading 'symbol')
    at getTokenDetails (main-BqCbYcCJ.js:411:39464)
    at getTransferDetails (main-BqCbYcCJ.js:411:39602)
    at Redeem (main-BqCbYcCJ.js:435:176233)
    at Nh (main-BqCbYcCJ.js:39:18669)
    at Vk (main-BqCbYcCJ.js:41:47458)
    at Uk (main-BqCbYcCJ.js:41:42913)
    at Tk (main-BqCbYcCJ.js:41:42843)
    at Ik (main-BqCbYcCJ.js:41:42691)
    at Nk (main-BqCbYcCJ.js:41:38796)
    at Ek (main-BqCbYcCJ.js:41:39657) {componentStack: '\n    at Redeem (https://deploy-preview-2985--wormh…et.netlify.app/assets/main-BqCbYcCJ.js:260:41813)'}
``` 

## Attachments/Notes

https://github.com/user-attachments/assets/3a4cc914-6071-4c60-ac45-219963d8e783

<img width="1440" alt="Screenshot 2024-12-27 at 17 15 46" src="https://github.com/user-attachments/assets/dcda243d-0166-434b-b9a6-4451130c3bbc" />

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by artursapek** [comment]
I fixed the `symbol` error. but I'm able to repro the `mintRecipient` in production.

1. https://portalbridge.com
2. resume Solana transaction `5hsE1fe5TimKspiwY5D2ASw51JbLzdGPW9xMC1hZi7DxbREt3v8HwQfnDiDoHAzX7TTRf4M4sK1pLtanGhM82j3D`
3. connect receiving wallet
4. observe error:

<img width="2560" alt="image" src="https://github.com/user-attachments/assets/a7eb0f3f-3744-4d31-878f-7b6b210c95a1" />

**Comment by agodlevska** [comment]
The issue is no longer reproducible, and the transaction has resumed without unexpected error page. 
Closing the ticket.
