### ISSUE TITLE
[QA] “Error 429: Too many requests for a specific RPC call” is displayed in Console when user reconnects Phantom/Solflare wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#318]
#### Steps:
1. Connect Phantom/ Solflare wallet
2. Select Solana network
3. Open dropdown and select “Disconnect” option
4. Connect Phantom/ Solflare wallet again
5. Observe errors in Console

#### Actual result:
Error 429 repeats in Console several times:

```
Uncaught (in promise) Error: 429 :  {"jsonrpc":"2.0","error":{"code": 429, "message":"Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com."}, "id": "5d898037-1ec7-4c81-b5db-6b6503fc09ea" } 

    at main.f2584e91.js:2:9114940
    at l (main.f2584e91.js:2:15850656)
    at Generator.<anonymous> (main.f2584e91.js:2:15852017)
    at Generator.next (main.f2584e91.js:2:15851019)
    at n (main.f2584e91.js:2:15844433)
    at s (main.f2584e91.js:2:15844636)
```

#### Expected result:
Errors do not appear in Console. 

#### Tested device:
MacBook Pro, macOS Monterey 12.6.1, Chrome version 111.0.5563.64 (Official Build) (x86_64)

#### Attachments:
* Sceenshot
![Phantom](https://user-images.githubusercontent.com/10746654/231379564-ff7c9def-8ab4-4eb1-a145-b9589d54afb5.png)

* Recording

https://user-images.githubusercontent.com/10746654/231379618-a02c9e42-f2cd-4576-b6ca-fe975be2b093.mov

**Comment by tsadovska** [comment]
Issue is no longer reproducible, Error: 429 do not appear in Console when user reconnects Phantom/ Solflare wallet.  
Closing the ticket. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c334bd46-e57c-4eeb-a983-d5f814e85378
