### ISSUE TITLE
[QA] [Sui] Sometimes “WalletSendTransactionError" appears in Console when user claims the assets

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#541]
#### Build:
https://sui-support--wormhole-connect.netlify.app/ 

#### Steps:

1. Connect Sui wallet in ‘From’ section
2. Connect Solflare wallet in ‘To’ section
3. Send 0.01 WAVAX from Sui to Solana
4. Click Claim button on Redeem screen

#### Actual results:
- “Your claim has failed, please try again” is displayed for the user
- Error appears in Console:

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Ch.solana.solflare.sendTransaction (main.68a18b01.js:37:9551518)
    at async wh.sendTransaction (main.68a18b01.js:37:9553708)
    at async Dh (main.68a18b01.js:37:9573042)
    at async jh (main.68a18b01.js:37:9573218)
    at async main.68a18b01.js:190:8814
    at async Object.onClick (main.68a18b01.js:190:8482)
```

#### Expected results:
Transaction proceeds without errors.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Reproducibility:
Noticed 3 times during testing.

#### Note:
Put priority P2, because issue is not reproducible 5/5. 

#### Attachment:
![Screenshot 2023-05-03 at 14 11 58](https://user-images.githubusercontent.com/10746654/235906184-5e5c517d-9dc9-474c-bcca-9fa8724e8ba8.png)

https://user-images.githubusercontent.com/10746654/235906215-061eec18-a807-4e15-8a94-c598c273b829.mov

**Comment by tsadovska** [comment]
Closed as duplicate #542
