### ISSUE TITLE
[QA][Testnet] wSUI from BSC -> Mumbai automatic relaying fails, "transaction may fail or may require manual gas limit"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#560]
#### Build:
https://wormhole-connect.netlify.app/ 

#### Steps:

1. Connect Metamask wallets in “From” and “To” sections
2. Prepare to send 0.1 SUI from BSC to Mumbai
3. Click “Approve and proceed with transaction” button

#### Actual result:

- Error is displayed for the user: “Error sending transfer, please try again”
- Error is displayed in Console:

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: insufficient amount", method="estimateGas", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0x49A401f7fA594BC618A7A39B316b78E329620103","data":"0x1019d6540000000000000000000000000ed284b018cb5af2267eabace13bb6ce8aad07400000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc1850000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: insufficient amount","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e73756666696369656e7420616d6f756e7400000000000000000000000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: insufficient amount\",\n    \"data\": \"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e73756666696369656e7420616d6f756e7400000000000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:14454)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:17394)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:18004)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:129727)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:130726\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:64901\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:14454)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:17394)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:18004)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:129727)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:130726\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:64901"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at l.makeError (main.05f7b2da.js:37:6516823)
    at l.throwError (main.05f7b2da.js:37:6516943)
    at Cp (main.05f7b2da.js:37:9488860)
    at Fp.<anonymous> (main.05f7b2da.js:37:9498910)
    at Generator.throw (<anonymous>)
    at s (main.05f7b2da.js:37:9487948)
```

#### Expected result:
Transaction proceeds without errors.

#### Devices:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-04 at 12 20 45](https://user-images.githubusercontent.com/10746654/236165512-2074adde-b6d4-4d2a-ae01-cb38f3f481d3.png)

https://user-images.githubusercontent.com/10746654/236165571-6c42d189-2125-44c2-a5c1-705afc6b9ba4.mov

**Comment by M-Picco** [comment]
@tsadovska I think there's something weird with the validation. Notice the input amount is `0.1` and the gas estimation is `0.103`, I'll check on that.

**Comment by anondev2323** [comment]
This might be a result of inputting the absolute minimum amount.  We probably need to require that the amount is a little higher

**Comment by M-Picco** [comment]
It seems so. Adding a few decimals (e.g: `0.200001`) is enough to make it work
