### ISSUE TITLE
[QA] “WalletSendTransactionError” appears in Console after user clicks on “Create account” link

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#593]
#### Build:
https://wormhole-connect.netlify.app/ 

#### Steps:

1. Connect From with Metamask
2. Select Alfajores as source network
3. Select CELO asset
4. Connect To with Solflare
5. Select Solana as destination network
6. Input an amount, 0.1
7. Click “Create account” link in the warning message “No associated token account exists for your wallet on Solana. You must create it before proceeding.”
8. Approve notifications in wallet

#### Actual result:

- “Encountered an error, please try again.” is displayed for the user in the warning message “No associated token account exists for your wallet on Solana. You must create it before proceeding.”
- Error is displayed in the Console:

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Tx.solana.solflare.sendTransaction (main.14209ac4.js:37:10281053)
    at async _x.sendTransaction (main.14209ac4.js:37:10283333)
    at async Nx (main.14209ac4.js:37:10353949)
    at async Object.createAssociatedTokenAccount (main.14209ac4.js:137:123437)
    at async onClick (main.14209ac4.js:137:122278)
```

#### Expected result:
User is able to create token account on Solana.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachments:

![Screenshot 2023-05-09 at 14 53 19](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0eb1ec4b-f2bc-48f6-88f5-db73a6fa523a)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c5b05cb9-08ea-4083-a28d-9efeedf91983

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with the following scenarios:
* Send ETH from Goerli to Solana (Solflare)
* Send MATIC from Mumbai to Solana (Solflare)
* Send BNB from BSC to Solana (Solflare)
* Send AVAX from Fuji to Solana (Solflare)
* Send FTM from Fantom to Solana (Solflare)
* Send CELO from Alfajores to Solana (Solflare)

Error is displayed in Console:
```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at bs.solana.solflare.sendTransaction (signer.ts:77:27)
    at async as.sendTransaction (solana.ts:193:13)
    at async ws (wallet.ts:183:3)
    at async Object.createAssociatedTokenAccount (TokenWarnings.tsx:168:14)
    at async onClick (TokenWarnings.tsx:61:5)
```

Attachment:
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a3fb2f52-61a5-4b18-a7fe-c5d2808c34d7)

**Comment by tsadovska** [comment]
Issue is reproducible with following wallets:

- Torus, error is displayed in Console: 
```
WalletSendTransactionError: Internal JSON-RPC error.
    at bs.solana.torus.sendTransaction (adapter.ts:170:23)
    at async as.sendTransaction (solana.ts:193:13)
    at async ws (wallet.ts:183:3)
    at async Object.createAssociatedTokenAccount (TokenWarnings.tsx:168:14)
    at async onClick (TokenWarnings.tsx:61:5)
```

- Solflare, error is displayed in Console:

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at bs.solana.solflare.sendTransaction (signer.ts:77:27)
    at async as.sendTransaction (solana.ts:193:13)
    at async ws (wallet.ts:183:3)
    at async Object.createAssociatedTokenAccount (TokenWarnings.tsx:168:14)
    at async onClick (TokenWarnings.tsx:61:5)
```

- Clover
- Slope
- Solong
- Exodus, error is displayed in Console:
```
WalletSendTransactionError: {"code":-32002,"message":"Transaction simulation failed: Blockhash not found","data":{"accounts":null,"err":"BlockhashNotFound","logs":[],"returnData":null,"unitsConsumed":0}}
    at bs.solana.exodus.sendTransaction (adapter.ts:183:23)
    at async as.sendTransaction (solana.ts:193:13)
    at async ws (wallet.ts:183:3)
    at async Object.createAssociatedTokenAccount (TokenWarnings.tsx:168:14)
    at async onClick (TokenWarnings.tsx:61:5)
```

- Backpack, error is displayed in Console:
```
WalletSendTransactionError: Error: user denied transaction signature
    at bs.solana.backpack.sendTransaction (adapter.ts:173:23)
    at async as.sendTransaction (solana.ts:193:13)
    at async ws (wallet.ts:183:3)
    at async Object.createAssociatedTokenAccount (TokenWarnings.tsx:168:14)
    at async onClick (TokenWarnings.tsx:61:5)
```

Issue is not reproducible with following wallets:

- Nightly ([Mumbai](https://mumbai.polygonscan.com/tx/0xbe06fe1aae48143ff17faf3e904f923af449af42594cc9be4345324bafa85100), [Solana](https://explorer.solana.com/tx/5hjvqJr5ZVT7xmFLXXJpvzD6FvSax4wyiru7VueL4kiNmbeawPD6AzuhHNQhTBX66tKqRP5bkeT5rFb8KSRo6WcW?cluster=devnet))  
- Phantom ([Mumbai](https://mumbai.polygonscan.com/tx/0x4862a3423441f55de1aa33d1edc13a8d6dbaf9c998995fcb70c0a8d16b7040ff), [Solana](https://explorer.solana.com/tx/635v3Sj5fQx1Zgd8uytwwHxZDtyJJhX32NLLJ9awbWVCvYn63qSYmVHGTNZmxCcdvEr223ZxJ5qJC5cNDbAjvQ8t?cluster=devnet))

Not able to check with following wallets:

- Blocto (ticket: [#755](https://github.com/wormhole-foundation/wormhole-connect/issues/755)) 
- Coin98 (ticket: [#708](https://github.com/wormhole-foundation/wormhole-connect/issues/708))

Attachments:

- Torus
![Torus](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4ad699ff-ab8b-4440-9073-637fe70388fe)
- Solflare
![Solflare](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9f5607c7-a841-40be-8850-fa846ac1808b)

- Exodus
![Exodus](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b0fcf838-35be-4376-ae69-622bced8df6f)

- Backpack
![Backpack](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/69147f38-cf1a-47fc-8523-3c186c75ef94)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] when sending 10 BONK from Osmosis (Leap wallet) to Solana (Solflare wallet).

Error is displayed in Console:
```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Ls.solana.solflare.sendTransaction (main.js:37:22634347)
    at async xs.sendTransaction (main.js:37:22636694)
    at async Vs (main.js:37:22718021)
    at async Object.createAssociatedTokenAccount (main.js:137:105561)
    at async onClick (main.js:137:104364)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3bc54c1f-750b-444a-aa5a-f228b7c7403f)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] when sending 0.01 WSOL from BSC (Metamask) to Solana (Backpack). Error appears in Console after user click on "Create account" link:
```
WalletSendTransactionError: Error: user denied transaction signature
    at Gc.solana.backpack.sendTransaction (main.6f254be4.js:37:19853107)
    at async jc.sendTransaction (main.6f254be4.js:37:19793569)
    at async Xc (main.6f254be4.js:37:19875457)
    at async Object.createAssociatedTokenAccount (main.6f254be4.js:137:106889)
    at async onClick (main.6f254be4.js:137:105701)
```

<img width="1224" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3a012af3-4dfa-472a-8ff4-5e682b55e1b1">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet] when
* sending 0.0001 BNB from BSC (Metamask) to Solana (Nightly). Error appears in Console after user click on "Create account" link:
```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Kc.solana.nightly.sendTransaction (main.599bb233.js:37:19791668)
    at async Fc.sendTransaction (main.599bb233.js:37:19794049)
    at async ed (main.599bb233.js:37:19875935)
    at async Object.createAssociatedTokenAccount (main.599bb233.js:137:106922)
    at async onClick (main.599bb233.js:137:105697)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8e9751ed-06d1-4409-a2d2-4cc776e23736)

* sending 0.0001 BNB from BSC (Metamask) to Solana (Exodus). Error appears in Console after user click on "Create account" link:

```
WalletSendTransactionError: {"code":-32002,"message":"Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.","data":{"accounts":null,"err":"AccountNotFound","logs":[],"returnData":null,"unitsConsumed":0}}
    at Kc.solana.exodus.sendTransaction (main.599bb233.js:37:19848475)
    at async Fc.sendTransaction (main.599bb233.js:37:19794049)
    at async ed (main.599bb233.js:37:19875935)
    at async Object.createAssociatedTokenAccount (main.599bb233.js:137:106922)
    at async onClick (main.599bb233.js:137:105697)
```

**Comment by tsadovska** [comment]
Error appears in Console when wallet doesn't have SOL on Solana.
Tested OK on https://deploy-preview-1005--wormhole-connect.netlify.app/ [mainnet] when sending 0.0001 BNB (Metamask) from BSC to Solana (Nightly):
* Send from: [BSC](https://bscscan.com/tx/0x193f31570efae5245621501c230bcda337326c7f8ddb603106fd5d54a68a9fda)
* Send to: [Solana](https://explorer.solana.com/tx/5BQJztjFT7jmNEdEhyFsGwVgTt4aRzLCCtAXoHGrDcW7wPiXnGvyb3PWeXxQE66N8ytxxsQVqjHJfeeEjnmfh55n)

**Comment by tsadovska** [comment]
Rechecked the issue on https://wormhole-connect.netlify.app/ [Testnet] with new Phantom account:
* User can successfully create account by clicking on "Create account" link when there are some SOL on Solana
* Error appears in Console when wallet doesn't have SOL on Solana

Ticket is closed.
