### ISSUE TITLE
[QA] Redeem screen does not open when sending BNB from BSC to Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#613]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Metamask wallet is connected in 'From' section
2. Phantom wallet is connected in 'To' section
3. Prepare to send 0.001 BNB from BSC to Solana
4. Click “Approve and proceed with transaction” button 

#### Actual result:

- Transaction is displayed as loading on wormhole-connect
- Transaction is displayed as Completed in block explorer: https://testnet.bscscan.com/tx/0x43afdc505890e76ff85e21c65b3591fae9c0761c298c4d17a5ff10843fc1cd41 
- Transaction ID is not found when searching for transaction on Resume transaction screen
- Error is displayed in Console

```
Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at l.makeError (main.14209ac4.js:37:1408340)
    at l.throwError (main.14209ac4.js:37:1408460)
    at Re.<anonymous> (main.14209ac4.js:37:5149772)
    at Generator.throw (<anonymous>)
    at s (main.14209ac4.js:37:5141514)
```

#### Expected result:
Redeem screen is opened.

#### Note:
Issue is not reproducible when user sends:

- ETH from Goerli to Solana
- MATIC from Mumbai to Solana
- AVAX from Fuji to Solana
- CELO from Alfajores to Solana

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Version 113.0.5672.92 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-17 at 17 13 05](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2be04736-20b0-4c34-9c47-dfa4f96e8f0b)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/293d09b6-4ab0-4d73-87b1-73a5051400e1

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. User can successfully send BNB from BSC (Metamask) to Solana (Phantom). 

Transactions:
- [BSC tx](https://testnet.bscscan.com/tx/0x66e7486789e8f5095827fccc915634b7febe0f99a90696564db70fb0b99d23a8), Metamask wallet: 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185
- [Solana tx](https://explorer.solana.com/tx/3faWQJo5R4xQPDx3ogvSuEfmrXAVUeNg1S5nNxEKs1J5wbRvACw64p7DLedJwhUjMjAcasm61xgyZQMCrnYo7nbL?cluster=devnet), Phantom wallet: 7yEFBzgwqBHmEtPLvKcQgzPTpfcnrScAfrvenvnBJA5n

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c5701ad2-bcc8-494c-9979-00393475d32f)

Ticket is closed.
