### ISSUE TITLE
[QA] User is not able to send assets from BSC 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#672]
#### Builds:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]
https://wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Metamask wallets in ‘From’ and ‘To’ sections
2. Prepare to send 0.0001 BNB  from BSC to Fantom
3. Observe “Current estimate” in “Gas payment” section
4. Observe “Source chain gas estimate” in Preview section
5. Click “Approve and proceed with transaction”
6. Confirm Metamask notification

#### Actual results:

- Current estimates are not calculated in “Gas payment” and Preview sections
- Loading does not finish and transaction does not move to the next step
- Errors are displayed in Console

```
Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at c.<anonymous> (json-rpc-provider.ts:483:23)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```

`Access to fetch at 'https://data-seed-prebsc-1-s3.binance.org:8545/' from origin 'https://feature-sei--wormhole-connect.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

#### Expected results:
Transaction proceeds successfully to the next step.

#### Notes:

- Issue is also reproducible when user sends wrapped asset (in my case, WFTM) from BSC to Fantom. Error is displayed in Console:

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: insufficient amount", method="estimateGas", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0x49A401f7fA594BC618A7A39B316b78E329620103","data":"0x1019d6540000000000000000000000009ab305b792dbdb8253bee909e7006611cb45175b00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc1850000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: insufficient amount","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e73756666696369656e7420616d6f756e7400000000000000000000000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: insufficient amount\",\n    \"data\": \"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e73756666696369656e7420616d6f756e7400000000000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:18:17794)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:18:20734)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:18:21344)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:74080)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:75079\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:58554\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:18:17794)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:18:20734)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:18:21344)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:74080)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:75079\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:58554"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at y (json-rpc-provider.ts:78:20)
    at u.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```

- Linked #670 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachments:
* Sending BNB from BSC to Fantom
![BSC - 1](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cd70107e-c5c5-495f-ae24-059e07c77882)

* Sending WFTM from BSC to Fantom
![BSC - 2](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/81ec13ce-d0af-4e9f-b47b-41481ca86b81)

**Comment by M-Picco** [comment]
Closing this and #670 since they seem to be due to issues with the testnet BSC RPC node
