### ISSUE TITLE
[QA]  “Fewcha Move” wallet option is not clickable 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#695]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Select Aptos wallet in ‘From’ section
2. Connect Fewcha wallet in ‘From’ section
3. Change network to Sui
4. Try to connect “Fewcha Move” wallet

#### Actual result:
“Fewcha Move” wallet option is not clickable. 

#### Expected result:
User is able to connect “Fewcha Move” wallet. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/06015b86-9897-44d9-9760-e451e115f5c4

**Comment by tsadovska** [comment]
Rechecked the issue on https://wormhole-connect.netlify.app/ [Testnet]. It is reproducible with one more scenario. 

#### Preconditions:
* “Fewcha Move Wallet” extension is installed and is enabled
* Fewcha wallet is locked

#### Steps:
1. Send 0.001 MATIC from Mumbai (Metamask wallet) to Aptos (Spika wallet)
2. Click “Bridge more assets” button on Redeem screen
3. Try to change Spika wallet to “Fewcha” or “Fewcha Move” wallet

#### Actual results:
* “Fewcha” and “Fewcha Move” options are not clickable
* Errors are displayed in Console:

```
TypeError: Cannot read properties of undefined (reading 'publicKey')
    at c.<anonymous> (FewchaWallet.ts:148:31)
    at Generator.next (<anonymous>)
    at a (Coin98Wallet.ts:66:1)
```
    
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at sui-inpage.1fe9dd09.js?id=cfe70022-d7d3-4b83-ae60-58a6c169c922:3:3038
    at async Kg.connect (sui.ts:88:13)
    at async WalletModal.tsx:213:24
```

#### Expected results:
User is able to connect “Fewcha” or “Fewcha Move” wallet.

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2a4f4b01-f762-4323-ad48-1b49df518c15

**Comment by tsadovska** [comment]
"Fewcha Move" wallet option is clickable when "Sui testnet" network is selected in the extension. Ticket is closed.
