### ISSUE TITLE
[QA] Pontem wallet notification not opening when user connects Pontem wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#713]
#### Builds:
https://wormhole-connect.netlify.app/  [Testnet] - Tested NOK
https://feature-sei--wormhole-connect.netlify.app/ [Testnet] - Tested OK

#### Steps:

1. Click “Connect wallet” button
2. Select Pontem option

#### Actual result:

- “Your file couldn’t be accessed” is displayed in wallet notification
- Error is displayed in Console:

```
Uncaught TypeError: Cannot destructure property 'register' of 'undefined' as it is undefined.
    at e (contentScript.js:501:48358)
    at contentScript.js:502:76
```

#### Expected result:
User is able to successfully connect Pontem wallet. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-22 at 21 33 10](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5db336dc-36cf-4a4d-87e4-da544b71b0ef)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. Pontem wallet is successfully connected. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/af76fd8a-1eec-453f-a84c-844e05cd8563)

Ticket is closed.
