### ISSUE TITLE
[QA] [Mainnet] User is not able to claim wrapped asset when sending from Aptos

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#723]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet] 

#### Steps:

1. Connect Spika wallet in From section
2. Connect Metamask wallet in To section
3. Send 0.001 CELO from Aptos to Moonbase
4. Click “Claim” button on Redeem screen

#### Actual result:

- “Your claim has failed, please try again” is displayed for the user
- Error is displayed in Console:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0xbc976D4b9D57E57c3cA52e1Fd136C45FF7955A96","data":"0xc687851900000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000100010000000001004366eb9d0369c0b916d1c64d597b8962928ec871b5e0478c54935f5f8150983002f7232c91872fd579e94f8aa500a166b161d495e9087c88493bbfb838b59edf0064981c3d00012687001600000000000000000000000000000000000000000000000000000000000000010000000000000258000100000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000f194afdf50b03e69bd7d057c1aa9e10c9954e4c9000e0000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc18500100000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"VM Exception while processing transaction: revert","data":"0x"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32603,\n    \"message\": \"VM Exception while processing transaction: revert\",\n    \"data\": \"0x\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:15154)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18094)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18704)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:94385)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:95384\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:22:58222\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:15154)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18094)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18704)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:94385)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:95384\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:22:58222"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.f2ca49db.js:37:1803301)
    at l.throwError (main.f2ca49db.js:37:1803421)
    at g (main.f2ca49db.js:37:1860317)
    at u.<anonymous> (main.f2ca49db.js:37:1870501)
    at Generator.throw (<anonymous>)
    at s (main.f2ca49db.js:37:1859648)

```

#### Expected result:
User is able to successfully claim asset.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-25 at 13 57 22](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/084ccded-53e1-47d4-b200-37b93af291bb)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending WBNB from Aptos (Martian wallet) to Ethereum (Metamask wallet).

- Sending From transaction: [Aptos tx](https://explorer.aptoslabs.com/txn/0x6b75e034bdd5f667cc2027ffa6db685009a41086de912184e4fb3ba3fb1bae3b)
-  Metamask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
-  Martian wallet: 0xebbb42751860774b5251b57a44f82997418d4d054987f393fb092d55ea9ef2fc 

- Error in Console:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0x3ee18B2214AFF97000D974cf647E7C347E8fa585","data":"0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000030d00d1fde2611a3ad1224b39edfd9bfbf50dd205e573d42ed62e70ff911b28ca7e222c406801d5d0bb5e67dfa75ee9214b085f78121e5ed3cac042ca75dc38a9d9e70102d6d93e423a6c83b7feeffb8b50421b2c3fd760db415df8c862d24377fa3416421027b1f1e1b27548be01c8d33e0acbc5df37ccde0e2b1c6125d4a654ff700e590003e7988d30ae81e8b2d8560e9574f80e089861ae641c69c66a3eb01686b19c416723b5fa82566bd6abeeaa6c93b065465f1843dcc2b05ee1025c3a24c0ffa09d6500047db20c44773f6ff0a94cbd227e2533c291de19f2eb76307cdac1e672bf8e7dd57e3fcdbb5a59b9c3a430116fb3bd2aff450f584df0dfcd91f5a5be92820ed2900106090822aa9ccfa1cdf49724e4bc4cbef06ffde18f705198147e9ace101146c22a75d30f4e5ff3f297d735bdfe46771afe2f185da4d335723d7c98fe965691595f010a2279d32a2821e74119a0093e2c9135315d9d89bb6960f8d5d6a134e8315df29e1134e9b59f289b9119b1aa1c7a747670f475dcf57f15b63a66f24afbb4aaf232010b7118a726dc9f0dcd4fd1534e095794def88e6b093e4f8599bb3e0bf622e839bf5d4b242c5e893ed29295199e2a9804c3239baaa2e15ccc12c944c79882b9ea05000c55c97ca7ebc35b11e418114300b549d0fc1c504a793f186d0efce04646a103f10f5774601d76d94f9fe4c2e63d4270208c8eaf062385d067e25c3de40c086c38000d6dacf0b21c58a0065379fc7d34e566f43f0a8456a29554ac8e676d70f44ee7710b94a2664e30d3b41f2ebca72f7fa4387e93f7273ab7cc8c6ef76cfcc52dcebb000e61e65732b85a3fd36eeeb6fa67f208c667c427a4dc9e8c006f3d2c082ef5b099686a127fc760ad13ff9356dbf9747ebf7952b882cf5da5400d624a109984deeb011033667b04aa1c901a2e3c809e5865a9132b9e57e517723c7d10740dc175423e62743a68ee0f8fd6f4fcf5a6ff42f45f2ae189004689ae37711be0b816957bc3080111aa6024ed4c1c71d2edfe2ce1b841ddeafed65292e6d6b5bbfd07d76e4feddfea7092972b1f1a9c8dab530e34c39030bb0fc971757e04358fd59fa1007e61f693001299c213716709258cadbe83c43cbf8fb98a3d40cc2bfbac82cca0cbc5abf34cb77b62d55b17b8e9a6cc0a8ff05d5eb912540a29a0088040fa7356c3e1c8a66e9301649975b90001756f0016000000000000000000000000000000000000000000000000000000000000000100000000000055e300010000000000000000000000000000000000000000000000000000000000000064000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00040000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000200000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.d13e45d0.js:37:7498881)
    at l.throwError (main.d13e45d0.js:37:7499001)
    at Cw (main.d13e45d0.js:37:12402784)
    at zw.<anonymous> (main.d13e45d0.js:37:12413068)
    at Generator.throw (<anonymous>)
    at s (main.d13e45d0.js:37:12402106)
```
![Screenshot 2023-06-26 at 14 42 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/27e52a63-8239-40cb-b58b-867ce094160b)

**Comment by tsadovska** [comment]
Linked https://github.com/wormhole-foundation/wormhole-connect/issues/228

**Comment by AigaD** [comment]
The same issue was reproduced for transaction 0.03 AVAX from Avalanche to Moonbeam at Mainnet - https://mainnet--wormhole-connect.netlify.app/#
TX Avalanche - https://snowtrace.io/tx/0xf82981385e5b8c9ea6869001bd48905e32ea5ad745a5c4a939d2fcc2cb067e05

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6358d55-86ff-4bda-8f27-6e295e897ad9

**Comment by SNIKO** [comment]
The same issue happens when claiming USDC in Polygon network transferred from Sui


```
MetaMask - RPC Error: Internal JSON-RPC error. Objectcode: -32603data: {details: 'Internal RPC Error. Try again after some time..', code: -32005}message: "Internal JSON-RPC error."[[Prototype]]: Object
 (anonymous) @ inpage.js:1

```
```
Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xB98990E67e4C45e406b9ba40eC1D04De1231789B","to":"0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE","data":"0xaa4efa5b160dcd80e54ecf838e28595949871ab6a7954c0c9df4ec02c7db128f5971067c","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"details":"Internal RPC Error. Try again after some time..","code":-32005},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"details\": \"Internal RPC Error. Try again after some time..\",\n    \"code\": -32005\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:22333)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26272)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26882)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44209)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45208\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:54199\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:22333)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26272)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26882)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44209)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45208\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:54199"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.js:37:1803162)
    at l.throwError (main.js:37:1803282)
    at g (main.js:37:1860182)
    at u.<anonymous> (main.js:37:1870366)
    at Generator.throw (<anonymous>)
    at s (main.js:37:1859513)
```

**Comment by AigaD** [comment]
Managed to reproduce the same behaviour when Claiming 0.001 WAVAX that were sent from Sui (Sui wallet) to Moonbase (Metamask).
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1351" alt="Screenshot 2023-07-28 at 14 54 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/32d5a20b-1476-4423-99c0-bfe0648289e1">

**Comment by tsadovska** [comment]
Rechecked on https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. Scenario "Send WBNB from Aptos (Spika) to Moonbeam (Metamask)" is still reproducible. 

Sending from tx: [Aptos tx](https://explorer.aptoslabs.com/txn/0xf6401ed18883d4c82e87b854e3e0af3311f59d4d1da0420a68cd818fab05d623?network=mainnet) 
* Spika wallet: 0x659900f39239fbfb0cdd74a188ee04fa38c8c4cb2e12c51998f82f80ee3f795b
* Metamask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012

Error:
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0xB1731c586ca89a23809861c6103F0b96B3F57D92","data":"0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000030d000d3c9c55041205df5874c4e7289618ba4fd9fe40afb28e27eef86855764e422826df7341c518d6439fafaddd4cae9fbb004928b6612220d366e699791b171a370102a55e9e0471a8fa3d5b739df1aeb1a3674562b0ba1077eb9bece390d1a70fff7d3546dc787d0cb34705ecfe9a94d73dbd8381537bdf19ca434dfc17dc04bcd3cc0103b9b3cfb6fc947d8b244ccc001ddc27518f7ce75e9ded00c9b202d5eb4913a9bc3c1ae73e48179265f03da11d5c7ec09001ceae4fb9a2fc2a741428b993f081a300045f7c5c69d2ee5ad54211ee0881a669479b843ff4aaaf70c2746982c535fe791c00c1715af4c169be76a716c4d49baa311faad07de901a28b9ac29d835f37e7f60105371585238395c03df5244ef824fd039fc915d76e389f93f1e77aa65c200e6e381241b761319a49988bc7b4b1ed3b95e487495766488e1767758c383b713b1645010a2633f9bcfd18b8f2ea7d1b42eb7b9ed76f46ca699937f9a47db86130d56f294e680156af4cee8653790a89db4a631a0ef3e7315863bc89446d3dfafa1415aef9010c8ea1d474e3d50c1dc4ff280227ea28818eabfb7483d7780f3d7fc342d642fb3c64dacc5a36e2a0bac72967c142300e13eb7b9490bb4033fdacd59a32116dd30a010dcc97ba23a2e8faad79a00081df0fc6f0fa2980aedfbb2bd911598e1fc42911c920e382990c576f13b3ae125e22b66abcb95514e1b8c75281dd9c2e82158dac36000e47453a6f80c65f6821c730ce815cf9c3940bca140fdd58b715199c43d05acdd63ae49fa4ce8896cbf4381ff76fde6d8fe8abaa3687f3da6e592c8720c5067ac5010fac0e44847a75402aa9d65f224e40218bfb0e5bb4de260509cb9b8b395ae93b3b741d1a04d6e00ec591fb1b9e764140a4d227ad7e3be0ba35a89ff01a8a3b053a001072eaceda94107984f2f88d97e232a808109232daa527d8b7ec9df264069f7d4414d7fdbfbc7659e2021cbcad65b720b6f9188950d409aa2c0d4137bdabc6a85d0111ef66f55e7ea720fefd421fab1734d3027fa70b8575e9a5091dc206da08a2267f1d25529e4b8bf53d7bee77352c6b1e4ab41510515964b02852c837753bb5560700124e1a0702321cae74bfc650e944502c4f3556b0597f09a0fb767319c8af042e6272e764e2ecb063441595800eb2c0e657eefb94526f3d534945279eb9115abef30064c772000000fef6001600000000000000000000000000000000000000000000000000000000000000010000000000007052000100000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00040000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012001000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"VM Exception while processing transaction: revert","data":"0x"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32603,\n    \"message\": \"VM Exception while processing transaction: revert\",\n    \"data\": \"0x\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:22333)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26272)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26882)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44209)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45208\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:54199\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:22333)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26272)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:26882)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44209)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45208\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:54199"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at y (json-rpc-provider.ts:66:16)
    at u.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/53309f31-7227-4139-871f-2afe006e6c89)

**Comment by tsadovska** [comment]
The following scenarios are no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet], user is able to claim token successfully:
* Send CELO from Aptos to Moonbase - Tested OK ([Aptos](https://explorer.aptoslabs.com/txn/0x739330be5b60a311326f22f1c8e2399af6d69e4794cb047d7a1cc2cee899925b?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0xf47e13c87175f9771137bdc50704fd635910533bf8cf5a55b98ca16f5fe0d3c0))
* Send WAVAX from Sui (Sui wallet) to Moonbase (Metamask) - Tested OK ([Sui](https://suiexplorer.com/txblock/2xJUfMijjFxcfd21pNqx6YVsEGGGaAG7icdQcekmB5zc?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0x40910f3c3e6beba6e2fc796548c0447959a93d47c69fb308914bcbab13523c12))

**Comment by tsadovska** [comment]
Issue will be rechecked after #946 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 
Scenarios - Tested OK:
* Send 0.0001 USDT from Aptos (Spika) to Moonbeam (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0xd2cce3ec486fe608bdb876a5a272273798e70e3fadb1a7f19416e67bab44d3ef), [Moonscan](https://moonscan.io/tx/0xd11733af5f0d69d03af350ec995ab22ea0e54ac475fdddc357b78b2b78ce4fed)
* Send 0.001 CELO from Aptos (Martian) to Moonbeam (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x67011889dc0e60ea35666bcecda908c66d6073f40b6338dec7a7e5be198f5657?network=mainnet), [Moonscan](https://moonscan.io/tx/0xc82625b374c4a494fc1212c5dcee21b119907a03d157916bd5dc399d80feb8d0)
* Send 0.00011 WMATIC from Aptos (Martian) to Avalanche (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x43914b95db5a82ac2395798056f62c79f09b8576c31d108137579c4e7afbde56), [Snowtrace](https://snowtrace.io/tx/0x6a438063ecd6c7afdf9c6588fdd75b515fe8cc2609b717fd4442a828fc4364f3)
* Send 0.00001 WBNB from Aptos (Pontem) to Fantom (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x783e6b4e29fb0c697751c40168811e5b27ac917fcb41ea0d61956ddcb5f951ad), [FTMScan](https://ftmscan.com/tx/0xfa9c7b1aee4399623543533fbd9700c1f62ee004ad3d05d801dc2c7e75adbb13)

**Comment by vanlikk** [comment]
issue is still persists if you do transfer 1 USD from Avalanch to SUI via whormhole on the https://bridge.cetus.zone/sui 
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/40547706/84bc83eb-9ee2-4a0f-a0ff-a698fcf636df)

`main.js:292 Error: Error: RPC Validation Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server.
Cause: StructError: At path: error.parent_object_id -- Expected a value of type `never`, but received: `"0xf6d72d89a9b817d2d324798e4b16c7526c918b2f5ed1ec321b2ae2f983c98959"`
Reponse Received: {
  "error": {
    "code": "dynamicFieldNotFound",
    "parent_object_id": "0xf6d72d89a9b817d2d324798e4b16c7526c918b2f5ed1ec321b2ae2f983c98959"
  }
}
    at JsonRpcClient$1.requestWithType (main.js:292:1129)
    at async JsonRpcProvider.getDynamicFieldObject (main.js:292:37518)`
