### ISSUE TITLE
[QA] [Mainnet] User is not able to send SOL from Phantom to Aptos

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#728]
#### Build:
https://mainnet--wormhole-connect.netlify.app/ [Mainnet] 

#### Precondition:
User has SOL in Phantom wallet

#### Steps:

1. Connect Phantom wallet in From section
2. Connect Martian wallet in To section
3. Prepare to send SOL from Solana to Aptos
4. Click “Approve and proceed with transaction” button

#### Actual results:

- SOL balance is not loading (issue [#696](https://github.com/wormhole-foundation/wormhole-connect/issues/696) ), balance is displayed as “-” when user has 0.77579 SOL
- “Error sending transfer, please try again” is displayed for the user
- Errors are displayed in Console:

```
Uncaught (in promise) Error: failed to get balance of account 4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU: fe: Expected the value to satisfy a union of `type | type`, but received: [object Object]
    at main.d13e45d0.js:37:2427927
    at async xa.getBalance (main.d13e45d0.js:37:2427854)
    at async A.getNativeBalance (main.d13e45d0.js:2:716732)
    at async h.getNativeBalance (main.d13e45d0.js:2:841337)
    at async Nk (main.d13e45d0.js:37:12663699)
```

```
fe: Expected the value to satisfy a union of `type | type`, but received: [object Object]
    at Ae (https://mainnet--wormhole-connect.netlify.app/static/js/main.d13e45d0.js:37:2344437)
    at ve (https://mainnet--wormhole-connect.netlify.app/static/js/main.d13e45d0.js:37:2344180)
    at xa.getMinimumBalanceForRentExemption (https://mainnet--wormhole-connect.netlify.app/static/js/main.d13e45d0.js:37:2440500)
```

#### Expected results:
Transaction proceeds without errors. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachments:
* wormhole-connect
![Screenshot 2023-06-26 at 19 34 59](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/049cde51-a3cd-45fc-99d9-291d475ebb79)

* Phantom wallet
![Screenshot 2023-06-26 at 19 35 22](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c75b5176-6115-4f79-ab78-4dae26f57691)

**Comment by tsadovska** [comment]
Closing this issue, current behaviour is described in #732
