### ISSUE TITLE
[QA] [Testnet, Mainnet] Cannot send and receive assets with Blocto wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#755]
#### Builds:
https://wormhole-connect.netlify.app/ [Testnet]
https://mainnet--wormhole-connect.netlify.app/ [Mainnet] 

#### Steps:

1. Connect Metamask wallet in ‘From’ section
2. Select Fantom network in ‘From’ section
3. Select Solana network in ‘To’ section
4. Connect Blocto wallet in ‘To’ section
5. Select FTM asset
6. Type Amount (in my case, 0.01)
7. Click “Approve and proceed with transaction” button

#### Actual result:

- “Approve and proceed with transaction” button is not clickable
- Error is displayed in Console:

```
Uncaught (in promise) TokenOwnerOffCurveError
    at mint.ts:169:78
    at Generator.next (<anonymous>)
    at index.ts:3:1
    at new Promise (<anonymous>)
    at o (index.ts:3:1)
    at t.getAssociatedTokenAddress (mint.ts:167:32)
    at A.getAssociatedTokenAddress (index.ts:146:18)
    at async A.getAssociatedTokenAccount (index.ts:160:11)
    at async TokenWarnings.tsx:136:13
```

#### Expected result:
Transaction proceeds successfully to the next step. 

#### Note:
Issue is also reproducible with different networks:

- Goerli
- Mumbai
- BSC

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e4098600-3066-4020-b12f-bc7fc89228f4

**Comment by tsadovska** [comment]
Issue is reproducible only with Blocto wallet.

Issue is not reproducible with other wallets, warning message to create wallet account is displayed when all fields are filled: 

- Nightly 
- Backpack
- Exodus
- Torus
- Solong 
- Slope
- Clover
- Solflare
- Phantom

Warning message to create wallet account: “No associated token account exists for your wallet on Solana. You must create it before proceeding.”

**Comment by tsadovska** [comment]
Issue is also reproducible with following scenarios:
* Send SEI from Sei (Fin) to Solana (Blocto)
* Send SUI from Sui (Sui) to Solana (Blocto)
* Send APT from Aptos (Martian) to Solana (Blocto)

"Approve and proceed with transaction" button is not clickable and error is displayed in Console:
```
Uncaught (in promise) TokenOwnerOffCurveError
    at mint.ts:169:78
    at Generator.next (<anonymous>)
    at index.ts:3:1
    at new Promise (<anonymous>)
    at o (index.ts:3:1)
    at t.getAssociatedTokenAddress (mint.ts:167:32)
    at A.getAssociatedTokenAddress (index.ts:146:18)
    at async A.getAssociatedTokenAccount (index.ts:160:11)
    at async TokenWarnings.tsx:136:13
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/36015eb3-05b7-48ab-8841-63257444421b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] when:
* Sending 0.1 MATIC from Mumbai (Metamask) to Solana (Blocto)
```
Uncaught (in promise) TokenOwnerOffCurveError
    at main.6f254be4.js:37:18434359
    at Generator.next (<anonymous>)
    at main.6f254be4.js:37:18431961
    at new Promise (<anonymous>)
    at a (main.6f254be4.js:37:18431706)
    at t.getAssociatedTokenAddress (main.6f254be4.js:37:18434275)
    at I.getAssociatedTokenAddress (main.6f254be4.js:37:18050363)
    at async I.getAssociatedTokenAccount (main.6f254be4.js:37:18050557)
    at async main.6f254be4.js:137:106427
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bd060c0a-b3de-4dbc-8a50-1e5bd7ebebd1)

* Sending 0.01 SOL from Solana (Blocto) to Mumbai (Metamask)
```
TokenOwnerOffCurveError
    at t.getAssociatedTokenAddressSync (main.6f254be4.js:37:18434813)
    at t.createTransferNativeTokensWithRelayInstruction (main.6f254be4.js:37:18124814)
    at async I.sendWithRelay (main.6f254be4.js:37:18060367)
    at async Vl.send (main.6f254be4.js:37:19945011)
    at async Object.send (main.6f254be4.js:37:19975954)
    at async Object.onClick (main.6f254be4.js:137:24760)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9a135217-0cd2-46b5-846a-4b688167d342)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet].
Error is displayed in Console:
```
Uncaught (in promise) TokenOwnerOffCurveError
    at main.599bb233.js:37:18434375
    at Generator.next (<anonymous>)
    at main.599bb233.js:37:18431977
    at new Promise (<anonymous>)
    at a (main.599bb233.js:37:18431722)
    at t.getAssociatedTokenAddress (main.599bb233.js:37:18434291)
    at I.getAssociatedTokenAddress (main.599bb233.js:37:18050388)
    at async I.getAssociatedTokenAccount (main.599bb233.js:37:18050582)
    at async main.599bb233.js:137:106460
```
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1740a877-c60d-43a9-9889-69ef22aebee4)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 SOL from Solana (Blocto) to Goerli (Metamask) w/o automatic deposit. Loading doesn't finish on confirmation pop-up. 

Error is displayed in Console:
```
Uncaught (in promise) WalletAccountError: Internal JSON-RPC error.
    at U0.solana.torus.connect (main.49b7c6e5.js:37:208829)
```

![Screenshot 2023-10-27 at 18 01 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e154207d-61f9-48a2-854b-770adfe347b0)

**Comment by tsadovska** [comment]
"Blocto" wallet is no longer shown in "Connect wallet" window when Solana network is selected.


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/13de2a65-ad7e-4d2c-89c4-008f94d40b8d)


Ticket is closed.
