### ISSUE TITLE
[QA] [Mainnet] WFTM from Avalanche → Moonbeam, “transaction may fail or may require manual gas limit”

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#780]
#### Build:
https://mainnet--wormhole-connect.netlify.app/ [Mainnet]

#### Steps:

1. Connect Metamask wallets in 'From' and 'To' sections
2. Prepare to send 0.001 WFTM from Avalanche to Moonbeam
3. Click “Approve and proceed with transaction” button

#### Actual result:

- “Error sending transfer, please try again” is displayed for the user
- Error is displayed in Console:

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: insufficient amount", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0xCafd2f0A35A4459fA40C0517e17e6fA2939441CA","data":"0x1019d654000000000000000000000000d19abc09b7b36f7558929b97a866f499a26c2f8300000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: insufficient amount","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e73756666696369656e7420616d6f756e7400000000000000000000000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: insufficient amount\",\n    \"data\": \"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013696e73756666696369656e7420616d6f756e7400000000000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:31538)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:34478)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:35088)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:72700)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:73699\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:100465\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:31538)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:34478)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:35088)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:72700)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:73699\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:100465"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at y (json-rpc-provider.ts:78:20)
    at u.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```

#### Expected result:
Transaction moves forward to next step and is completed.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-07-21 at 12 56 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2644b005-d8d9-4067-b81e-f23a053058e5)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. 
Send from tx: [Snowtrace](https://snowtrace.io/tx/0x732238cbbfaec68c138b4b316ea99228cc3cabed40842c2f7fc44b33168a8671)
Send to tx: [Moonscan](https://moonscan.io/tx/0x68fdb0eb34a1bee14170e4d4d36b68afdfa69090c83f4e90b1bf177662225767)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/412e864b-29ad-477b-a463-b8fddba0e88d)

Ticket is closed.
