### ISSUE TITLE
[QA] User is not able to send assets with Brave wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#785]
#### Precondition:
Open https://wormhole-connect.netlify.app/ [Testnet] in Brave browser

#### Steps:

1. Prepare to send 0.01 SOL from Solana to Goerli
2. Click “Approve and proceed with transaction” button

#### Actual results:

- User is not able to send asset, "Error sending transfer, please try again" is displayed for the user.
- Error is displayed in Console:

```
WalletSignTransactionError: Blockhash is invalid or cannot be validated
    at bs.solana.brave.signTransaction (adapter.ts:197:23)
    at async as.signAndSendTransaction (solana.ts:212:11)
    at async ws (wallet.ts:183:3)
    at async As (wallet.ts:260:7)
    at async index.ts:177:11
    at async Object.onClick (Send.tsx:104:13)
```

#### Expected results:
User is able to successfully send asset.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Brave Version 1.56.11 Chromium 115.0.5790.102 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-07-25 at 14 47 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7012686e-93b7-4655-b3e0-f9d62d80088d)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]. 
Error is displayed in Console after user clicks on "Approve and proceed with transaction" button:
```
WalletSendTransactionError: Error processing the transaction
    at Kc.solana.phantom.sendTransaction (main.b5733f60.js:37:19815484)
    at async Fc.sendTransaction (main.b5733f60.js:37:19794468)
    at async ed (main.b5733f60.js:37:19876354)
    at async td (main.b5733f60.js:37:19876540)
    at async Hl.send (main.b5733f60.js:37:19939597)
    at async Object.send (main.b5733f60.js:37:19977665)
    at async Object.onClick (main.b5733f60.js:137:24760)
```
User has 0.06 SOL in Brave wallet and 44.148378 FTM in Metamask wallet.

![Screenshot 2023-09-19 at 21 47 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1f81309c-a2c6-4369-a260-5d427ad3a698)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

* Send from tx: [Solana explorer](https://explorer.solana.com/tx/5vUkMW3PB12kW2NgXGm6chhBi6AjJ4KbZYs5fW3Tq22y46ZVMhFhEtjMZ4GqdP9njVkA3HTJs55x7ajQk2y56FFb)
* Send to tx: [FTMScan](https://ftmscan.com/tx/0xaf8696ba7209aa2e76d577266f64d00918d435ee085ec0c546fb48781e44a880)

<img width="1408" alt="Screenshot 2023-12-29 at 08 44 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2fe84289-9fd5-4639-aecb-932858e687be">


Ticket is closed.
