### ISSUE TITLE
[QA] "ERC20: transfer amount exceeds allowance" when sending asset for the first time

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#798]
## Describe the current behavior in detail
"ERC20: transfer amount exceeds allowance" error appears in Console when sending baseETH from Polygon to Base for the first time:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC20: transfer amount exceeds allowance" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="transferTokens(address,uint256,uint16,bytes32,uint256,uint32)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at A.decodeFunctionResult (interface.ts:427:23)
    at Object.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at i (hashes.ts:1:25)
```
Tested from https://mainnet--wormhole-connect.netlify.app/ with macOS Monterey 12.6.5 and Chrome Version 115.0.5790.102 (Official Build) (x86_64).

Steps:
1. Prepare to send  WETH (in my case 0.00001) from Polygon (Metamask) to Base (Metamask)
2. Click "Approve and proceed with transaction" button

Note:
Issue is not reproducible when clicking on "Approve and proceed with transaction" button again. 

![Screenshot 2023-08-03 at 12 26 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f3e356d8-1232-4447-8156-7ceeee5a6267)

## What is the expected/desired behavior
An asset is successfully transferred from the first attempt.

**Comment by tsadovska** [comment]
Issue is also reproducible when sending baseETH from Avalanche (Metamask) to Base (Metamask) for the first time.

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending WFTM from Avalanche (Metamask) to Moonbeam (Metamask) for the first time. Issue is not reproducible when user clicks on  "Approve and proceed with transaction" button again.

Error in Console:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC20: transfer amount exceeds allowance" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="transferTokens(address,uint256,uint16,bytes32,uint256,uint32)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at A.decodeFunctionResult (interface.ts:427:23)
    at Object.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at i (hashes.ts:1:25)
```
![Screenshot 2023-08-10 at 17 57 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c9aa5a3e-7fab-4e3d-bc42-68e203be98e1)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] when sending WFTM from Fuji (Metamask) to Solana (Phantom) for the first time. Issue is not reproducible when user clicks on "Approve and proceed with transaction" button again. 

Error is displayed in Console:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC20: transfer amount exceeds allowance" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="transferTokens(address,uint256,uint16,bytes32,uint256,uint32)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (main.6f254be4.js:37:3858001)
    at l.throwError (main.6f254be4.js:37:3858121)
    at A.decodeFunctionResult (main.6f254be4.js:37:3719902)
    at Object.<anonymous> (main.6f254be4.js:37:3756115)
    at Generator.next (<anonymous>)
    at i (main.6f254be4.js:37:3751602)
```

![Screenshot 2023-09-15 at 20 51 45](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/61b6d08b-d94d-4326-95d6-51dd6a00f2f3)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1057--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending SUI from Fantom (Metamask) to Sui (Sui wallet) for the first time. Issue is not reproducible when user clicks on "Approve and proceed with transaction" button again.

```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC20: transfer amount exceeds allowance" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="transferTokens(address,uint256,uint16,bytes32,uint256,uint32)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (main.59bdb575.js:37:3857993)
    at l.throwError (main.59bdb575.js:37:3858113)
    at A.decodeFunctionResult (main.59bdb575.js:37:3719894)
    at Object.<anonymous> (main.59bdb575.js:37:3756107)
    at Generator.next (<anonymous>)
    at i (main.59bdb575.js:37:3751594)
```

![Screenshot 2023-10-03 at 20 04 34](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/07b811bc-59b0-4f9a-853d-5305da43f8f6)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
Path - Tested OK:
* Polygon -> Base ([Polygonscan](https://polygonscan.com/tx/0xf39d7732d9ac33ce5f3d693f56d7ef833e56f076b9f6c822e3cd4dcc953edad9), [BaseScan](https://basescan.org/tx/0x33bcae5c53cbe2df0f1d918621edbbc7ab91b0ff4714bfa08310729286043fb7))
* Avalanche -> Moonbeam ([AvaScan](https://avascan.info/blockchain/c/tx/0xa57b8e2cee713d790dbb6fb84b018439a87e5b63d01e2a640ac77bbdd2b47655), [Moonbeam](https://moonscan.io/tx/0x0c735c9f7d6f12768402f3489d35581836ee8976a1fe5e38eef232a450f8e07d))
* Sui -> Fantom ([Sui explorer](https://suiexplorer.com/txblock/Ak9rVQDLicY4bcSKTCm9B6iXg9srzNXWZFMJmnL5wGhP), [FTMScan](https://ftmscan.com/tx/0xf22e0d89e91e76bb520b02be07a767bf1b2f3fc3950ca1c87d7bb10e8e97d27a))
