### ISSUE TITLE
[QA] [Mainnet] Not able to claim baseETH, tx Ethereum -> Base

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#804]
## Describe the current behavior in detail
Not able to claim baseETH on Base when sending 0.00001 baseETH from Ethereum (Metamask) to Base (Metamask).

Tested from https://mainnet--wormhole-connect.netlify.app/ with macOS Monterey 12.6.5 and Chrome Version 115.0.5790.102 (Official Build) (x86_64).

Send from tx: [Ethereum](https://etherscan.io/tx/0x1936db1559b6e4963b4de38ae32669fb877190ce0f2eecc149691bcf581251b0)

Error in Console:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid emitter" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="completeTransfer(bytes)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f696e76616c696420656d69747465720000000000000000000000000000000000", errorArgs=["invalid emitter"], errorName="Error", errorSignature="Error(string)", reason="invalid emitter", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at A.decodeFunctionResult (interface.ts:427:23)
    at Object.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at i (hashes.ts:1:25)
```

Steps:
1. Connect Metamask wallets in 'From' and 'To' sections
2. Prepare to send 0.00001 baseETH from Ethereum to Base
3. Click "Approve and proceed with transaction" button
4. Click "Claim" button on Redeem screen

![Screenshot 2023-08-04 at 15 59 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0c2baa70-5503-46be-b329-8a7a58ad1100)

## What is the expected/desired behavior
Asset is successfully sent and received.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. User can successfully claim baseETH on Base.
* Send from tx: [Etherscan](https://etherscan.io/tx/0x9777aa6e3f70d571cda344a346fcd0675871e6e2ba745c57345472368a6f7833)
* Send to tx: [Basescan](https://basescan.org/tx/0x1d1f0b89e4801a2a7816e1aac38e9dab29b67b3df7d4379e2b6017042f54e936)
