### ISSUE TITLE
[QA] Not able to claim asset on Moonbase

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#821]
## Describe the current behavior in detail
Not able to claim asset (WFTM, WBNB) on Moonbase.

Tested from https://base-relayer--wormhole-connect.netlify.app/  [Testnet] with macOS Monterey 12.6.7 and Chrome Version 115.0.5790.170 (Official Build) (x86_64).

Error is displayed in Console:

```
Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0xbc976D4b9D57E57c3cA52e1Fd136C45FF7955A96","data":"0xaa4efa5b1e7ea4d9322c315d05e6ed188bd754035b3f68bf8d631521de1f17dfbc8d5cdb","accessList":null}, error={"code":-32603,"message":"JsonRpcEngine: Response has no error or result for request:\n{\n  \"method\": \"eth_call\",\n  \"params\": [\n    {\n      \"from\": \"0x0a370e7c5f7f944d451b48bc151a7bec454bc185\",\n      \"to\": \"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96\",\n      \"data\": \"0xaa4efa5b1e7ea4d9322c315d05e6ed188bd754035b3f68bf8d631521de1f17dfbc8d5cdb\"\n    },\n    \"0x4ab635\"\n  ],\n  \"jsonrpc\": \"2.0\",\n  \"id\": 2898067012,\n  \"origin\": \"https://base-relayer--wormhole-connect.netlify.app\",\n  \"tabId\": 1170924318\n}","data":{"request":{"method":"eth_call","params":[{"from":"0x0a370e7c5f7f944d451b48bc151a7bec454bc185","to":"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96","data":"0xaa4efa5b1e7ea4d9322c315d05e6ed188bd754035b3f68bf8d631521de1f17dfbc8d5cdb"},"0x4ab635"],"jsonrpc":"2.0","id":2898067012,"origin":"https://base-relayer--wormhole-connect.netlify.app","tabId":1170924318}},"stack":"{\n  \"code\": -32603,\n  \"message\": \"JsonRpcEngine: Response has no error or result for request:\\n{\\n  \\\"method\\\": \\\"eth_call\\\",\\n  \\\"params\\\": [\\n    {\\n      \\\"from\\\": \\\"0x0a370e7c5f7f944d451b48bc151a7bec454bc185\\\",\\n      \\\"to\\\": \\\"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96\\\",\\n      \\\"data\\\": \\\"0xaa4efa5b1e7ea4d9322c315d05e6ed188bd754035b3f68bf8d631521de1f17dfbc8d5cdb\\\"\\n    },\\n    \\\"0x4ab635\\\"\\n  ],\\n  \\\"jsonrpc\\\": \\\"2.0\\\",\\n  \\\"id\\\": 2898067012,\\n  \\\"origin\\\": \\\"https://base-relayer--wormhole-connect.netlify.app\\\",\\n  \\\"tabId\\\": 1170924318\\n}\",\n  \"data\": {\n    \"request\": {\n      \"method\": \"eth_call\",\n      \"params\": [\n        {\n          \"from\": \"0x0a370e7c5f7f944d451b48bc151a7bec454bc185\",\n          \"to\": \"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96\",\n          \"data\": \"0xaa4efa5b1e7ea4d9322c315d05e6ed188bd754035b3f68bf8d631521de1f17dfbc8d5cdb\"\n        },\n        \"0x4ab635\"\n      ],\n      \"jsonrpc\": \"2.0\",\n      \"id\": 2898067012,\n      \"origin\": \"https://base-relayer--wormhole-connect.netlify.app\",\n      \"tabId\": 1170924318\n    }\n  },\n  \"stack\": \"Error: JsonRpcEngine: Response has no error or result for request:\\n{\\n  \\\"method\\\": \\\"eth_call\\\",\\n  \\\"params\\\": [\\n    {\\n      \\\"from\\\": \\\"0x0a370e7c5f7f944d451b48bc151a7bec454bc185\\\",\\n      \\\"to\\\": \\\"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96\\\",\\n      \\\"data\\\": \\\"0xaa4efa5b1e7ea4d9322c315d05e6ed188bd754035b3f68bf8d631521de1f17dfbc8d5cdb\\\"\\n    },\\n    \\\"0x4ab635\\\"\\n  ],\\n  \\\"jsonrpc\\\": \\\"2.0\\\",\\n  \\\"id\\\": 2898067012,\\n  \\\"origin\\\": \\\"https://base-relayer--wormhole-connect.netlify.app\\\",\\n  \\\"tabId\\\": 1170924318\\n}\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:33894)\\n    at o._checkForCompletion (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:53419)\\n    at o._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:52611)\\n    at async o._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:52399)\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:33894)\n  at o._checkForCompletion (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:53419)\n  at o._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:52611)\n  at async o._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:52399)"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at g (json-rpc-provider.ts:66:16)
    at u.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)

```

Scenario 1:
1. Send 0.01 WBNB  from BSC (Metamask) to Moonbase (Metamask)
2. Click “Approve and proceed with transaction” button
3. Click “Claim” button on Redeem screen

Send from tx: [BscScan](https://testnet.bscscan.com/tx/0xe4003ce974219180c44c90cd9f9081e0a3027bb977edc91d493f84018f20734d)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0d4aa80e-38c1-4a32-bba7-e2aa54822969)

Scenario 2:
1. Send 0.001 WFTM from Base Goerli (Metamask) to Moonbase (Metamask)
2. Click “Approve and proceed with transaction” button
3. Click “Claim” button on Redeem screen

Send from tx: [BaseScan](https://goerli.basescan.org/tx/0x98b5bef330839ec5c68e3339c99a950d9358e73a2a4a17617e0596cd879b282c)

<img width="1320" alt="Screenshot_2023-08-11_at_14 44 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/df8391ae-ce8e-48cc-8c13-cbd2fc27a745">

## What is the expected/desired behavior
Asset is successfully sent and received.

**Comment by tsadovska** [comment]
Issue is also reproducible when claiming SEI, CELO, WAVAX, APT assets on Moonbase.

Tested from https://base-relayer--wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 115.0.5790.170 (Official Build) (x86_64).

Error is displayed in Console when sending 0.0001 SEI from Goerli ([Etherscan](https://goerli.etherscan.io/tx/0x9ea668444a5908d9404e87e8a5ff406a445a8e3148a5ae12d3e6faf33dba881a)) to Moonbase :
```
Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0xbc976D4b9D57E57c3cA52e1Fd136C45FF7955A96","data":"0xaa4efa5b9bb70b44ce3a8b9cc707deafe6e627f4fefd4d6f09803fcd893a19294e964090","accessList":null}, error={"code":-32603,"message":"JsonRpcEngine: Response has no error or result for request:\n{\n  \"method\": \"eth_call\",\n  \"params\": [\n    {\n      \"from\": \"0x0a370e7c5f7f944d451b48bc151a7bec454bc185\",\n      \"to\": \"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96\",\n      \"data\": \"0xaa4efa5b9bb70b44ce3a8b9cc707deafe6e627f4fefd4d6f09803fcd893a19294e964090\"\n    },\n    \"0x4b641a\"\n  ],\n  \"jsonrpc\": \"2.0\",\n  \"id\": 4158880857,\n  \"origin\": \"https://wormhole-connect.netlify.app\",\n  \"tabId\": 1170928775\n}","data":{"request":{"method":"eth_call","params":[{"from":"0x0a370e7c5f7f944d451b48bc151a7bec454bc185","to":"0xbc976d4b9d57e57c3ca52e1fd136c45ff7955a96","data":"0xaa4efa5b9bb70b44ce3a8b9cc707deafe6e627f4fefd4d6f09803fcd893a19294e964090"},"0x4b641a"],"jsonrpc":"2.0","id":4158880857,"origin":"https://wormhole-connect.netlify.app","tabId":1170928775}}}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at g (json-rpc-provider.ts:66:16)
    at u.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```
Scenarios - Tested NOK:
* Send SEI from Goerli (Metamask) to Moonbase (Metamask), ([Etherscan](https://goerli.etherscan.io/tx/0x9ea668444a5908d9404e87e8a5ff406a445a8e3148a5ae12d3e6faf33dba881a))
* Send CELO from Fantom (Metamask) to Moonbase (Metamask), ([Fantom](https://testnet.ftmscan.com/tx/0x1ce6a70430334c81438472818e53b5c10689396614e201d028069e52803859cc))
* Send WAVAX from Base Goerli (Metamask) to Moonbase (Metamask), ([Base Goerli](https://goerli.basescan.org/tx/0x21c5eac4ec88833b58c4164a2cf6890634857e623e78d34f6e3d338cc8187ba8))
* Send APT from BSC (Metamask) to Moonbase (Metamask), ([Bscscan](https://testnet.bscscan.com/tx/0x54985ba95c2e25cb86a71f1e4b3b88464f37f7965a2ee745639dfac013a916ee))

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 
Scenarios - Tested OK:
* Send WBNB from BSC to Moonbase ([BscScan](https://testnet.bscscan.com/tx/0x9bc9fdf2dd6dae77b974f83499e59785f419351b1a9f22006e6f63ced38f1444), [Moonscan](https://moonbase.moonscan.io/tx/0xde24a8d253dc7da66aaff511aace7869db5be0afd9c5cf3fe6325a4b075c1536))
* Send CELO from Fantom to Moobase ([Fantom](https://testnet.ftmscan.com/tx/0x534efa3c97320ee0842b1ae3f00ed3d41765e75b54644584e735ecb2453e4af2), [Moonscan](https://moonbase.moonscan.io/tx/0x4ad0092450bd3865f5bcf46da883a098e51d98e86fbd9a7fa31d210ffd64fcfd))
* Send WAVAX from Base Goerli to Moonbase ([BaseScan](https://goerli.basescan.org/tx/0xc4021451c16ee6b2846e924b67c2bca4f80d801172577608aac06e198ca9ae72), [Moonbase](https://moonbase.moonscan.io/tx/0x1346831c8cac5b032fd0af2bc63962e284b94797e73d9bd140ab71cadb8f9f2f))

Ticket is closed.
