### ISSUE TITLE
[QA] [Mainnet] Claiming on Ethereum fails when sending assets from Osmosis

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#858]
## Describe the current behavior in detail
Claiming on Ethereum fails when sending assets from Osmosis to Ethereum.

Checked from https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] with macOS Monterey 12.6.7 and Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Connect Leap wallet in "From" section
2. Connect Metamask wallet in "To" section
3. Send 0.01 USDT from Osmosis to Ethereum
4. Click Claim button on Redeem screen

Issue is reproducible when:
* sending 0.01 USDT from Osmosis (Leap) to Ethereum (Metamask)
* sending 0.00001 tBTC from Osmosis (Keplr) to Ethereum (Metamask)
* sending 0.001 DAI from Osmosis (Keplr) to Ethereum (Metamask)

Error is displayed in Console:
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0x3ee18B2214AFF97000D974cf647E7C347E8fa585","data":"0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000030d02a38afb1f2f7d9cbe59e81e381939c8f6332814b6a8a8d3efed8051df59b6bb5002b5959880c13a74daf55616abc94a4f382782d2bae118dc5f18b31cedd96ae50103ac3ebcb31c575173c216d32f5a531b60c7c95f1edae3a0b665387f520b7716a21d17bb88cde57d1bc35b0c8a0eaa02dccadf41865c701e766b92a1cfb964580c0004fe5328b9dd6605e847af1d3bd912f2ffda176ca38ce5055ac019dfd7819c70e07a650c73df2cdf60bcf8a1369317a9482bab81f59fff306c7c0f90ff86f54d49010521d3720454a99e8dea4108f3578538958e201b8bb1278c98ecd37b3a3f36bfc14398fc1ac8fbc507ed100ed4b1975c4a075b9f6d2f57ee61df631da175f8db490006e2444581a719b74291e28c3dfa3222974a7c36fca5734c5cb6ae3650701510fd43c6eb3f01d4cd9ff54c55768cc7bdbc492b26f8978c18596f2ee76590b8e2b00007564e573559eea7ffdb8370704a80ca9d0784a9845d478775452bcd65a3e7778b722d74deab4b4e90d567fd5f3153983fd78561586983275000c854401998a8b7000a5ce6c2954ec8f06ab57f344049b0cd1cb62d067b0d8e2ac81159a6ddea57f8e9531d9b75db0c4a87cab21e1bf1761ff5b44defedc0f148f23f38a2bf0cdbf1f8000cb4894aa69974bfb102a58f6afbaa47d773d54ac8cc2de973dc95fd76f63581445727e1dd5f273b8ffe011889977ce65d25241d0d8cfa286e71e09daaacf18f85000da0d22317cfd3c6beceeabc81961a598a4aeb478bd75068b25e7df9c82feebe74483caa9d31655ea9d27fd9a719e3a37946a539273fb407285c9944fea0b50398010e016abb7bc803b1a53ba5a740696a8cd25d606699e6b47c209f6d77250c4b2e1b03bd4ae292fac667b881e3f296d0e7035a67fe0eeaff187e3e07202dafc5555700107b32aca7ac948ea4f093f92b25b07c9dfaf89d0831789f810759a7d4d032ad9c6f24e13e7153444b25fb01dec6b757e6e444294ebc6a46708a22bd23360bc0cc011132667b9c452a2a3b63886c1be08419d517f04b252f9dd729adcde01708deeb507dc58a024909de13d1d3a9bd292c39a8ae90a8a21e3bb0f897db966e853bed3e001240c2ffb59a8880987ac4be019954cbab18b4d285cbe6c6e8024d9395793a497c59df20fee438e512dd97df2ad72d86f1078da1bed5202ec3182a67e18899c2340164e85e5200001d400c20aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924000000000000000000010000000000000000000000000000000000000000000000000000000000002710000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec700020000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000200000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at f.makeError (main.bbca42eb.js:37:4463233)
    at f.throwError (main.bbca42eb.js:37:4463353)
    at y (main.bbca42eb.js:37:4520249)
    at u.<anonymous> (main.bbca42eb.js:37:4530433)
    at Generator.throw (<anonymous>)
    at s (main.bbca42eb.js:37:4519580)
```
Attachments:
* USDT transfer, [MintScan](https://www.mintscan.io/osmosis/transactions/FE59EFF5CD9BE901B5305D57FA0538180F1D1884DFB96769EC9190D4433F2D06)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4bdb3ee3-a493-496b-a7ec-85164e3f64e2)
* tBTC transfer, [MintScan](https://www.mintscan.io/osmosis/transactions/FA6D2416D4A01C8BE497B5B2C1B511F2393F1A3EA049111E58C62CB355CF065A)

<img width="1328" alt="Screenshot_2023-08-25_at_11 49 25" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1ea39477-62d8-4dd3-903c-5fcf649121a6">

* DAI trasfer, [MintScan](https://www.mintscan.io/osmosis/transactions/85720AD3225ED17FC9DB60D828FCB33B0C8989F366E0898235C34240054AB1B0)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/33011037-ef01-40c6-abe0-d0afb5f00c9d

## What is the expected/desired behavior
User can successfully claim assets on Ethereum.

**Comment by tsadovska** [comment]
Closing the ticket, issue is no longer reproducible. 
* Send USDT from Osmosis (Leap) to Ethereum (Metamask): [Osmosis](https://www.mintscan.io/osmosis/transactions/0B506440E2DBCFCB43D3C96F76A1EE921806BA52DCBE318E292123C3DA40FAAE), [Ethereum](https://etherscan.io/tx/0x5230af68969a3ea9231ef74ea22e49758417084b720276c8d724b648d2d7aa03)
* Send WBTC from Osmosis (Leap) to Ethereum (Metamask): [Osmosis](https://www.mintscan.io/osmosis/transactions/875AB830390F47994A825C7345AEDFB021D8392B60BA01F0E215819E9E61FBCC), [Ethereum](https://etherscan.io/tx/0xa2ec8f82dc910043c92131b4c70b23017fcda68e91a6f1510370116b8eb57ddb)
* Send DAI from Osmosis (Leap) to Ethereum (Metamask): [Osmosis](https://www.mintscan.io/osmosis/transactions/99A051A602307AD29A3314FA37953418F1F696DFB93D659B399DFBECFE90ED57), [Ethereum](https://etherscan.io/tx/0x4f11f8b1da6db560febdf390c574b14873597b8ae1ea29c26e95c996ab41bd0e)
