### ISSUE TITLE
[QA] Not able to connect Falcon for Cosmos wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#866]
## Describe the current behavior in detail
User is not able to connect Falcon for Cosmos wallet.

Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7, Chrome Version 116.0.5845.110 (Official Build) (x86_64) and Falcon Wallet Version 0.5.14.

Steps:
1. Select Osmosis network in From section
2. Click "Connect wallet" button
3. Select Falcon option

Error is displayed in Console:
```
Uncaught (in promise) Error: Chain config not found for osmo-test-5
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269273)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1759c470-04db-4f25-8f41-1036061db366)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/df5e8950-213b-4da9-b79f-a184883abba5)

## What is the expected/desired behavior
User can successfully connect Falcon for Cosmos wallet.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet]. 
Error is displayed in Console when user selects "Falcon" option on "Connect wallet" screen:
```
Uncaught (in promise) Error: Access denied
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269330)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```
Steps:
1. Open https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
2. Click "Connect wallet" button in From section
3. Select Falcon wallet

**Comment by tsadovska** [comment]
Rechecked issue on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet]
Error is displayed in Console when user selects "Falcon for Cosmos" wallet:
```
Uncaught (in promise) Error: Chain config not found for pacific-1
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269330)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet].
Error is displayed in Console:
```
Uncaught (in promise) Error: Access denied
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269330)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```
Steps:
1. Select Osmosis network
2. Click "Connect wallet" button
3. Select Falcon option


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a226ed8e-b79a-4014-9991-69db81732a55

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].
Error is displayed in Console:
```
Uncaught (in promise) Error: Chain config not found for osmo-test-5
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269273)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when user selects Cosmoshub or Evmos network and then connects Falcon wallet.

Falcon wallet notification is not opened and error is shown in Console when wallet is locked:
```
inpage.js:32 Uncaught (in promise) Error: Wallet locked
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269273)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```
Error is displayed in Console when wallet is unlocked:
```
Uncaught (in promise) Error: Chain config not found for evmos_9000-4
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269330)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/498e1bdf-7158-41e3-ac77-e03baf638466

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when user selects Kujira network and then connects Falcon wallet. Falcon option is unclickable. 

Error is displayed in Console:
```
Uncaught (in promise) Error: Wallet locked
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269273)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when user selects Kujira network and then connects Falcon wallet. Falcon option is unclickable.

Falcon wallet version 0.5.14

Error is displayed in Console:
```
Uncaught (in promise) Error: Access denied
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269273)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

**Comment by tsadovska** [comment]
Issue is still reproducible on:
- https://wormhole-connect.netlify.app/
- https://wormhole-connect-mainnet.netlify.app/

1) Error (https://wormhole-connect.netlify.app/ [Testnet]):

```
Uncaught (in promise) Error: Wallet locked
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269330)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```

![Screenshot 2023-11-29 at 14 13 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2fd46f10-b2c5-4ca2-9005-51296891e606)


2) Error (https://wormhole-connect-mainnet.netlify.app/ [Mainnet]):

```
Uncaught (in promise) Error: Access denied
    at c.<anonymous> (inpage.js:32:219635)
    at u.emit (inpage.js:10:269330)
    at w (inpage.js:32:173298)
    at b (inpage.js:32:173113)
    at v.push (inpage.js:32:173924)
    at c.value (inpage.js:32:154490)
    at c.value (inpage.js:32:194830)
```


![Screenshot 2023-11-29 at 14 17 07](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/54af745c-01ef-40c1-99ce-48399210b231)

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/
When trying to connect to Falcon wallet, console shows error `Uncaught (in promise) Error: Access denied`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b7768c30-6ddb-448e-b42b-f83ab916d8da

**Comment by AigaD** [comment]
Closing.
Falcon wallet is removed from wallet list https://github.com/XLabs/wallet-aggregator-sdk/issues/36
