### ISSUE TITLE
[QA] Not able to claim to claim USDC (Solana), tx Solana -> Osmosis

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#998]
## Describe the current behavior in detail
Not able to claim to claim USDC (Solana), tx Solana -> Osmosis

Checked on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Select Solana network in From section
2. Select Osmosis network in To section
3. Connect Phantom in From section
4. Connect Leap in To section
5. Prepare to send 0.1 USDC (Solana)
6. Click "Approve and proceed with transaction" button
7. Click "Claim" button on Redeem screen

Error is displayed in Console:
```
Error: Unregistered type url: /cosmwasm.wasm.v1.MsgExecuteContract
    at t.Registry.lookupTypeWithError (main.6f254be4.js:37:3415271)
    at t.Registry.encode (main.6f254be4.js:37:3415407)
    at t.Registry.encodeAsAny (main.6f254be4.js:37:3415522)
    at main.6f254be4.js:37:3415634
    at Array.map (<anonymous>)
    at t.Registry.encodeTxBody (main.6f254be4.js:37:3415621)
    at t.Registry.encode (main.6f254be4.js:37:3415378)
    at _.signDirect (main.6f254be4.js:37:3501601)
    at async _.signAndBroadcast (main.6f254be4.js:37:3499424)
    at async fc.signAndSendTransaction (main.6f254be4.js:37:19769860)
```

Send from tx: [Solana](https://explorer.solana.com/tx/3XavNW98RnPfX7Sn8sBgwMvXbeceQyDZVs8wyG72kZQDb2Dxz2vwCmSpSYuVhRqbnvPvzV96kSP4sGLftxAGHHZv?cluster=devnet)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3dc03b88-f6fb-4900-a7ca-bd014f7d19be)

## What is the expected/desired behavior
User can successfully claim USDC (Solana) on Osmosis.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/46b6fc1f-3120-4fb2-a761-467cc88b4080
